### ISSUE TITLE
0.7 build failure 

### ISSUE THREAD

**Issue by bergmark** [tidalcycles/Tidal#100]
Got this when building stackage nightly:
```
Preprocessing library tidal-0.7...

Sound/Tidal/Parse.hs:1:55: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[ 1 of 19] Compiling Sound.Tidal.MIDI.Device ( Sound/Tidal/MIDI/Device.hs, dist/build/Sound/Tidal/MIDI/Device.o )
[ 2 of 19] Compiling Sound.Tidal.Utils ( Sound/Tidal/Utils.hs, dist/build/Sound/Tidal/Utils.o )
[ 3 of 19] Compiling Sound.Tidal.Tempo ( Sound/Tidal/Tempo.hs, dist/build/Sound/Tidal/Tempo.o )

Sound/Tidal/Tempo.hs:26:10: Warning:
    No explicit implementation for
      either ‘==’ or ‘/=’
    In the instance declaration for ‘Eq WS.Connection’
[ 4 of 19] Compiling Sound.Tidal.Time ( Sound/Tidal/Time.hs, dist/build/Sound/Tidal/Time.o )
[ 5 of 19] Compiling Sound.Tidal.Pattern ( Sound/Tidal/Pattern.hs, dist/build/Sound/Tidal/Pattern.o )
[ 6 of 19] Compiling Sound.Tidal.Parse ( Sound/Tidal/Parse.hs, dist/build/Sound/Tidal/Parse.o )
[ 7 of 19] Compiling Sound.Tidal.Stream ( Sound/Tidal/Stream.hs, dist/build/Sound/Tidal/Stream.o )
[ 8 of 19] Compiling Sound.Tidal.Params ( Sound/Tidal/Params.hs, dist/build/Sound/Tidal/Params.o )
[ 9 of 19] Compiling Sound.Tidal.OscStream ( Sound/Tidal/OscStream.hs, dist/build/Sound/Tidal/OscStream.o )
[10 of 19] Compiling Sound.Tidal.Transition ( Sound/Tidal/Transition.hs, dist/build/Sound/Tidal/Transition.o )
[11 of 19] Compiling Sound.Tidal.MIDI.Params ( Sound/Tidal/MIDI/Params.hs, dist/build/Sound/Tidal/MIDI/Params.o )
[12 of 19] Compiling Sound.Tidal.MIDI.Control ( Sound/Tidal/MIDI/Control.hs, dist/build/Sound/Tidal/MIDI/Control.o )
[13 of 19] Compiling Sound.Tidal.MidiStream ( Sound/Tidal/MidiStream.hs, dist/build/Sound/Tidal/MidiStream.o )

Sound/Tidal/MidiStream.hs:267:36:
    Couldn't match expected type ‘CLong’ with actual type ‘PM.PMMsg’
    In the first argument of ‘PM.PMEvent’, namely ‘msg’
    In the expression: PM.PMEvent msg (t)
```

**Comment by bergmark** [comment]
This is due to PortMidi-0.1.6.0 being released

**Comment by yaxu** [comment]
Thanks @bergmark, from the changelog:
```
Sun Apr 3 00:46:02 PDT 2016 paul@thev.net * PMEvent uses CLong as message type to better handle SysEx. - This is a breaking change. Use encodeMsg or decodeMsg to work with PMMsg.
```

**Comment by lennart** [comment]
finally, I've been waiting for this change for a very long time.

however, to avoid breakage in the future, I'll try to fix it against master and also lock version to 1.6.0 in `tidal.cabal`

**Comment by yaxu** [comment]
I made a branch 0.7.1 for this about to commit a quick fix.. are we duplicating on work?

**Comment by lennart** [comment]
@yaxu no, I just checked, the change I've been waiting for was already introduced in 1.4. I haven't done any work on this you are free to merge

**Comment by yaxu** [comment]
Righto @lennart can you please check 0.7.1 branch for sanity before I merge and send to hackage please

**Comment by yaxu** [comment]
https://github.com/tidalcycles/Tidal/pull/102

**Comment by lennart** [comment]
this is not related to the change itself but we have to be aware that this will again lead to breakage for all users on OS X, mostly because portmidi is not compiled correctly by cabal. I guess these options have to be added on the PortMIDI side (`PortMidi.cabal`), we need to instruct people on OS X to do:

```shell
cabal install portmidi --ghc-options="-optl-Wl,-framework,CoreMIDI,-framework,CoreAudio" --reinstall --jobs=1 --force-reinstalls
```

as seen in the [install guide for OS X under Haskell](http://tidal.lurk.org/getting_started.html#tidal-on-mac-os-x)

**Comment by lennart** [comment]
everything seems fine with tidal 0.7.1, portmidi 1.6 on osx 10.11.4 ghc 7.10.2

**Comment by yaxu** [comment]
Thanks, uploaded to hackage now. Shall we split portmidi and serial into separate packages as they cause problems? They caused issues elsewhere too https://github.com/fpco/stackage/issues/1299 https://github.com/fpco/stackage/issues/1297

**Comment by lennart** [comment]
yes. having a generic _backend_ in core is good. dropping dependencies on this repo seems like a good plan.

I guess eventually haskell midi and serial implementation may only be necessary if running supercollider/superdirt is not an option. I guess SuperDirt should be easily extendable to allow midi and also serial controls analog to the current way to write custom synthdefs.

This might ease the process of getting midi (and also serial) to work for newcomers, as supercollider is easily installable on all major platforms (?!) and comes with serial and midi support out-of-the-box (not sure about the quality of the serial port interface though).
