### ISSUE TITLE
Thank you message in a bug

### ISSUE THREAD

**Issue by clickglue** [tidalcycles/Tidal#1002]
Dear Alex, 

I read https://post.lurk.org/@yaxu/109947527246078388

I'm just one person in the entire tidal universe, but let me tell you how grateful I am for tidal. I'm not using tidal in classes or workshops, but I've spend countless hours trying to make music with tidal. I owe these countless hours of pleasant late night tinkering to you, and by extension to all the wonderful people that spend so much time, creativity and knowledge in developing platforms that we can use. I'm in awe if I look at the work that Felix Roos is doing with Strudel. I've learned soo much about music making, functional programming, patterns and whole new kinds of music (http://www.wearenisennenmondai.com/ !!) thanks to your work at tidal. 
So why did I not send you a 'thank you message' earlier? There are ways and places to do that. There are possibilities to show appreciation. But there is some kind of distance in the virtual world. The actual developers, the creators, are the heroes of open source. I'm just a simple guy tinkering with patterns. Who am I to speak up? It is not like the live coding show I followed recently, twenty people in a club, talking like normal people, where I could have walked up to you, shook your hand and say: "thank you". For friendly gratitude to regain its place, we need to descale, to nearize, to closify, familify or any other kind of word we can invent. But even if we don't, Alex: thank you, for the countless hours of fun, all the lessons and the challenges that Tidal has given me. Kind regards, Guido

**Comment by yaxu** [comment]
Thanks @clickglue + also thanks for doing fun stuff with tidal, it would be nothing without that! I wasn't really fishing for thank-yous, although I admit this is very nice to read :) I was more thinking it would be nice if there was some social shared space/practice for sharing stuff people are doing with free software. But you're right, it's good to focus on local communities and activities, especially at this point in the pandemic.
