### ISSUE TITLE
Windows - Tidal fails to start with ghc 9.6.1

### ISSUE THREAD

**Issue by HighHarmonics2** [tidalcycles/Tidal#1009]
Multiple Windows users have reported failure to run Tidal under Pulsar after running the Chocolatey automated installer. The problem started March 12 when the GHC package on Chocolatey was updated to 9.6.1. The Tidal installer did not require a fixed GHC version, so Chocolatey would install the latest GHC. 

With further investigation and install testing, it was determined that GHC 9.6.1 has similar errors  when installed via ghcup. These problems do not occur on Linux or MacOS with 9.6.1. 

These errors come when running Tidal commands via Pulsar or from a boot/reboot of Tidal:
```
t> ghc-9.6.1.exe:  | C:\Users\cristofolini\AppData\Roaming\cabal\x86_64-windows-ghc-9.6.1\network-3.1.2.8-5DV0dwervpqBgBVxbTLy29\libHSnetwork-3.1.2.8-5DV0dwervpqBgBVxbTLy29.a: unknown symbol '__mingw_vsprintf'`

GHC.ByteCode.Linker.lookupIE
During interactive linking, GHCi couldn't find the following symbol:
  tidalzm1zi9zi4zmCLxK61fFt9vJnm5xEO9En4_SoundziTidalziStream_Target_con_info or tidalzm1zi9zi4zmCLxK61fFt9vJnm5xEO9En4_SoundziTidalziStream_Target_static_info
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
```

There is a closely related Issue recently raised on Haskell GitLab: https://gitlab.haskell.org/ghc/ghc/-/issues/23309

----
We have been telling people that ghc 9.6.1 is not compatible with Tidal and they need to downgrade to 9.4.4, which is known to be stable and reliable on Windows. Work is underway to get the Tidal Cycles package in Chocolatey to restrict ghc to 9.4.4, but that is delayed. Ultimately, we need a fix for this so that Windows users could run Tidal with ghc 9.6.1.

**Comment by Zalastax** [comment]
The linked issue has a great discussion that I find easy to follow. The very quick summary is that GHC changed compiler tool chain on Windows and now no longer ships MinGW. However, the network library accidentally forced loading of MinGW. This was fixed in https://github.com/haskell/network/pull/552. Let's monitor the thread to see whether we should force a newer version of network in Tidal or if they will resolve it: https://github.com/haskell/network/pull/552#issuecomment-1530874721

**Comment by il-mix** [comment]
Fix was implemented in network-3.1.2.9. Installing GHC 9.6.1 and Cabal 3.10.1.0 (last versions at the current time), network-3.1.2.9 package will be automatically installed by Cabal. With this version there will be no more errors when booting Tidal from Pulsar.

**Comment by Zalastax** [comment]
They ended up fixing this at the source! From the discussion in https://github.com/haskell/network/pull/552 I believe this is solved and cabal will install the correct version of the library. @HighHarmonics2 let's close this issue?

**Comment by HighHarmonics2** [comment]
Thanks @Zalastax. Yes, this is resolved. I'll close it.
