### ISSUE TITLE
add streamGetbpm to Stream.hs

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#1018]
`bpm <- Link.getTempo ss` is already available here, so it would be nice to add `streamGetbpm` here:

https://github.com/tidalcycles/Tidal/blob/bc03ed82496e1e84e7b814401af074006fc1fd82/src/Sound/Tidal/Stream.hs#L754-L759

**Comment by jarmitage** [comment]
```hs
getbpm :: Stream -> IO Double
getbpm s = fmap (\cps -> cps * 2 * 120) (streamGetcps s)
```

**Comment by mindofmatthew** [comment]
As of #1059 this has been added, and then #1083 closes the loop by adding `getbpm` and `setbpm`.
