### ISSUE TITLE
Have arp function in tidal work the same way as in strudel

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/Tidal#1033]
Is there a way to make arpeggios work in the same way they do in strudel? A couple of examples.

In strudel you can list a series of notes and then use the `arp` function to pick notes from them. For example https://strudel.tidalcycles.org/?GfzjArDNl_FP#YXdhaXQgc2FtcGxlcygnZ2l0aHViOnRpZGFsY3ljbGVzL0RpcnQtU2FtcGxlcy9tYXN0ZXInKQphd2FpdCBzYW1wbGVzKCdnaXRodWI6eWF4dS9zcGljdWxlL21hc3Rlci8nKQoKICBzb3VuZCgiYmFzczE6MTUiKSAgCiAgLm5vdGUoIltjLGU0LGc0LGY0XSIpCiAgLmFycCgiPDEgMD4gMSBbfiAxXSA8MSAyIDIgMz4iKQogIC5zcGVlZCgiMC4yNSIpCiAgLnNoYXBlKCIwLjUiKQogIC5zbG93KDIpCiAgLnBseSgyKQogIC5jcG0gKDE2MC80KQo%3D

But reinterpreting it in tidal does not produce the same results
```
d4
$ slow 2
$ ply 2
$ arp "<1 0> 1 [~ 1] <1 2 2 3>"
$ note "[c e g f]"
# sound "bass1:15"
# speed "0.25"
# shape 0.5
|+ note "24"
```

https://github.com/tidalcycles/Tidal/assets/151947/67a7d9ca-7233-4dd4-9aa2-beacefc4b404

I can't tell specifically what is happening but it appears like `arp` is assuming the scale is c major (even though it isn't specified) and is picking notes from this as if the line of code was:

Can it work in the same way as strudel instead?

**Comment by gamar3is** [comment]
Have you seen the `dagoarp` function, [here](https://github.com/tidalcycles/Tidal/issues/1050)? It allows for custom arpeggio sequences, not really sure if it's exactly what you're looking for.

**Comment by hellocatfood** [comment]
Thanks, this is exactly what I'm after. I'll close this so attention can be paid to the other issue/feature request.
