### ISSUE TITLE
Link not working on recent OSX versions

### ISSUE THREAD

**Issue by ribon3000** [tidalcycles/Tidal#1056]
When starting Tidal and attempting to connect Link-Enabled applications nothing happens. 
OSC communication works and i can use Tidal functions normally. 
I don't use SuperDirt or Supercollider so i don't know whether that's also affected. 

at least 4 users on the forum seem to be having the same issue: 

https://club.tidalcycles.org/t/ableton-link-installation/4625/5
https://club.tidalcycles.org/t/link-not-working-issue-os-sonoma/4963
https://club.tidalcycles.org/t/carabiner-variable-not-in-scope/4969

me and @eyd are on OSX Sonoma, @sherwood is on ventura 13.6.2

i've installed tidal using the automatic script from the tidal website.

my versions: 
M1 MBP 2020
OSX Sonoma 14.1.2 (23B92)
cabal-install version 3.10.2.0
compiled using version 3.10.2.1 of the Cabal library 
The Glorious Glasgow Haskell Compilation System, version 9.8.1
TidalCycles version 1.9.4

**Comment by ribon3000** [comment]
After wiping the hard drive and installing OSX Monterey 12.7.2 (21G1974) Link works as expected.

**Comment by yaxu** [comment]
Hmm it's hard to know what the problem might be :/ E.g. could be a security setting, or some problem with Haskell.

**Comment by yaxu** [comment]
I can see there's a flurry of [commits to the link library](https://github.com/Ableton/link/commits/master/) a few months ago. I think probably just updating tidal to the latest link would solve it.

**Comment by yaxu** [comment]
I've released a new tidal-link candidate here: https://hackage.haskell.org/package/tidal-link-1.0.2/candidate

We could just release it and bump the dependency on https://hackage.haskell.org/package/tidal (on hackage, without needing to do a new release)

We should do some testing first though, at least checking it still works on any platform.

**Comment by yaxu** [comment]
Ok I've released tidal-link version 1.0.2 which should hopefully work with newer mac os versions.

If you reinstall tidal after a `cabal update` it should install with tidal-link-1.0.2

**Comment by ribon3000** [comment]
awesome, thank you for the quick fix! confirmed working by the first forum user already 🙂

**Comment by yaxu** [comment]
@ribon3000 excellent :)
