### ISSUE TITLE
mini-notation syntax error causes stream to freeze

### ISSUE THREAD

**Issue by ahihi** [tidalcycles/Tidal#1099]
sometimes, a syntax error in the mini-notation causes the stream thread to freeze. an example of a pattern that causes this is:

```haskell
d1 $ stack
  [ (1/16) ~> s "ride*4"
  , n "<0 1 2§>*16" # s "808" -- note the invalid '§'
  ]
```

after this, there is no sound even if i evaluate a valid block like `d1 $ s "bd*4"`.

**Comment by yaxu** [comment]
Great thanks!
