### ISSUE TITLE
Sample preloading

### ISSUE THREAD

**Issue by annybs** [tidalcycles/Tidal#15]
> You could do something like this, a bit of a hack..

    d1 $ sound (pick <$> "[sn,bd,psr]*16" <*> run 32) |+| end "0.00001"

via @yaxu on [Twitter](https://twitter.com/yaxu/status/444070992043073536)

I'll give this a shot, but as suggested in the conversation, it would be nice to have a formal function to preload samples as first-time sample loading in a dirt process can cause delay in playback (affecting already-playing channels as well as the sample in question...)

**Comment by munshkr** [comment]
@annybs Just to let you know: samples are now loaded asynchronously in Dirt, so playback is never delayed :-) Maybe that solves your issue.

**Comment by lennart** [comment]
@annybs does async sample loading in Dirt solve your issues? then we can close this…
