### ISSUE TITLE
Expose websocket or UDP API tidal can be used programatically

### ISSUE THREAD

**Issue by lpil** [tidalcycles/Tidal#167]
Currently the main way Tidal is used is through pasting Tidal code into a GHC repl.

If Tidal there was a proper programatic interface like Sonic Pi does we could step towards better editor integration, performance tools, and interesting programmatic experimentation.

**Comment by yaxu** [comment]
This does exist as a prototype - see comment on #159, this feels like a duplicate of that issue so will close this one for now

**Comment by lpil** [comment]
Oh rats, I knew that felt familiar as I was writing it.

**Comment by yaxu** [comment]
No worries at all! Let's make some progress on it soon
