### ISSUE TITLE
Shape > 0.9 => SuperDirt crash

### ISSUE THREAD

**Issue by datamads** [tidalcycles/Tidal#170]
Hi everyone

I noticed this problem when messing around with the Shape synth parameter and since I'm new to Tidal I do a lot of stupid shit like for example set the Shape param to 1.5 or something. But if I accidentaly do that, it'll crash the synth totally. 

It's not a huge issue if you know what you're doing but could be a problem live if you by accident or lack of knowledge put a value higher than 1.0 into that one shape parameter. It doesn't do the same for other parameters with a 0.0-1.0 range (for example hcutoff) as far as I can see. 

Here's a simple example that'll make your SuperDirt cry:

```
-- Keep this going so you'll hear when the synth crashes
d2 $ sound "hh*4"

--  Now, start this: it WON't crash the synth
d1 $ sound "bd"
# shape "0.5" 

--  But this will crash the synth
d1 $ sound "bd"
# shape "1.0" 
```

**Comment by bgold-cosmos** [comment]
This is an issue for SuperDirt (and I think I know what the issue is), so I'll close here and re-open over at https://github.com/musikinformatik/SuperDirt

**Comment by datamads** [comment]
Thanks Bgold – and sorry for posting in the wrong spot. Hadn't figured out SuperDirt had it's own repository :D

**Comment by telephon** [comment]
I can't reproduce this here. Beyond `1.0`, shape will just go silent here.

Could you please check if this crashes for you, too?

```

(
{
	var signal = PinkNoise.ar;
	var shape = 1.2;
	shape = min(shape, 1.0 - 1e-16); // avoid division by zero
	shape = (2.0 * shape) / (1.0 - shape);
	
	signal = (1 + shape) * signal / (1 + (shape * abs(signal)));
	signal * 0.3
}.play;
)
```

**Comment by bgold-cosmos** [comment]
I don't think it "crashes", but it's not supposed to go silent.  It even seems to be muting the hh.  As I posted in SuperDirt, I think `1.0 - 1e-16` is too close to 1.0 and it's outputting something garbage and blowing the limiter.
