### ISSUE TITLE
`rev` dropping events (was: issue with `fit'`)

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#185]
The code 
```
d1 $ rev $ slow 4 $ fit' 1 8 (run 8) (run 8) (chop 8 $ s "breaks125")
```
produces no output, even though it works fine without the `rev`.  My suspicion is that `fit'` is the culprit, specifically it's helper function `unwrap'`, but I've yet to dive into it.  I'm posting this as an issue here to make sure I resolve it.

**Comment by yaxu** [comment]
I've noticed that `rev` after `off` can sometimes 'lose' events as well

**Comment by bgold-cosmos** [comment]
So maybe the issue is between `rev` and output somehow?  The pattern 
```
rev $ slow 4 $ fit' 1 8 (run 8) (run 8) (chop 8 $ s "break125")
```
does return events, and they seem to have normal onsets, so I don't know why no sound comes out.

**Comment by bgold-cosmos** [comment]
Hmm, OK, try this:
```
> let pat = slow 4 $ fit' 1 8 (run 8) (run 8) (chop 8 $ s "break125")

> arc pat (0,1)
[((0 % 1,1 % 2),(0 % 1,1 % 2),fromList [(begin,VF {fvalue = 0.0}),(end,VF {fvalue = 0.125}),(s,VS {svalue = "break125"})]),((1 % 2,1 % 1),(1 % 2,1 % 1),fromList [(begin,VF {fvalue = 0.125}),(end,VF {fvalue = 0.25}),(s,VS {svalue = "break125"})])]

> arc pat (0, 0.1)
[((0 % 1,1 % 2),(0 % 1,1 % 2),fromList [(begin,VF {fvalue = 0.0}),(end,VF {fvalue = 0.125}),(s,VS {svalue = "break125"})])]

> arc (rev pat) (0, 1)
[((1 % 2,1 % 1),(1 % 2,1 % 1),fromList [(begin,VF {fvalue = 0.0}),(end,VF {fvalue = 0.125}),(s,VS {svalue = "break125"})]),((0 % 1,1 % 2),(0 % 1,1 % 2),fromList [(begin,VF {fvalue = 0.125}),(end,VF {fvalue = 0.25}),(s,VS {svalue = "break125"})])]

> arc (rev pat) (0, 0.1)
[]
```

That's weird.

**Comment by yaxu** [comment]
As a minimal example, this is only playing three events but should be playing four:
  `d1 $ rev $ off 0.25 (# speed 2) $ sound "arpy arpy:2"`

**Comment by bgold-cosmos** [comment]
OK, I think an issue might be related to `mirrorArc`.  Specifically, in `rev` there are two uses of it, one on the query (which gets wrapped by `splitQueries`), and one that gets mapped over the individual Event Arcs themselves (which don't get wrapped by `splitQueries`).  I think maybe the latter is troublesome.  For example:
```
> mirrorArc (-1/4,1/4)
((-5) % 4,(-3) % 4)
```
Since the `off` is going to have an Event at (-1/4,1/4), it winds up getting placed somewhere odd and I think that's how it gets skipped.

Actually, that by itself isn't the whole problem, since there's another event at (3/4, 5/4) that gets mapped to (-1/4, 1/4), and one at (7/4, 9/4) that gets mapped to (3/4, 5/4).  

But when I ask for `arc pat (0,1)` where `pat` is the `rev $ off ...` above, it returns the events that get mapped to (-5/4, -3/4) and (-1/4, 1/4), instead of the events that get mapped to (-1/4, 1/4) and (3/4, 5/4).  So one winds up getting lost.

**Comment by yaxu** [comment]
Your original example is still not producing sound in 0.9.2. I think I was looking at a separate issue before.

Here's another example that doesn't produce sound:

`d1 $ rev $ substruct "x x/2" $ n "0 ~ 4" # sound "feel"`

**Comment by yaxu** [comment]
I think you're right on `mirrorArc`, reversing things is surprisingly confusing!

**Comment by yaxu** [comment]
Here's another minimal example that drops events:
`d1 $ rev $ density 1.1 $ sound "bd*4"`

The `splitQueries` is there to simplify the problem of how to reverse things, by cutting events into bits when they go over cycle boundaries. My feeling is that it's probably working fine on the second arcs in the resulting events (the ones that give the part). But the first arcs (the ones that give the whole) are not changed by `splitQueries`, and so the `mirrorArc` messes this up (because it works on the assumption that the arc does not span cycle boundaries).

Tidal's representation of events gets a bit awkward here..

**Comment by yaxu** [comment]
I think this makes clearer still that events get dropped when they occur over cycle boundaries:
  `d1 $ rev $ 0.125 <~ sound "bd*4"`

the 'whole' arc doesn't match with the 'part' arc so `Stream` filters them out as not having 'onsets'.

**Comment by yaxu** [comment]
Hmm https://github.com/tidalcycles/Tidal/commit/0d092a0a9b9fe57dd8f9120935d3fe049f75d2df is not quite it..

**Comment by yaxu** [comment]
This seems to fix `substruct`: https://github.com/tidalcycles/Tidal/commit/2377a30aa781109ce1fbf4344f4d636913e96653
- don't know why `filterStartInRange` was there..

**Comment by bgold-cosmos** [comment]
Had some time to investigate this a bit more today:

I think I have a working `rev`, except it only works with `rotR` but not `~>`. The latter seems to be a little different about how it handles events that straddle cycle boundaries.  For example

```
let a = n "[1 2 3 4 5 6 7 8]/2"

arc (0.125 `rotR` a) (0.9,1.0)
tidal> [((7 % 8,9 % 8),(7 % 8,9 % 8),fromList [(n,4)])]

arc (0.125 ~> a) (0.9,1.0)
tidal> [((7 % 8,9 % 8),(7 % 8,1 % 1),fromList [(n,4)])]
```
I think the difference then combines with `rev`s behavior to cause things to be dropped - `onTick` in Stream.hs filters events using `seqToRelOnsetDeltas` which might be causing something odd?  It's difficult for me to track.

**Comment by bgold-cosmos** [comment]
Latest merge from `topic-rev` seems to improve some things, but the original example still produces no sound...
