### ISSUE TITLE
`shuffle` can lock the computer

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#186]
`shuffle n` randomly chooses perturbations from a list `[0..n-1]`.  This is bad, because the number of perturbations possible is the factorial of `n`.  `shuffle 16` will rapidly consume all resources of any machine.

**Comment by telephon** [comment]
One can do it with a Lehmer Code, here is a nice explanation: http://stackoverflow.com/questions/7918806/finding-n-th-permutation-without-computing-others#7919887

**Comment by bgold-cosmos** [comment]
Cool, looks like exactly what I was trying to figure out.

**Comment by vivid-synth** [comment]
I won't have time to publish it for a few days, but inspired by this issue I've written a library to get the nth permutation of a list. Will post again here when it's up -- just posting to prevent duplication of effort.

**Comment by vivid-synth** [comment]
Whoops, just saw https://github.com/tidalcycles/Tidal/pull/189 . I'll still post when it's up, in case it turns out to be useful.

**Comment by bgold-cosmos** [comment]
Ah, I did forget to close this.  But I'm definitely still interested in your library - I worked around it since I realized that just returning a _random_ permutation is simpler than finding the nth one, but there might be interesting functions to be made with finding permutations in a specific order.

**Comment by yaxu** [comment]
Have you looked at `permStep`? It's allows permutations to be indexed according to how 'balanced'. Probably not very efficient either, thinking about it..
