### ISSUE TITLE
Installing with Stack on OSX

### ISSUE THREAD

**Issue by janaipakos** [tidalcycles/Tidal#188]
Hi there, after struggling to set up Tidal via Stack, following the note [here](https://www.reddit.com/r/haskell/comments/5nfiyi/how_to_completely_purge_my_computer_of_anything/dcc9y0x/) by running atom in stack worked and produced sound.

For mac this command is `stack exec /Applications/Atom.app/Contents/MacOS/Atom -- --processStart Atom.app`, and the default `ghci` in the Atom plugin is fine.

 Is it possible to add the above instructions for running Tidal via stack?

**Comment by jeffswitzer** [comment]
+1 to this... also on a mac you can just run: stack exec /usr/local/bin/atom

**Comment by chsm** [comment]
If you add the `atom` and `apm` commands during Atom's installation, it's even simpler: `stack exec atom`.

There's a note in the Atom guide about what to do if the commands are not installed: http://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-mac

**Comment by yaxu** [comment]
It would be good to include stack in the install instructions, but the current version of tidal in LTS haskell on stackage is 0.8.2. This is rather old, so I'm not keen on including instructions on the website for installing it.
The nightly version is up-to-date, but I couldn't find a good way to install it. Tips very welcome!

The repository for the tidal website + docs is here by the way, PRs are also very welcome: https://github.com/tidalcycles/tidalcycles.github.io/

**Comment by chsm** [comment]
Was thinking about perhaps peering through the docs and submitting some PRs. Been needing to start learning how to contrib, and Tidal is cool, so it's a perfect opportunity ;).

**Comment by chsm** [comment]
Makes sense about not wanting to include Stack-based instructions given the out-of-date package on Stackage. I'll look into what it takes to get it updated.

**Comment by afcondon** [comment]
In case anyone else is struggling with Mac / Stack combo, later version of Tidal can be found by using a different resolver (which necessitates, i think, using that same resolver in the atom tidal package settings, ie `stack install tidal --resolver nightly-2017-11-13 --install-ghc` to match command line install of `stack install tidal --resolver nightly-2017-11-13 --install-ghc`)

There's probably other ways too, but this works.
