### ISSUE TITLE
Tidal not working after Windows 10 Creators update

### ISSUE THREAD

**Issue by ArcoMul** [tidalcycles/Tidal#200]
It **seems** Tidal stopped working after the Windows 10 Creators update. First experienced GHC(i)/Haskall not starting at all [1], which seemed to be caused by an issue with GHC after the Windows 10 Creators update [2]. After using the new binaries provided in that thread Tidal still didn't work though.

Also reinstalled SuperCollider and the tidalcycles Atom plugin.

[1] https://github.com/haskell/cabal/issues/4442#event-1054120142
[2] https://ghc.haskell.org/trac/ghc/ticket/13411

**Comment by kindohm** [comment]
This is a greater issue with ghc and is not something we can fix in Tidal. The links supplied in the issue shed some light on a workaround. Another link with workaround info: https://www.reddit.com/r/haskell/comments/665kpw/how_to_get_haskell_platform_to_work_under_windows/

**Comment by ArcoMul** [comment]
After applying the workaround ghc is working again in that it doesn't immediately exits/crashes. The Atom plugin still doesn't manage to communicate with ghci though. Is there a set of command I could execute in ghci to test if the Haskell > SuperCollider communication is working?

It's either going wrong at Atom plugin to ghci, or ghci to SuperCollider right?

**Comment by kindohm** [comment]
Atom hosts a ghci process. SuperCollider and ghci are not used together. Some things to try:

1. In the Atom TidalCycles package settings, check the `ghciPath` setting value. What is the value? 

2. Check on your file system to validate that the path in step #1 above exists on your system.

3. If the value in #1 is just simply set to "ghci", then Atom is assuming that `ghci` is on your path. If this is the case, can you open a terminal and type "ghci" and enter into the ghci REPL?

I'm not sure how this setting could have changed while you were resolving the GHCI issues, but these are the steps I would go through.

**Comment by yaxu** [comment]
Perhaps the workaround fixes the ghc compiler but not the ghci interpreter that tidal uses?

**Comment by ArcoMul** [comment]
The Atom plugin does manage to start the ghci process. As it shows its output in the console it opens. But then the commands sent to it don't seem to be either sent or received well.

So I'm wondering how the plugin, ghci and supercollider work together exactly? To figure out where exactly it goes wrong. And how I could test what does work and what doesn't work :-)

Like what could I type in ghci (when i start it manually) to see if it works as it should (although I don't really know what its purpose is)

Thanks for any help, really like to fix this, but I unfortunately don't know too much about the inner-workings of Tidal.

**Comment by yaxu** [comment]
Good plan, start ghci in a terminal window, then
```
import Sound.Tidal.Context
(cps, nudger, getNow) <- cpsUtils
(d1,t1) <- superDirtSetters getNow
d1 $ sound (p "bd sn")
```

**Comment by ArcoMul** [comment]
That is actually executing fine, and playing the sample.

Seems like the issue is between Atom Cycles and ghci then?

**Comment by deepbluesome** [comment]
got the same problem, waiting for the solution.

**Comment by ArcoMul** [comment]
You could try the solution in this pull request: https://github.com/tidalcycles/atom-tidalcycles/pull/14

**Comment by yaxu** [comment]
Assuming this issue isn't a problem any more, but feel free to reopen.
