### ISSUE TITLE
Tidal mode not supported with intero / flycheck

### ISSUE THREAD

**Issue by jfennick** [tidalcycles/Tidal#201]
Syntax checker in buffer pattern002.tidal in tidal-mode:

  intero
    - major mode: `tidal-mode' not supported
    - may enable: yes

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to
enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170415.1006)
Emacs version:    24.5.1
System:           x86_64-pc-linux-gnu
Window system:    x

**Comment by yaxu** [comment]
Is this still an issue?

**Comment by quasi-coherent** [comment]
I'm getting this same issue:

Syntax checker in buffer test.tidal in tidal-mode:

  intero
    - major mode: `tidal-mode' not supported
    - may enable: yes
    - predicate:  t

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20180907.1319)
Emacs version:    26.1
System:           x86_64-apple-darwin16.7.0
Window system:    ns
