### ISSUE TITLE
Make [x, y, .. z] style enumerations work in the parser

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#202]

**Comment by yaxu** [comment]
Here (https://github.com/tidalcycles/Tidal/commit/0ceedb0a5e653b8a8ffd4461ed656f14e00ace75)'s an attempt to get e.g. `"0 .. 3" to work like `listToPat [0 .. 3]`, and `"0 0.5 3"` to work like `listToPat [0, 0.5 .. 3]`. It seems to work so far. Also gives you e.g. `"<0 0.25 .. 10>"`

**Comment by yaxu** [comment]
@vivid-synth do you mind taking a look at this? Feels hacky so far..

**Comment by vivid-synth** [comment]
I'm slowly plugging away at this, is this closed because it's merged or because you're going in another direction?

**Comment by vivid-synth** [comment]
(Sorry for the slow response!)

**Comment by vivid-synth** [comment]
The biggest issue I've been trying to get my head around so far is how we do enumerations for all types we might have patterns for -- e.g. there's not a clear definition for ``[red..blue]``

**Comment by yaxu** [comment]
I closed because I think it's about there now. `0..3` works, I decided against `[0 0.3..3]` in the end though as overcomplicating things.  `0..<4 6>` works though as does `3 .. 1`. The implementation is still rather hacky so cleaner versions welcomed! I did get rid of the GADT thingie

**Comment by vivid-synth** [comment]
@yaxu can you point to the branch where you got rid of the GADT structure? (Couldn't find it with a quick search). I can also submit my WIP that has that.

**Comment by yaxu** [comment]
It should be in 1.0-dev
