### ISSUE TITLE
Add perlin noise

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#210]
As implemented in fluxus..
x/y coordinate
octave for self similarity
http://paulbourke.net/texture_colour/perlin/

**Comment by bgold-cosmos** [comment]
https://hackage.haskell.org/package/Noise-1.0.6 seems like a starting point, it seems to work and doesn't add too many dependencies (data-default and vector, afaict).  I'm playing around with it.

**Comment by yaxu** [comment]
Oops sorry @tonyday567 I meant to tag @nini-faroux but the question stands for anyone!

**Comment by bgold-cosmos** [comment]
I played with the package a bit but didn't get far with integrating things into Tidal.

**Comment by nini-faroux** [comment]
sure, I'd really like to try it if nobody else is working on it at the moment?

**Comment by yaxu** [comment]
@nini-faroux go for it!

**Comment by msp** [comment]
This would be cool to have!

**Comment by yaxu** [comment]
This is working nicely now! Some thoughts on the 1d `perlin` oscillator..

Am I right that it is tweening between a random value once per cycle? It seems it can be defined like this:
```
perlin' = smooth $ segment 1 rand
```
The numbers that come out of `perlin` and the above version are not exactly the same but are very similar.

I was then wondering how to make a version that wasn't tied to a cycle boundary.. I like the periodic feel to the current implementation but can see it could be nice to have that optional.

Here's a go at that, doesn't seem to work too well though, as it's creating discontinuities which I think shouldn't be there.
```
perlin = smooth $ struct ((segment 1 rand) <~ "t") rand
```

**Comment by bgold-cosmos** [comment]
Yes, I think 1D Perlin is equivalent to interpolation between random values.  It looks like `smooth` is doing linear interpolation, though, whereas Perlin implementations often use something smoother.  The particular function I used is smooth in the second derivative.

If you don't want it on a cycle boundary it's possible to use `fast` or `slow`, or for more complicated stuff you can `perlinWith` any arbitrary function of time using `sig`.

**Comment by yaxu** [comment]
Aha, makes sense. Shall we close this for now then?

**Comment by bgold-cosmos** [comment]
OK
