### ISSUE TITLE
Patterned function parameters are slow

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#211]
Compare this: `length $ arc (fast 12 $ chunk 4 (fast 2) $ iter 4 ("x x x" :: Pattern String)) (0,1)`
with this: `length $ arc (_fast 12 $ chunk 4 (_fast 2) $ _iter 4 ("x x x" :: Pattern String)) (0,1)`

The first one takes much longer, the only difference being that the first parameters of `iter` and `fast` are patterns of values rather than the original versions (now renamed to `_iter` and `_fast`) which were plain values. It seems that each of these patterns of patterns multiplies up the number of function calls.

If there is an answer to this, it might be in memoization.
  https://wiki.haskell.org/Memoization

**Comment by vivid-synth** [comment]
What am I doing wrong?:

```
>   length $ arc (_fast 12 $ chunk 4 (_fast 2) $ _iter 4 ("x x x" :: Pattern String))

<interactive>:6:1: error:
    • No instance for (Foldable ((->) Arc))
        arising from a use of ‘length’

>   length $ arc (fast 12 $ chunk 4 (fast 2) $ iter 4 ("x x x" :: Pattern String))

<interactive>:8:1: error:
    • No instance for (Foldable ((->) Arc))
        arising from a use of ‘length’
```

**Comment by yaxu** [comment]
You're missing the second parameter of `arc`

**Comment by yaxu** [comment]
This `length $ concatMap (\n -> arc x (n,n+0.25)) [0, 0.25, 0.5,0.75]` is *much* faster than this `length $ arc x (0,1)`

(where `x = fast 12 $ chunk 4 (fast 2) $ iter 4 ("bd bd bd" :: Pattern String)`)

In other words, if you split a pattern into chunks, it's massively faster, when you'd expect it to be slower.

**Comment by yaxu** [comment]
```
import Sound.Tidal.Context
x = fast 12 $ chunk 4 (fast 2) $ iter 4 ((p "bd bd bd") :: Pattern String)
main = putStrLn $ show $ length (arc x (0,1))
```

**Comment by yaxu** [comment]
Am I right in my understanding that it's spending most of its time on parsing? The only reason I can think that this is happening is chronic lack of memoisation.. Strange!

**Comment by yaxu** [comment]
Here's the profile for this:
```
import Sound.Tidal.Context

x = fast 12 $ chunk 4 (fast 2) $ iter 4 y
y = (p "bd bd bd") :: Pattern String
main = putStrLn $ show $ length $ concatMap (\n -> arc x (n,n+0.25)) [0, 0.25, 0.5,0.75]
```
[test.prof.split-4.txt](https://github.com/tidalcycles/Tidal/files/1025007/test.prof.split-4.txt)

The above takes 0.25s to run whereas the previous version without the four-way split takes 14 seconds. Any insights appreciated!

**Comment by vivid-synth** [comment]
I'm not able to reproduce this, on 3492b053e14a0d7df84a919e9c611656ad91a12d and on GHC 8.1. Is there a code change you're running these with? I'm very doubtful that it's a GHC version issue, as each version is so drastically different for you (12 seconds vs. 0.2 seconds, 11gb allocation vs 200mb). I even see similar performance with no optimizations at all (```ghc -O0```).

Also: these seem to not be computing the same thing!:

```
>  length $ arc x (0,1)
84
>  length $ concatMap (\n -> arc x (n,n+0.25)) [0, 0.25, 0.5,0.75] 
82
```

Also, looking at the profiler output, parsing doesn't seem to be the main thing taking time. The time spent in each function is actually very similar in both profiles -- just one is for some reason doing much, much more of each thing.

**Comment by vivid-synth** [comment]
Aha. Was able to repro the problem on 03283f55e5c348e1c9592d5b504caa137fb90a26 .

The issue is with this commit: c6ebab9289f9a29cd31ef716bb93ebeefbc80b3f - the bugfix for within.

```
-within (s,e) f p = stack [sliceArc (0,s) p,
-                           compress (s,e) $ f $ zoom (s,e) p,
-                           sliceArc (e,1) p
-                          ]
+within (s,e) f p = stack [playWhen (\t -> cyclePos t >= s && cyclePos t < e) $ f p,
+                          playWhen (\t -> not $ cyclePos t >= s && cyclePos t < e) $ p
+                         ]
```

My guess is that there's some recursive definition in ```within``` that takes a ton of time to terminate. I'll try to dig more into why.

Also note a behavior change (maybe this is what the ```within``` code was fixing?):

Fast version:

```
>  length $ arc x (0,1)
84
```

Slow version:

```
>  length $ arc x (0,1)                                                                                                               
60
```

**Comment by yaxu** [comment]
Thanks @vivid-synth! This is strange though, as I can't see where `within` is being used in the above, apart from with `chunk`, but that's present in both the fast- and slow-running examples.. I suppose it must be an interaction between `chunk` and `unwrap` that is causing something to blow up when a larger `arc` query is given. Hmm!

**Comment by bgold-cosmos** [comment]
Don't know if this helps, but I think the do-structure in `chunk` to take a value from a pattern isn't strictly necessary.  I think this does the same thing:

```
chunk n f p = cat [within (i%(fromIntegral n),(i+1)%(fromIntegral n)) f p | i <- [0..n-1]]
```
If the slowdown is related to packing/unpacking things to/from Patterns, then maybe that'll help?  I haven't had a chance to test the effect on running time.

Also, the `within` rewrite looks perfectly reasonable but I'm wondering if adding extra filtering on all the events might be an issue as well.

**Comment by vivid-synth** [comment]
That new ```chunk``` is significantly faster but returns different results.

Speaking of different results, I also notice that this returns a different result than the ```within``` that tidal defines (57 instead of 60 -- have I written something wrong?):
```haskell
within :: Arc -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
within (s, e) f (Pattern p0) = Pattern $ \a@(t, _) ->
   if isIn (s,e) (cyclePos t) -- or: cyclePos t >= s && cyclePos t < e
      then let Pattern p1 = f (Pattern p0)
           in p1 a
      else p0 a
```

**Comment by yaxu** [comment]
A differing number of events returned isn't necessarily a problem, as events can be split in two and still represent the same single event.

**Comment by yaxu** [comment]
Looking at visual renderings I can see that @bgold-cosmos 's chunk is the same as the current chunk for simple cases, i.e. in this case without the `iter 4`. I think I'll swap it in for now as it does seem to fix the performance issue..

**Comment by vivid-synth** [comment]
Here's an example of different results, that's very confusing to me. Maybe we've found a bug somewhere?:

```haskell
import Sound.Tidal.Context

-- "chunk1" vs "chunk2":
x1 = fast 12 $ chunk1 2 (fast 2) $ iter 4 ((p "bd bd bd") :: Pattern String)
x2 = fast 12 $ chunk2 2 (fast 2) $ iter 4 ((p "bd bd bd") :: Pattern String)

within1 (s,e) f p = stack [playWhen (\t -> cyclePos t >= s && cyclePos t < e) $ f p,
                          playWhen (\t -> not $ cyclePos t >= s && cyclePos t < e) $ p
                         ]

within2 :: Arc -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
within2 (s, e) f p0 = Pattern $ \a@(t, _) ->
   -- Note this is the same predicate as in 'within1':
   if cyclePos t >= s && cyclePos t < e
      then arc (f p0) a
      else arc p0 a

-- "within1" vs "within2":
chunk1 n f p = do i <- _slow (toRational n) $ run (fromIntegral n)
                  within1 (i%(fromIntegral n),(i+)1%(fromIntegral n)) f p
chunk2 n f p = do i <- _slow (toRational n) $ run (fromIntegral n)
                  within2 (i%(fromIntegral n),(i+)1%(fromIntegral n)) f p

main = do
   print $ length $ arc x1 (0, 1)
   print $ length $ arc x2 (0, 1)

```

I get the results:

```
69
66
```

**Comment by yaxu** [comment]
Ref benchmarking #447

**Comment by yaxu** [comment]
There's some profiling now, and against my expectations, patterning all the parameters doesn't seem to have caused major complexity explosions.
