### ISSUE TITLE
slowing a Pattern causes (at least) the show function to lose some of it

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [tidalcycles/Tidal#219]
In the example below, slowing the `Pattern` causes the snare to disappear from the representation returned by `show`.

```
> let pat = "bd sn" :: Pattern String

> pat
"bd" 0 1/2
 "sn" 1/2 1

> slow 2 pat
"bd" 0 1

>
```

Elsewhere I reported a [similar-looking problem](http://lurk.org/groups/tidal/messages/topic/1T5n4YuGERJGryQ0GR4waz) that might or might not be the same thing.

**Comment by yaxu** [comment]
That's expected - show will only give the first cycle.
