### ISSUE TITLE
Raise error if choose is given empty list

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#220]

**Comment by pd3v** [comment]
Not sure if this is what you're talking about.

```
choose :: [a] -> Pattern a
choose [] =  throw (ErrorCall "Empty list. Nothing to choose from.")  -- new line here
choose xs = (xs !!) <$> (irand $ length xs)

```
This is setting the error message, nothing fancy. I wonder if a better solution could be - in case of an empty list, keep playing  the previous working `choose` list.

**Comment by yaxu** [comment]
Yes looks good. I think if an error is thrown like this, the previous pattern will continue running.

**Comment by pd3v** [comment]
It stops playing. If you want me to PR this solution, please let me know.

**Comment by yaxu** [comment]
yes please @pd3v

**Comment by yaxu** [comment]
against the 1.0-dev branch

**Comment by pd3v** [comment]
@yaxu, this one is ✅.
