### ISSUE TITLE
Error in REPL (hackage/cabal install)

### ISSUE THREAD

**Issue by the-drunk-coder** [tidalcycles/Tidal#221]
Hi, i just installed the latest tidal version (0.9.4) from hackage. It seems to work fine (there's sound), but there's always this error in the tidal REPL:
```
tidal> tidal> 
<interactive>:462:15: error:
    • Couldn't match type ‘Ratio Integer’ with ‘Pattern Time’
      Expected type: Pattern Time
        Actual type: Time
    • In the first argument of ‘(~>)’, namely ‘now’
      In the expression: (now ~>)
      In an equation for ‘retrig’: retrig = (now ~>)
tidal> 
<interactive>:463:38: error:
    Variable not in scope:
      retrig :: Pattern Double -> Pattern (Pattern Double)
tidal> 
<interactive>:464:37: error:
    Variable not in scope:
      retrig :: Pattern Double -> Pattern (Pattern Double)
```
Seems to happen when you install from hackage with cabal, on arch linux (ghc 8.0.2). Happened in a tidal workshop, and two people using a similar config (arch linux, installation from hackage) experiences this error ... can't tell how relevant it is ... 

Best,
n

**Comment by vivid-synth** [comment]
@the-drunk-coder what's the code you ran that triggered those errors?

**Comment by bgold-cosmos** [comment]
I suspect this is an issue with Emacs/Atom.  The editors are set up to redefine retrig using the current cycle count every time you send a command.  Due to some changes in Tidal I think the relevant command should be changed from
`let retrig = (now ~>)`
to
`let retrig = (pure now ~>)`

**Comment by bgold-cosmos** [comment]
Actually, it looks like `tidal.el` in the latest version of Tidal does have this fixed, and I don't think the Atom tidalcycles package actually defines `retrig`, so maybe the problem is due to some kind of version mismatch?

**Comment by the-drunk-coder** [comment]
The code was a simple `d1 $ sound "bd"`.

The editor in question was emacs, with the latest tidal.el from the repo.

**Comment by vivid-synth** [comment]
@the-drunk-coder did you install tidal from the same commit?

**Comment by yaxu** [comment]
I see the problem.. the install instructions for Emacs are out of date, pulling the tidal.el file from an old repo.

**Comment by yaxu** [comment]
Here's the correct tidal.el : https://raw.githubusercontent.com/tidalcycles/Tidal/master/tidal.el

**Comment by yaxu** [comment]
I've updated this in the docs. 
If you notice anything else that could be improved, PRs welcome!
https://github.com/tidalcycles/tidalcycles.github.io/blob/master/_getting_started/editors/emacs.md

**Comment by the-drunk-coder** [comment]
Yes, that was the problem ... thanks!

Btw, the link is now correct, but the code part with `curl ...` still points to the yaxu repo ...
