### ISSUE TITLE
`k` notation to denote thousands

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#234]
Example uses:

```
# cutoff "0.1k" -- # cutoff "100"
...
# hcutoff "10k" -- # hcutoff "10000"
...
# scale 0 10k sine1 -- # scale 0 10000 sine1
```

**Comment by bgold-cosmos** [comment]
It's not quite as short, but these work
```
# cutoff "0.1e3"
# hcutoff "10e3"
# scale 0 10e3 sine1
```
For the third, I think changing the notation would mean altering the parser in GHCi itself, and I'm not sure that's possible.

**Comment by jarmitage** [comment]
I guess if we can't cover all cases we should drop this idea..?
