### ISSUE TITLE
Ability to pattern global tempo with `cps`

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#236]
This would be great.

`cps "180/120 160/120 120/120"`

`cps (scale 100 120 saw1)`

etc.

**Comment by yaxu** [comment]
Here is one way (might need some updating)
http://lurk.org/groups/tidal/messages/topic/4k3RrVt8qHYrRd7WuLoAng/

but more tightly integrated cps patterning would be better.

**Comment by yaxu** [comment]
I think this is related to another big issue - that sometimes it's nice to have different cycles with different numbers of beats (with a constant beat duration). This could be achieved by simultaneously putting more events in a cycle and changing the cps for that cycle.

That would require tempo changes being schedulable by cycle position, and probably tempo changes being made via the scheduler in `Sound.Tidal.Stream` (e.g. `p "x" $ sound "<[bd sn] [bd sn sn]>" # cps (cat [pure (2/2), (2/3)])`).

It should also make fun stuff like this possible `p "tempo" $ cps (slow 4 $ discretise 32 $ scale 1 2 sine)`

**Comment by jarmitage** [comment]
Even conceptually the idea of defining tempo per pattern is really exciting I think and would lead to lots of interesting musical adventures.

**Comment by kindohm** [comment]
I think this is a huge feature that many Tidal users would love to have. Personally, the `cps (scale 120 140 $ slow 8 saw)` idea makes me giddy, even though it sounds like a recursive nightmare to implement.

**Comment by yaxu** [comment]
Seems to work!
risset rhythm:
`s "bd*2 sn:2 snare:3 ~" # cps (slow 16 $ scale 1 2 saw)`
cycles with different durations:
`s "bd*2 sn:2 snare:3 ~" # cps "<1 1.2>"`
