### ISSUE TITLE
Emit code position of currently firing Event

### ISSUE THREAD

**Issue by lennart** [tidalcycles/Tidal#245]
While the scheduler evaluates a Pattern it should also emit the code position of the currently firing event.

Therefore it is necessary to have the Parser store the code positions of all generated Tokens and then somehow pass this to the scheduler.

Currently the Parser only works on Strings (see #217 for an extension to all of tidal's functions) so the simplest case to produce this functionality would be:

- reduce the parser to only atoms, e.g. it only parses Patterns like "bd sn cp cp"
- have the parser tokenize strings as usual but keep the code position (find out if Parsec can do this, or if we have to use haskell-src-exts for this) along the token value (e.g. a tuple of `(SampleName|Int|Double, Line, Row)`)
- have the parser call the underlying function `atom` with the extra parameters for line and row, e.g. within toPat: `TPat_Atom x l r -> atom (x, l, r)` (_this would create a Pattern of triples_, e.g. `Pattern (String,Line,Row)`)  
- have the scheduler handle the triples to emit messages on a separate stream containing the line/row information simultaneously to emitting the osc/midi message to the _normal_ stream.
  - write a (dummy) EditorStream that can handle line/row tuples and is readable from e.g. emacs/atom (possible WebSocket)
  - within `Stream.hs` adjust `start`/`state` to accept an additional EditorStream
  - within `Stream.hs` adjust `onTick` to extract line/rows from events before passing them to a backend
  - within `Stream.hs` in `onTick` pass line/rows to the EditorStream for emission

**Comment by jwaldmann** [comment]
(notes from discussion at hackathon)

1. Text.Parsec knows source positions, and represents them as `SourcePos`, see https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec.html#v:getPosition This should be called before and after parsing a token, so we can associate a source-range. We could make a type
```
data SourceRange = SrcRange { begin :: SourcePos, end :: SourcePos }
data Located a = Located { location :: SourceRange, contents :: a }
```

2. The backend gets `Pattern ParamMap`. Should this be replaced by `Pattern (Located ParamMap)`? No, that's not enough. We want `Pattern (ManyLocated ParamMap)` where

```
data ManyLocated a = ManyLocated { locations :: Set SourceRange, contents :: a }
```
because at any on time, we might want to highlight several things. 

3. The operators `#, |+|` etc. need to combined source-range information, so they should get type
```
-- old:  (#) :: ParamPattern -> ParamPattern -> ParamPattern
-- new:
(#) :: Pattern (ManyLocated ParamMap) -> Pattern (ManyLocated ParamMap) -> Pattern (ManyLocated ParamMap) 
```

**Comment by yaxu** [comment]
Very interesting! To check my understanding though, won't `SourcePos` point to a position within the parsec-parsed bit (the mini language for sequences) and not the wider Haskell context for it?

**Comment by jwaldmann** [comment]
Yes, within a string. Different strings need to be identified in some way. Parsec SourcePos has a "file name" attribute for this. This could be set by the `#` (etc.) operators.

For getting the position of this string in the Haskell context, we'd need to parse the full Haskell expression.
This can be done with  https://hackage.haskell.org/package/haskell-src-exts 

I think even the very basic functionality of highlighting (several positions) within one string would be useful for understanding or demonstrating how the pattern language works.

**Comment by jwaldmann** [comment]
I am starting to work on a prototype, see https://github.com/jwaldmann/Tidal/blob/1.0-dev/tidal-highlight.hs

The code will be quite minimal (and ugly in places). I just want to quickly reach the point where the semantics of highlighting can be experimented with. Later, details of evaluation and rendering (for editors of your choice) can be polished. For now, I am quite happy the I got the basic  "GUI" working.

**Comment by yaxu** [comment]
Hi can you update on how far you got with this please jwaldmann? It's pretty exciting stuff!

**Comment by jwaldmann** [comment]
Hi. Currently stalled, for lack of time. I do hope to continue working on this.

**Comment by jwaldmann** [comment]
Hi. This is still near the top of my batch-of-things-to-do.

**Comment by yaxu** [comment]
Good to know, it would be very interesting to get this working with feedforward editor https://github.com/yaxu/feedforward

**Comment by yaxu** [comment]
It looks like this would be straightforward if we used template haskell quasiquoting, rather than overloaded strings: https://www.schoolofhaskell.com/user/marcin/quasiquotation-101

**Comment by yaxu** [comment]
Started work on this in the 'emit' branch
https://github.com/tidalcycles/Tidal/commit/4c187b827a401607059cdfb3d1e6b3fda1907be3

**Comment by yaxu** [comment]
Now added to tidal-parse except I assumed tidal-parse uses Parsec, which it doesn't any more. After some discussion on https://chat.toplap.org/channel/tidal-innards, that baton now passed to @dktr0!

The way I have this, events can have more than one location, e.g. in the following, events know both the location of its `fast` time and its string value. It would be easy to add further annotation for the purpose of in-source visualisation, in this case tagging the time value with the name of the function it fed into.

```
Prelude Sound.Tidal.Context> (fast (parseBP_E "2 3") $ parseBP_E "hello [there bing]") :: Pattern String
[((1,1),(6,1)),((1,1),(2,1))](0>¼)|"hello"
[((8,1),(13,1)),((1,1),(2,1))](¼>⅜)|"there"
[((14,1),(18,1)),((1,1),(2,1))](⅜>½)|"bing"
[((1,1),(6,1)),((3,1),(4,1))](⅔>⅚)|"hello"
[((8,1),(13,1)),((3,1),(4,1))](½> 7/12)|"there"
[((14,1),(18,1)),((3,1),(4,1))]( 7/12>⅔)|"bing"
[((8,1),(13,1)),((3,1),(4,1))](⅚> 11/12)|"there"
[((14,1),(18,1)),((3,1),(4,1))]( 11/12>1)|"bing"
```

**Comment by yaxu** [comment]
A bit of a workaround for now..
```haskell
deltaMini "sound \"bd sn\" # vowel \"a e o\""
```
wraps each quoted string with a function giving its location within the whole pattern, returning:
```haskell
sound (deltaContext 6 0 "bd sn") # vowel (deltaContext 22 0 "a e o")
```
Then when you run that, you get the correct locations:
```
[((7,1),(9,1)),((23,1),(24,1))](0>⅓)-½|s: "bd", vowel: "a"
[((7,1),(9,1)),((25,1),(26,1))]0-(⅓>½)|s: "bd", vowel: "e"
[((10,1),(12,1)),((25,1),(26,1))](½>⅔)-1|s: "sn", vowel: "e"
[((10,1),(12,1)),((27,1),(28,1))]½-(⅔>1)|s: "sn", vowel: "o"
```

**Comment by yaxu** [comment]
A working demo!
https://www.youtube.com/watch?v=2t7Ab0Phz7s&feature=youtu.be

**Comment by yaxu** [comment]
Fairly hacky, but basically working here https://github.com/yaxu/feedforward
