### ISSUE TITLE
Structured silence

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#250]
Not so long ago, tidal used to have a half-implemented way of representing silence in a pattern, in the form of a Maybe type wrapped around the value. I removed this while tidying up. I think it should go back in though, as it would be great to represent silences in a pattern so that pattern transformations could 'invert' a pattern, e.g. turn `x  ~ ~ x ~ ~ x ~` into `~ x x ~ x x ~ x`

**Comment by bgold-cosmos** [comment]
What would happen with `stack ["x ~", "~ x"]`?  Do the Maybes stick around and it's up to the invert function to sort through things?

**Comment by yaxu** [comment]
Yes that would be a pattern of `Just x`s and `Nothing`s

**Comment by yaxu** [comment]
I found the `Maybe` type I removed back in March:
https://github.com/tidalcycles/Tidal/commit/7f79ee88ca5e88cfc1d0a7a86dab38636d554217

It was in `OscParam`, I think we probably want it right down in `Event` although could take a `Pattern (Maybe a)` approach

**Comment by telephon** [comment]
couldn't it also be a sound named `"~"`, which a pattern could match against?

**Comment by yaxu** [comment]
It would be best to have a solution that works with patterns of numbers too

**Comment by yaxu** [comment]
Made a (typo-ridden) branch for experimentation https://github.com/tidalcycles/Tidal/tree/topic-structred-silence

**Comment by yaxu** [comment]
This is kind of possible now, in the form of boolean patterns.
