### ISSUE TITLE
(suggested refactoring) Sound.Tidal.Parse.toPat should not require Parseable constraint 

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#255]
I was wondering why 
```
toPat :: Parseable a => TPat a -> Pattern a
```
when we call this function, the parser is finished, as it did produce the `TPat a`. Of course the parser needed the type constraint, but later processing steps should not. When I remove the constraint from the type,
I get an error for `fromTo` in this branch of `toPat`
```
TPat_EnumFromTo a b -> unwrap $ fromTo <$> (toPat a) <*> (toPat b)
```
This is because of
```
class Parseable a where
  parseTPat :: String -> TPat a
  fromTo :: a -> a -> Pattern a
  fromThenTo :: a -> a -> a -> Pattern a
```
It seems to me that enumeration is not part of parsing, and this class could be split up in two
```
class Parseable a where
  parseTPat :: String -> TPat a
class Enumerable a where
  fromTo :: a -> a -> Pattern a
  fromThenTo :: a -> a -> a -> Pattern a
```

**Comment by jwaldmann** [comment]
... and then `toPat :: Enumerable a => TPat a -> Pattern a`

**Comment by yaxu** [comment]
This seems to have been done a while back
