### ISSUE TITLE
Comments on Installation Instruction (windows)

### ISSUE THREAD

**Issue by jblanteigne** [tidalcycles/Tidal#261]
Hi, I recently went through a clean installation and I figured I would share my experience to help you improve the guide and make it as thorough as possible so new users can get started quickly.

1) Which version of Haskell is required to install / run Tidal? Core of Full? I did not full troubleshoot this but I tried installing with the Core version and I had trouble until I install the Full version. On a 2nd computer, I went with the Full version and had no issue. **I am not 100% sure** but maybe it would be better to advice people to install the full version.

2) After installation Haskell you have to run "cabal update". This is not a big deal because the command prompt tells you to run this command when running "cabal install tidal" unsuccessfully but I think the instruction should include this step.

3) Again this is not a big deal but I wasn't sure whether to install the 32-bit or the 64-bit version of SuperCollider. I know both are compatible but considering the possible compatibility issues with other audio softwares and vsti I think it's important to specify that both versions are compatible.

Thanks.

**Comment by vivid-synth** [comment]
Point 1: I think this is true that the Full version of Haskell Platform is required
Point 2: Agree!

**Comment by yaxu** [comment]
Thanks for this, you can also send PRs for the website here: https://github.com/tidalcycles/tidalcycles.github.io

**Comment by yaxu** [comment]
Windows install has changed since this report.
