### ISSUE TITLE
Connection to remote SuperDirt instance fails

### ISSUE THREAD

**Issue by gramorgan** [tidalcycles/Tidal#263]
I'm trying to connect tidal to a superdirt instance running on another computer on my local network. As per the instructions in the howtos (https://tidalcycles.org/howtos.html) I ran

`d1 <- stream "10.0.1.4" 7771 dirt`

where 10.0.1.4 is the address of the other computer running superdirt.

It fails with this error:

```
<interactive>:6:7: error:
    • Couldn't match expected type ‘Shape -> IO a1’
                  with actual type ‘IO (ParamPattern -> IO ())’
    • The function ‘stream’ is applied to three arguments,
      but its type ‘Backend a0 -> Shape -> IO (ParamPattern -> IO ())’
      has only two
      In the first argument of ‘GHC.GHCi.ghciStepIO ::
                                  forall a. IO a -> IO a’, namely
        ‘stream "10.0.1.4" 7771 dirt’
      In a stmt of an interactive GHCi command:
        d1 <- GHC.GHCi.ghciStepIO :: forall a. IO a -> IO a
              (stream "10.0.1.4" 7771 dirt)
```

I'm running tidal through tidalvim on ubuntu 17.04

**Comment by yaxu** [comment]
Apologies the howto is out of date. Lets keep this issue open and sort this out (and also make this simpler to do). But here's a way:
```
import Sound.Tidal.OscStream

let sd ip port = do s <- makeConnection ip port superDirtSlang
                    let backend = Backend s (\_ _ _ -> return ())
                    ds <- Sound.Tidal.Stream.state backend dirt
                    return (setter ds)

s1 <- sd "192.168.0.2" 57120
```

**Comment by renderful** [comment]
@yaxu Thanks for the tip, but how would I use that snippet. I've tried it and the snippet parses fine with my edited IP address, but when I do:

d1 $ sound "bd cp"

It still comes out of my local instance.

macOS

**Comment by vivid-synth** [comment]
Apologies that i'm not testing this, but I think you'd just write: ```s1 $ sound "bd cp"``` (```s1``` instead of ```d1```)

**Comment by jkbd** [comment]
I can't connect to another host than `127.0.0.1`. This is what I tested:
JACK, scsynth, sclang and Superdirt are running. I get the configuration and run Tidal
```
$ curl https://raw.githubusercontent.com/tidalcycles/Tidal/master/BootTidal.hs --output .ghci
$ ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Listening for controls on 127.0.0.1:6010
Loaded GHCi configuration from /home/jakob/Dokumente/TidalCycles/.ghci
tidal> d1 $ sound "bd sn"
```
This gives audible kick and snare, which proves I installed Haskell and TidalCycles correctly today.
However, if I change the IP address in the configuration to the outbound IP of the very same host, like this
```
$ sed -i 's/oAddress = "127.0.0.1"/oAddress = "192.168.178.97"/' .ghci
```
and then run `ghci` and `d1 $ sound "bd sn"` again, I get no audible effect nor any error message.

When I inspect the UDP ports of this machine from the outside
```
$ nmap -sU -p 57110,57120 192.168.178.97
...
PORT      STATE         SERVICE
57110/udp open|filtered unknown
57120/udp open|filtered unknown
```
I conclude that I am not facing a packet filter problem.

Of course, what I really want to achieve is running SuperCollider on a separate machine than TidalCycles for audio hardware and computational power reasons.
@yaxu Any ideas how to progress?

**Comment by jkbd** [comment]
Using Wireshark, I found TidalCycles is sending OSC messages to the remote host. With
```
> oscdump osc.udp://:57120
```
I checked that it actually receives the `/play2 ...` OSC messages sent by `tidal> d1 $ sound "bd"`.
Next I'll check my remote SuperCollider configuration.

**Comment by yaxu** [comment]
@jkbd Hm, yes I have a feeling you have to tell superdirt to process OSC received from remote hosts, but can't find how, @telephon do you have some advice?

**Comment by jkbd** [comment]
@yaxu Thank you very much for the hint. I found it!
In the [SuperDirt startup script](https://raw.githubusercontent.com/musikinformatik/SuperDirt/develop/superdirt_startup.scd) change the line
```
~dirt.start(57120, [0, 0]);
```
to
```
~dirt.start(57120, [0, 0], NetAddr("192.168.178.97"));
//...or whatever IP the Tidal client has
```
For me the problem is solved.

A future direction to investigate is now, if a remote server can be tweaked to be useful with real-world network jitter. My test over LAN unfortunately sounds like "students first day on the drumset".

**Comment by yaxu** [comment]
Great! Can you also try this:
```
~dirt.start(57120, [0, 0], NetAddr("0.0.0.0"));
```
That should listen on all devices.

Network jitter shouldn't be a problem, as long as the system clocks are in sync. I'd recommend ptpd for that (and not ntp)

**Comment by jkbd** [comment]
`sclang` prints a lot of `late 294.*` messages. Neither increasing the `s.latency` to `2.0` nor increasing the Jack buffer size did help. Any idea?

**Comment by jkbd** [comment]
Thank you very much! My server's clock was off by 294 seconds. Now the timing is better.

**Comment by yaxu** [comment]
Great! Does it also work with `0.0.0.0` for the listen address?

**Comment by jkbd** [comment]
No. But it would be nice to have.

**Comment by yaxu** [comment]
Hmm, that's strange, I would really have expected that to work.

**Comment by jkbd** [comment]
@gramorgan, @renderful is this issue solved and can it be closed?

**Comment by yaxu** [comment]
It's old enough that everything has changed so I think best to close!
