### ISSUE TITLE
`prompt2` renamed in newer GHC

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#269]
`prompt2` -> `prompt-cont`

https://ghc.haskell.org/trac/ghc/ticket/12524

Perhaps `tidal.el` needs to detect the GHC version to set this correctly?

https://github.com/tidalcycles/Tidal/blob/9c7a5bd0a237e199da83258f8b383ed74d992c74/tidal.el#L88

**Comment by yaxu** [comment]
Yes, but my elisp isn't strong enough at least.. Perhaps there's a way to turn off or ignore ghc feedback, set both `prompt2` and `prompt-cont`, then turn it back on again?

**Comment by kgwgk** [comment]
I've created #277 for this. I'm not much familiar with elisp as well, but it seems to be working. The ghci version is grabbed as a string with

 `(substring (shell-command-to-string (concatenate 'string  tidal-interpreter " --numeric-version")) 0 -1)`

and compared to `"8.2.0"` to set either `prompt2` or `prompt-cont`.

**Comment by yaxu** [comment]
Hi @kgwgk thanks for this. I had to make a small change to get it to work for me: https://github.com/tidalcycles/Tidal/commit/0f704d24204f87a1b31df42919b6a7609a0bacdb
Does that look reasonable?

**Comment by kgwgk** [comment]
Yes, that looks fine!

**Comment by yaxu** [comment]
Super! Will close this issue for now, thanks!
