### ISSUE TITLE
fast and fastcat not in scope

### ISSUE THREAD

**Issue by diegovdc** [tidalcycles/Tidal#271]
I am new to Tidal, so I am not sure if more functions are missing. I am running Haskell 7.10.3, and installed Tidal 0.9 via cabal. 

Any ideas as to why this functions are missing?

**Comment by yaxu** [comment]
Hi @diegovdc, the latest version is 0.9.6, make sure that's installed.

**Comment by yaxu** [comment]
Closing this for now, but let me know if this is still an issue, thanks!

**Comment by diegovdc** [comment]
Thanks @yaxu that worked perfectly
