### ISSUE TITLE
Warning: No mirrors found for http://hackage.haskell.org/

### ISSUE THREAD

**Issue by dadaisdada** [tidalcycles/Tidal#272]
Hello everyone i don't know how to solve this problem 
I try to de-install and install again around 5 time but it's still have a problem
Can you help me please and sorry for my english  

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

**C:\Users\KITCHAPON>cabal install tidal
Warning: No mirrors found for http://hackage.haskell.org/
dieVerbatim: user error (cabal: Failed to download http://hackage.haskell.org/ro
ot.json : No Status
Code could be parsed from response: --01:56:47--
http://hackage.haskell.org/root.json
=> `C:\Users\KITCHA~1\AppData\Local\Temp\transportAdapterGet6088-4'
Connecting to hackage.haskell.org:80... connected!
HTTP request sent, awaiting response... 200 OK
2 Server: nginx/1.10.3 (Ubuntu)
3 Content-Type: application/json
4 Accept-Ranges: bytes
5 Cache-Control: public, no-transform, max-age=60
6 Content-MD5: xWiO9or7P2GG01FiQjvYxg==
7 ETag: "c5688ef68afb3f6186d35162423bd8c6"
8 Content-Length: 3850
9 Accept-Ranges: bytes
10 Date: Wed, 20 Dec 2017 18:56:51 GMT
11 Via: 1.1 varnish
12 Connection: keep-alive
13 X-Served-By: cache-sin18026-SIN
14 X-Cache: MISS
15 X-Cache-Hits: 0
16 X-Timer: S1513796210.195035,VS0,VE954
17 Vary: Accept-Encoding
18

0K ... 100% @ 129.65 KB/s

01:56:48 (129.65 KB/s) -
`C:\Users\KITCHA~1\AppData\Local\Temp\transportAdapterGet6088-4' saved
[3850/3850]

FINISHED --01:56:48--
Downloaded: 3,850 bytes in 1 files
)**
C:\Users\KITCHAPON>

**Comment by yaxu** [comment]
This seems like the same issue: https://github.com/haskell/cabal/issues/4747

so try:
```
cabal install Cabal
cabal install tidal
```

or if that doesn't help
```
cabal --http-transport=plain-http update
cabal --http-transport=plain-http install tidal
```

**Comment by dadaisdada** [comment]
Hello Alex 

I don't know how to say thank you for your help

Now It's work

**Comment by yaxu** [comment]
Great!
