### ISSUE TITLE
Install issue with SHA from cabal

### ISSUE THREAD

**Issue by cinterloper** [tidalcycles/Tidal#273]
when running 
cabal update && cabal -v install tidal
The install fails with the message:

Waiting for install task to finish...
Downloaded to
/root/.cabal/packages/hackage.haskell.org/SHA/1.6.4.2/SHA-1.6.4.2.tar.gz
Extracting
/root/.cabal/packages/hackage.haskell.org/SHA/1.6.4.2/SHA-1.6.4.2.tar.gz to
/tmp/cabal-tmp-315...
truncated tar archive

as a side note 
https://hackage.haskell.org/SHA/1.6.4.2/SHA-1.6.4.2.tar.gz 
does not exist however,
https://hackage.haskell.org/package/SHA-1.6.4.2/SHA-1.6.4.2.tar.gz
does exist

**Comment by yaxu** [comment]
Maybe it you delete `/root/.cabal/packages/hackage.haskell.org/SHA/1.6.4.2/SHA-1.6.4.2.tar.gz` and try again it will be better?

As an aside you don't need to install this as `root`, generally you would use cabal as your normal user

**Comment by cinterloper** [comment]
ah, well I am actually installing it in a docker container, in the same build I install cabal fresh. 
Ill try an experiment with su'ing to a user though

**Comment by yaxu** [comment]
Ah so this is a repeatable error?

**Comment by cinterloper** [comment]
I think it had something to do with my build environment.
