### ISSUE TITLE
Installing problems in Win7

### ISSUE THREAD

**Issue by neoslaughter** [tidalcycles/Tidal#275]
Hello, i am having problems installing with a fresh Haskell instalation. After running `cabal install tidal` gets me this:
`cabal install tidal
Resolving dependencies...
Configuring network-2.6.3.2...
Failed to install network-2.6.3.2
Build log ( C:\Users\niños\AppData\Roaming\cabal\logs\ghc-8.2.2\network-2.6.3.2-2iWQlx53wB4Dxiv
TL1C0NQ.log ):
Configuring network-2.6.3.2...
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.
cabal: Leaving directory 'C:\Users\NIOS~1\AppData\Local\Temp\cabal-tmp-3996\network-2.6.3.2'
cabal: Error: some packages failed to install:
hosc-0.16-7xDJZm1vFs87fe9UvxRnnv depends on hosc-0.16 which failed to install.
network-2.6.3.2-2iWQlx53wB4DxivTL1C0NQ failed during the configure step. The
exception was:
ExitFailure 1
streaming-commons-0.1.18-BU0DxctWBeoEt9oZbZ2DWn depends on
streaming-commons-0.1.18 which failed to install.
tidal-0.9.6-48r04tMGMRiK7FBBYVHRm3 depends on tidal-0.9.6 which failed to
install.
websockets-0.12.3.0-97FwO19lfEP7DbgktpslrE depends on websockets-0.12.3.0
which failed to install.`

**Comment by kindohm** [comment]
I'm not sure how you installed Haskell, but basically there are some dependencies that are being built on demand, and Windows cannot find the build tools. 

The recommendation is to install the "Full" Haskell Platform: https://www.haskell.org/platform/

Then try "cabal install tidal" after that.

-Mike

**Comment by neoslaughter** [comment]
that might be because i downloaded the core
thanks :)
