### ISSUE TITLE
An inverse of `breakUp` that turns arpeggios into chords

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#279]
`breakUp` is a pretty great idea, it breaks chords up into arpeggios:

https://github.com/tidalcycles/Tidal/blob/67c344884dec66147008ed0c0c3864daa08171a7/Sound/Tidal/Pattern.hs#L1636-L1645

What about an inverse, `breakIn` (can't think of a better name right now) that uses an integer to create nested lists, e.g.:

- `breakIn 3 "[0 4 7 5 9 12]"` => `"[0, 4, 7] [5, 9, 12]"`
- `breakIn 2 "[0 12 2 14 4 16]"` => `"[0, 12] [2, 14] [4, 16]"`

Edit: @efairbanks suggested another version (let's call it `breakUp'`) that divides the first list using an arc instead of the number of elements.

**Comment by telephon** [comment]
in sclang, this is called `clump`.

**Comment by yaxu** [comment]
Just an observation for now - `clump` sounds like a variant of the existing `struct`

**Comment by telephon** [comment]
to be precise, in sclang, `clump` maps an array to an array of sub arrays (the clumps): http://doc.sccode.org/Classes/SequenceableCollection.html#-clump
