### ISSUE TITLE
Tidal installer for Windows

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#283]
It'd be great if there was an easy way of installing for windows. (see #282 for the equivalent issue for mac and #284 for linux)

There is this by the fine @kindohm :
https://github.com/tidalcycles/tidal-chocolatey

It does work sometimes, but I believe there are reports of windows deleting things (bits of haskell?) because it finds them suspicious for some reason, so we haven't publicised it.

The next level would be a one-click download that included everything you need (supercollider, superdirt + dependences, ghc, tidal + dependencies) and installed it all for you.

Any windows-based tidalcyclists up for helping with this?

**Comment by ChewieInsomniac** [comment]
Here!

**Comment by yaxu** [comment]
Closing for now, as the chocolatey install seems to work for a lot of people.
