### ISSUE TITLE
Problem with [ ] and < > 

### ISSUE THREAD

**Issue by gilfuser** [tidalcycles/Tidal#288]
Hi.
This is a really weird problem. After upgrading to 0.9.7, whenever I try to use something between square braquets or less-then more-then signs, the pattern stops to sound, and I can't make it sound again.

Like this:

this will work:
` d1 $ fast "2 3" $ s "bd hh" `

if I do this:
` d1 $ fast "[2 3]" $ s "bd hh" `
or this
` d1 $ fast "<2 3>" $ s "bd hh" `
or this
` d1 $ s "[bd hh]" `

d1 will make no sound even if I change it to something like ` d1 $ s "bd" `

There will be no error in the post pane. I tried within Atom and tidalvim
I'm on Linux, using SC 3.9.1 from a fork with Link support. I tried with Link enabled and disabled. Always with the same result.

I appreciate some directions to debug this weird... thing.

best regards,
Gil

**Comment by yaxu** [comment]
Hi @gilfuser, I've heard one similar report but haven't been able to reproduce it myself. While we try to narrow it down can you please let me know

* operating system and version
* supercollider version
* how you installed tidal (stack or cabal)
* ghc version (`ghc --version` in a terminal window if you installed with cabal, or `stack ghci` will tell you if you installed via stack)

Thanks!

**Comment by yaxu** [comment]
Also, if `d1` stops working, will `d2` be broken too?

**Comment by yaxu** [comment]
Another thing, can you run this (without the `d1 $` in front), and paste in here what you see in the output window in atom?

```
fast "[2 3]" $ s "bd hh"
```

**Comment by gilfuser** [comment]
- operating system and version: Linux Ubuntu Studio 16.10
- supercollider version: 3.9.1
- how you installed tidal (stack or cabal): cabal (but earlier, when I installed the 0.9.6 I mixed up things and did both)
- ghc version: 8.0.2

"Also, if d1 stops working, will d2 be broken too?" No.

`fast "[2 3]" $ s "bd hh"`
Atom won't show any error, neither the GHCi pane in tidalvim
Prelude> Prelude> tidal> tidal> Prelude Sound.Tidal.Context| Prelude Sound.Tidal.Context|

**Comment by yaxu** [comment]
Ah. You should see something like this:
```
 fromList [(s,bd)] 0 1/4
 fromList [(s,hh)] 1/4 1/2
 fromList [(s,hh)] 1/2 2/3
 fromList [(s,bd)] 2/3 5/6
 fromList [(s,hh)] 5/6 1
```
Does this give any output?
```
fast "2 3" $ s "bd hh"
```

**Comment by gilfuser** [comment]
Yes, this give this output:
```fromList [(s,bd)] 2/3 5/6 fromList [(s,hh)] 5/6 1 tidal> Prelude Sound.Tidal.Context| Prelude Sound.Tidal.Context| fromList [(s,bd)] 0 1/4
fromList [(s,hh)] 1/4 1/2 fromList [(s,hh)] 1/2 2/3
fromList [(s,bd)] 2/3 5/6 fromList [(s,hh)] 5/6 1 tidal>```

**Comment by vism2889** [comment]
I ran into this same problem on MacOS the other day while jumping back and forth between branches, I believe the issue was that the sc3-plugins version was different then the SuperCollider version i updated to, when downloading and adding the correct (matching release number)plug-ins folder following this installation guide: https://github.com/supercollider/sc3-plugins  it seemed to have fixed everything.  This may not be the issue, but i would recommend checking to make sure your 'extensions' folder exists as noted in the linked guide.

**Comment by yaxu** [comment]
@gilfuser ah, if `fast "[2 3]" $ s "bd hh"` doesn't give output then the problem does indeed seem to be with tidal and not supercollider..

@vism2889 did you definitely have the same problem - simple patterns working, but `[]` breaking them?

**Comment by gilfuser** [comment]
The SC3-plugins version is the same as SC. This shouldn't be the problem.

**Comment by yaxu** [comment]
@gilfuser could you try seeing if this gives output:
```
("[4 3]" :: Pattern String)
```

**Comment by gilfuser** [comment]
This output nothing.

**Comment by yaxu** [comment]
And this?
```
("4 3" :: Pattern String)
```

**Comment by gilfuser** [comment]
@yaxu it seams like something broke when I tried `("[4 3]" :: Pattern String)`. Now I can get no sounds and no output. I'm restarting it all.

**Comment by gilfuser** [comment]
this '("4 3" :: Pattern String)' 
output this:
Sound.Tidal.Context| Prelude Sound.Tidal.Context| "4" 0 1/2
"3" 1/2 1 tidal>

**Comment by gilfuser** [comment]
but if I try this again: ` ("[4 3]" :: Pattern String) `
and there's a pattern running, it won't stop. Even with hush.

**Comment by yaxu** [comment]
Ok that's isolated the problem, thanks. I'll try to replicate it here. If you can find a way to try it with a newer version of ghc that'd be helpful.

**Comment by vism2889** [comment]
@yaxu @gilfuser I was having an issue where simple patterns would work ```d1 $ sound "bd*4"``` but when i tried to eval more complex lines like ```d1 $ sound "bd*([5 3]/3,8)"```, audio would stop without any error output from SC or Tidal in atom.  Unfortunately i cannot pin-point it directly to ```[]``` .   I was also having issues with the hush command.  I'm using ghci 8.2.2

**Comment by yaxu** [comment]
That does sound like the same issue. Did you make any changes on the
Haskell/tidal side?

**Comment by yaxu** [comment]
When this happens, do you see a ghc process in your process manager using a lot of CPU?

**Comment by vism2889** [comment]
@yaxu i posted my setup process, have had limited time to play around since fixing it, but audio was working normal, with no error messages: https://talk.lurk.org/channel/tidal-install .

**Comment by gilfuser** [comment]
I updated ghc to 8.2.2. Unfortunately it didn't help.

**Comment by yaxu** [comment]
I installed ghc 8.4.2, and can't replicate the problem with that..
Could you let me know the output of this please @gilfuser `ghc-pkg list parsec`

**Comment by gilfuser** [comment]
This is the output:
    WARNING: there are broken packages.  Run 'ghc-pkg check' for more details.
    /usr/lib/ghc/package.conf.d
        (no packages)
    /home/gilfuser/.ghc/x86_64-linux-8.0.2/package.conf.d
        parsec-3.1.13.0

**Comment by yaxu** [comment]
I've managed to replicated this in the test suite:
  https://travis-ci.org/tidalcycles/Tidal/builds/365463801

It looks like it is specific to particular ghc versions.

**Comment by gilfuser** [comment]
Yes! That solved the problem!
Nice!
Good job, Alex. Thank you tons!

bests,
Gil

**Comment by yaxu** [comment]
Great!
For the record, the issue was to do with 'semigroups'. I had to implement this for compatibility with 8.4.1, and followed the instructions to make it work in older versions, but somehow this didn't work in all cases. I'm not sure why -- it was working under 7.10.3 for me originally, but not after a clean re-install.. So I guess some weird interaction between library versions that was causing a lockup. 
Will release this fix properly just as soon as hackage comes back..
  https://github.com/tidalcycles/Tidal/pull/290/commits

**Comment by yaxu** [comment]
I'll reopen until the release, to make the issue easier for others to find who might still be hitting it..

**Comment by OscarSouth** [comment]
Hackage back online

**Comment by dmrager** [comment]
Huge thanks @yaxu @gilfuser @vism2889, you just saved me lots of debugging time. Ran into this exact same problem with Tidal installation this weekend (almost config is almost identical to @gilfuser's: SC 3.9.0, ghc 8.0.2). caball install-ing @yaxu's fix did the trick! @vism2889 I think I have a slightly less complicated (or at least a just a little different) working Tidal installation procedure for MacOS running Sierra. Will post on [https://talk.lurk.org/channel/tidal-install] later

**Comment by durwin88** [comment]
Heya,

Just installed Atom and Supercollider to run Tidal Cycles following the walkthrough (https://tidalcycles.org/getting_started.html)

Walking through the step by step instructions, and working all good, until using stack or parallel part commands. Error =

:1553:13: error: parse error (possibly incorrect indentation or mismatched brackets)

....any thoughts?

Cheers

**Comment by yaxu** [comment]
Hi @durwin88, you're posting on an old issue. Maybe best to join us on the #tidal channel on http://talk.lurk.org as this doesn't look like a bug in tidal
