### ISSUE TITLE
Backend: Make it easy to specify IP and Port

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#297]
Defining a backend destination for Tidal to send to is somewhat buried currently, e.g.:

https://github.com/tidalcycles/Tidal/blob/master/Sound/Tidal/Dirt.hs#L73-L75

Here's an example of connecting to a remote IP and adding a nudge for compensation: https://github.com/yaxu/spicule/blob/master/init32.tidal

Vivid allows you to do something like this which is helpful: `createSCServerConnection $ defaultConnectConfig {  _scConnectConfig_hostName = "192.168.7.2" }`

It would be good if one could easily use both the local and remote simultaneously. E.g.:

```
d1 $ sound "bd"
rd1 $ sound "bd" -- "remote dirt" somewhere via a different IP+port
```

**Comment by yaxu** [comment]
It's now quite easy in the refactor: https://github.com/tidalcycles/Tidal/blob/refactor/src/Sound/Tidal/Stream.hs
`d <- stream (superdirtTarget {address = "192.168.1.2", port = 2342})`
