### ISSUE TITLE
Make juxBy patternable

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#299]
`juxBy "0.25 0.75" (rev)` etc

**Comment by pd3v** [comment]
Hi there, @jarmitage and @yaxu I did a PR for this.

**Comment by pd3v** [comment]
@yaxu, @jarmitage , this issue could be set as resolved...next :)

**Comment by pd3v** [comment]
@yaxu, @jarmitage , this issue is in Refactor's to do list but `juxBy` was "upgraded" in May.

**Comment by yaxu** [comment]
Oh sorry didn't spot that, thanks @pd3v !
