### ISSUE TITLE
Make master branch the dev branch?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#304]
I think it'd be simpler if we treated the master branch as the development branch, and used tags for releases. Thoughts/opinions?

**Comment by telephon** [comment]
yes!

**Comment by mtift** [comment]
That is how I work and that is the workflow I use with all of my clients. But no need to take my word for it -- according to https://git-scm.com/book/en/v2/Git-Basics-Tagging:

> Like most VCSs, Git has the ability to tag specific points in history as being important. Typically people use this functionality to mark release points (v1.0, and so on).

**Comment by yaxu** [comment]
Ok great, seems a good way forward then! Here's a PR, will merge tomorrow if there aren't objections. https://github.com/tidalcycles/Tidal/pull/305

**Comment by telephon** [comment]
I've also made the `1.0-dev` branch the `develop` branch, which is now the default branch where new pull requests go.

**Comment by yaxu** [comment]
@telephon do you think we should do the same for the tidal repo? My suggestion here was to make master the dev branch.
