### ISSUE TITLE
SuperDirt synths not being found

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#307]
On Mac

In the SuperCollider program I have:

include("SuperDirt")
SuperDirt.start

but get:

no synth or sample named 'supermandolin' could be found.
instrument not found: nil

**Comment by songproducer** [comment]
I was able to get it working by cmd shift L but now can't play supersaw and got these errors:

```
exception in GraphDef_Recv: UGen 'SwitchDelay' not installed
exception in GraphDef_Recv: UGen 'MdaPiano' not installed.
exception in GraphDef_Recv: UGen 'MembraneHexagon' not installed.
exception in GraphDef_Recv: UGen 'SawDPW' not installed.
exception in GraphDef_Recv: UGen 'SawDPW' not installed.
exception in GraphDef_Recv: UGen 'AY' not installed.
exception in GraphDef_Recv: UGen 'BMoog' not installed

SuperDirt: listening to Tidal on port 57120
*** ERROR: SynthDef dirt_delay2 not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef dirt_delay2 not found
```

**Comment by songproducer** [comment]
Fixed by downloading the latest release zip from
https://github.com/supercollider/sc3-plugins/releases
and moved to the Extensions folder and recompiling with cmd shift L

**Comment by telephon** [comment]
thanks for the report!
