### ISSUE TITLE
cabal install tidal doesn't work on Mac

### ISSUE THREAD

**Issue by i3games** [tidalcycles/Tidal#309]
On MacOS Sierra / Haskell 8.4.2 / XCode 9.2

`cabal install tidal `

reports: 
```
clang: error: unknown argument: '-no-pie'
`gcc' failed in phase `C Compiler'. (Exit code: 1)
```

The failure comes up in both cases, when Haskell has been installed with homebrew or via the core installer from www.haskell.org. Also, the workaround suggested in the closed issue #45 to `brew install --build-from-source cabal-install` does not work. The tidal-bootstrap script has the same issue.

This means currently I can't find a a way of installing tidal into that configuration.

**Comment by i3games** [comment]
Workaround: After installing Haskell, edit your version of `/Library/Frameworks/GHC.framework/Versions/8.4.2-x86_64/usr/lib/ghc-8.4.2/settings` and change the line `C compiler supports`  to `, ("C compiler supports -no-pie","NO")` (needs admin rights).

**Comment by calumgunn** [comment]
This is saving so many lives today! Thank you @i3games :)

**Comment by i3games** [comment]
Wish I was in Berlin at the workshop :)

**Comment by lebenspuls** [comment]
I am on Yosemite 10.10.5 , HAskell 8.4.2, XCode 7.2.1
I have the same error like i3games. When I change the settings-file according to your suggestions I get the error 
cabal: '/usr/local/bin/ghc' exited with an error:
Can't parse
"/Library/Frameworks/GHC.framework/Versions/8.4.2-x86_64/usr/lib/ghc-8.4.2/settings"

any ideas? Sorry I am realy new to this!

**Comment by yaxu** [comment]
@lebenspuls can you copy and paste the contents of the file here?

**Comment by lebenspuls** [comment]
Thank you!

[ ("GCC extra via C opts"," -fwrapv -fno-builtin")
, ("C compiler command“,“gcc“)
, ("C compiler flags"," -fno-stack-protector")
, ("C compiler link flags"," ")
, ("C compiler supports -no-pie“,“NO“)
, ("Haskell CPP command“,“gcc“)
, ("Haskell CPP flags", "-E -undef -traditional -Wno-invalid-pp-token -Wno-unicode -Wno-trigraphs")
, ("ld command","ld")
, ("ld flags","")
, ("ld supports compact unwind","YES")
, ("ld supports build-id","NO")
, ("ld supports filelist","YES")
, ("ld is GNU ld","NO")
, ("ar command","ar")
, ("ar flags","qcls")
, ("ar supports at file","NO")
, ("ranlib command","")
, ("touch command","touch")
, ("dllwrap command","/bin/false")
, ("windres command","/bin/false")
, ("libtool command","libtool")
, ("perl command","/usr/bin/perl")
, ("cross compiling","NO")
, ("target os","OSDarwin")
, ("target arch","ArchX86_64")
, ("target word size","8")
, ("target has GNU nonexec stack","False")
, ("target has .ident directive","True")
, ("target has subsections via symbols","True")
, ("target has RTS linker","YES")
, ("Unregisterised","NO")
, ("LLVM llc command","llc")
, ("LLVM opt command","opt")
, ("LLVM clang command","clang")
]

**Comment by yaxu** [comment]
@lebenspuls it's because you have `“` instead of `"`

**Comment by lebenspuls** [comment]
Sorry yaxu about my dumbness. I am realy newbie: what do you mean by that? Where is " instead of"?

**Comment by lebenspuls** [comment]
silly me... now i see

**Comment by yaxu** [comment]
Yes a visually small but important difference :)

**Comment by lebenspuls** [comment]
Now it starts installing - Thank you - but I get the following error messages. Befor I give up I post it here...

Last login: Thu Jun  7 10:37:51 on ttys001
PieterMB:~ volger$ cabal install tidal
Resolving dependencies...
Configuring mersenne-random-pure64-0.2.2.0...
Configuring hosc-0.16...
Configuring streaming-commons-0.2.0.0...
Building mersenne-random-pure64-0.2.2.0...
Building streaming-commons-0.2.0.0...
Building hosc-0.16...
Failed to install streaming-commons-0.2.0.0
Build log ( /Users/volger/.cabal/logs/ghc-8.4.2/streaming-commons-0.2.0.0-BXFDK5bqOmt8P2SJuUBxpL.log ):
cabal: Entering directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2267/streaming-commons-0.2.0.0'
Configuring streaming-commons-0.2.0.0...
Preprocessing library for streaming-commons-0.2.0.0..
Building library for streaming-commons-0.2.0.0..
<command line>: cannot satisfy -package-id async-2.2.1-3X0mHaSk33iDgPguLk3azN
Failed to install hosc-0.16
    (use -v for more information)
cabal: Leaving directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2267/streaming-commons-0.2.0.0'
Build log ( /Users/volger/.cabal/logs/ghc-8.4.2/hosc-0.16-DPOmbWars0W1xD4iUMwtas.log ):
cabal: Entering directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2265/hosc-0.16'
Configuring hosc-0.16...
Preprocessing library for hosc-0.16..
Building library for hosc-0.16..
<command line>: cannot satisfy -package-id network-2.6.3.5-6joSpwHklnzHDdmASCHqXt
    (use -v for more information)
cabal: Leaving directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2265/hosc-0.16'
Failed to install mersenne-random-pure64-0.2.2.0
Build log ( /Users/volger/.cabal/logs/ghc-8.4.2/mersenne-random-pure64-0.2.2.0-E6ept8G0XXGA5R07cmwcnH.log ):
cabal: Entering directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2266/mersenne-random-pure64-0.2.2.0'
Configuring mersenne-random-pure64-0.2.2.0...
Preprocessing library for mersenne-random-pure64-0.2.2.0..
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
Building library for mersenne-random-pure64-0.2.2.0..
<command line>: cannot satisfy -package-id random-1.1-7T1TXpwb46H1j0av1OnVaD
    (use -v for more information)
cabal: Leaving directory '/var/folders/6p/pcn9f8sx4p354fd5wf4jtrww0000gn/T/cabal-tmp-2266/mersenne-random-pure64-0.2.2.0'
cabal: Error: some packages failed to install:
hosc-0.16-DPOmbWars0W1xD4iUMwtas failed during the building phase. The
exception was:
ExitFailure 1
mersenne-random-pure64-0.2.2.0-E6ept8G0XXGA5R07cmwcnH failed during the
building phase. The exception was:
ExitFailure 1
streaming-commons-0.2.0.0-BXFDK5bqOmt8P2SJuUBxpL failed during the building
phase. The exception was:
ExitFailure 1
tidal-0.9.9-5hZpDhrnPvRJJnCmnwAlSc depends on tidal-0.9.9 which failed to
install.
websockets-0.12.5.0-B8DYDNVCNV9FjbjMAyLLij depends on websockets-0.12.5.0
which failed to install.

**Comment by i3games** [comment]
Re new error - I had a similar problem on Windows that was solved by installing the "full" version of Haskell first  - button "Download Full" - and then run `cabal install tidal`.

**Comment by lebenspuls** [comment]
@i3games Thank you! Finally it worked!

**Comment by yaxu** [comment]
This no-pie error doesn't seem to happen any more. Please shout if it has happens to you!

**Comment by dktr0** [comment]
Just filing in case it helps someone: the issue still happens on OS X 12.6 with GHC 8.4.3 and the fix mentioned above still works to resolve it.
