### ISSUE TITLE
This pattern only plays the first sample in the folder

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#310]
This pattern only plays the first sample in the folder:
```
d1 $ sound "blip:3(3,8)" # n "2"
```
Expected it to play the third sample.

**Comment by songproducer** [comment]
No, many samples

**Comment by yaxu** [comment]
There are only two blip samples by default. Did you add more?

**Comment by songproducer** [comment]
Yes. I had my own folder called blips with many samples so when I made this issue I took out the s thinking that the blip folder would have many samples too.

**Comment by mtift** [comment]
Are all of the samples .wav files?

**Comment by songproducer** [comment]
Yes. Sorry I didn't quite understand how the function works. This is a non-issue
