### ISSUE TITLE
Build a Tidal binary 

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#315]
It'd be great to make a Tidal binary so that people don't have to install Haskell and all the libraries. Currently if some hackage package or new haskell version has an issue (and this happens fairly often), then Tidal becomes very difficult to install.
I see this happening in two steps:

* Step 1 - make a drop-in replacement for ghci based on hint, that has tidal etc loaded. Good enough for the current editor plugins to use
* Step 2 - make something like a websocket api that can make all kinds of editor interactions possible

Step 2 is [already kind of done](https://github.com/yaxu/tidal-websocket), but using it would require updating the editor plugins, and the websocket library has some dependencies that might complicate making a standalone binary of tidal-websocket. So I think stripping things back and getting step 1 done is a good first aim.
We have three problems - linux, mac os x and windows. I'll be focusing on Linux, if anyone fancies helping with the other platforms that'd be great.
There are [simple instructions for packaging binaries](http://gelisam.blogspot.com/2014/12/how-to-package-up-binaries-for.html). The complication is that it's fiddly to get '[hint](http://hackage.haskell.org/package/hint)', the haskell interpreter library, to work without the whole of ghc being installed. However, [it is possible](https://github.com/gelisam/deploy-hint/tree/85918a527c8801f5b56f94897e6744c2cc86ee38) ([more info](https://github.com/haskell-hint/hint/issues/3)).

**Comment by yaxu** [comment]
Work in progress over here:
  https://github.com/tidalcycles/tidali

**Comment by yaxu** [comment]
Giving up on this.

**Comment by yaxu** [comment]
(making a tidal-parse library a better approach, I think)

**Comment by yaxu** [comment]
This looks v promising:
https://mpickering.github.io/ide/posts/2020-07-10-ghc-libdir.html

**Comment by tonyday567** [comment]
Having dug fairly deeply into the haskell ecosystem, I think that ghcup is an interesting project that could be leveraged to provide a hassle-free tidal install. Adopting a similar style, you would see something like this:

```
✗  tidal 1.6.1 compatible with SuperCollider 2.3.7
✓  tidal 1.7.4 latest, recommended, compatible with 3.11.1
✓  ghc 8.10.4 recommended
✓  stack 1.9.1 recommended
✓  SuperCollider 3.11.1
...

that wraps the whole install experience.  Call it tidalup, say, so as not to confuse people, but just really piggy back the projects technology to be able to install everywhere.

I think this would be a worthwhile community project but I'm unsure what others may think.

**Comment by yaxu** [comment]
That could be a nice way to make a development environment, but if we make an API we no longer need ghci and the whole haskell ecosystem, we just need to distribute Tidal as a binary that somehow ships with supercollider and superdirt. @onthepeakofnormal is currently looking at making a tidal binary with hint here: https://github.com/gelisam/deploy-hint/issues/6

**Comment by tonyday567** [comment]
@yaxu Yes, has a quick look and the binary idea looks tight. And yes, this is my development environment that I keep manually. I feel seen!

**Comment by yaxu** [comment]
Oh you mean you already made a tidalup?

**Comment by tonyday567** [comment]
No, that’s a lot of work. I just meant I was thinking about my own development wants - I like to have the latest superdirt etc - and probably agree that this is not a good target for general usage.

**Comment by yaxu** [comment]
`tidal-listener` is mostly this!
