### ISSUE TITLE
Tidal in SCIDE

### ISSUE THREAD

**Issue by paum3** [tidalcycles/Tidal#317]
Hi, 
sorry if I am writing to wrong place, it's not issue but rather feature request. indeed.

It will be definitely cool if one can run tidal haskell commands from sc ide. somehow.
What do you think?

**Comment by telephon** [comment]
using `unixCmd` it should be possible to write a wrapper. @yaxu what would be the terminal command to pine into the tidal ghci?

**Comment by yaxu** [comment]
Sorry for the long delay.. @telephon it'd either be `ghci` or `stack ghci`. Then initialising by piping in something like this: https://github.com/tidalcycles/atom-tidalcycles/blob/master/lib/BootTidal.hs

**Comment by yaxu** [comment]
Is this still desired? It'd be better with an OSC protocol, but that seems a wider feature for providing an API for editor plugins.
