### ISSUE TITLE
Variable not in scope: sound

### ISSUE THREAD

**Issue by hippolyte-dubois** [tidalcycles/Tidal#319]
I just installed Tidal on my laptop running Arch, Supercollider works, Superdirt too, I use VSCode with its extension to run Tidal.

When trying to play `d& $ sound "bd sn"` I get this error:

> <interactive>:38:1: error: Variable not in scope: d1 :: t0 -> t
> 
> <interactive>:38:6: error:
>     · Variable not in scope: sound :: [Char] -> t0
>     · Perhaps you meant 'round' (imported from Prelude)
> tidal>

I have tidal0.9.9 installed.

**Comment by hippolyte-dubois** [comment]
Tried an other install on another laptop. Same issue, either using atom or vim with the tidal plugin.

**Comment by yaxu** [comment]
My guess is that tidal didn't install successfully, or you have more than one version of haskell installed. If this is still an issue, we can step you through troubleshooting on the #tidal-install channel on talk.lurk.org.

**Comment by jcguu95** [comment]
I have the same issue with emacs.. :(
