### ISSUE TITLE
Variable not in scope: now

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#320]
Hello,

Trying to run this example:

> 
>   d1 $ (pure now) ~> seqP [ 
>     (0, 12, sound "bd bd*2"), 
>     (4, 12, sound "hh*2 [sn cp] cp future*4"), 
>     (8, 12, sound (samples "arpy*8" (run 16)))
>   ]

Do I need to include something?

**Comment by bgold-cosmos** [comment]
The emacs editor defines "now" for you, in Atom you can do this yourself by wrapping the example with a do statement:
```
do {
  now <- getNow;
  d1 $ (pure $ nextSam now) ~> seqP [
   (0, 12, sound "bd bd2"),
   (4, 12, sound "hh2 [sn cp] cp future4"),
   (8, 12, sound (samples "arpy8" (run 16)))
   ]
}
```

**Comment by songproducer** [comment]
Thanks!
