### ISSUE TITLE
d1 $ n "[0..7] [3..1]" # sound "supergong"   doesn't make any sound

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#321]
No errors, but no sound either.

**Comment by Thaega** [comment]
The sample "supergong" seems to have disappeared from my copy of SuperCollider, maybe it's also the case for you?

**Comment by bgold-cosmos** [comment]
supergong isn't a sample, it's a soft-synth in SuperDirt (in `library/default-synths-extra.scd`)  If you haven't installed the SC3-plugins for SuperCollider it's possible that it failed to load.

**Comment by yaxu** [comment]
Try with 'note' instead of 'n'

**Comment by pd3v** [comment]
@Thaega, two workarounds, a bit more verbose for sure.. 

`d1 $ n (append (run 8) (rev $ run 3+1)) # s "supergong"`
`d1 $ n (fastcat [run 8, rev $ (run 3+1)]) # s "supergong"`

**Comment by songproducer** [comment]
Thanks @pd3v this worked well
