### ISSUE TITLE
Installation problems in Win10

### ISSUE THREAD

**Issue by philipspavilion** [tidalcycles/Tidal#322]
When I type `cabal install tidal` this message appears

```
```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
cabal: There is no package named 'tidal'.
```
You may need to run 'cabal update' to get the latest list of available
packages.
```

**Comment by kindohm** [comment]
@philipspavilion did you run `cabal update` as the message suggests? Did this resolve your issue? It's normal for that to happen the first time you run `cabal install`.

**Comment by yaxu** [comment]
I'll close this for now, please reopen if it's still an issue
