### ISSUE TITLE
This example clicks and pops

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#323]
d1 $ sound "hh*32" # cutoff (scale 300 1000 $ slow 4 $ sine) # resonance "0.4"

If I change 

> hh*32

to

>hh*16

 it works fine. Any idea how I can make the clicks/pops go away?

I already tried setting latency to 0.01 and 0.20

I am on Ubuntu and in the start up of Super collider it states:
JackDriver: max output latency 21.3 ms

**Comment by bgold-cosmos** [comment]
Sounds OK on my computer - what CPU usage does Supercollider report?  Does `# cut 1` help?

**Comment by yaxu** [comment]
Yes this shouldn't happen. If it's still an issue please restate it here, giving more info about supercollider and superdirt versions, and what kind of hardware you're running it: https://github.com/musikinformatik/SuperDirt/issues
