### ISSUE TITLE
Meta-issue: Refactor

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#326]
Tidal has had a few rewrites in its life, but not for a while. I think it's time!

I have started sketching something here:
  https://github.com/tidalcycles/Tidal/tree/refactor

See the refactor project for a list of issues:
  https://github.com/tidalcycles/Tidal/projects/2

**Comment by yaxu** [comment]
Work is ongoing here: https://github.com/tidalcycles/Tidal/tree/refactor

**Comment by yaxu** [comment]
@bgold-cosmos I renamed `unwrap'` to `unwrapSqueeze`.. Does that name make sense to you?

**Comment by bgold-cosmos** [comment]
Sure, as I recall `unwrap'` is mostly a helper function for `fit'` rather than something I'd expect most users would call directly, but was exposed globally on the chance it might come in handy.
