### ISSUE TITLE
Test suite required

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#327]
With a pending refactor, this is a good time to make a test suite, to avoid regressions and encourage more contributors.

**Comment by yaxu** [comment]
@vivid-synth is going to look at this

**Comment by vivid-synth** [comment]
A starting point is here: https://github.com/tidalcycles/Tidal/pull/328

Btw you can see how thorough your tests are with something like:

```
 $ ghc -isrc test/Test.hs  -fhpc
 $ test/Test
 $ hpc markup Test.tix 
 $ firefox hpc_index.html
```

(If you click on a module, everything in yellow is an expression or alternative that has never been reached by a test)

And then to clean up:

```
rm test/Test Test.tix
rm -r .hpc
rm *.html # be sure you don't have anything else with ".htm"l!
```

(I'm sure there's a simpler way to do this, but it works!)

**Comment by yaxu** [comment]
Lovely, thanks!
