### ISSUE TITLE
Proposal: New syntax

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#332]
Currently `+`, `-` etc works for combining patterns, and `|+|`, `|-|` works for combining patterns of parameters. I think we can instead use the same syntax for both. i.e. `n ("1 2" |+| "3 4 5")` could work the same as `n "1 2" |+| n "3 4 5"`.

Also with the new applicative behaviour, `"1 2" |+| "2 3 4"` will equal `"3 [4 5] 6"`. For the old behaviour you would do `"1 2" |+ "2 3 4"` to get structure from the left. For structure from the right, you would then do `"1 2" +| "2 3 4"`.

In addition the `|=|` operator would be replaced with `|>|`, the direction of the arrow indicating that values come from the right, while the `|`s indicate that structure comes from both sides. You can then do for example `<|` to take the values from the left and the structure from the right. (`|>` is the current behaviour of the `struct` function).

We could also make `+` be shorthand for `|+|`, and keep `#` and shorthand for `|>|`, to reduce the amount of typing for common cases.. and make `|=|` an alias for `|>|` in a nod to backward compatibility.. But nonetheless this will involve large, breaking changes..

**Comment by yaxu** [comment]
(These would be defined in terms of `<*>`, and the new `<*` and `*>`)

**Comment by yaxu** [comment]
True, but quite a few are using tidal for composition, so it'd be nice to find an easier way to switch between versions in the future (which would be easier for compiled binaries). It'd probably just be a few manual definitions to get the old structure-from-the-right default though.

**Comment by d0kt0r0** [comment]
Well this is of course one of those old "discourse fault lines" that pops up around computer music languages perennially. In general I think "an update broke my composition and now I have to do an infitesimally small amount of work to render it with the new version" ranks extremely low on the hierarchy of problems worth attending to (and I feel like I have watched many people's time resources for contributing to / communicating about FOSS projects be wasted attempting to cater to those who resist changes).  re: switching between versions though - doesn't stack install tidal-x.y.z cover it?

**Comment by yaxu** [comment]
Yes agreed!

That issue aside, there is one problem with the above - existing Haskell syntax. `<*` and `*>` already exist in prelude, although I don't think they're useful to tidal and they're easy enough to 'hide' and replace. The other is that if `+` is shorthand for `|+|`, then is would be nice if `>` is shorthand for `|>|`.. But `>` is of course an existing useful operator, with a different type signature than we want for it..

**Comment by d0kt0r0** [comment]
For <* and *> my instinct would be to hold on to and encourage the default Haskell implementations! (So <* would be something that samples the left according to the structure of the right, *> samples the right according to the structure of the left. At least in the way the angle brackets are used it is congruent with what you are proposing - I guess it is a kind of compromise between standard Haskell and Tidal's custom combinators).

**Comment by d0kt0r0** [comment]
The + (existing) and > shorthands are trickier... While I understand the economic attraction of the shorthand (and have certainly been using it willfully all over the place!) at the same time it seems like it is somewhat abusing the semantics of the Num typeclass (you can't implement signum, for a pattern, for example - what is the sign of this pattern? "-1 1"). No doubt this is more controversial but I wonder about abandoning the shorthand and simply insisting that patterns be combined with appropriate combinators - since they are not numbers...

**Comment by bgold-cosmos** [comment]
I don't mind if the syntax has a few idiosyncracies.  `+` as a shorthand for `|+|` doesn't bother me.  No, you can't really do `>` as shorthand for `|>|`, but is `|>|` really going to be as common?

And I want to disagree with @d0kt0r0 - Patterns absolutely are numbers.  `signum "-2 2"` should give `"-1 1"`, `abs "-2 2"` should give `"2 2"`, and with this the law abs x * signum x == x is satisfied for any Pattern x.  Lots of weird things (matrices, functions, etc) can be instances of Num.

**Comment by d0kt0r0** [comment]
@bgold-cosmos re: patterns are numbers - what about "bd cp"? I think there may be a question of different "kind"ness involved. Int is * - Pattern is * -> *.

(A small correction to a comment above: <* in the standard Haskell application would sample the left from the combined structure of the left and right, not just the structure from the right.)

**Comment by d0kt0r0** [comment]
Anyway, the existing implementation makes sense - patterns are numbers if they are patterns of numbers. Perhaps what bugs me just a little bit about it (not enough to hold on to any real discomfort with it) is the sense that it might - in "users'" minds - conceal the pattern-ness of the patterns beneath simpler abstractions. In other words, using |+| it is very clear that what is happening is an operation concerning structure and value, while just + may make it easier to forget (or never learn in the first place) this. Is two characters worth that risk? I don't know. Just my two cents!

**Comment by d0kt0r0** [comment]
PS re: "weird" things being Num. I could be missing something here but notice that [] Maybe and functions *don't* seem to be defined as Num instances in the Prelude. I'm not exactly sure why (after at least a little bit of searching, I could find no documented answer) but wonder if it has to do with these things not really behaving according to everyday expectations of numbers, even when they "contain" numbers. [] and Maybe - like Pattern - have the possibility of structures representing absence, so that makes me think about this case:

"1 2 3 4" + "" == "1 2 3 4" ...or... "" ?

"" seems like the more likely answer given the present state of things but it doesn't seem very number-y. It might seem more number-y if adding/subtracting absent structure used 0 instead of Nothing, and multiplying absent structure used 1. But I'll freely grant these are "funny" edge cases, maybe not so important to the ways people will typically use TidalCycles...

**Comment by yaxu** [comment]
@d0kt0r0 I found some links about containers of num being nums here: https://wiki.haskell.org/Num_instance_for_functions

There are some functions for which don't seem to work for applicative nums, see the 'noOv' (no overload) ones here: 

https://github.com/tidalcycles/Tidal/blob/master/Sound/Tidal/Pattern.hs#L37

This definition was lifted from here: 
 http://hackage.haskell.org/package/applicative-numbers

Note that the above was written by Conal Elliot, who is behind a lot of functional reactive programming research. It seems representing values which change over time that leads to this way of thinking.

**Comment by bgold-cosmos** [comment]
I think the concern about how things appear in users' minds is a good one... I think there it's best to be really clear and provide lots of examples.  `"1 2" + "3 4 5" == "4 [5 6] 7"` doesn't seem to confusing to me as a shorthand for `|+|`, but then I've been using Tidal for a while.

Careful consideration of "empties" will be important.  I think there should be a rigorous way of doing it, but I'm not sure what is actually best.  In my head it actually seems like it would be nice if
`"1 2 3 4" |+| "~ 0" == "1 2 3 4"` (nothing is zero over addition)
`"1 2 3 4" |*| "~ 0" == "~ ~ 0 0"` (nothing is nothing over multiplication)
but I'm not sure that this behavior makes sense.

SIde note re: strange Num instances - I realize functions may be a bad example, upon following some discussions there's apparently some unpleasant side effect, though I think it's really more the fault of GHCi implicitly sticking `fromIntegral` everywhere you have literals.  And strings can be represented as Num, although '*' and '+' may not do what you think they should...

**Comment by kindohm** [comment]
I'm generally OK with the proposed syntax changes. Trying to catch up as I've had trouble making time to engage in this discussion. 

If Tidal 1.0.0 had been released, then I'd suggest that these changes would warrant a new major version since backward compatibility would be broken. That being said, we don't have a major version yet, so I'm not sure what we can do other than release a new minor version and alert users to the changes. I agree that an older version of Tidal can be used if an older syntax is needed. Personally I'm OK with breaking changes, and having to cope, and modifying old code, but I know others may not be and the changes could be jarring.

**Comment by OscarSouth** [comment]
In terms of use in composition (mentioned by @yaxu at the beginning of the thread) I think it's ok to introduce breaking changes. I feel that a collective push forward is more favourable now than accommodating all legacy cases in a comfortable manner (which can be solved individually with version control). I'm still digging deeper in exploring tidal for composition (currently moving into a recording project from the primarily performance based work I've been doing up to now) but I think a composition workflow for lasting works should include a `.cabal` or `package.yaml` to build the project as well as a customised `BootTidal.hs` to facilitate period-specific re-creation of the piece. This is stuff I've only thought about and will explore in practice over the next few weeks.

The specific changes mentioned all sound like a logical direction to move in. I would personally advocate for shortcut versions of operators to be maintained -- it can of course be solved individually with shortcuts to insert template text and stuff, but in performance speed and accuracy are really key and some of the pattern operators are pretty fiddly (alternating 'shift' characters) and difficult to perform at speed. In my mind, Tidal is an instrument and like any instrument should be designed with expressiveness for the performer in mind over 'absoluteness' of the construction logic.

I also agree that `"1 2 3 4" |+| "~ 0" == "~ ~ 3 4"` feels more logical than `"1 2 3 4" |+| "~ 0" == "1 2 3 4"` in terms of performance.

**Comment by yaxu** [comment]
Ok now we have things like this:
```
(|+|) :: (Applicative a, Num b) => a b -> a b -> a b
a |+| b = (+) <$> a <*> b
(|+ ) :: Num a => Pattern a -> Pattern a -> Pattern a
a |+  b = (+) <$> a <* b
( +|) :: Num a => Pattern a -> Pattern a -> Pattern a
a  +| b = (+) <$> a *> b
```
https://github.com/tidalcycles/Tidal/blob/refactor/src/Sound/Tidal/Pattern.hs#L455

`ParamMap` has a `Num` instance now too:
https://github.com/tidalcycles/Tidal/blob/refactor/src/Sound/Tidal/Pattern.hs#L279

This means that `|>|`, `|+|`, `|/|` and all the `|>` `>|` variants work with both patterns of numbers, and patterns of hashmaps. As they're all just `Num`s, `+`, `/` etc automatically work as defaults for `|+|`, `|/|` etc.

Not fully tested, well I haven't connected any of this stuff up to superdirt yet.. But looks promising, will close this for now..

**Comment by yaxu** [comment]
Ok there's an ambiguity here..
```
s "bd" <| (s "cp" +| n "1 2")
```
Currently in the refactor that gives
```
s "bd bd"
```
but sometimes you'd want:
```
s "bd:1 bd:2"
```
i.e. the `<` preserves values inside the map on the right with keys that aren't on the left.

We could make additional operators for the latter behaviour, e.g. `<:`.. starting to feel a bit fiddly though!

**Comment by yaxu** [comment]
Ok I think this'd do it. Just one annoying thing - identifiers can't start with `:`, so need a different scheme for the operator names.. Anyway I guess best to try this out to see if it makes sense to have both behaviours as operators
```
(<:) :: ControlPattern -> ControlPattern -> ControlPattern
a <: b = (Map.union) <$> a *> b

(:<) :: ControlPattern -> ControlPattern -> ControlPattern
a :< b = (Map.union) <$> a <* b

(>:) :: ControlPattern -> ControlPattern -> ControlPattern
a >: b = (flip Map.union) <$> a <* b

(:>) :: ControlPattern -> ControlPattern -> ControlPattern
a :> b = (flip Map.union) <$> a <* b
```

**Comment by yaxu** [comment]
going with `/>` `>/` `/<` `</` for now.. a bit ugly but hey
