### ISSUE TITLE
Support queries with duration of zero

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#333]
It looks really useful to query events active at a discrete point, i.e. one with start and end that are the same. This has always returned an empty list of events in the past.

**Comment by yaxu** [comment]
Supporting this is proving to be a bit tricky..

https://github.com/tidalcycles/Tidal/commit/c8066b52a30644ec402bbc10fe630dcdf5cbe4c5#diff-e9ef85b1fa65610b76d8d846ba7e48b2R437

**Comment by yaxu** [comment]
The issue I'm hitting is that:

* no part of `(2,3) is in the range `(1,2)`
* no part of `(2,2)` is in the range `(1,2)` either, but
* `(2,2)` *is* in the range `(2,2)`

There seems to be something a bit odd about `(2,2)` not being a subset of `(1,2)`.

**Comment by bgold-cosmos** [comment]
I think it's issues with real (possibly rational too?) numbers and the formal definition of range.  

If a range includes both endpoints, then there **is** a part of (2,3) in (1,2), although it has measure zero, and "all" of (2,2) is in (1,2), but again "all of (2,2)" has measure zero compared to (1,2).

If a range includes one endpoint but not the other (common in computers), then (2,2) is the empty set, and so technically (2,2) is in the range of (2,2) but it's not super meaningful.

**Comment by yaxu** [comment]
Right, maybe it's not too meaningful for discrete patterns, but is in the case of continuous patterns, when you want to sample a value at a specific point.
