### ISSUE TITLE
Reconsidering pure

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#334]
Currently pure/atom gives you one event per cycle. Should it instead give you a single event that lasts from -inf to +inf?

**Comment by yaxu** [comment]
Maybe, although the current definition is very useful, and a 'structureless' pattern can be implemented the same way as sine et al

**Comment by bgold-cosmos** [comment]
Hmm, I like the current definition too, but with other changes to operators it might mean you wind up with surprises like:
`(slow 2 "1") + 1 == "2"` rather than `slow 2 "2"`
But thinking on it more, maybe that's OK, since that's a case where most often you'd want to use `|+` anyway.

**Comment by yaxu** [comment]
I've come to the conclusion that a discrete event should last for one cycle, and a continuous event should last from -inf to +inf. For now I decided to just wrap the 'whole' event arc in a maybe type, see #336
