### ISSUE TITLE
Retaining unmatched values

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#335]
It could be nice to have a way of mapping an `a -> a -> a` function over a pattern such that `"4 2" + "~ 1"` gave `"4 3"`.. e.g. for conditionally applying accents

**Comment by bgold-cosmos** [comment]
Maybe as a `.+` operator?  Though should `"~" .+ "~"` be zero or "~"?  Not quite sure how to implement "treat silence as zero" though.

**Comment by yaxu** [comment]
I think this probably isn't the way to go.
