### ISSUE TITLE
Different kinds of unwrap

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#338]
In the current release of tidal, there's `unwrap` and `unwrap'`. They both turn a pattern of patterns into a pattern.

I've rewritten the first one as `joinPattern` in the refactor.

```
-- | Turns a pattern of patterns into a single pattern.
-- (formerly known as unwrap)
--
-- 1/ For query 'span', get the events from the outer pattern @pp@
-- 2/ Query the inner pattern using the 'part' of the outer
-- 3/ For each inner event, set the whole and part to be the intersection
--    of the outer whole and part, respectively
-- 4/ Concatenate all the events together (discarding wholes/parts that didn't intersect)

joinPattern :: Pattern (Pattern a) -> Pattern a
joinPattern pp = Pattern f
  where f span = concatMap (\((whole, part), p) -> catMaybes $ map (munge whole part) $ query p part) (query pp span)
        munge oWhole oPart ((iWhole, iPart),v) = do w <- subSpan oWhole iWhole
                                                    p <- subSpan oPart iPart
                                                    return ((w,p),v)
```

So an inner pattern is one of the events inside the outer pattern, therefore given a 'start' and 'end', during which the inner pattern's events have effect.

Am I right @bgold-cosmos that `unwrap'` is similar, but that a cycle from the inner pattern is 'compressed' to fit the timespan of the outer event?

**Comment by yaxu** [comment]
Thinking about it `ur` is similar to a join, as it's also about patterns of patterns.

**Comment by bgold-cosmos** [comment]
Yes, it's been a while but I believe that was the idea of `unwrap'`.  If you had patterns

`a = "0 1"`
`b = "2 3 4"`

then the "pattern of patterns" `"a b"` would `unwrap'` to

`"[0 1] [2 3 4]"`

**Comment by yaxu** [comment]
Ok here's a first go:
https://github.com/tidalcycles/Tidal/commit/27c16779d0250da94b75970e887b53318a95539c

Really I think `unwrap` is a nicer name than `joinPattern` so will probably change it back!

**Comment by yaxu** [comment]
In particular it breaks `m >>= return ≡ m`

`p` and `p'` should be the same
```
*Sound.Tidal.Pattern> let p = fastCat [pure "a", pure "b"]
*Sound.Tidal.Pattern> let p' = p >>= return
*Sound.Tidal.Pattern> query p (0,1)
[(((0 % 1,1 % 2),(0 % 1,1 % 2)),"a"),(((1 % 2,1 % 1),(1 % 2,1 % 1)),"b")]
*Sound.Tidal.Pattern> query p' (0,1)
[(((0 % 1,1 % 1),(0 % 1,1 % 2)),"a"),(((0 % 1,1 % 1),(1 % 2,1 % 1)),"b")]
```

**Comment by yaxu** [comment]
I guess the second option is best then, and mirrors the change to `<*>` - there structure comes from both sides, and here structure comes from both the inner and outer pattern.

**Comment by yaxu** [comment]
Still far from right, e.g.

`rotR 0.25 (pure "a")` gives this as you'd expect
```
[(((-3 % 4,1 % 4),(0 % 1,1 % 4)),"a"),
 (((1 % 4,5 % 4),(1 % 4,1 % 1)),"a")
]
```

but `(~>) 0.25 (pure "a")` (which uses unwrap to patternify its first parameter) gives this, with incorrect 'wholes':
```
[(((0 % 1,1 % 4),(0 % 1,1 % 4)),"a"),
 (((1 % 4,1 % 1),(1 % 4,1 % 1)),"a")
]
```

**Comment by yaxu** [comment]
OK this is because `temporalParam` needs to `unwrap` based on `*>`, not `<*>`. It seems there are bugs in `<*` and `*>` though..

**Comment by yaxu** [comment]
Ok I made `innerJoin` and `outerJoin` now, slightly worried that I'm re-inventing SQL
