### ISSUE TITLE
Can't update Tidal (problems with hosc-0.16?)

### ISSUE THREAD

**Issue by ardanchess** [tidalcycles/Tidal#343]
Hi everyone!
I have a problem while trying to reinstall an updated version of Tidalcycles.

My environment:
- OSX Yosemite 10.10.5
- Haskell 8.4.3

I state that I have already solved some first problems related to that message
"clang: error: unknown argument: '-no-pie'
`gcc' failed in phase `C Compiler'. (Exit code: 1)" 
...according to this issue already reported: https://github.com/tidalcycles/Tidal/issues/309
Everything seems to work properly at that time. 
The I tried to use tidal-bootstraps and this is what comes out: 

Checking packages..
Checking if tidal package is installed..
WARNING: cache is out of date: /Library/Frameworks/GHC.framework/Versions/8.4.3-x86_64/usr/lib/ghc-8.4.3/package.conf.d/package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
Installing tidal..
Resolving dependencies...
In order, the following will be installed:
hosc-0.16 (via: tidal-0.9.10) (new package)
mersenne-random-pure64-0.2.2.0 (via: tidal-0.9.10) (new package)
safe-0.3.17 (via: tidal-0.9.10) (new package)
stm-2.4.5.1 (via: streaming-commons-0.2.1.0 async-2.2.1) (new version)
async-2.2.1 (via: streaming-commons-0.2.1.0) (reinstall) (changes: stm-2.4.5.0
removed)
streaming-commons-0.2.1.0 (via: websockets-0.12.5.1) (new package)
websockets-0.12.5.1 (via: tidal-0.9.10) (new package)
tidal-0.9.10 (new package)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Downloading hosc-0.16...
Configuring mersenne-random-pure64-0.2.2.0...
Configuring safe-0.3.17...
Configuring stm-2.4.5.1...
Invalid package hosc-0.16
Could not install tidal!
Checking if tidal atom package is installed..
✓ ├── tidalcycles@0.12.1
Checking if SuperDirt quark is installed..
✓ /Users/Ardan/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt
Sorry, all packages could not be installed
Tidal cabal package could not be installed
Visit: http://tidalcycles.org/getting_started.html and install them using the instructions found there
logout

So I tried with cabal install tidal and again, this: 

Resolving dependencies...
In order, the following will be installed:
hosc-0.16 (via: tidal-0.9.10) (new package)
mersenne-random-pure64-0.2.2.0 (via: tidal-0.9.10) (new package)
safe-0.3.17 (via: tidal-0.9.10) (new package)
stm-2.4.5.1 (via: streaming-commons-0.2.1.0 async-2.2.1) (new version)
async-2.2.1 (via: streaming-commons-0.2.1.0) (reinstall) (changes: stm-2.4.5.0
removed)
streaming-commons-0.2.1.0 (via: websockets-0.12.5.1) (new package)
websockets-0.12.5.1 (via: tidal-0.9.10) (new package)
tidal-0.9.10 (new package)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Downloading hosc-0.16...
Configuring safe-0.3.17...
Configuring stm-2.4.5.1...
Configuring mersenne-random-pure64-0.2.2.0...
Invalid package hosc-0.16

Seems that this hosc-0.16 package doesn't work somehow, I always get that "invalid package hosc-0.16" message.
Can you please help me? 
Thank you a lot! 

<img width="1208" alt="schermata 2018-09-22 alle 03 19 59" src="https://user-images.githubusercontent.com/43485095/45911656-98634280-be16-11e8-9ea6-fc8bef62f4f1.png">
<img width="712" alt="schermata 2018-09-22 alle 03 20 12" src="https://user-images.githubusercontent.com/43485095/45911657-9a2d0600-be16-11e8-82de-f4672b942f03.png">

**Comment by yaxu** [comment]
Hi @ardanchess, I've not seen this 'Invalid package' message before. Perhaps something got corrupted.

Try deleting the '.cabal' and '.ghci' subfolders in your home folder, and then trying to install tidal again with `cabal update; cabal install tidal`.

**Comment by ardanchess** [comment]
Just tried. 
Cabal update shows me no problems, but  cabal install tidal seems to went even worse and I've got all these error messages:

Resolving dependencies...
In order, the following will be installed:
async-2.2.1 (via: streaming-commons-0.2.1.0) (reinstall) (changes: stm-2.4.5.0
-> 2.4.5.1)
hosc-0.16 (via: tidal-0.9.10) (new package)
mersenne-random-pure64-0.2.2.0 (via: tidal-0.9.10) (new package)
streaming-commons-0.2.1.0 (via: websockets-0.12.5.1) (new package)
websockets-0.12.5.1 (via: tidal-0.9.10) (new package)
tidal-0.9.10 (new package)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring async-2.2.1...
Configuring hosc-0.16...
Configuring mersenne-random-pure64-0.2.2.0...
Building async-2.2.1...
Building mersenne-random-pure64-0.2.2.0...
Building hosc-0.16...
Failed to install async-2.2.1
Build log ( /Users/Ardan/.cabal/logs/ghc-8.4.3/async-2.2.1-L8kwiDA2On8GhMo9CY3lJ3.log ):
cabal: Entering directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29396/async-2.2.1'
Configuring async-2.2.1...
Preprocessing library for async-2.2.1..
Building library for async-2.2.1..
<command line>: cannot satisfy -package-id hashable-1.2.7.0-3hrKWzET808E40baaqgc23
    (use -v for more information)
cabal: Leaving directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29396/async-2.2.1'
Failed to install hosc-0.16
Build log ( /Users/Ardan/.cabal/logs/ghc-8.4.3/hosc-0.16-DPOmbWars0W1xD4iUMwtas.log ):
cabal: Entering directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29397/hosc-0.16'
Configuring hosc-0.16...
Preprocessing library for hosc-0.16..
Building library for hosc-0.16..
<command line>: cannot satisfy -package-id network-2.6.3.5-6joSpwHklnzHDdmASCHqXt
    (use -v for more information)
cabal: Leaving directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29397/hosc-0.16'
Failed to install mersenne-random-pure64-0.2.2.0
Build log ( /Users/Ardan/.cabal/logs/ghc-8.4.3/mersenne-random-pure64-0.2.2.0-E6ept8G0XXGA5R07cmwcnH.log ):
cabal: Entering directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29398/mersenne-random-pure64-0.2.2.0'
Configuring mersenne-random-pure64-0.2.2.0...
Preprocessing library for mersenne-random-pure64-0.2.2.0..
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: argument unused during compilation: '-finline-functions'
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
Building library for mersenne-random-pure64-0.2.2.0..
<command line>: cannot satisfy -package-id random-1.1-7T1TXpwb46H1j0av1OnVaD
    (use -v for more information)
cabal: Leaving directory '/var/folders/fk/vw4h7t054hn3j820cp7gqlyh0000gn/T/cabal-tmp-29398/mersenne-random-pure64-0.2.2.0'
cabal: Error: some packages failed to install:
async-2.2.1-L8kwiDA2On8GhMo9CY3lJ3 failed during the building phase. The
exception was:
ExitFailure 1
hosc-0.16-DPOmbWars0W1xD4iUMwtas failed during the building phase. The
exception was:
ExitFailure 1
mersenne-random-pure64-0.2.2.0-E6ept8G0XXGA5R07cmwcnH failed during the
building phase. The exception was:
ExitFailure 1
streaming-commons-0.2.1.0-AUnV9kPsGiCI9J62TJeX9p depends on
streaming-commons-0.2.1.0 which failed to install.
tidal-0.9.10-JS0sxreQGxR4EQzAgMqtK1 depends on tidal-0.9.10 which failed to
install.
websockets-0.12.5.1-Fw2DBBUQIkwELbkCCQ8IOb depends on websockets-0.12.5.1
which failed to install.

**Comment by rencamp96** [comment]
i have the same error

**Comment by yaxu** [comment]
Please re-open this if you still have issues.
