### ISSUE TITLE
wchoose

### ISSUE THREAD

**Issue by danielmkarlsson** [tidalcycles/Tidal#346]
I like `choose`. 
Things starts out fine. But then later, I get into trouble: 

```d1 $ s "house*10" # n (choose [0,1]) # cut 1```

```d1 $ s "house*10" # n (choose [0,0,0,0,0,0,0,0,0,0,1]) # cut 1```

```
d1 $ s "house*10" # n (choose [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]) # cut 1
```

Here is a solution tho:

```
let wchoose values weights = choose $ concatMap (\x -> replicate (snd x) (fst x)) (zip values weights)
```

```d1 $ s "house*10" # n (wchoose [1,0] [1,1]) # cut 1```

```d1 $ s "house*10" # n (wchoose [1,0] [1,10]) # cut 1```

```d1 $ s "house*10" # n (wchoose [1,0] [1,100]) # cut 1```

The likeliness of stochastic operations occurring is something I care deeply about. 
Please include `wchoose` in TidalCycles.

**Comment by yaxu** [comment]
How about grouping weights with values? `wchoose [(1,1),(0,100)]`

**Comment by danielmkarlsson** [comment]
Sure!
I'm not picky at all about how it is expressed in terms of syntax.
The added functionality is where I'm at.
What do you think?
Would you consider including this functionality?

**Comment by calumgunn** [comment]
I've been using this particular function for years now also, would like to see it being useful for others!

**Comment by yaxu** [comment]
Ok here's a version that groups them
```
let wchoose :: [(a, Double)] -> Pattern a
    wchoose xs = filterJust $ (get xs) <$> scale 0 total rand
      where total = sum $ map snd xs
            get [] n = Nothing
            get (x:[]) n = Just $ fst x
            get ((v,n'):xs) n | (n-n') < 0 = Just v
                              | otherwise = get xs (n-n') 
```
I'm wondering whether it feels better to group them like `(value,weight)` or `(weight,value)`

**Comment by calumgunn** [comment]
The `Pwrand` Pattern function in Supercollider seems a good base - it uses `(weight,value)`.
Docs: http://doc.sccode.org/Classes/Pwrand.html

**Comment by calumgunn** [comment]
Whoops, I think I got myself the wrong way round there! `(value, weight)` is what I _meant_, sorry!

**Comment by danielmkarlsson** [comment]
Wonderful in that case we both agree on `(value,weight)`.

Also Alex it seems that I am getting some rather surprising results here:

```
let wchoose :: [(a, Double)] -> Pattern a
    wchoose xs = filterJust $ (get xs) <$> scale 0 total rand
      where total = sum $ map snd xs
            get [] n = Nothing
            get (x:[]) n = Just $ fst x
            get ((v,n'):xs) n | (n-n') < 0 = Just v
                              | otherwise = get xs (n-n') 

d1
$ s "house*10"
# n (wchoose [(0,1),(10,1)])
```
Compared to:
```
let wchoose values weights = choose $ concatMap (\x -> replicate (snd x) (fst x)) (zip values weights)

d1
$ s "house*10"
# n (wchoose [0,1] [10,1])
```

To my ears it sounds as tho the tenth sample is being chosen instead of the first sample having a tenfold increase in likeliness of occurring.

**Comment by yaxu** [comment]
Ok!

**Comment by yaxu** [comment]
Righto I'll have another look at the logic later
