### ISSUE TITLE
Easier way of making controls

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#347]
Currently making a new control (formerly known as parameter) is a bit fiddly, specifying defaults that are rarely used, etc. It should be as simple as this:

```
let foo = cI "foo" -- integer control
    distortion = cF "distortion" -- float control
    envname = cS "envname" -- string control
```

Then you could more easily use them inline, e.g.
```
sound "bing*8" # cF "distortion" sine
```

I don't know if there's a way of making it even easier than that..

**Comment by cannc4** [comment]
if you could do a type check(or alike) behind the scenes for each `#` you could prepend `cF` to it before it gets to the parser .. not sure how it would work in Haskell though.

**Comment by yaxu** [comment]
This would be great, Haskell is good at inferring types.. I think it could guess for example the type if you did `c "distortion" sine`, because sine is a pattern of floats. It couldn't really guess that `c "envname" "<a b>"` was about string control though.
