### ISSUE TITLE
chooseBy - choose how to make choices

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#348]
`choose` uses `rand` internally. It'd be useful to be able to provide alternative ways to make choices, for example `chooseBy sine [1,2,3,4]` or `chooseBy (discretise 0.25 rand) [1,2,3,4]`. Same for making a `wchooseBy` for `wchoose`.

**Comment by danielmkarlsson** [comment]
I've tried running the example and I can get it to make a sound but the resultant pattern is static.
I expected there to be stochastic choices and things changing over time.

Could you walk me through what happens in your example bgold-cosmos?

**Comment by yaxu** [comment]
Thanks a lot @bgold-cosmos, that's neater than my attempt. I swapped it around a bit:
```
wchooseBy :: Pattern Double -> [(a,Double)] -> Pattern a
wchooseBy pat pairs = match <$> pat
  where
    match r = values !! ((findIndices (> r) cweights) !! 0)
    cweights = scanl1 (+) (map snd pairs)
    values = map fst pairs
```

**Comment by yaxu** [comment]
@danielmkarlsson you can swap the `sine` bit with a random pattern, putting your discretise in there, e.g.:
`d1 $ s (wchooseBy (discretise 0.25 rand) [(0.3, "bd"), (0.7, "sn:2")])`
