### ISSUE TITLE
'Ramping' continuous patterns

### ISSUE THREAD

**Issue by OscarSouth** [tidalcycles/Tidal#350]
This has been a holy grail of mine for some time and something that I've tried to implement myself as a function (and failed). I haven't found that it 'fits' well with the cyclic nature of TidalCycles, but it would be very useful in musical performance. Perhaps it's possible and I just need to look harder, but as there's a push forward with TidalCycles happening at the moment I thought I'd share it.

What I'm trying to achieve is a smooth 'ramp' from one static value to another over a period of time (and then remain on the new value). I'd personally use it for modulating the pitch of external sampled instruments or for smooth transitions of external synth parameters. It feels logical to exist as a transition function.

**Comment by yaxu** [comment]
There is an experimental 'interpolate' transition that does this now

**Comment by OscarSouth** [comment]
I'll have a play with `interpolate`. Also, the updates proposed in the pull request here: (https://github.com/tidalcycles/Tidal/pull/473) following discussion on Lurk here: (https://talk.lurk.org/channel/tidal?msg=HDpMTCRXq6hh9K2F8) also make this functionality possible using the `onceFor` function in that PR.
