### ISSUE TITLE
testcase/showcase: the "deep note"

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#352]
Accidentally I found this http://earslap.com/article/recreating-the-thx-deep-note.html about re-creating a specific sound in supercollider. It would be nice to express this in the Tidal language. 
I have no doubt that it can be done - the challenge is to do it in a nice (readable) way.

**Comment by yaxu** [comment]
It would be easy to just use the supercollider version and trigger it from tidal :)

**Comment by jwaldmann** [comment]
that's cheating .. no, I was thinking, we have the Power of Haskell, can use higher-order functions, etc.

**Comment by yaxu** [comment]
Closing this for now as it's about using tidal rather than an issue with tidal itself, would be nice to see a solution though! Probably better as a forum post. https://forum.toplap.org/c/communities/tidalcycles
