### ISSUE TITLE
Doing without the parser

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#353]
The mini-language for sequences frequently annoys people coming to tidal from the functional programming side. I don't really understand this feeling, but think it could be a nice exercise - how would tidal look without the parser? Well, @sleexyz made a tidal-inspired thing without one: https://github.com/sleexyz/syzygy

and of course just about anything you can do in the parser you could do without it..

for example this: `"[bd sn:2?] ~ cp*3"`

could be made with this: `cat [cat [s "bd", degrade $ s "sn" # n "2"], silence, s $ fast 3 "cp"]`

a bit fiddly.. but does it have advantages, and could it be improved?

**Comment by yaxu** [comment]
Maybe Template Haskell is the way forward? https://wiki.haskell.org/A_practical_Template_Haskell_Tutorial#Template_Haskell_for_building_Embedded_Domain_specific_Languages_.28EDSLs.29

**Comment by telephon** [comment]
couldn't all syntactic structures be described directly as functions?

**Comment by yaxu** [comment]
One problem is polyrhythm. `polystack [fastcat [1, 2, 3], fastcat [4,5] ]` can't really represent the same as `"{1 2 3, 4 5}"`, because the structure of `fastcat [1,2,3]` and `fastcat [1,2,3]` is locked away inside functions of time..

Some syntactic sugar like `[]` can be overridden to some extent.. But `[1, 2 [3, 4]]` wouldn't be possible afaik. Neither would `[1 2]` (without a comma) or `[a,b]` (if you wanted `a` and `b` to be a bareword).

The main criticism of having a parser in tidal seems to be that the parsed language isn't typesafe.. But I don't understand this, how is it not typesafe?

Maybe there's a misunderstanding.. I can see that if you thought tidal really was passing strings around and manipulating them that would be a strange approach. But what it's actually doing is immediately parsing the string into a function of time, which seems to me to be a *more* FP-oriented approach to representing music with lists.

**Comment by telephon** [comment]
Sorry, I am being (hopefully helpfully) naive. But if one would represent `[1, 2 [3, 4]]` as, say, `p([1, 2, p([3, 4]))`, couldn't the function `p` construct this polyrhythm?

**Comment by yaxu** [comment]
I might be getting confused between polyrhythm and polymeter again. That would be `stack [1, fastcat [2, stack [3, 4]]]`

That takes advantage of class instance magic to avoid having to do `stack [pure 1, fastcat [pure 2, stack [pure 3, pure 4]]]`

What you can't do is `{2, 3 4}`, without explicitly slowing down the second part, i.e. `stack [2, slow 2 $ fastcat [3, 4]]`
You can't match up events like that once they're time varying values. The parser does it while they're still lists.

**Comment by yaxu** [comment]
Here's someone incredibly annoyed by tidal's parser: https://www.reddit.com/r/programming/comments/8vwih0/i_use_haskell_to_write_music/e6unqs9/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage

Hopefully they'll explain what they're annoyed by at some point..

**Comment by bgold-cosmos** [comment]
Since it doesn't seem to have much support, I'd like to chime in as really very much liking having the mini-language around.  IMO it's somewhat like the regex language or string formatting syntax - a foreign thing embedded in another programming language because it's very compact and good at doing one thing.  You could do without it, but why?

**Comment by yaxu** [comment]
Yes agreed, I'm definitely not in favour of getting rid of the mini-language either. It's based on some great research into representation of Tabla rhythm by Bernard Bel (via BP2), and is a big part of what tidal is.

Reimplementing it in template haskell could be a possibility, but I don't see the point in doing that. But still, maybe a useful thought experiment, to see if other parts of tidal could be less verbose.
