### ISSUE TITLE
Combining structure and values

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#357]
It'd be nice to have a simple ways fill the structure from a pattern with values. So:

 `newFunction [1,2] "x(5,8)"` is the same as "1 ~ 2 1 ~ 2 1 ~"`

The list would be applied afresh each cycle (i.e. the next cycle in this case wouldn't start with `2`)

**Comment by bgold-cosmos** [comment]
Apart from the "applied afresh each cycle" this is like the pattern replace family, e.g.

`notQuiteNewFunction list pat = preplace1 pat (listToPat list)`

I think to get the "applied afresh" takes a bit of trickery

```newFunction list pat = Pattern $ \a -> arc (almostNewFunction list pat) (arcToFirst a) where 
    arcToFirst (s,e) = (s - (fromIntegral . floor) s, e- (fromIntegral . floor) (e-1e-6))
```

**Comment by bgold-cosmos** [comment]
OK, that previous definition didn't actually work, but this one does (and is a little simpler)

```
newFunction list pat = Pattern $ \a@(s,e) -> 
  arc (rotR (fromIntegral $ floor s) $ notQuiteNewFunction list pat) a
```

**Comment by yaxu** [comment]
Aha thanks @bgold-cosmos, I can see the strong relation to `prrw` and friends now. It'd be good to work understand all the tradeoffs involved in case there are adjustments to be made during the refactor. This is difficult stuff though!

As I understand it, `preplace1` only uses the first cycle (or cycles) of the pattern. I guess there is a big trade off here, either you lose the long-form structure of the pattern, or you have difficulty with the lack of state.

That's where the 'applying the list afresh each cycle' thing came from - the lack of state. It's not something I desire in particular, but something I thought would be necessary.. Because when you calculate events for one query you don't really know what happened the previous query. Calculating a whole cycle in order to query a part of it seems reasonable, calculating a whole timeline seems less reasonable, at least for a core function like this.

I was thinking the values should be provided as a list, because the structure isn't used, the values are contiguous and two values can't happen at the same time - not much like patterns. I guess one reason for doing so is to use some of the shorthands of the parser, so perhaps we should make a separate parser for lists.. This seems a bit like feature creep though..

`<|` and `|>` are related to this discussion, they take values from the left and structure from the right, and vice-versa, respectively. This is kind of what we're doing here, but with an alternative algorithm for matching events with values. `<|` and `|>` work by aligning events timewise, but we want to align events stepwise. Because we're dealing with functions of time rather than lists, this is difficult..

Maybe we should add sibling operators, say `<!` and `!>`, which try to match things stepwise, with calculation limited to each cycle. So e.g. `"x <[x x] x> x" !> "1 2 3 4"` would give the equivalent of `"[1 2 3 1 [2 3] 4]/2"`.

Then if you wanted the scope of calculation for to happen over more than one cycle you could combine these operators with e.g. `inside 3` to expand the period of calculation to three cycles.

**Comment by yaxu** [comment]
Not really sure where I was going with this one.
