### ISSUE TITLE
Adding Speech Synthesis?

### ISSUE THREAD

**Issue by JeremyRubin** [tidalcycles/Tidal#37]
Just a fun idea... would be neat if from the pattern you could specify a word/phrase type and then be able to pass it to `say`, so you could get speech synthesis for live loops.

Let me propose the following syntax....

"@(say what you want to say, optional: synth name) "

By writing them to a special sample/speech dir, say would only need to be used for new phrases.

Thoughts?

**Comment by telephon** [comment]
In SuperDirt, you could probably add a diversion (see hacks/function-hacks.scd) to use the OS's speech synthesizer.

**Comment by lennart** [comment]
also a good question for ask.tidalcycles.org

I'd think we could close it as an issue here.

**Comment by vivid-synth** [comment]
I'd personally be against the "@" syntax -- "@" would be nice to have for other things, and syntax can get cluttered fast.

If you want, you can always make a hack with e.g.:

> s "here is my sentence" # n "speech"

**Comment by bgold-cosmos** [comment]
Hmm, looks like there might be some experimental speech in SuperCollider?  I'll have to poke around with that.

I think it would be really great if it could be "singing" speech synthesis using the midinote for pitch.  And to be in line with other softsynths, the syntax might be something like:

`n "c e g" # s "superspeech" # text "doo dee doo"`

**Comment by telephon** [comment]
in supercollider, speech is just being deprecated, because it isn't platform independent. But there will be a quark library that will keep this functionality.

So yes, just make a diversion, examples are in the folder `hacks/function-hacks.scd`

**Comment by vivid-synth** [comment]
Note though that if you use OS-level speech it'll be totally separate sound output. E.g. you won't be able to put effects on it.

**Comment by yaxu** [comment]
Opened this on SuperDirt https://github.com/musikinformatik/SuperDirt/issues/94
closing here..
