### ISSUE TITLE
More minilanguages?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#370]
e.g. an ixilang inspired one, where space = time

**Comment by yaxu** [comment]
Yes ixilang is based on a pre-determined beat duration in a similar way. 

`[ixi|oxox o x ]" would be the same as something like `s "{bd sn bd sn ~ bd ~ sn ~ }%4"`, where symbols map to samples. There'd need to be a configurable list of them, somewhere.

**Comment by kindohm** [comment]
or a way to redefine the symbol mapping on the fly? Also, I think it would be good if different patterns could have different amounts of "space" but keep the same time division. e.g. one pattern have 16 steps and another have 15 steps, but the notes play at the same time. like how `{...}%16` works. I don't know ixilang syntax but something like:

```
[ixi|oxox o x ]
[ixi|h hhh h  h  ]
[ixi|   bb    bb   bb b]
```

**Comment by yaxu** [comment]
Yep agreed, that is how ixi works. I guess the beat duration would have to be configurable somewhere.

**Comment by yaxu** [comment]
Closing speculative issues (we can still find them via the tag)
