### ISSUE TITLE
Would it be possible to have the values in the polyrythmic/polymeter syntax `{}%x` become patternable ?

### ISSUE THREAD

**Issue by ArthOrban** [tidalcycles/Tidal#379]
I would like to pattern the value of the {}%, using something like

`d3  $ s "~ superpiano" # n  "{5 7 0 7 9}%<1 3>"`.

But then, in order to work like other patterns, shouldn't you be also able to write like this ?

`d3  $ s "~ superpiano" # n  "{5 7 0 7 9}%( slow 2 $ "[4, <3 5>]")"`.

I don't know how useful would that be.

and then you have problem of quotation marks inside quotation marks, and I don't think that works.

I have though about it, and came up with a snippet that I think could accomplish something similar
`d3 $ s "~ superpiano" # n (every 4 ((slow 2 $ "<2 3>"/5) <~) $ "{5 7 0 7 9}%1")`.

**Comment by yaxu** [comment]
`{1 2 3}%<1 3>` is fixed in https://github.com/tidalcycles/Tidal/commit/50f11a200c3258eb5aa9d9932702b110b3a385e0
you can't embed tidal code inside the mininotation unfortunately
