### ISSUE TITLE
timeLoop doesn't seem to work right with patterns

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#385]
The second cycle doesn't sound like `timeLoop 2`, but maybe the first one slowed down?

```
d1 $ timeLoop "<1 2>" $ sound "bd*8" # speed rand
```

**Comment by yaxu** [comment]
Still the case..

**Comment by yaxu** [comment]
```
timeLoop n = outside n loopFirst
```
So either a problem with 'outside' or ''loopFirst'..

**Comment by yaxu** [comment]
If I redefine `outside` in terms of versions of fast / slow that don't have patterned parameters, it seems to work:
```
_inside n f p = _fast n $ f (_slow n p)
_outside n = _inside (1/n)
outside np f p = innerJoin $ (\n -> _outside n f p) <$> np
timeLoop n = outside n loopFirst
```
I don't really understand why the original breaks so spectacularly though. I fear there is an underlying bug/misunderstanding. Insights welcome!

**Comment by ndr-brt** [comment]
Could be because in the current inside:
```inside n f p = density n $ f (slow n p)```
the "patternization" of the parameter `n` is done two different times? (one in the `density` and one in the `slow`).
I'm not sure about what I wrote, but could be this the issue?
