### ISSUE TITLE
Cabal sandboxes

### ISSUE THREAD

**Issue by msp** [tidalcycles/Tidal#395]
Should we be using sandboxed installs ?

http://coldwa.st/e/blog/2013-08-20-Cabal-sandbox.html

Seems like it would be a sensible step towards #282 & friends.

**Comment by yaxu** [comment]
Please do - I haven't got my head around it but it seems there's a new thing in the form of `cabal new-install`, seems like it is intended as the 'next generation' of cabal sandbox. It seems the latest haskell release encourages people to use that - which has lead to confusion and brokenness, but probably can be used for good if we could understand it!

**Comment by yaxu** [comment]
Closely related - #405

**Comment by yaxu** [comment]
Closing for now, I think the new-style stuff replaces sandboxes. I still can't get the new-style stuff to work reliably though #572
