### ISSUE TITLE
Timing issues with 1.0.0

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#400]
The default 100Hz calculation rate default leads to high CPU with some patterns, e.g.

```
d1 $ fix ( fast 2 ) (pF "cc64" 1)
   $ fix ( # crush 4 ) (pF "cc65" 1)
   $ fix ( stut' 4 (0.125/4) ( + up "1" )) (pF "cc66" 1)
   $ fix ( |*| speed "-1" ) (pF "cc67" 1)
   $ fix ( (# delaytime 0.125).(# delay 0.5)) (pF "cc68" 1)
   $ fix ( # coarse 12) (pF "cc69" 1)
   $ s "[808bd:1(3,8), dr(7,8)]"
   #  pF "cc64" (cF 0 "64")
   #  pF "cc65" (cF 0 "65")
   #  pF "cc66" (cF 0 "66")
   #  pF "cc67" (cF 0 "67")
   #  pF "cc68" (cF 0 "68")
   #  pF "cc69" (cF 0 "69")
```

If you drop to 10Hz then cpu drops but timing goes awry - looks like there's something wrong with advanced scheduling.

**Comment by yaxu** [comment]
We should

- Decrease the default calculation rate
- Make it configurable via BootTidal.hs (currently an environment variable)
- Fix the timing

**Comment by echophon** [comment]
Testing this code again today, I see baseline performance on ghc to be around 0.1% cpu (one basic pattern playing)

With one stut' transformation (as above) the performance load of ghc degrades significantly to 10-13% cpu.  But it plays as expected.  Adding a second stut' transformation does not change the cpu performance much more, but immediately starts late messages to accumulate in SC & a perceived tempo shift to half the original amount (or more).

**Comment by yaxu** [comment]
Looking at profiling, I made this:
```
{-# LANGUAGE OverloadedStrings #-}

import Sound.Tidal.Context
import Control.Concurrent (threadDelay)

main = do tidal <- startTidal (superdirtTarget {oLatency = 0.04}) defaultConfig
          streamReplace tidal "1" p
          threadDelay $ 1000000 * 3

p = fix ( fast 2 ) (pF "cc64" 1)
    $ fix ( # crush 4 ) (pF "cc65" 1)
    $ fix ( stut' 4 (0.125/4) ( + up "1" )) (pF "cc66" 1)
    $ fix ( |*| speed "-1" ) (pF "cc67" 1)
    $ fix ( (# delaytime 0.125).(# delay 0.5)) (pF "cc68" 1)
    $ fix ( # coarse 12) (pF "cc69" 1)
    $ s "[808bd:1(3,8), dr(7,8)]"
    #  pF "cc64" (cF 0 "64")
    #  pF "cc65" (cF 0 "65")
    #  pF "cc66" (cF 0 "66")
    #  pF "cc67" (cF 0 "67")
    #  pF "cc68" (cF 0 "68")
    #  pF "cc69" (cF 0 "69")
```
Here's the profiling output:
```
alex@stanage:~/src/tidal/perf$ ./test +RTS -sstderr
Listening for controls on 127.0.0.1:6010
   5,284,931,576 bytes allocated in the heap
      48,944,832 bytes copied during GC
         106,664 bytes maximum residency (5 sample(s))
          51,768 bytes maximum slop
               2 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     10154 colls,     0 par    0.104s   0.103s     0.0000s    0.0004s
  Gen  1         5 colls,     0 par    0.002s   0.002s     0.0003s    0.0009s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    2.451s  (  2.897s elapsed)
  GC      time    0.106s  (  0.105s elapsed)
  EXIT    time    0.009s  (  0.009s elapsed)
  Total   time    2.569s  (  3.010s elapsed)

  %GC     time       4.1%  (3.5% elapsed)

  Alloc rate    2,155,847,757 bytes per MUT second

  Productivity  95.9% of total user, 96.5% of total elapsed
```
I think all this tells us so far is that garbage collection (GC) isn't the main culprit..

**Comment by cannc4** [comment]
I don't really think the problem is caused by `stut` or any sort of delay operation but rather the `fix` function or perhaps the `%` notation

as an example 
```
d1 
$ fix ((# orbit 0).(#pan "0.0")) (n "0") 
$ fix((# orbit 1).(#pan "0.0")) (n "1") 
$ fix((# orbit 2).(#pan "0.0")) (n "2") 
$ fix ((# orbit 3).(#pan "0.0")) (n "3") 
$ fix ((#orbit 4).(#pan "0.5")) (n "4") 
$ fix ((#orbit 4).(#pan "0.5")) (n "5") 
$ off 0.5 (#s "drum2")  $nToOrbit  $ n "{0 <~ 0> <1 [ 1 1]> ~, 3*2 [3 3] ,2}%5" 
# s "drum1" 
```

**Comment by echophon** [comment]
I suspect it's the matching portion of `fix` being applied at high rates, which is compounded by multiple `fix` operations.  This lines up with the original assessment. This minimal pattern below is complicated only by fix but shows a cpu increase of 3%

```
d1 
$ fix ( # up 1 )(n "0")
$ fix ( # up 2 )(n "1")
$ fix ( # up 3 )(n "2")
$ fix ( # up 4 )(n "3")
$ fix ( # up 5 )(n "4")
$ fix ( # up 6 )(n "5")
$ fix ( # up 7 )(n "6")
$ fix ( # up 8 )(n "7")
$ n (run(8))
# s "808"
```

**Comment by cannc4** [comment]
I was using the function mentioned in #345 for a quite while and didn't experience any CPU spikes. perhaps we could just make that function play well with 1.0 as it was already quite useful w/o eating up the CPU

**Comment by yaxu** [comment]
Looking at this more the timing is fine, as long as latency is increased to be more than the calculation period

**Comment by yaxu** [comment]
Calculation rate is configurable now via `cFrameTimespan`:
  https://userbase.tidalcycles.org/index.php/Configuration#Frame_timespan

I dropped the default to 0.05 (20Hz)
