### ISSUE TITLE
Piano keyboard MIDI in via SuperCollider using cP seems to break Tidal

### ISSUE THREAD

**Issue by efairbanks** [tidalcycles/Tidal#404]
**The bug**
I'm capturing MIDI in from a MIDI keyboard and sending it to Tidal over OSC via SuperCollider. I am formatting the note values like so: `[]` `[0, 3, 7]` etc... When re-executing the Pattern, the sub-Pattern that uses these note values seems to vanish and become inaudible.

**To Reproduce**
1. Download [my project](https://drive.google.com/file/d/1N1I9UizE59SdZ5bPJcaulLVyGZctpWvC/view?usp=sharing).
2. Connect a MIDI keyboard to your computer.
3. Run `main.scd` and `main.tidal`.
4. Mess with the pattern as outlined in the comments in `main.tidal`.
5. Observe that the synth seems to cut out upon subsequent _(3rd or 4th)_ Pattern re-execution.

**Expected behavior**
When keys are pressed on the MIDI keyboard, those notes should be sent through `cP` and played by TidalCycles.

**Video**
Here's [a video of what I'm trying to do](https://photos.google.com/share/AF1QipNLonajeG8PqPi9AXpBDPxfVtepFUFpBs-ena3ucVteJSXfAbKX-7T8eZioNWuR0w?key=Sjh1bERWYkNreDJydHY4Tl9BdE9ncmFwY2RSVDJ3), ending with the bug.

**Environment (please complete the following information):**
 - OS: MacOS
 - Haskell version: 8.0.2
 - Tidal version: 1.0
 - SuperCollider version: 3.9dev

**Comment by efairbanks** [comment]
Update #2:

The behavior that I'm seeing now is that instead of `cP` ceasing to function wholesale, if a message is not received by Tidal for some time, there is a 1+ second delay between the packet being sent and Tidal's response. Once it responds to this, it seems to update in a timely manner until there is an elongated break in the OSC messages being sent.

**Comment by yaxu** [comment]
Can you check with a packet sniffer whether the problem is SC not sending out the packets, or tidal not processing them?

**Comment by yaxu** [comment]
I think this was down to an old version of superdirt
