### ISSUE TITLE
Multi-process tidal (tempo sharing)

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#412]
Tidal currently only works as a single (multithreaded) process. There is some code towards OSC tempo sharing but it's not working yet.
Meanwhile @d0kt0r0 is working on ESPgrid support, but multiple tidal processes running on the same computer should be able to share tempo sync with each other over OSC as the old websocket-based code used to.

**Comment by d0kt0r0** [comment]
Contextual question here: do people really run separate Tidal processes on the same computer, as in separate launches of ghci? Trying to understand that use case better.

**Comment by yaxu** [comment]
In 0.9.x, each d1, d2 etc is a separate process, sharing tempo over the network.
Things are a bit more clever in 1.0.0, but there still might be the case that you have two editors running at once for example, or a separate process that simply visualises the tempo/cycle number. No beta testers have been demanding this so far but I still think it would be worth getting in place before releasing 1.0.0. The work is mostly done

**Comment by yaxu** [comment]
Looking at this now
