### ISSUE TITLE
TidaLink support in 1.0.x

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#414]
**Describe the bug**
TidaLink does not work with Tidal-1.0.0

**To Reproduce**
1. Install and run TidaLink
2. Run Tidal
3. Tidal tempo does not follow TidaLink

**Expected behavior**
Tidal should follow the tempo set by TidaLink or by extension the "Link" network.

**Environment (please complete the following information):**
 - OS: Mac
 - GHC 8.2.X 
 - Tidal-1.0.0 / master
 - SuperCollider-1.0 dev / master

**Additional context**

Tidal-1.0.0 is developing a different approach to how the tempo of patterns are set, for example:

`p "cps" $ cps 1.5`

Presumably there is still some kind of global clock, or otherwise the individual pattern tempo params can derive from / deviate relative to a Link network..?

**Comment by yaxu** [comment]
Just a correction on one point - there's no plan to have cps defined locally per pattern.

**Comment by yaxu** [comment]
I think this is a small fix to tidalink rather than tidal, will have a look

**Comment by yaxu** [comment]
The next release of sclang will hopefully have link support. https://github.com/supercollider/supercollider/pull/4081

**Comment by jarmitage** [comment]
Good enough for me!

**Comment by yaxu** [comment]
There'll, still be work to do, and tidalink support is still on the card, so reopening for now :)

**Comment by OscarSouth** [comment]
Worth taking into account a tidalink upgrade to the latest Link Kit. Lots of progress has been made there and the newer 'Start/Stop' Link functionality could be very useful.

**Comment by yaxu** [comment]
Rather than fix tidalink I propose we switch focus to carabiner #491
