### ISSUE TITLE
scsynth + tidal

### ISSUE THREAD

**Issue by lennart** [tidalcycles/Tidal#42]
Hi there,

I would like to use Tidal to build patterns to play via dirt and play synths via scsynth, both with the same clock but not necessarily via the same output.

How would one sync Tidal's clock to that of scsynth? Is this currently possible, or what has to be done to make this work? 

best regards,

Lennart

**Comment by yaxu** [comment]
Hi both,
Sorry for long delay!
It would be easy enough to add an option to tidal OSCShapes to give named parameters in this way. I didn't know this was how things are done in scsynth.
Tidal outputs messages in chunks, so timing will be very bad unless you use bundle timestamps. Is this where the 'time' parameter comes from? What's the best way of scheduling with it, or does this just happen magically if bundles are sent to scsynth?

Alexandra Cardenas sent me the below synth, what OSC message should I send to trigger it?

Is this right?

"/s_new", "potato", -1, 1, 1, "vol", 0.3, "freq", 50, "dist", 0.4, "cut", 130, "pos", 0, "atk", 0.01, "rel", 0.1

I guess that'd be siiisfsfsfsfsfsfsf ?

```sc
(
SynthDef(\potato, {| vol=0.3, freq=50, dist=0.4, cut=130, pos=0, atk=0.01, rel=0.1|
	var  sig, filt, pan, out;
	sig=SinOsc.ar(freq, 0, 2).distort*dist;
		filt=LPF.ar(sig, cut, 1);
			pan=Pan2.ar(filt, pos, vol);
	out=pan*EnvGen.ar(Env.perc(atk, rel), doneAction:2);
		Out.ar(0, out);
}).add
);
```

**Comment by yaxu** [comment]
Ah apparently that example from Alex needed some actual potatoes!

But I got it working with this synth:

```sc

(
SynthDef(\hn1, {|vol=1.2, freq=3000, atk=0.01, rel=0.2, pos=0|
	var  sig, rev, filt, env, pan, out;
	sig=WhiteNoise.ar(0.5);
		filt=RHPF.ar(sig, freq, LFDNoise3.kr(0.5).range(0.001, 2) );
			rev=FreeVerb.ar(filt, 0.7, 1);
			  pan=Pan2.ar(rev, pos, vol);
	           env=EnvGen.ar(Env.perc(atk, rel), doneAction:2);
	out=pan*env;
		Out.ar(0, out);
}).add
		);
```
and this OscShape:

```haskell
{-# LANGUAGE NoMonomorphismRestriction #-}

module Cardenas where

import Sound.Tidal.Stream
import Sound.Tidal.Pattern
import Sound.Tidal.Parse
import Sound.OSC.FD

cardenas :: OscShape
cardenas = OscShape { 
  -- The OSC path
  path = "/s_new",
  preamble = [string "hn1", int32 (-1), int32 1, int32 1],
  namedParams = True,
  params = [ F "vol" (Just 1.2),
             F "freq" (Just 3000),
             F "atk" (Just 0.01),
             F "rel" (Just 0.2),
             I "pos" (Just 0)
           ],
  timestamp = BundleStamp,
  latency = 0.04
  }

-- This gives the IP address and port number
cardenasStream = stream "127.0.0.1" 57110 cardenas

vol   = makeF cardenas "vol"
freq  = makeF cardenas "freq"
atk   = makeF cardenas "atk"
rel   = makeF cardenas "rel"
pos   = makeI cardenas "pos"
```

**Comment by yaxu** [comment]
The 'preamble' and 'namedParams' parameters are new.

Then in emacs with tidal loaded I evaluated these lines in turn:

```
:load Cardenas
import Sound.Tidal.Context
d1 <- dirtStream
d2 <- dirtStream
d3 <- dirtStream
d4 <- dirtStream
d5 <- dirtStream
d6 <- dirtStream
c <- cardenasStream
(cps, getNow) <- bpsUtils
let bps x = cps (x/2)
let hush = mapM_ ($ silence) [d1,d2,d3,d4,d5,d6,c]
let solo = (>>) hush
```

(some errors crop up in the middle of that which can be ignored)

And then this works:

```haskell
c $ density 16 $ freq "200 1000 250"
  |+| atk (slow 3 $ scale 0 0.01 sine1)
  |+| rel "0.01"
```

Any suggestions about how to streamline this welcome!

**Comment by yaxu** [comment]
I've now added a generic SuperCollider package, so this works:

```haskell 
(sc, shape) <- scStream "hn1" [ F "vol" (Just 1.2),
                                F "freq" (Just 3000),
                                F "atk" (Just 0.01),
                                F "rel" (Just 0.2),
                                I "pos" (Just 0)
                              ] 0


let vol   = makeF shape "vol"
    freq  = makeF shape "freq"
    atk   = makeF shape "atk"
    rel   = makeF shape "rel"
    pos   = makeI shape "pos"

sc $ vol "0.6"
  |+| rel "1"
```

**Comment by yaxu** [comment]
The `0` there at the end of the first call adds latency -- if dirt and supercollider aren't in sync, you could add an offset here.

If you want `hush` to silence that synth as well as dirt you'd have to redefine hush by evaluating this:

```haskell
let hush = mapM_ ($ silence) [d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,sc]
```

**Comment by lennart** [comment]
Thanks for this, I'll try it. 

Having the ability to setup your own named params was the missing puzzle (I hacked it into my local repo to make dirt + scsynth work in parallel)

**Comment by Djoust** [comment]
Hi,
This works really nice! I'm not using dirt anymore, only my own synths.
I'm playing around with it, and i wanna add a fx synth at the tail of my group or put it in a separate group at the tail of my node tree so it always receives the output of my synths.

I was looking at this line in the Supercollider.sh file: https://github.com/tidalcycles/Tidal/blob/master/Sound/Tidal/SuperCollider.hs#L14

If i change is to: `preamble = [string n, int32 (-1), int32 0, int32 1], ` all synths will go to the head of the group including the fx synth. Is there a way to specify in which group the synths go when you define the synth in tidal?

Best, Joost
