### ISSUE TITLE
Zero denominator kills Tidal process (1.0.0)

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#420]
Any pattern that results in
`ghc: Ratio has zero denominator`
will kill the Tidal process and require a restart.  Examples include
`"cp/0"`
`"cp(5,0)"`
`"cp(5,c)"` (because note parsing kicks in and turns the "c" into "0")

**Comment by yaxu** [comment]
I fixed these specific cases, but couldn't think of a sure way of fixing more generally. if `every 100 (slow 0)` crashed out after 100 cycles (which it wouldn't any more, but for the sake of argument..), what would you do then? Hmm.

**Comment by jwaldmann** [comment]
I am seeing "ratio has zero denominator" for inputs `"{}"` and `"[]"`. Is this still relevant?

**Comment by AleXoundOS** [comment]
It seems I've caught the same exception after executing `setcps (-1)` once or twice...
