### ISSUE TITLE
Pattern and Event structure

### ISSUE THREAD

**Issue by tonyday567** [tidalcycles/Tidal#427]
So Pattern is pretty much a list of Events, once you strip away State and Nature, and an Event is a value, a whole time arc and a partial arc.

That's a lot of whole time arcs for one pattern.  Is a better representation something like this?

```
data Event a = Event { part :: Arc, value :: a }
data Chunk a = Chunk { whole :: Arc, events :: [Event a] }
data Pattern a = Pattern { nature :: Nature, query :: State -> Chunk a }
```

In other words, does any particular [Event] list created from a Pattern inevitably have a single sensible whole Arc?  Is this whole arc the same as State eg `query (State theArc Empty) === Chunk theArc events`?

Another open question I have is whether any particular Event list created from a Pattern would inevitably be sorted on usage.  If this is so, you can almost get another representation of the Chunk of a Pattern as:

```
data Chunk a = Chunk { cuts :: [Time], values :: Map Int a }
```

where the cuts are the boundaries of the partial arcs, and in sorted order, so that the whole arc of the chunk is Arc (head cuts) (last cuts).

So "1 ~ 2" is then `Chunk [0, 1/3, 2/3, 1] (FromList $ [(0,1), (2,2)])`.

This lines up with the commentary in #406: The (+) operator (for the values) would be `Map.unionWith (+)`.

**Comment by yaxu** [comment]
I think each event needs its own part and whole. Here's an example of different events having different parts/wholes:
```
queryArc (slow "1 2" "a b" :: Pattern String) (Arc 0 4)
[(0>½)|"a",
 0-(½>1)|"a",
 (1>1½)|"a",
 1-(1½>2)|"b",
 (2>2½)|"a",
 2-(2½>3)|"a",
 (3>3½)|"a",
 3-(3½>4)|"b"
```
The first half of the pattern is a window on `"a b"`, which is always 'a'.  The second half is a window on `slow 2 "a b"`, which alternates between the second half of `a` and the second half of `b`.

(I think this behaviour was different in 0.9.x, hm!)

**Comment by tonyday567** [comment]
Ok, cool, there's a lot more going on than I can wrap my head around.  Having show be `queryArc x (Arc 0 1)` led me to oversimplify.

**Comment by tonyday567** [comment]
```
let p1 = slow "1 2" "0 1" :: Pattern Double
let p2 = "0 1" :: Pattern Double

queryArc p1 (Arc 0 2)
[(0>½)|0.0,0-(½>1)|0.0,(1>1½)|0.0,1-(1½>2)|1.0]

queryArc (p1 |+| p2) (Arc 0 2)
[(0>½)|0.0,(½>1)|1.0,(1>1½)|0.0,(1½>2)|2.0]

queryArc (p1 |+ p2) (Arc 0 2)
[(0>½)|0.0,0-(½>1)|0.0,(1>1½)|0.0,1-(1½>2)|1.0]
```

I would have thought that |+| would have preserved the p1 structure.  It might help if we can nail down what `structure` means in this context.

The p1 structure seems to be preserved in other cases eg

```
queryArc (p1 |+| ("0" :: Pattern Double)) (Arc 0 2)
[(0>½)|0.0,0-(½>1)|0.0,(1>1½)|0.0,1-(1½>2)|1.0] 
```

**Comment by tonyday567** [comment]
(I think) another way of asking this is why is the arc queried the part (and not the whole) in this line:

https://github.com/tidalcycles/Tidal/blob/master/src/Sound/Tidal/Pattern.hs#L251

And then why the choices of queried arc for all of the digital, Analog combos.

**Comment by yaxu** [comment]
Good questions, I'm certainly not convinced these are right, but would need to set some time aside to think them through.. Open to ideas/analysis!

**Comment by bgold-cosmos** [comment]
The results look correct to me, the confusing thing is that `slow "1 2" "a b"` results in some parts of wholes that don't play (because their onset isn't in the "window" where the `slow 2` part is applying).  But the resulting pattern from `|+|` does seem to be getting the "greatest common substructure" which in this case is just the `"a b"` structure of the right-hand side.

**Comment by yaxu** [comment]
Closing for now, but feel free to reopen if you think there is an issue or more questions to explore here.
