### ISSUE TITLE
Pattern '..' notation doesn't cope well with floats

### ISSUE THREAD

**Issue by echophon** [tidalcycles/Tidal#431]
0.9.x branch had pattern shorthand for the run command so that:
`d1 $ s "drum*8" # n "0..8"`  would be equivalent to  `d1 $ s "drum*8" # n (run 8)`

This was useful as you could pattern these list expansions in various ways, ie
`d1 $ s "drum*8" # n "<0 4>..<6 8 12>"`

Attempting this pattern notation in 1.0.0 kills the Tidal process and requires a restart

**Comment by bgold-cosmos** [comment]
I'm puzzled, it seems to be working for me.  Are those the exact lines that cause the error?

**Comment by echophon** [comment]
yeah, this is off a fresh pull from master.  I run into this on both my Win & OSX machine.  The error got swallowed on the latest Atom update, but appears to be dying on this error:
 `ghc: Syntax error in sequence: "0..8" ^ unexpected "." expecting fraction`

**Comment by yaxu** [comment]
this works:
```
d1 $ s "drum*8" # n "<0 4>..<6 8 12>"
```
This doesn't:
```
d1 $ s "drum*8" # n "0..8"
```
This does:
```
d1 $ s "drum*8" # n "0 .. 8"
```
As does this:
```
d1 $ s "drum*8" # n "0.0..8.0"
```
Can you verify it's the same for you, @echophon?
I think it was the same way in 0.9.. It's because `n` now works with doubles, not integers, and so periods are ambiguous. The floating point parser could do some negative lookahead to make sure it's looking at a decimal point rather than the start of a range.

**Comment by echophon** [comment]
Ahh, okay this makes sense now.  This matches the behavior I'm seeing.  Thanks!

**Comment by yaxu** [comment]
Will reopen as I think it's worth fixing at some point

**Comment by yaxu** [comment]
"Attempting this pattern notation in 1.0.0 kills the Tidal process and requires a restart" - @echophon I'm having trouble reproducing this, can you share code that crashes tidal out in this way please?

**Comment by echophon** [comment]
`d1 $ s "drum*8" # n "0..8"` will do it.  When executed in Atom, it will stop all audio until a restart of Atom is done.  Maybe not technically a crash, but effectively one.

**Comment by yaxu** [comment]
Thanks @echophon, that's crashing for me too. Will continue looking at that one on #432

**Comment by yaxu** [comment]
Doesn't crash any more (you get a syntax error, but audio continues!), the UI problem with floats is still there though
