### ISSUE TITLE
up not working with latest superdirt

### ISSUE THREAD

**Issue by echophon** [tidalcycles/Tidal#434]
Expected:  the example below (from the userbase tutorial) should transpose the sample across a 12-tone scale

Actual:  all samples are played at the default speed.

Repro:
-- get latest superdirt quark

Evaluate:
`d1 $ up "0 1 2 3 4 5 6 7 8 9 10 11" # sound "arpy"`

**Comment by echophon** [comment]
hmm, I can't repro on my other machine.  I'll investigate some more and reopen if I can reliably repro

**Comment by echophon** [comment]
appears to be an issue with recent superdirt, which aliases `up` to `note`

**Comment by yaxu** [comment]
When you say the latest quark, do you mean v1.0 ?
Because LATEST is not the latest.

**Comment by yaxu** [comment]
I can't reproduce it here

**Comment by echophon** [comment]
I ran the following to remove and update SuperDirt so that I can make use of SuperDirt MIDI.  Not sure how to check exact version installed.
```
Quarks.uninstall("SuperDirt");
Quarks.install("SuperDirt");
```
I'm running v8.0.2 of ghci on OSX 10.13

I unregistered Tidal `ghc-pkg unregister tidal` and reinstalled from cabal (tidal-1.0.3).  

Both of these play the same sound without variation at present.
`d1 $ s "arpy*4" # up "0 1 2 3"`  
`d1 $ s "arpy*4" # note "0 1 2 3"`

**Comment by yaxu** [comment]
Try running `Quarks.install("SuperDirt", "v1.0")` and then recompiling class libraries
Or try running `Quarks.gui` and poking about in there

**Comment by echophon** [comment]
Thanks, using Quarks.gui I've installed & recompiled all the different SuperDirt's quarks (0.91, 1.0-alpha, & LATEST) and am seeing the same results on multiple machines. Perhaps "arpy" is not the best example, as there are multiple samples in this folder that map chromatically.

The below example is the 808 cowbell, which has very distinct pitch but it is the only cowbell sample in the folder.  Since `up` is now an alias to `note` I would expect the following to play a series of semitones.  Presently, it's the same sound 4 times.

```d1 $ s "808*4" # note "0 1 2 3"```

Speed still works as expected, but it slightly more work to get semitones from
```d1 $ s "808" # speed (1 + (3/12))```

**Comment by yaxu** [comment]
Those are all old versions, you want v1.0

**Comment by echophon** [comment]
Thanks!  This fixed it
