### ISSUE TITLE
"Failed to send" with malformed pattern

### ISSUE THREAD

**Issue by purpleposeidon** [tidalcycles/Tidal#443]
**Describe the bug**
Running
```haskell
d1 $ sound "hh:h"
```

causes `Failed to send. Is the target (probably superdirt) running?` instead of a proper error message.

**Environment (please complete the following information):**
 - OS: Linux
 - Haskell version : GHC 8.0.2
 - Tidal version: 1.0.4
 - SuperCollider version: 3.8.0

**Comment by yaxu** [comment]
Reproduced this problem here.. thanks!
