### ISSUE TITLE
stut' is not working correctly in 1.0.5

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#444]
**Describe the bug**
`stut'` seems to add extra notes that shouldn't be there:

**To Reproduce**

`d1 $ stut' 5 (0.125*3) (id) $ slow 4 $ s "bd"`

Notating each 0.125 step over 4 cycles, this is what I'm hearing

`x--x--x-Xx--x--xX-------X-------`

The capital `X`'s should not be there and should not be heard. In addition, the capital `X`'s sound _louder_ than the "stuttered" notes. I would expect them to be the same.

This is what I'd expect

`x--x--x--x--x--x----------------`

**Environment (please complete the following information):**
 - Tidal version: 1.0.5

**Comment by yaxu** [comment]
Thanks for this, if you can describe the expected output as a simple tidal pattern that'd be perfect, then I can easily make a test to catch future regression.

Can you try with this definition please:
```
let stutWith n t f p = innerJoin $ (\a b -> _stutWith a b f p) <$> n Sound.Tidal.Context.<* t
```

**Comment by yaxu** [comment]
Ok these look equivalent:
```
d1 $ slow 2 $ sound "bd*4 ~"
  # pan 1

d2 $ stutWith 3 (0.25) (id) $ slow 2 $ s "bd"
  # pan 0
```

**Comment by yaxu** [comment]
These are also equivalent:
```
d1 $ stut 4 1 1 $ slow 2 $ sound "bd"
  # pan 1

d2 $ stutWith 3 (0.25) (id) $ slow 2 $ s "bd"
  # pan 0
```
This has bugged me a while, the semantics are different.

For the first parameter, I think the `stutWith` version is off-by-one.

The second (gain factor) parameter only exists in `stut`, that's fine I think.

The next parameter is total timespan for `stut`, and IOI (inter onset interval) for `stutWith`. I think I prefer the former, partly because specifying the gap between repeats is pretty tedious if you have (say) 16 of them.

What do you think, @kindohm?

**Comment by kindohm** [comment]
@yaxu should the new `stutWith` definition fix `stut'`? When I eval the new `stutWith` I still have the problem with `stut'`:

`d1 $ stut' 1 (0.125*3) (id) $ s "bd/2"`

The sample plays on every cycle instead of every other cycle, even though the `stut'` effect only happens every other cycle.

**Comment by kindohm** [comment]
actual:

`d1 $ stut' 1 (0.125*3) (id) $ s "bd/2"`

expected:

`d1 $ s "bd/2 [~ bd/2] ~ ~"`

**Comment by yaxu** [comment]
@kindohm sorry I wasn't clear - `stutWith` is the new name for `stut'` so try `d1 $ stutWith 1 (0.125*3) (id) $ s "bd/2"`

Let me know what you think about the changes to `stut'`/`stutWith`

**Comment by yaxu** [comment]
For now, I've updated the documentation to describe the current behaviour for stut and stutWith, indicating that the latter will be changed to match the former. https://tidalcycles.org/index.php?title=stut&curid=728&diff=2994&oldid=2106

**Comment by kindohm** [comment]
Ok, `stutWith` works well for me.

I think of "stuttering" in terms of the IOI value a _lot_. e.g. "repeat the sound x number of times and each sound should be y cycles apart". I lean and rely on this behavior heavily. 

However, I also have some wrapper functions that use `stut`, and so I use the "total timespan" behavior too.

I think it would be best to make functions consistent though, so I would propose this:

- make `stutWith` match the timespan behavior of `stut`
- make a new function named something else that uses IOI instead of total timespan as its time argument. I've been using names like `rep` or `roll` in some wrapper functions for the old `stut'`.

Does this make sense?

**Comment by yaxu** [comment]
I don't have strong feelings either way, so I'm happy to go with your preferred behaviour, which is also how its been documented for a while.

**Comment by yaxu** [comment]
I think I'll fix it so `stutWith 4` results in four repeats including the original though, ok?

**Comment by kindohm** [comment]
Sure that sounds good.

**Comment by yaxu** [comment]
The gain values you end up with in `stut` is calculated in a fairly complicated way. I can't remember what I was trying to do, just that it was inspired by the feedback parameter of the stutter effect on a volca beats.. Maybe best to redefine `stut` in terms of `stutWith`, with the function `|* speed feedback`? 
```
_stut :: Integer -> Double -> Rational -> ControlPattern -> ControlPattern
_stut count feedback steptime p = stack (p:(map (\x -> (((x%1)*steptime) `rotR` (p |* P.gain (pure $ scalegain (fromIntegral x))))) [1..(count-1)]))
  where scalegain x
          = ((+feedback) . (*(1-feedback)) . (/(fromIntegral count)) . ((fromIntegral count)-)) x
```

**Comment by kindohm** [comment]
I do like how the old `stut` worked. I have a `rip` function that wraps it:

```
let rip a b p = within (0.25, 0.75) (slow 2 . rev . stut 8 a b) p
let rip' a b c d e p = within (a, b) (slow 2 . rev . stut c d e) p
```

I'm a little worried about those functions breaking if `stut` were re-written, but if we keep an old `_stut` around then that would be fine. However, I wonder if the classic `stut` is already broken after the 1.0 re-write. I don't think I've tried it!

**Comment by yaxu** [comment]
the _ prefix just means it has unpatterned parameters.
otherwise, `_stut` is the same as `stut`.

**Comment by yaxu** [comment]
I think this is OK in 1.0.6 but please try it out !

**Comment by kindohm** [comment]
thanks @yaxu will give a try ASAP
