### ISSUE TITLE
Tidal crashing out

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#445]
Certain patterns can freeze or crash tidal.
There are two issues really..

* Parser errors still not being caught at the right moment and crashing out the tidal scheduling thread. E.g. things like `"1..3" :: Pattern Double`
* Things like infinite lists e.g. from the typo `[1,1..2]` freezing the interpreter

**Comment by XiNNiW** [comment]
I've got some unit tests failing for these on a branch. What is the desired behaviour in these cases? Should "1..3" result in silence?

**Comment by XiNNiW** [comment]
Ah I see now that this is throwing an error not freezing. Has this already been fixed?

**Comment by yaxu** [comment]
I think `"1...3"` should result in an error (with no change to running patterns)

I might well have fixed it in a pre-gig frenzy!
