### ISSUE TITLE
semantics of irand

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#446]
Hi. Not clear whether it's a bug. Documentation of `irand` 
(did you know you can get this in ghci with `:doc irand`) suggests

```
d1 $ n (irand 5) # sound "drum"
```
but this sounds strange (with tidal-1.0.5) as it seems to play the samples as fast as it can.
I was rather expecting the sound of
```
d1 $ n (fast 5 ( pure 0 ) # irand 5) # sound "drum"
```
Is this because `nature (irand 5) == Analog`? While `nature (run 5) == Digital` and this works:
```
d1 $ n (run 5) # sound "drum"
```

**Comment by yaxu** [comment]
Yes random number generators are analog, you need to sample and hold them with e.g. `d1 $ segment 4 $ n (irand 5) # sound "drum"`

It's not playing the samples as fast as it can, but as fast as the calculation rate (which isn't a limit - events can be scheduled faster than this). Pre 1.0 this was something like 4 or 8 times per second, which sounded reasonable. Now the default is more like 20Hz.

**Comment by jwaldmann** [comment]
I see. Then the example in the doc of irand should be changed? (using `segment` as in your comment)

**Comment by yaxu** [comment]
Yes that'd be good in the short term.
There are probably other problems with the in-source docs.. Longer term it'd be nice to find a way of automatically keeping them in sync with the wiki, although I can't think of a nice way of doing that.

**Comment by jwaldmann** [comment]
There is https://hackage.haskell.org/package/doctest which helps in keeping the examples in documentation in sync with the code. (Haven't used it, but I buy the general idea.)

**Comment by yaxu** [comment]
I made Nature showable as well
