### ISSUE TITLE
Transitions not working as expected?

### ISSUE THREAD

**Issue by f-f** [tidalcycles/Tidal#450]
#### Describe the bug
All the transition functions I could try are acting weird. I found this behaviour first in 1.0.5 (did not try previous versions), then I upgraded to the latest master to see if it's still the case, and it seems to be.

#### To Reproduce
Let's say I have a simple pattern like this one:
```haskell
p 1 $ sound "bd sd bd cp"
```

Then I want to transition to a different pattern, let's say by fading in:
```haskell
xfadeIn 1 4 $ sound "hc*8"
```

This works (as it fades the pattern in), though:
- it seems to do it over 2 cycles only
- it doesn't fade out the previous pattern, though I'm addressing it with the same id

This is not the only weird case though, there seem to be several:
```haskell
-- `clutch` goes crazy and it seems to play the given pattern faster than it should 
-- (maybe twice as fast? It would match with the above "skipping cycles":
clutch 1 $ sound "hc*8"

-- `anticipate` feels the same way, something there is going way too fast while
-- transitioning, but then the transition happens at the right time
anticipate 1 $ sound "hc*8"

-- Though there seems to be a general problem with the `In` functions, 
-- and `jump` is the easiest way to notice
-- (happens with `xfadeIn`, `anticipateIn`, `clutchIn`, etc
-- So this transitions just fine
jump 1 $ sound "hc*8"
-- ..but this keeps the old pattern playing as well :(
jumpIn 1 2 $ sound "hc*8"
```

#### Environment
 - OS: macOS
 - Haskell version: 8.6.3 (stack lts-13)
 - Tidal version: latest master, eb388a0713982d0fafb0250ea6fd4ab98bce83ed
 - SuperCollider version: 3.9.3

**Comment by kindohm** [comment]
I'm also noticing some weird behavior. In my case with `clutch`, it sounds like a lot of extra sound events are being added. When `clutch` is eval'd, it sounds like a lot of random sounds from the first pattern are added, then a rush of sounds from the second pattern:

```
p "test" $ fast 2 $ s "bd(3,8)"

clutch "test" $ s "drum:1*4"
```

**Comment by kindohm** [comment]
Also, `clutchIn` won't let me eval patterns named with strings:

```
p "test" $ fast 2 $ s "bd(3,8)"

clutchIn "test" 16 $ s "drum:1*4"
```

results in:

```
Warning: GHCi | <interactive>:165:10: error:
Warning: GHCi |     • No instance for (Data.String.IsString Time)
Warning: GHCi |         arising from the literal ‘"test"’
Warning: GHCi |     • In the first argument of ‘clutchIn’, namely ‘"test"’
Warning: GHCi |       In the expression: clutchIn "test" 16
Warning: GHCi |       In the expression: clutchIn "test" 16 $ s "drum:1*4"
```

**Comment by jwaldmann** [comment]
#446 may be related (it shows the same symptom - rush of sounds)

**Comment by yaxu** [comment]
Thanks for the reports, keep them coming and I'll try to fix them later today.

**Comment by yaxu** [comment]
Ok the original post has the parameters 'the wrong way around'. This does a crossfade correctly:
```
p 1 $ sound "bd sd bd cp"

xfadeIn 4 1 $ sound "hc*4"
```
However, I think `xfadeIn 1 4` makes more sense, i.e. always put the pattern name/identifier first. I think I'll swap them for everything, unless there are objections?

**Comment by yaxu** [comment]
Here's transisition functions with swapped parameters, we can just update boottidal.hs with this:
```
let xfade i = transition tidal (Sound.Tidal.Transition.xfadeIn 4) i
    xfadeIn i t = transition tidal (Sound.Tidal.Transition.xfadeIn t) i
    histpan i t = transition tidal (Sound.Tidal.Transition.histpan t) i
    wait i t = transition tidal (Sound.Tidal.Transition.wait t) i
    waitT i f t = transition tidal (Sound.Tidal.Transition.waitT f t) i
    jump i = transition tidal (Sound.Tidal.Transition.jump) i
    jumpIn i t = transition tidal (Sound.Tidal.Transition.jumpIn t) i
    jumpIn' i t = transition tidal (Sound.Tidal.Transition.jumpIn' t) i
    jumpMod i t = transition tidal (Sound.Tidal.Transition.jumpMod t) i
    mortal i lifespan release = transition tidal (Sound.Tidal.Transition.mortal lifespan release) i
    interpolate i = transition tidal (Sound.Tidal.Transition.interpolate) i
    interpolateIn i t = transition tidal (Sound.Tidal.Transition.interpolateIn t) i
    clutch i = transition tidal (Sound.Tidal.Transition.clutch) i
    clutchIn i t = transition tidal (Sound.Tidal.Transition.clutchIn t) i
    anticipate i = transition tidal (Sound.Tidal.Transition.anticipate) i
    anticipateIn i t = transition tidal (Sound.Tidal.Transition.anticipateIn t) i
```

**Comment by yaxu** [comment]
This doesn't fix `clutch` et al though, looking at that..

**Comment by f-f** [comment]
@yaxu how about also requiring the pattern identifier to be a string? (and not e.g. a number) 
This would avoid the possibility of mixing up parameters altogether

**Comment by yaxu** [comment]
@f-f Hmm.. good point.. I think I like having the flexibility though personally

**Comment by f-f** [comment]
@yaxu I tested the changes and it works wonderfully, thanks!

Though `anticipateIn` switches immediately to the new pattern, so I guess that's still not as intended?

**Comment by yaxu** [comment]
It works for me @f-f

**Comment by yaxu** [comment]
We do have a testsuite which is run via jenkins ci https://github.com/tidalcycles/Tidal/tree/master/test

I'm not sure how to best write tests for transitions though. I guess we'd just need a way to test the pattern that the transition makes. Perhaps it wouldn't be as difficult as I was thinking.. The pseudorandom ones will be fiddly, though.

**Comment by kindohm** [comment]
The new transitions still don't seem to work correctly for me. Two issues:

1. 

```
d1 $ s "bd*8?"

xfade 1 $ (1 <~) $ s "drum:1*8?" 
```
The old `bd*8?` pattern keeps playing after the `drum:2*8?` pattern fades in

2. 

```
d1 $ s "bd*8?"

xfade 1 $ (1 <~) $ s "drum:1*8?" 

hush

d1 $ s "bd*8?"

xfade 1 $ (1 <~) $ s "drum:2*8?" 
```

On the 2nd `xfade`, the `drum:1` pattern from the 1st `xfade` starts playing at full volume along with the 2nd `d1`.

Verified I'm on 1.0.6:

```
➜  tidal git:(f040adf) cabal list tidal
* tidal
    Synopsis: Pattern language for improvised music
    Default available version: 1.0.5
    Installed versions: 1.0.6
    Homepage: http://tidalcycles.org/
    License:  GPL-3
```

**Comment by yaxu** [comment]
Did you get any warnings when you installed 1.0.6 ?

**Comment by yaxu** [comment]
Actually, I think that just means that you haven't run `cabal update`, 1.0.6 is installed so is presumably being run here. Have you restarted your editor etc?

**Comment by kindohm** [comment]
Pretty sure I had everything set up correctly and restarted but I will double check.

**Comment by kindohm** [comment]
Works now, and I didn't change anything. Weird!

**Comment by DaveParr** [comment]
> Ok the original post has the parameters 'the wrong way around'. This does a crossfade correctly:
> 
> ```
> p 1 $ sound "bd sd bd cp"
> 
> xfadeIn 4 1 $ sound "hc*4"
> ```
> However, I think `xfadeIn 1 4` makes more sense, i.e. always put the pattern name/identifier first. I think I'll swap them for everything, unless there are objections?

It appears to me the docs are still out of line with the implementation as of Tidal 1.0.7?

`xfadeIn "drums" 8 $ s "arpy*8" # n (run 8)` - error
`xfadeIn 8 "drums" $ s "arpy*8" # n (run 8)` - works

I'm happy to go update the docs if the proposed by @yaxu wasn't implemented in the end? Or if it will be in a future version I'll obviously just leave it :)

**Comment by yaxu** [comment]
It is implemented, please check your editor plugin/tidal boot script is up to date.
