### ISSUE TITLE
Introduce and maintain upper bounds in cabal dependencies

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#451]
(Following a chat with Hackage trustee @hvr)

We should make sure this contains only green shades:
  https://matrix.hackage.haskell.org/#/package/tidal

This has been done by @hvr et al by manually editing the metadata, e.g.:
  https://hackage.haskell.org/package/tidal-0.9.8/revisions/

Revising metadata is better than uploading whole new packages, and keeps historical versions working. Detailed info on metadata revisions:
  https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md

We should take the load off the hackage trustees by keeping an eye on the matrix, and new versions of dependencies.

For the latter, we can run `cabal outdated`, it'd be good to add this to travis.

So things to do:
- [x] Fix tidal.cabal to include upper bounds for everything.
- [x] Add `cabal outdated` to travis to track new versions of dependencies, updating metadata upper bounds on new and historical versions of tidal appropriately

.. generally keep an eye on the matrix

**Comment by yaxu** [comment]
I'm not 100% convinced that `cabal outdated` is being run.. https://github.com/tidalcycles/Tidal/blob/master/.travis.yml

**Comment by hvr** [comment]
@yaxu it is run; you just need to look for the line

```
All dependencies are up to date.
```

in the build log. Btw, while upper bounds are the most important (since the solver is biased towards using latest versions of dependencies) lower bounds are important as well when the solver needs to backtrack.
