### ISSUE TITLE
Performance in Euclid patterns

### ISSUE THREAD

**Issue by d0kt0r0** [tidalcycles/Tidal#455]
I think I discovered more performant implementations of _euclid _euclidInv and _euclidFull, in the course of doing some optimizing on Togo (the Cybernetic orchestra's personal mini-language over Tidal's euclid patterns). The browser context is very unforgiving of these things - using the alternate versions here seemed to reduce the required computation by approximately 50% in simple cases with even more substantial gains in less simple cases like nested Bjorklund rhythms. The alternate versions are here: https://github.com/d0kt0r0/estuary/blob/52b6081d65eca58f60138dbdb93dcb14d63b3031/client/src/Estuary/Languages/Togo.hs#L84

**Comment by yaxu** [comment]
This needs benchmarking as part of #447

**Comment by yaxu** [comment]
(thanks @d0kt0r0 !)

**Comment by yaxu** [comment]
BTW I put in some tests from Toussaints paper: https://github.com/tidalcycles/Tidal/blob/1d6719de89fce1c83b43f1feaf86efcf4fb25418/test/Sound/Tidal/UITest.hs#L182
