### ISSUE TITLE
solo/unsolo followed by Integer not working

### ISSUE THREAD

**Issue by MAKIO135** [tidalcycles/Tidal#457]
**Describe the bug**
`solo 1` does nothing (no error in the console) but `solo "1"` works as expected. Same with `unsolo`

**To Reproduce**
1. In Atom:
```
d1 $ sound "bd sd:1"
d2 $ sound "hh*4"
```
2. `solo 1`
3. Nothing is muted, console returns `t>`
4. `solo "1"`
5. d2 is muted, console returns `t>1`

**Expected behavior**
`solo 1` should mute other cycles, as seen in [documentation](https://tidalcycles.org/index.php/Tutorial#Silence)

**Environment:**
 - OS: OSX 10.14.2
 - Haskell version 8.2.1
 - Tidal version 1.0.6
 - SuperCollider version 3.9.3
 - Atom 1.34.0
 - tidalCycles for Atom 0.14.0

**Comment by yaxu** [comment]
Thanks, I've just pushed atom-tidalcycles 0.15, could you please update the tidalcycles package in atom and check whether that fixes this? Atom might need restarting

**Comment by MAKIO135** [comment]
Will try tomorrow morning. Thanks

Le dim. 13 janv. 2019 à 22:33, Alex McLean <notifications@github.com> a
écrit :

**Comment by yaxu** [comment]
Thanks, feel free to reopen this issue if there's a problem

**Comment by MAKIO135** [comment]
works perfectly

**Comment by yaxu** [comment]
great thanks!
