### ISSUE TITLE
clutchIn not working correctly

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#460]
**Describe the bug**
The `clutchIn` transition does not work as expected: 

1.  It continues playing the previous pattern even after the designated number of cycles has elapsed
2. It will play samples from a previous `clutchIn` execution instead of the one being evaluated.

**To Reproduce**

1. First, execute the following pattern and then the transition:

```
d1 $ s "bd*8?"

clutchIn 1 8 $ s "arpy(3,8)"
```

The `bd` pattern will continue to play instead of gradually degrading itself into the `arpy` pattern.

2. Then, execute the following:

```
hush

d1 $ s "bd*8?"

clutchIn 1 8 $ s "numbers(3,8)"
```

The `bd` pattern still plays, but also, the `numbers` sample  is not played. Instead, the `arpy` sample from the previous `clutchIn` plays instead.

**Environment (please complete the following information):**
 - Tidal version: 1.0.6

**Comment by gilfuser** [comment]
The same is happening in Tidal version 1.0.7

**Comment by yaxu** [comment]
It works for me.
`d1` et al should be defined in your editor's boottidal.hs (or similar) file as `d1 = p 1` (and not  `d1 = p "1"`)

**Comment by gilfuser** [comment]
Hi @yaxu 
If I do this `d1 = p 1` instead of `d1 = p "1"` in the Tidal.ghci (I'm using tidal-vim)
I get this error:
![error](https://user-images.githubusercontent.com/9404458/51483193-9e930c80-1d7f-11e9-83dd-a8daafd93cce.png)

**Comment by kindohm** [comment]
@yaxu I will double check when I get a chance. I am pretty sure I was using the boottidal.hs defined in the Atom plugin's latest source code.

**Comment by kindohm** [comment]
weird. works now. I realize I keep opening these transition issues, will try to remember to triple check my environment next time!
