### ISSUE TITLE
sometimesBy / const interaction sounds wrong

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#464]
**Describe the bug**
When `const` is used inside a `sometimesBy`, the `const` pattern plays every cycle.

**To Reproduce**

```
d1 $ sometimesBy 0 (const $ s "cp") $ s "bd*8"
```

**Expected behavior**
For `sometimesBy 0`, I would expect the `cp` pattern to never play. Or for `sometimesBy 0.5`, it would only play 50% of the time, etc.

**Environment (please complete the following information):**
- Tidal 1.0.7

**Comment by yaxu** [comment]
Interesting, so `sometimesBy` is defined as `overlay (degradeBy x p) (f $ unDegradeBy x p)`
So maybe that should be 
```
overlay (degradeBy x p) (unDegradeBy x $ f p)
```
I don't think that would have problems..

**Comment by yaxu** [comment]
Hm this change doesn't work well with this sort of thing:
````
d1  $ sometimesBy 0.5 (stutWith 3 (1/16) (|* gain 0.9)) $ s "bd*4" 
```
In that case it would be better to apply the f after the degrade, so you either heard the full stut or didn't.

I think I'll change it back, and make a `sometimes'` / `sometimesBy'` with the current behaviour

**Comment by yaxu** [comment]
A cleaner way to swap between patterns would be:
```
d1 $ sew (brandBy 0.5) (s "bd*8") (s "cp")
```
where `brandBy` is a boolean rand
```
-- | Boolean rand
brand :: Pattern Bool - a continuous stream of true/false values, with a 50/50 chance.
brand = _brandBy 0.5

-- | Boolean rand with probability as input, e.g. brandBy 0.25 is 25% chance of being true.
brandBy :: Pattern Double -> Pattern Bool
brandBy probpat = innerJoin $ (\prob -> _brandBy prob) <$> probpat

_brandBy :: Double -> Pattern Bool
_brandBy prob = fmap (< prob) rand
```

**Comment by kindohm** [comment]
thanks @yaxu. I always prefer to avoid using `const` when I can, so your suggestion is helpful not for just this issue but for other cases as well.

**Comment by BenjaminWynn** [comment]
Hey All,
Sorry for jumping in, but I didn't realize that there were issues with `const` and it should be avoided. I've been using it a lot so I'm curious what the issues might be... And is the best work around only available with 1.7 and `brand`? Thanks!

**Comment by yaxu** [comment]
Conversely in 1.7 `sometimesBy'` now means `sometimes play events from a pattern with this function applied, rather than the original` - const will still work fine with that.

**Comment by BenjaminWynn** [comment]
Ah, got it. Makes sense and thanks for the explanation @yaxu !
I'm definitely upgrading to 1.7 soon btw, just after an upcoming performance.
