### ISSUE TITLE
Wedge 1 freezes Tidal

### ISSUE THREAD

**Issue by echophon** [tidalcycles/Tidal#468]
**Describe the bug**
Wedge expects a ratio as it's first parameter, if that parameter is equal to 1, Tidal freezes and Atom needs to be restarted. 

**To Reproduce**
1. Run this sample pattern `d1 $ wedge (1) (s "ho ho:2 ho:3 hc") (rev $ s "ho ho:2 ho:3 hc")`
2. Tidal freezes

**Expected behavior**
When (0) is provided, an error is thrown "Error in pattern: Ratio has zero denominator".  I think the same behavior should be applied when (1) is provided.  Interestingly, ratios above 1 and below zero are valid and result in a doubling up of the pattern.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Haskell version: 8.2.2
 - Tidal version: 1.07
 - SuperCollider version: 3.10.0

**Additional context**
Seems related to #445

**Comment by XiNNiW** [comment]
I wrote a unit test and found that both 0 and 1 produce the  "Error in pattern: Ratio has zero denominator". However, 1 causes tidal to freeze and 0 does not. From reading the documentation, which describes the parameter as representing a percentage of pattern replacement, it seems odd to me that either parameter causes exception. Shouldn't 100% replacement result in the first pattern all the time?

**Comment by XiNNiW** [comment]
I think I have a fix provided my assumption about the desired behaviour is correct. I made it so 0 results in the original pattern for the whole duration and 1 results in the replacement pattern for the whole duration. Opening a pull request now.

**Comment by yaxu** [comment]
I think @XiNNiW did indeed fix this, please reopen if not.
