### ISSUE TITLE
chord abbreviations do not work with the # n operator

### ISSUE THREAD

**Issue by Dsm0** [tidalcycles/Tidal#472]
something like `d1 $ up "7 9*8 'min7" # s "rash:20" ` will evaluate normally,
whereas something like `d1 $ n "7 9*8 'min7" # s "rash:20" `
will not

**Comment by gilfuser** [comment]
Hi.
Just use 'note' instead of 'n'.
'n' will choose the sample number of 'hash', not transpose it, and it is
hardcoded as the 20th anyway.

bests,
Gil
