### ISSUE TITLE
irand, choose, etc are incompatible with once & asap ?

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#476]
Examples:

```
asap $ n (irand 20) # s "fx"
once $ choose [(run 10)] # s "fx"
```

**Comment by bgold-cosmos** [comment]
The new transition-based `onceFor` will fix this for `once`.  After toplap15 I'll give a look at `asap` and see if something can be done there too, I think there's probably an easy fix.

**Comment by yaxu** [comment]
I'm guessing the problem here is that arbitrary values are returned correctly, but the same ones each time. I just want to flag that this will be desired behaviour some of the time.

**Comment by jarmitage** [comment]
Yes, I understand this to be "expected behaviour" as far as the current implementation goes, just not "desirable" in this very specific case!

**Comment by yaxu** [comment]
I think most would want it to be different each time, just flashing it could be nice to have the option

**Comment by yaxu** [comment]
Here's a pseudorandom once:
```
import System.Random (getStdRandom, randomR)
randOnce p = do i <- getStdRandom $ randomR (0, 8192)
                once $ rotL (toRational i) p
```

A different version that plays whatever the current cycle is:
```
randOnce p = do now <- O.time
                tempo <- readMVar $ sTempoMV tidal
                let cyc = timeToCycles tempo now
                once $ rotL (sam cyc) p
```

The first one is better I think, the second one only plays something different every cycle.

We just need a nice name for it. Suggested names from the channel:
`onceMore` `freshOnce` `onceUnique` `newOnce` `newOne` `onceReseed` `onceOrig`

**Comment by yaxu** [comment]
Howabout `once` for a random cycle and `first` for the first one (the current behaviour)?

**Comment by jarmitage** [comment]
Separate `once` and `first` are nice solutions. 

If `once` is random, maybe there could be `onceAt c` where `c` is a given cycle number to enable a deterministic option. This would cover the case where you want repeatability, but you're looking for something alternative to the `first` cycle's output.
