### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#479]
Some noise in the builds from warnings, mostly missing, mostly missing signatures in minitidal:
 https://travis-ci.org/tidalcycles/Tidal/jobs/496618954

(Longer term we should write a styleguide).

@dktr0 are you OK fixing MiniTidal? I think I cleared these up before but a recent refactor brought them back. I think they're issues worth fixing rather than suppressing the warnings.

I can fix the others.

**Comment by dktr0** [comment]
Yeah, I'll clean that up. Me being hacky and leaving out type signatures in a hurry... (sshhh don't tell anyone!)....

**Comment by yaxu** [comment]
Thanks @dktr0! I did manage to get the emacs package to generate a type signature with a key combination, but haven't managed to get it to work a second time..

**Comment by dktr0** [comment]
Actually on second thought, maybe we could consider turning the warning about missing type signatures off? There's no question that it is best practice to give things explicit type signatures, but there are nonetheless cases where this is more a timesink than a help. In this case, the un-signatured functions are temporary and will be replaced by some kind of TH thing soon-ish. I'm also looking at the explicit type signatures that someone added to all those standard Parsec tokenizer imports, no doubt to suppress a warning since the signatures are just carbon copies of the Parsec originals.

**Comment by yaxu** [comment]
If it's a lot of work on transient code that you don't expect others to want to contribute to then feel to suppress the warning locally.

**Comment by dktr0** [comment]
I just added the signatures anyway... PR shortly.

**Comment by dktr0** [comment]
Here's the PR #481 
It adds a TH dependency so could use some testing on machines other than mine.

**Comment by yaxu** [comment]
It's not working on older versions of Haskell:
 https://travis-ci.org/tidalcycles/Tidal/builds/497263474

**Comment by dktr0** [comment]
I think it's just a matter of setting an earlier bound on template-haskell in the .cabal file. If we set it early enough it should work. I didn't realize we were still trying to support 7.x but fair enough. Surprising that 8.0.2 fails when the version I chose as the bound is in lts-9.21 but I don't know how the test chooses a package version to make available for each ghc version (apparently not by taking the latest lts version for that compiler version)... Any thoughts about how to pick the correct bound for template-haskell (other than just dragging it back until it works, which I guess would be okay)?

**Comment by yaxu** [comment]
We're doing well with backwards compatibility: https://matrix.hackage.haskell.org/#/package/tidal

This is thanks to the efforts of @hvr behind the scenes, who might have advice for best practice for picking template-haskell lower bounds here too. I'm not sure of this myself.

We should set upper bounds as well though (ref #451), I think to `< 2.14`.

**Comment by dktr0** [comment]
Is 7.10.3 the earliest version we care about?

**Comment by dktr0** [comment]
Looks like template-haskell 2.10.0.0 was the version in the final lts for ghc-7.10.2 and 7.10.3 so I am trying that as the new lower bound; and for the upper bound I am putting 3 since so far I am using very standard TH features that are very unlikely to change.

**Comment by dktr0** [comment]
Seems to pass all the required build checks now.

**Comment by yaxu** [comment]
Thanks!

**Comment by yaxu** [comment]
I'm still getting one warning - `The import of ‘Language.Haskell.TH’ is redundant`

**Comment by yaxu** [comment]
Just a couple of annoying to fix warnings left now..

**Comment by yaxu** [comment]
There's a couple of annoying warnings left but I'll close this for now.

**Comment by hvr** [comment]
@dktr0 

> and for the upper bound I am putting 3 since so far I am using very standard TH features that are very unlikely to change.

Putting an upper bound of `< 3` is pointless; it's even worse than not setting any upper bound at all as you're implying some kind of versioning contract that just does not exist. `template-haskell`'s versioning is governed by the PVP, and it's quite likely we'll never bump to TH 3.0 and quite more likely that a version of `template-haskell`  in the 2.* range will will be released which *will* break tidal, as by defintion, *every* major version, 2.13, 2.14, 2.15, etc is by definition a backward-compatibility breaking change... So please either use a PVP-compliant upper bound or don't use any at all.

**Comment by dktr0** [comment]
That makes sense to me. I tend to think no upper bound makes sense in this case, with such an extremely limited standard usage of TH features.

**Comment by yaxu** [comment]
@dktr0 I think we should take @hvr's advice as a cabal trustee who's put some work in adjusting Tidal's bounds behind the scenes.
I'll set the upper bound to 2.15, it's a little bit of work to test with each upcoming version, but I'm happy to keep an eye on it along with the other dependencies.

**Comment by dktr0** [comment]
Not sure I was questioning the advice "either use a PVP-compliant upper bound or don't use any at all" - anyway, all good.

**Comment by yaxu** [comment]
Fair point, for now I'm happy to have the same simple policy for all the deps anyway.

**Comment by asm13243546** [comment]
.
