### ISSUE TITLE
Some flags have not been recognized

### ISSUE THREAD

**Issue by telephon** [tidalcycles/Tidal#480]
**Describe the bug**
On startup, using Atom, we get:

```
Some flags have not been recognized: prompt-cont, 
t>Listening for controls on 127.0.0.1:6010
```

Tidal is usable, but not the external control functions.

**To Reproduce**

start tidal from atom

**Environment (please complete the following information):**

- macOS 10.13.6
- atom package tidalcycles 0.16.0
- `$ which ghci`returns `/usr/local/bin/ghci`
- `tidal-1.0.7`

**Comment by bgold-cosmos** [comment]
This is very likely an old GHC version, what does `ghci --version` report?

**Comment by telephon** [comment]
`The Glorious Glasgow Haskell Compilation System, version 8.0.2`

**Comment by telephon** [comment]
… doing `cabal install ghci` right now.

**Comment by bgold-cosmos** [comment]
OK, it turns out the prompt continuation interface changed in 8.2, so that's the issue.  Unfortunately I don't think there's any way _within_ ghci to detect what version is actually installed, which is why we don't have a more sophisticated boot script that autodetects the version and uses the appropriate command.

**Comment by telephon** [comment]
I've now got `Installed ghci-8.4.3`. Now it's even worse: same warning, but tidal doesn't seem to compile anything. I get a new prompt for every line, `>t` but nothing behind it.

**Comment by bgold-cosmos** [comment]
I'm not sure, but I suspect upgrading using `cabal install gchi` means all the other packages (including tidal) will need to be upgraded as well, more or less manually.  I would agree with you if you think this is clunky and unintuitive.

You may have more luck downloading the latest Haskell Platform and installing that, it should be fairly good about creating a new independent set of directories and packages that you can switch between with `activate-hs`

**Comment by telephon** [comment]
I've force reinstalled tidal now, but also this dodn't help. I understand that you may need to update other stuff. Do I get warnings for packages that are not up to date relative to my version of ghci?

**Comment by yaxu** [comment]
The original 'prompt-cont' warning wasn't important, external controls should have worked fine.

I'm not exactly sure what `cabal install ghci` does..  ghc version 8.0.2 is a couple of years old now, but should work fine. Perhaps it's work removing the `.cabal` and `.ghc` folders and starting with `cabal update; cabal install tidal` again.

(The emacs plugin does manage to detect old ghci versions and use a different method to set the prompt.)

**Comment by telephon** [comment]
>Perhaps it's worth removing the `.cabal` and `.ghc` folders and starting with `cabal update; cabal install tidal` again.

This didn't work, now reinstalling haskell ...

**Comment by telephon** [comment]
Completely reinstalling the whole Haskell Platform did it, finally. Thank the both of you!

**Comment by vrx** [comment]
on ubuntu 18.04 lts, i ran into same kind of problems and finally solved it using this installation procedure, 
!! watch out !!  this will remove your previous installation of ghc/cabal

sudo apt purge ghc cabal-install
sudo add-apt-repository ppa:hvr/ghc
sudo apt-get update

rm -r ~/.cabal
rm -r ~/.ghc

sudo apt install cabal-install-2.4 ghc-8.6.4 
sudo update-alternatives --config opt-ghc
sudo update-alternatives --config opt-cabal

sudo ln -s /opt/ghc/bin/ghci /usr/bin/
sudo ln -s /opt/ghc/bin/ghc-pkg /usr/bin/

cabal update
cabal install tidal

**Comment by ekg** [comment]
@vrx I had to also link everything else in the /opt based install of ghc and cabal into /usr/bin.

**Comment by b1tfl0w** [comment]
> on ubuntu 18.04 lts, i ran into same kind of problems and finally solved it using this installation procedure,
> !! watch out !! this will remove your previous installation of ghc/cabal
> 
> sudo apt purge ghc cabal-install
> sudo add-apt-repository ppa:hvr/ghc
> sudo apt-get update
> 
> rm -r ~/.cabal
> rm -r ~/.ghc
> 
> sudo apt install cabal-install-2.4 ghc-8.6.4
> sudo update-alternatives --config opt-ghc
> sudo update-alternatives --config opt-cabal
> 
> sudo ln -s /opt/ghc/bin/ghci /usr/bin/
> sudo ln -s /opt/ghc/bin/ghc-pkg /usr/bin/
> 
> cabal update
> cabal install tidal

Also I had to add path to .bashrc or .zshrc
export PATH=/opt/ghc/bin:$PATH
