### ISSUE TITLE
IO patterns

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#483]
Below is a quick hack for scheduling patterns of IO actions..

Some things to figure out.. Firstly, the events should be simply sorted by onset so they're scheduled in the right order.
Also state isn't currently carried from one event to the next, but could be. But this raises a conceptual issue - what happens if two (or more) events happen at the same time? should they both get the same state input, and their state output combined in some way? Or put in random order? 

```
import qualified Sound.Tidal.Tempo as T
import qualified Sound.OSC.FD as O
import Control.Concurrent.MVar
import Control.Concurrent

onTick :: MVar (Pattern (IO b)) -> MVar T.Tempo -> T.State -> IO ()
onTick pMV tempoMV st = do tempo <- readMVar tempoMV
                           p <- readMVar pMV
                           now <- O.time
                           let es = filter eventHasOnset $ queryArc p (T.nowArc st)
                               on e = (sched tempo $ start $ whole e)
                           mapM_ (\e -> do threadDelay (floor $ (on e - now) * 1000000)
                                           value e
                                 ) es
                           return ()

                             :t patternIO

patternIO :: IO (Pattern (IO ()) -> IO ())
patternIO = do pMV <- newMVar empty
               (tempoMV, _) <- T.clocked defaultConfig (onTick pMV)
               return $ \x -> do swapMVar pMV x
                                 return ()
                        

p1 <- patternIO

p1 $ euclid 3 8 $ pure (putStrLn "hello world")
```

**Comment by bgold-cosmos** [comment]
This is really interesting, and I don't have much experience with how Haskell handles concurrency.  But if you try to have "simultaneous" IO, is there even a way to sensibly handle conflicts among all possible IO actions?

**Comment by dktr0** [comment]
One way to coordinate patterns, state and IO with Tidal would be to pattern the type (StateT s IO a) where s is a common state we care about, and a is any value would like to be consumed "upstream".

When events in (StateT s IO a) happen at the same time, they do not need to be thought of as concurrent - indeed I think that could make things needlessly complex. Instead, one can execute the actions synchronously in a deterministic order. This does not preclude that any of those actions might fork a parallel process to do more work, provided the forked process is "all side effects" and has no impact on the state you are managing.  

This is related to a pattern I see all the time working with the Reflex FRP framework. In that framework there are different ways of merging simultaneous events but by far the most common/useful one in my experience involves a "biased" (ie. pre-ordered) combination of simultaneous events via composition (the events are state functions a -> a; when you compose them you also get an a -> a).

I'm not super clear what the scope of the state to manage might be, nonetheless I think deterministic synchronous execution of simultaneous events is applicable to most of the use cases I can imagine using state for in Tidal - computationally efficient random numbers, global variables, on the fly pattern language tweaks. These are all things that are clearly distinct from each other. One might need to add a semantics that orders pattern rendering (if there isn't one already) though.

**Comment by ovitus** [comment]
Might it be possible to get this hack working with the current version of Tidalcycles? It would be great to be able to sequence the setF variable states.

**Comment by yaxu** [comment]
@ovitus Hm, but doesn't `setF` set a pattern already?

**Comment by yaxu** [comment]
Closing as speculative, still available via the label..
