### ISSUE TITLE
Package problems in Atom with 0.16.0 (ghci packages?)

### ISSUE THREAD

**Issue by ardanchess** [tidalcycles/Tidal#486]
Hi everyone. 
I can't understand what's happening here... 
I have update tidalcycles in Atom to 0.16.0 via Package Manager. As soon as I restarted and try to use it, a long error message comes up every time. 
I even tried to reinstall everything with tidal.boostrap and manual installation, but nothing. 
I'm running ghci 8.4.3, tidal 1.0.7, tidalcycles package 0.16.0, Atom 1.34.0 on OS 10.12.6.
Please help me because I absolutely don't know what to do.

Here's the error message I get: 

_**Note: No local targets specified, so a plain ghci will be started with no package hiding or package
      options.
      
      If you want to use package hiding and options, then you can try one of the following:
      
      * If you want to start a different project configuration
        than /Users/Ardan/.stack/global-project/stack.yaml, then you can use stack init to create a
        new stack.yaml for the packages in the current directory. 
        
      * If you want to use the project configuration
        at /Users/Ardan/.stack/global-project/stack.yaml, then you can add to its 'packages' field.
      
Configuring GHCi with the following packages: 
t>

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘;’

 parse error on input ‘\*\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’
Some flags have not been recognized: -XOverloadedStrings\
Can't parse prompt string. Use Haskell syntax.
Couldn't read " \"\"\\" as String

    parse error (possibly incorrect indentation or mismatched brackets)

 parse error on input ‘\’

    parse error (possibly incorrect indentation or mismatched brackets)

    parse error on input ‘<-’
    Perhaps this statement should be within a 'do' block?

    parse error (possibly incorrect indentation or mismatched brackets)

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

 parse error on input ‘\’

    parse error (possibly incorrect indentation or mismatched brackets)
Can't parse prompt string. Use Haskell syntax.

 parse error on input ‘`’

 Variable not in scope: d1 :: t0 -> t

    • Variable not in scope: sound :: [Char] -> t0
    • Perhaps you meant ‘round’ (imported from Prelude)**_

...
Thank you! 
A.

**Comment by yaxu** [comment]
Perhaps you need to configure atom to use Tidal as installed with cabal rather than stack.
Try changing the `ghci path` setting for the tidalcycles atom package to the default of `ghci`.

**Comment by ardanchess** [comment]
Hi Alex. Thanks for the immediate response.
Unfortunately, I have tried changing the path but nothing happened. Even tried to reinstall everything again, including the full Haskell platform (so now I'm running Haskell 8.6.3) and try with several paths, but nothing. Got a different error message now: 



:1:7: error: parse error on input ‘\’

:2:10: error: parse error on input ‘\’

:3:11: error: parse error on input ‘;’

:4:2: error: parse error on input ‘\*\’

:5:13: error: parse error on input ‘\’

:6:6: error: parse error on input ‘\’

:8:4: error: parse error on input ‘\’
Some flags have not been recognized: -XOverloadedStrings\
Can't parse prompt string. Use Haskell syntax.
Couldn't read " \"\"\\" as String

:12:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:13:27: error: parse error on input ‘\’

:14:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:16:7: error:
    parse error on input ‘<-’
    Perhaps this statement should be within a 'do' block?

:17:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:18:28: error: parse error on input ‘\’

:19:28: error: parse error on input ‘\’

:20:28: error: parse error on input ‘\’

:21:28: error: parse error on input ‘\’

:22:32: error: parse error on input ‘\’

:23:28: error: parse error on input ‘\’

:24:32: error: parse error on input ‘\’

:25:34: error: parse error on input ‘\’

:26:33: error: parse error on input ‘\’

:27:36: error: parse error on input ‘\’

:28:24: error: parse error on input ‘\’

:29:64: error: parse error on input ‘\’

:30:68: error: parse error on input ‘\’

:31:68: error: parse error on input ‘\’

:32:62: error: parse error on input ‘\’

:33:68: error: parse error on input ‘\’

:34:58: error: parse error on input ‘\’

:35:66: error: parse error on input ‘\’

:36:68: error: parse error on input ‘\’

:37:68: error: parse error on input ‘\’

:38:96: error: parse error on input ‘\’

:39:72: error: parse error on input ‘\’

:40:80: error: parse error on input ‘\’

:41:62: error: parse error on input ‘\’

:42:70: error: parse error on input ‘\’

:43:70: error: parse error on input ‘\’

:44:78: error: parse error on input ‘\’

:45:15: error: parse error on input ‘\’

:46:15: error: parse error on input ‘\’

:47:15: error: parse error on input ‘\’

:48:15: error: parse error on input ‘\’

:49:15: error: parse error on input ‘\’

:50:15: error: parse error on input ‘\’

:51:15: error: parse error on input ‘\’

:52:15: error: parse error on input ‘\’

:53:15: error: parse error on input ‘\’

:54:17: error: parse error on input ‘\’

:55:17: error: parse error on input ‘\’

:56:17: error: parse error on input ‘\’

:57:17: error: parse error on input ‘\’

:58:17: error: parse error on input ‘\’

:59:17: error: parse error on input ‘\’

:60:17: error: parse error on input ‘\’

:61:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)
Can't parse prompt string. Use Haskell syntax.

:63:1: error: parse error on input ‘`’

:65:1: error: Variable not in scope: d1 :: t0 -> t

:65:6: error: Variable not in scope: s :: [Char] -> t0


...
I can't understand what actually went wrong...
Any ideas? 
Thank you again, 
A.

**Comment by yaxu** [comment]
what happens if you run `cabal update; cabal install tidal` in a terminal window?

**Comment by ardanchess** [comment]
Just tried. Tidal is built correctly, restart Atom but again the same message...

**Comment by yaxu** [comment]
Again from a terminal window, what happens when you run `ghci -XOverloadedStrings`, and then from the ghci prompt you should get, rrun `import Sound.Tidal.Context`

If that works, make sure the that `ghci path` setting in atom is completely empty. It shouldn't have any spaces in there.

**Comment by ardanchess** [comment]
Mmm, I don't think has worked... I simply got this: 

Prelude> import Sound.Tidal.Context
Prelude Sound.Tidal.Context>

**Comment by yaxu** [comment]
@ardanchess that's positive, it means ghci can load the tidal the library fine.

Run this in a terminal window:
`which ghci`
.. then whatever it says (it'll be something like `/usr/local/bin/ghci`), put that in the `ghci path` setting for the atom tidalcycles package, making sure there are no extra spaces in there. Then restart atom and try again.

**Comment by ardanchess** [comment]
Ok. It says the same path (/usr/local/bin/ghci). Pasted into ghci path with no extra spaces and tried evaluating the simple line d1 $ sound "bd". 
For a moment it seems to load the ghci interpreter, but the message disappears almost immediately (I can only read something like "Ghci version...") and this error message appears: 


:1:52: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:2:40: error: parse error on input ‘;’

:3:11: error: parse error on input ‘;’

:4:2: error: parse error on input ‘\*\’

:5:76: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:6:121: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:8:15: error: parse error on input ‘`’
Some flags have not been recognized: -XOverloadedStrings\
Can't parse prompt string. Use Haskell syntax.
Can't parse prompt string. Use Haskell syntax.

:12:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:13:27: error: parse error on input ‘\’

:14:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:16:7: error:
    parse error on input ‘<-’
    Perhaps this statement should be within a 'do' block?

:17:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:18:29: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:19:29: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:20:29: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:21:29: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:22:33: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:23:29: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:24:33: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:25:35: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:26:34: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:27:37: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:28:25: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:29:65: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:30:69: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:31:69: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:32:63: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:33:69: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:34:59: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:35:67: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:36:69: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:37:69: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:38:97: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:39:73: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:40:81: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:41:63: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:42:71: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:43:71: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:44:79: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:45:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:46:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:47:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:48:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:49:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:50:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:51:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:52:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:53:16: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:54:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:55:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:56:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:57:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:58:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:59:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:60:18: error:
    parse error (possibly incorrect indentation or mismatched brackets)

:61:2: error:
    parse error (possibly incorrect indentation or mismatched brackets)
Can't parse prompt string. Use Haskell syntax.

:63:1: error: parse error on input ‘`’

:65:1: error: Variable not in scope: d1 :: t0 -> t

:65:6: error:
    • Variable not in scope: sound :: [Char] -> t0
    • Perhaps you meant ‘round’ (imported from Prelude)

**Comment by bgold-cosmos** [comment]
I'm a bit puzzled about where all these messages about `'\'` are coming from... there shouldn't be any of those in the BootTidal.hs

**Comment by yaxu** [comment]
Yes.. Do you have something funny in your `Boot Tidal Path` setting in the tidalcycles atom package @ardanchess ? That should probably be blank.  If that doesn't help

**Comment by ardanchess** [comment]
Oh well there's something strange in my boot file actually haha! I really don't know what's happened... 
The path was actually blank as always, I tried to replace with another boot file (using, to give it a try, the default  template I found here: https://github.com/tidalcycles/atom-tidalcycles) and some error message actually disappeared! 
Think we're almost done!
Now the problems are: 
1) I could rewrite a completely new boot file from scratch, but my code knowledge is actually really poor...
2) Maybe I could fix the original boot file but I can't find it anywhere... I have reinstalled the atom plugin but the problems remains, and still can't find the default one. 
So, can I find somewhere the original default boot file???
Thank you a lot for the quick help!
Let me know!

**Comment by yaxu** [comment]
Great,
It's here https://github.com/tidalcycles/atom-tidalcycles/blob/master/lib/BootTidal.hs

It's probably the same as you already have so I guess you fixed it.

you can find where the plugin is stored by running `apm ls tidalcycles`

the default file will be in there under the lib folder

**Comment by ardanchess** [comment]
Yup! It works!
Perfect, thank you and see you soon!
