### ISSUE TITLE
"msec" function

### ISSUE THREAD

**Issue by mxmxyz** [tidalcycles/Tidal#488]
Would be nice to have a function that translates milliseconds to cycles. Apart from being more convenient/readable in some contexts, it would allow for things like the following:

```
d1 $ cps (slow 4 $ scale 0.5 1.0 $ saw)

d2 $ stut 4 0.75 (msec 80) $ sound "bd hh"
```

Here the cps is constantly changing, but (ideally) the result of `msec 80` changes as well, so that sounds always end up being delayed by 80 milliseconds.

**Comment by bgold-cosmos** [comment]
In Haskell, functions have to be pure (always return the same output for a given input) which makes it tricky to implement something like this.

**Comment by yaxu** [comment]
We could pass in state like cps as control state I think, I'll have a go..

**Comment by yaxu** [comment]
Done! https://github.com/tidalcycles/Tidal/commit/13d29f5daaf56a49b87fd1c3098ef194ab9cb155

**Comment by yaxu** [comment]
I'm a bit unsure about it though.  It only works if the result is used as a cycle duration. Maybe `msecToCycle` is a better name but it's a long one..

**Comment by mxmxyz** [comment]
works correctly with "regular" (`dx $`) patterns; i don't know why, but with `asap` and `once` it always behaves as though the cps was 1.

**Comment by yaxu** [comment]
Ok https://github.com/tidalcycles/Tidal/commit/332da130639c8f431fcba25949ee3c6c0f186d82 should fix that
