### ISSUE TITLE
Setting cps creates warnings in SuperDirt

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#489]
`setcps 1.1` works fine, but generates an error in supercollider:
```
no synth or sample named 'nil' could be found.
module 'sound': instrument not found: nil
```
Same with `d1 $ cps 1.1`.

The problem is that cps is dealt with as a control pattern now, and as a result that means that an OSC message is sent to SuperDirt that contains no sound to trigger, which it doesn't like.

We should either make superdirt not generate an error in this case, or not send the message if there's no sound to play. Which would you prefer, @telephon ?

It might be better for superdirt/supercollider to be the tempo clock, especially with e.g. link support on the horizon. In that case, the current behaviour might be useful.

**Comment by telephon** [comment]
> We should either make superdirt not generate an error in this case, or not send the message if there's no sound to play. Which would you prefer, @telephon ?

A missing sound argument might also occur from a user error, no? In that case, you want an error message.

> It might be better for superdirt/supercollider to be the tempo clock, especially with e.g. link support on the horizon. In that case, the current behaviour might be useful.

Shouldn't tidal send a different, separate message for cps changes? 

All in all, if it is not too much trouble to care for it in tidal, I'd prefer to write a separate listener for tempo changes. Or are there other cases where you send a message without a `sound`?

On the other hand, the sclang side quick fix would be really easy, so I can also just ignore messages that have no instrument.

**Comment by yaxu** [comment]
On one hand, it's nice to be able to mix cps changes in with sound events
```
d1 $ sound "bd(3,8)" # cps "0 0.5 0.75"
```
On the other, this isn't very nice as cps is global, so it doesn't make sense to add `cps` to more than one pattern at once.

I think a better aproach would be able to change a cps factor locally to a pattern, relative to the global cps, which is patterned and scheduled separately.

**Comment by kindohm** [comment]
Mixing `cps` and `sound` patterns is a very, very important feature of Tidal!

```
d1 $ plyWith 10 (# gain 0.8) $ s "<bd hh>" # cps "<4 2 3 2 1 1>"
```

I think maintaining both global and local cps patterns would be just fine. Not sure what those patterns would look like exactly, but:

```
p "globalCps" $ globalCps "<1 1 0.75 1.25>"

d1 $ plyWith 10 (# gain 0.8) $ s "<bd hh>" # cps "<4 2 3 2 1 1>"
```

**Comment by yaxu** [comment]
We'd end up having a separate scheduler per pattern then.. A bit wasteful, but it is how things used to work before version 1.0

**Comment by kindohm** [comment]
I think it would be a _huge_ benefit if all local patterns could run at their own cps. I can't cite a specific conversation but I know others are interested in this.

I don't know the internals of Tidal well enough to know if this is relevant to mention, but it would be great if each local pattern could handle continuous changes to cps in addition to mini-notation:

```
d1 
    $ (|* cps (range 0.5 1.5 $ slow 4 sine)) 
    $ plyWith 10 (# gain 0.8) $ s "<bd hh>" # cps "<4 2 3 2 1 1>"

d2 
    $ (|* cps (range 0.25 2 $ slow 5.333 sine)) 
    $ (|* cps (range 0.5 1.5 $ rand)
    $ plyWith "<15 10 20>" (|* gain 0.95) $ s "feel" # cps "<3 1 0.5 2 1 0.5 0.5 0.5>"

d3 $ slow 2 $ s "drum/2 drum" # n "0 1" # cps 0.5
```

**Comment by yaxu** [comment]
Ideally each pattern could have smooth cps changes locally while still staying in sync relative to the global cps. Unfortunately I think this is impossible (ref @telephon's piece on algorithmic complementarity https://drops.dagstuhl.de/opus/volltexte/2014/4420/pdf/dagrep_v003_i009_p130_s13382.pdf). If you change the cps relative to the global one (so local cps of `1/3` is always in phase with another local one at `1/4`, you can't take the history of local changes into account, so there will be a big jump in the pattern for small cps changes.

Perhaps we need a way to switch modes between a cps that stays in lockstep with global clock (and therefore other patterns), and one that allows cps changes without jumping around the timeline. I think it's not possible to do both.

**Comment by jwaldmann** [comment]
NB: thanks for linking to the Dagstuhl report! I was not aware of that.
