### ISSUE TITLE
~> ignored in superimposed stack

### ISSUE THREAD

**Issue by ryanlaws** [tidalcycles/Tidal#490]
**Describe the bug**
The `~>` function is ignored when applied to a pattern within a superimposed `stack`.

**To Reproduce**
Run:
```
d1 $ superimpose (# stack ([
	s ((1/6) ~> "hc")
]))
$ "cb ~ cb ~ ~ ~"
```

**Expected behavior**
`hc` pattern is 1/6 of a cycle after `cb` pattern, as is the case here:
```
d1 $ superimpose (
	((1/6) ~>) . (# s "hc")
)
$ "cb ~ cb ~ ~ ~"
```

**Observed behavior**
`hc` pattern lines up with `cb` pattern

**Environment**
 - OS: Arch Linux
 - Haskell version: 8.6.3 
 - Tidal version: 1.0.8
 - SuperCollider version: 3.10.2

**Comment by yaxu** [comment]
You're shifting the `"hc"` and then combining it with the original using `#`, so the structure comes from the left (i.e, the original). I think you have to do this as two separate options, as you do in the second example.

**Comment by yaxu** [comment]
(I'd say this isn't a bug but feel free to ask more questions if this isn't clear!)

**Comment by bgold-cosmos** [comment]
I agree, I don't think it really has anything to do with `superimpose` or `stack`.  But there may still be a bug.  Here's a simpler example:

```
tidal> s $ "cb ~ cb ~ ~ ~" # ((1/6) ~> "hc")
(0>⅙)|s: "hc"
(⅓>½)|s: "hc"
tidal> s $ "cb ~ cb ~ ~ ~" >| ((1/6) ~> "hc")

tidal> 
```
I'm not sure I understand the second case.  Shouldn't it there be something there?

**Comment by yaxu** [comment]
You've missed an `s` on the second bit, but even with that fixed, it's broken:

`(s "cb ~ cb ~ ~ ~") >| (s ((1/6) ~> "hc"))`

**Comment by yaxu** [comment]
Oh I see, it's taking the structure from the left, with an onset at `1/6`, and there's no event active on the right at that point, so nothing to match with, so it returns nothing.

**Comment by ryanlaws** [comment]
Thank you! Turns out `layer` is what I was looking for :+1:
