### ISSUE TITLE
Consider switching to megaparsec

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#492]
As an actively developed fork of parsec, it seems that it would be easy to switch, with the most immediate payoff being improved error messages.

**Comment by yaxu** [comment]
I made a branch to explore megaparsec here:
https://github.com/tidalcycles/Tidal/tree/topic-megaparsec

First go: https://github.com/tidalcycles/Tidal/commit/a10706b7834b6638feedb897bd280cca6c6edb24

Problems I'm hitting at the moment:
- I think there is not a built-in way to handle state, like the random seed
- Getting source code position is different, and maybe a bit harder

**Comment by yaxu** [comment]
Help is welcome!

**Comment by polymorphicengine** [comment]
might look into this some more - while i already reworked the current parser with parsec; switching to megaparsec would probably have a couple of advantages like better error messages and a clearer and more readable structure of the parser itself:
as @JeffreyBenjaminBrown mentioned here: https://github.com/tidalcycles/Tidal/pull/952, Text.Megaparsec.Expr (which was moved to Control.Monad.Combinators.Expr) would allow for a generic definition of the parser where we can decide on the various assosciativities/precedences of the operators
