### ISSUE TITLE
stutWith sounds wrong inside sometimesBy

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#493]
**Describe the bug**
When using `stutWith` inside of `sometimesBy`, it sounds like some of the stuttered notes are removed.

**To Reproduce**
`d1 $ sometimesBy 0.5 ( stutWith 9 (0.0625/2) (|* gain 0.95) ) $ s "bd"`

This sounds fine:
`d1 $ stutWith 9 (0.0625/2) (|* gain 0.95)  $ s "kit1"`

**Expected behavior**
I would expect `stutWith` inside of `sometimesBy` to produce a smooth, stuttered pattern _sometimes_. Instead, it sounds like some of the stuttered notes are removed.

**Comment by kindohm** [comment]
Perhaps this is not a bug. From **guiot** on the Lurk chat:

_@kindohm doesn't sometimesBy apply a function randomly event-by-event? i think what you're getting is expected behavior
as in, 50% of the notes are getting stutted
**a smooth, stuttered pattern sometimes** sounds more like `somecyclesBy`_

**Comment by bgold-cosmos** [comment]
I had the same thought as you originally, that some events should get `stut`.  But guiot is right - here's the definition of `sometimesBy`

`sometimesBy x f p = overlay (degradeBy x p) (unDegradeBy x $ f p)`

So you're going to randomly get some events from the stut'ed pattern and some from the original.
