### ISSUE TITLE
Slice struct

### ISSUE THREAD

**Issue by sam-schorb** [tidalcycles/Tidal#494]
I would like a fucntion to define a pattern without stating the sounds inside it? (e.g. using integers).

I would like to be able to store patterns then apply them to strings of sounds which could be changed by quickly changing the string, rather than having to rewrite the whole pattern.
Something like this - 
```
d1 $ fix (# nudge 0.04) (slice "4") 
$ slice 4 "1 2 3 [2 1] [~ 4] [2 4] 3 2" $ sound "[bd,hh,cp,hh:2]"

```

**Comment by bgold-cosmos** [comment]
It sounds like `fit`is what you want:

```
d1 $ sound $ fit 4 ["bd", "hh", "cp", "hh:2"] "0 1 2 [1 0] [~ 3] [1 3] 2 1"
```
except that it's not possible to use `fix` directly with the slice index.  For that, you might find the related `fit'` useful, though it's a bit cumbersome:
```
d1 $ fit' 1 4 (run 3) "0 1 2 [1 0] [~ 3] [1 3] 2 1" (s "bd hh cp hh:2" # nudge "0 0 0 0.04")
```

**Comment by sam-schorb** [comment]
This seems to be right but fit' isn't working for me in tidal 1.10.

**Comment by bgold-cosmos** [comment]
OK, that needs fixing.

**Comment by ndr-brt** [comment]
I tried the examples reported by @bgold-cosmos and they are both working on tidal 1.7.8. 
Should be closed?
