### ISSUE TITLE
can't install tidal-midi

### ISSUE THREAD

**Issue by stalexxx** [tidalcycles/Tidal#496]
**Describe the bug**
Can't install tidal-midi

**To Reproduce**
1. trying to install 
 cabal new-install  tidal-midi (same on just install)
**Expected behavior**

**Environment (please complete the following information):**
Mac, Haskell version : 8.6.4
 - 1.0.10
 - SuperCollider 3.10.0

**Additional context**
in attachment
[tidal.txt](https://github.com/tidalcycles/Tidal/files/2989870/tidal.txt)

**Comment by yaxu** [comment]
The tidal-midi haskell module is no longer supported.

Information on working with SuperDirt-based MIDI instead is here:
  https://tidalcycles.org/index.php/MIDI
