### ISSUE TITLE
Things that KILL tidal (requiring GHCi reboot)

### ISSUE THREAD

**Issue by OscarSouth** [tidalcycles/Tidal#498]
I've been lazy about documenting these (pun not intended, although this is always funny in the context of Haskell), so I'll keep updating this as I run into stuff again (so that I can supply the output). A lot of these might/are probably a result of my own decision making, but are probably worth knowing about, since in improv situations it's best to just throw everything at the wall and hopefully not trainwreck the whole thing.

I've found that a few specific things will outright KO tidal and require GHCi to be restarted.

`((<~) $ 1/ irand 4)` -- used as a function
output: `ghc: Ratio has zero denominator`

will update as I go,
Oscar

**Comment by yaxu** [comment]
Thanks for this. An intermittent divide-by-zero error like this should result in an event not being sent, rather than terminating the scheduling thread completely as seems to be happening here..

**Comment by OscarSouth** [comment]
Ok, just hit another one. 

In a rush to hit the next downbeat with a big impact, I didn't correctly update my syntax and didn't close the `[` `]` brackets in a pattern for `ur`. This resulted in a complete KO of the tidal stream (I would normally have just expected a syntax error).

`d9 $ ruismk 4 "[bd:crotchet"`

Output:
```
ghc: Syntax error in sequence:
  "[bd:crotchet"
               ^  
unexpected end of input
expecting charnum, rest, "[", "{", "<", ".", "_", "," or "]"
```

A little insight here -- `ruismk` is a named instance of `ur` (you can probably tell from the syntax)

I've seen this message and same outright crash in other situations too. One specific case was when U typed `"bd(3/8)"` (instead of `"bd(3,8)"`), again resulting in total KO of tidal's output and a restart of GHCi.

**Comment by lf3zumba** [comment]
Hi, found one that I run into a lot `d1 $ n { , 1 2 3 4}%4` crashes the interpreter with division by zero. Similarly `d1 $ n {1 2, , 3 4}%4`. This happens to me often when live coding drum patterns and I remove a  snare pattern or kick without adding a ~ in the empty slot.

**Comment by yaxu** [comment]
Will redirect all the crash bugs here, so they're in one place.

**Comment by yaxu** [comment]
I think these are fixed but please reopen if not
