### ISSUE TITLE
[discussion] Tablets or phones ..?

### ISSUE THREAD

**Issue by hangtwenty** [tidalcycles/Tidal#500]
**Is your feature request related to a problem? Please describe.**

This is not a problem, just a discussion/question.

**Describe the function/feature you'd like**

* Is it unthinkable to imagine a (subset) of Tidal on iOS? Whether it’s actually SC or perhaps just midi and osc and meant to be used with other tools.
* If not iOS, has anybody tried running it on a Surface Pro etc?

**Why even..?**

I have loved using BitWiz and other small livecoding languages on a phone or tablet.

I have also loved using Monome’s Teletype eurorack module.

Tidal on phone or tablet → Expert Sleepers module(s) for MIDI/OSC → Eurorack hardware ... could be a very powerful combo.

I know this is somewhat apart from some other Tidal/livecoding play-styles. I’m just curious if it’s way out of reach, or if it’s just waiting for someone to try and figure it out — I may have some extra hack time coming up.

**Comment by bgold-cosmos** [comment]
I think the main obstacle is that Tidal (as it works now) runs in a Haskell interpreter (GHCi), and one doesn't exist or exists only in buggy form on iOS or Android.

It might be easier to just have it as a web service (like extramuros/estuary), although I don't know if such things can send back MIDI/OSC for output.

**Comment by hangtwenty** [comment]
Very good point!


________________________________

**Comment by yaxu** [comment]
Also Tidal has a GPL3 license, which I believe iOS is still hostile towards.

**Comment by yaxu** [comment]
Closing for now, feel free to continue the discussion on the forum: https://forum.toplap.org/c/communities/tidalcycles
