### ISSUE TITLE
comparison interacting strangely with types

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#503]
I've noticed some odd behavior with `>` and `<` operators:

First, the good behavior is that for things like `+` a bare literal gets automatically promoted to a Pattern Double and then to a ControlPattern, like this:
```
tidal> n "0 3" + 1
(0>½)|n: 1.0f
(½>1)|n: 4.0f

tidal> n "0 3" + n 1
(0>½)|n: 1.0f
(½>1)|n: 4.0f
```

Now, this doesn't work for `>`, which is fine:
```
tidal> n "0 3" > 1
*** Exception: compare: not supported for patterns
CallStack (from HasCallStack):
  error, called at ./Sound/Tidal/Pattern.hs:389:13 in main:Sound.Tidal.Pattern

tidal> n "0 3" > n 1
*** Exception: compare: not supported for patterns
CallStack (from HasCallStack):
  error, called at ./Sound/Tidal/Pattern.hs:389:13 in main:Sound.Tidal.Pattern
```

Where it gets weird is if you try to make it work with `fmap`:
```
tidal> (>) <$> n "0 3" <*> n 1
(0>½)|False
(½>1)|True

tidal> (>) <$> n "0 3" <*> 1
(0>½)|False
(½>1)|False
```
I expected the second case to throw an error or something - instead it just gives a wrong answer. 

It seems that what's happening in the second case is that Haskell is interpreting `>` as having a type of `Num a => (ControlMap -> a -> b)`:
```
tidal> :t \f -> (f) <$> n "0 3" <*> 1

\f -> (f) <$> n "0 3" <*> 1
  :: Num a => (ControlMap -> a -> b) -> Pattern b
```
I suppose since Maps are instances of Ord then somehow this is allowed!  So the comparison that's messing things up is this:
```
tidal> (Map.singleton "n" (VF 3)) > 0

False
```
I was really baffled by this, because `>` shouldn't compare things of different types.  But it turns out ControlMap is defined to be an instance of Num in Pattern.hs, which I believe is the source of all this.

I'm not sure if there's a solution since I think having ControlMap as a Num instance is pretty central to some core code.  But it has the side effect of messing up Haskell's interpretation of literals.  Is there an explicit way to specify the desired behavior?  I'm finding it hard to think my way through the chain of type inferences.

**Comment by yaxu** [comment]
I think the confusion comes from `"bd"` being shorthand for `s "bd"`.
So `(>) <$> n "0 3" <*> 1` is the same as `(>) <$> n "0 3" <*> s 1`

**Comment by yaxu** [comment]
This is done in Sound.Tidal.Simple: 
```
instance {-# OVERLAPPING #-} IsString ControlPattern where
  fromString = s . parseBP_E
```

**Comment by yaxu** [comment]
Hmm no I'm wrong, as of course `1` isn't a string.. sorry for the noise!

**Comment by bgold-cosmos** [comment]
I think numbers get handled differently:
```
tidal> n "0 3" # 1

(0>½)|n: 1
(½>1)|n: 1
```

**Comment by yaxu** [comment]
Yes `1` gets turned into `n 1`, but that `1` ends up as an integer (inside `VI` instance of a `Value`).

So I thought this would 'fix' it: 
`(>) <$> n "0 3" <*> 1.0`

That ends up with a floating point `VF` value, but still...
```
(>) <$> n "0 3" <*> 1.0
(0>½)|False
(½>1)|False
```
Strange!

**Comment by yaxu** [comment]
Aha, floating point is interpreted as `speed`..
```
1.0 :: ControlPattern
(0>1)|speed: 1.0f
```

**Comment by yaxu** [comment]
It's kind of nice that you can do 
```
("bd" # 1 # 1.0) :: ControlPattern
(0>1)|n: 1, s: "bd", speed: 1.0
```
All ears on whether this is the best intepretation of bare numbers though!

**Comment by bgold-cosmos** [comment]
I think having the bare `1` interpreted as n (VI 1) is very weird:
```
tidal> 1 :: ControlPattern
(0>1)|n: 1

tidal> n 1
(0>1)|n: 1.0f
```
I think SuperDirt doesn't care, but under the hood these are completely different OSC messages!

**Comment by yaxu** [comment]
I think this is a case of not being explicit about types, and Haskell making its best guess. I'm not sure if we can tweak this guessing, but don't think we should force all bare numbers to be floating point.

**Comment by bgold-cosmos** [comment]
Ah, I think for this specific issue we could provide an instance of Ord for Value.  Right now the Value type automatically derives the comparisons, so we get this behavior:
```
tidal> (VF 2) > (VI 1)
False

tidal> (VF 2) < (VI 1)
True
```
Turns out this happens by default because `VI` is defined later in the constructor.

I'll try providing an explicit instance, and if it improves things (and doesn't break anything else) I'll put together a PR.

**Comment by telephon** [comment]
I don't think it is a very good decision to use the different types of numbers for dispatching between different functions or argument names. This is hard to read. Also it assumes that those functions or arguments (`speed` and `n`) are always more important than others, which might not be a universal (enough) assumption.

**Comment by telephon** [comment]
superdirt interprets all numbers in the same way in these cases, so the type doesn't/shouldn't matter.

**Comment by yaxu** [comment]
Agreed in general Julian, I added this feature for a simplified Tidal
interface designed for young children. We could make Sound.Tidal.Simple
with all these tricks an optional import.

**Comment by telephon** [comment]
Agreed in general, but I have didactic concerns. Should children learn to associate integers with sample choice and floats with speed? Maybe yes, maybe no.

**Comment by yaxu** [comment]
Just has an example who'd added +9 on the end of a pattern, found it increased pitch, but that they couldn't pattern the `9`.. Definitely worth hiding this feature
