### ISSUE TITLE
Automatically generated documentation

### ISSUE THREAD

**Issue by JPenuchot** [tidalcycles/Tidal#504]
Cheap, easy, would generate a doc far better than the userbase

**Comment by yaxu** [comment]
We went for mediawiki to make it easy to contribute, and for the internationalisation feature. Further, generating documentation from code is fine for API docs, but less for UI docs. Feel free to reopen if you disagree and want to put work into this.

**Comment by JPenuchot** [comment]
What's lacking for the docs is an exhaustive index with brief descriptions. The userbase has such an index, but it might not be exhaustive and it doesn't provide a direct overview of the functions. I think the best way to reshape the userbase would be to derive it from a more detailed, automatically generated documentation. I'll get my hands into it.

**Comment by yaxu** [comment]
Thanks!

**Comment by yaxu** [comment]
Did you get anywhere with this @JPenuchot ? I'm still unconvinced this is the way forward for the previously stated reasons.. But interested in what you found.

**Comment by JPenuchot** [comment]
Hey, I'm sorry I've been very busy with my main project during the last months and I didn't really take time. I had a quick look at [Haddock](https://www.haskell.org/haddock/) that seems to be the standard way to make automatically generated but didn't get my hands into it.

**Comment by yaxu** [comment]
Ok, closing for now, feel free to reopen if you think it has legs, but for now I think the mediawiki is the way forward.
