### ISSUE TITLE
ease-of-use addition to `ur` function

### ISSUE THREAD

**Issue by Dsm0** [tidalcycles/Tidal#507]
**Describe the function/feature you'd like**

with `ur`, you could add a special case for multi-line strings, making it act as 
making it act like two patterns in brackets separated by commas,
ie. a1 = pattern 1, a2 = pattern 2,
`ur 4 "[a1 a1 a1 a1, b1 b1 ~ b1]"`
would be the same as
```
ur 4 """
a1 a1 a1 a1
b1 b1 b1 b1
"""
```
this would look more like how different tracks are organized in a daw, and would be great for composing longer songs

**Comment by stalexxx** [comment]
It has nothing to do with tidal itself. As far as I know you can choose different options
1)haskell multiline strings

ur 4 "[\
\ a1 a1 a1 a1,\
\ b1 b1 b1 b1  ]"

2. Other option is quasi quotes notations, your query gonna be like this

ur 4 [r|
a1 a1 a1 a1
b1 b1 b1 b1
|]

this can be trickier, so you should install package 
cabal install raw-strings-qq 

and than add to you bootTidal.hs something like this

import Text.RawString.QQ
:set -XQuasiQuotes
