### ISSUE TITLE
tidal.el: pulse highlighting delays sending the string

### ISSUE THREAD

**Issue by unthingable** [tidalcycles/Tidal#51]
I wonder if it's just me, but pulse highlighting prevents `tidal-send-string` from doing its thing until the pulsing is finished.

**Comment by yaxu** [comment]
I don't see this behaviour (emacs 24.3.1, linux).

Try just evaluating something simple like 1+1. Do you see '2' in the post
window immediately, or after the pulsing is finished? If the latter, does
commenting out the pulse-* calls in tidal.el, then re-evaluating (or just
restarting emacs) get rid of the delay? If so, what version of emacs are
you using?

cheers

alex

**Comment by unthingable** [comment]
Yes to both questions (I also posted a comment in the corresponding commit).

This is 24.4 (9.0), OSX.

**Comment by unthingable** [comment]
Upgrading to 24.5 fixed it!
