### ISSUE TITLE
Pattern with `slow`/`fast` breaks `trigger`

### ISSUE THREAD

**Issue by tuchella** [tidalcycles/Tidal#512]
**Describe the bug**
In a patten with `slow`/`fast` and `trigger`, no triggered transition happens.  

**To Reproduce**
Execute the following pattern:

```
setcps 1

d1 $ slow 2 $ s "bd*8" # gain 1 # hpf (trigger 1 $ range 1000 10 $ slow 1 envL)
```

The HPF will stay at 1000 Hz without any transition. The same applies for other controls.
The pattern looks correct when printed, but no change audible:

```
t>(0>¼)|gain: 1.0f, hcutoff: 1000.0f, s: "bd"
(¼>½)|gain: 1.0f, hcutoff: 876.25f, s: "bd"
(½>¾)|gain: 1.0f, hcutoff: 752.5f, s: "bd"
(¾>1)|gain: 1.0f, hcutoff: 628.75f, s: "bd"
```

**Expected behavior**
I think the result should be the sames as:

```
setcps 0.5

d1 $ s "bd*8" # gain 1 # hpf (trigger 1 $ range 1000 10 $ slow 1 envL)
```

With `slow 1` it also works as expected :

```
setcps 0.5

d1 $ slow 1 $ s "bd*8" # gain 1 # hpf (trigger 1 $ range 1000 10 $ slow 1 envL)
```

**Environment:**
 - OS: Windows 10 64 Bit
 - Haskell version: 8.6.4 
 - Tidal version: 1.0.11
 - SuperCollider version: 3.10.0

**Additional context**
Using the latest atom plugin.

**Comment by yaxu** [comment]
Hmm this is expected behaviour from my perspective, but I can see the confusion and it needs some careful documenting. `trigger` will reset time to `0` for that part of the pattern, but if you then manipulate time it'll do that relative to a different time point and the trigger will go awry.

Things should be better if you isolate the trigger from that slow:
```
d1 $ (slow 2 $ s "bd*8" # gain 1) # hpf (trigger 1 $ range 1000 10 $ slow 1 envL)
```

**Comment by tuchella** [comment]
Got it. Thanks! 

I added small section to the `trigger` wiki page. More careful explanation may be required, but for now should at least help others facing the same issue.

**Comment by yaxu** [comment]
Thanks a lot @tuchella !
