### ISSUE TITLE
Control input and state

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#514]
We have experimental control input working, there is a lot more to explore with state though I think.

It's possible to share values between multiple patterns via assignment but this isn't 'reactive', i.e. you have to re-evaluate a pattern to get it to run with the new value.

I think the thing to do is make the control input store patterns rather than simple values, then make it easy to store them in global state so running patterns will automatically use the new values.

Making control input patterns also brings up the possibility of being able to store the history of an external control source and then play with that as a pattern.

**Comment by bgold-cosmos** [comment]
What happens if you query the future of an input pattern?

**Comment by yaxu** [comment]
I was thinking that it could do some generation based on analysis of the past, maybe even just building up a simple markov chain..
