### ISSUE TITLE
cat and multicycle patterns

### ISSUE THREAD

**Issue by derekxkwan** [tidalcycles/Tidal#515]
Pretty new to Tidal (so apologies if I'm wrong...):

Take

`d1 $ cat  [slow 3 $ sound "bd*4" ,sound "hh*4"]` (or equivalently `d1 $ cat  [sound "[bd*4]/3" ,sound "hh*4"]` if I understand  correctly?)

What I'm wanting here is 4 bass drums over 3 cycles, then a cycle  of 4 hi hats.

Instead I'm getting `"bd ~ ~ bd"` `"hh hh hh hh"` `" ~ ~ bd ~"` `"hh hh hh hh"` `"~ bd ~ ~"` `"hh hh hh hh"`, essentially the same 4 against 3 as originally desired, but broken up with alternating `sound "hh*4"`s 

According to the docs: "cat, (also known as slowcat, to match with fastcat defined below) concatenates a list of patterns into a new pattern; each pattern in the list will maintain its original duration", which isn't happening here?

I installed the Quark awhile ago, but I've installed the Haskell side just this week so I think I'm on the newest version.

**Comment by yaxu** [comment]
This is expected - `cat` takes a cycle from each pattern you give it. By 'slowing down' a pattern by a factor of three, you're spreading out each cycle over three cycles. The reference duration of a cycle stays the same.

Try `squeeze` for making patterns of patterns:
```haskell
d1 $ squeeze "0@3 1" [sound "bd*4" ,sound "hh*4"]
```

**Comment by derekxkwan** [comment]
ah cool, things are starting to click a bit more. thanks for the help!
