### ISSUE TITLE
been trying to install for 2 days. HALP ME PLZ!

### ISSUE THREAD

**Issue by outlowd** [tidalcycles/Tidal#516]
I am running macOS 10.12.6

I've tried for a couple of days to install first using the manual installation (this was accidental) and then uninstalling everything (actually reverted using time machine)  and doing it using the bootstrap for macOS. I installed Haskell 8.2.1 using the link under "Automated Installation with Tidal Bootstrap". I think my mistake was that I installed it AFTER running the bootstrap installer. I have attached below the error I received when attempting $ cabal install tidal.  Should I try to uninstall everything except Haskell and then run the bootstrap again? How should I even go about uninstalling if that is the case?

**********************************************************************

=== Configuration for cabal has been written to
    /Users/TFM/.cabal/config

=== Executables will be installed in:
    /Users/TFM/Library/Haskell/bin

    You may wish to place this on your PATH by adding the following
    line to your ~/.bash_profile:

    export PATH="$HOME/Library/Haskell/bin:$PATH"

=== When documentation is built, a master index to all documentation
    will be placed in:

    /Users/TFM/Library/Haskell/doc/index.html

    You may wish to bookmark that file once it gets built (after the
    first cabal install).

**********************************************************************

Downloading the latest package list from hackage.haskell.org
Warning: --root-cmd is no longer supported, see
https://github.com/haskell/cabal/issues/3353 (if you didn't type --root-cmd,
comment out root-cmd in your ~/.cabal/config file)
Resolving dependencies...
Downloading base-orphans-0.8.1...
Downloading blaze-builder-0.4.1.0...
Configuring base-orphans-0.8.1...
Downloading cabal-doctest-1.0.6...
Downloading clock-0.7.2...
Configuring blaze-builder-0.4.1.0...
Configuring cabal-doctest-1.0.6...
Configuring clock-0.7.2...
Building base-orphans-0.8.1...
Building blaze-builder-0.4.1.0...
Building clock-0.7.2...
Building cabal-doctest-1.0.6...
Failed to install base-orphans-0.8.1
Build log ( /Users/TFM/.cabal/logs/ghc-8.2.1/base-orphans-0.8.1-1ZPS5Bdn4cGAFsiFaSKBoB.log ):
cabal: Entering directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20438/base-orphans-0.8.1'
Configuring base-orphans-0.8.1...
Preprocessing library for base-orphans-0.8.1..
Building library for base-orphans-0.8.1..
[1 of 2] Compiling Data.Orphans.Prelude ( src/Data/Orphans/Prelude.hs, dist/build/Data/Orphans/Prelude.o )
[2 of 2] Compiling Data.Orphans     ( src/Data/Orphans.hs, dist/build/Data/Orphans.o )
[1 of 2] Compiling Data.Orphans.Prelude ( src/Data/Orphans/Prelude.hs, dist/build/Data/Orphans/Prelude.p_o )

In file included from /Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Rts.h:30:0: error:
    0,
                     from /var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/ghc20698_0/ghc_7.c:2:

/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Stg.h:30:3: error:
     error: #error __STDC_VERSION__ does not advertise C99 or later
     # error __STDC_VERSION__ does not advertise C99 or later
       ^
   |
30 | # error __STDC_VERSION__ does not advertise C99 or later
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20438/base-orphans-0.8.1'
Downloading colour-2.3.5...
Configuring colour-2.3.5...
Building colour-2.3.5...
Failed to install clock-0.7.2
Build log ( /Users/TFM/.cabal/logs/ghc-8.2.1/clock-0.7.2-9fV7rV7wNUo6v6mDurfiVg.log ):
cabal: Entering directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20441/clock-0.7.2'
Configuring clock-0.7.2...
Preprocessing library for clock-0.7.2..
Clock.hsc:44:0: warning: "hsc_alignment" redefined [enabled by default]
In file included from dist/build/System/Clock_hsc_make.c:1:0:
/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/template-hsc.h:91:0: note: this is the location of the previous definition
 #define hsc_alignment(x...)                                           \
 ^
Building library for clock-0.7.2..
[1 of 1] Compiling System.Clock     ( dist/build/System/Clock.hs, dist/build/System/Clock.o )

System/Clock.hsc:136:1: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘clockToConst’:
        Patterns not matched: MonotonicRaw
    |
136 | clockToConst Monotonic = #const SYSTEM_CLOCK
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
[1 of 1] Compiling System.Clock     ( dist/build/System/Clock.hs, dist/build/System/Clock.p_o )

System/Clock.hsc:136:1: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘clockToConst’:
        Patterns not matched: MonotonicRaw
    |
136 | clockToConst Monotonic = #const SYSTEM_CLOCK
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

In file included from /Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Rts.h:30:0: error:
    0,
                     from /var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/ghc20716_0/ghc_3.c:2:

/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Stg.h:30:3: error:
     error: #error __STDC_VERSION__ does not advertise C99 or later
     # error __STDC_VERSION__ does not advertise C99 or later
       ^
   |
30 | # error __STDC_VERSION__ does not advertise C99 or later
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20441/clock-0.7.2'
Failed to install cabal-doctest-1.0.6
Build log ( /Users/TFM/.cabal/logs/ghc-8.2.1/cabal-doctest-1.0.6-9O7RODlr6Em2d8dir5ofmU.log ):
cabal: Entering directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20440/cabal-doctest-1.0.6'
Configuring cabal-doctest-1.0.6...
Preprocessing library for cabal-doctest-1.0.6..
Building library for cabal-doctest-1.0.6..
[1 of 1] Compiling Distribution.Extra.Doctest ( src/Distribution/Extra/Doctest.hs, dist/build/Distribution/Extra/Doctest.o )
[1 of 1] Compiling Distribution.Extra.Doctest ( src/Distribution/Extra/Doctest.hs, dist/build/Distribution/Extra/Doctest.p_o )

In file included from /Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Rts.h:30:0: error:
    0,
                     from /var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/ghc20728_0/ghc_5.c:2:

/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Stg.h:30:3: error:
     error: #error __STDC_VERSION__ does not advertise C99 or later
     # error __STDC_VERSION__ does not advertise C99 or later
       ^
   |
30 | # error __STDC_VERSION__ does not advertise C99 or later
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20440/cabal-doctest-1.0.6'
Failed to install blaze-builder-0.4.1.0
Build log ( /Users/TFM/.cabal/logs/ghc-8.2.1/blaze-builder-0.4.1.0-2BGGsmNQw0nCOX3ckEmSsq.log ):
cabal: Entering directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20439/blaze-builder-0.4.1.0'
Configuring blaze-builder-0.4.1.0...
Preprocessing library for blaze-builder-0.4.1.0..
Building library for blaze-builder-0.4.1.0..
[ 1 of 11] Compiling Blaze.ByteString.Builder.Internal.Write ( Blaze/ByteString/Builder/Internal/Write.hs, dist/build/Blaze/ByteString/Builder/Internal/Write.o )
[ 2 of 11] Compiling Blaze.ByteString.Builder.Compat.Write ( Blaze/ByteString/Builder/Compat/Write.hs, dist/build/Blaze/ByteString/Builder/Compat/Write.o )
[ 3 of 11] Compiling Blaze.ByteString.Builder.Int ( Blaze/ByteString/Builder/Int.hs, dist/build/Blaze/ByteString/Builder/Int.o )
[ 4 of 11] Compiling Blaze.ByteString.Builder.Html.Word ( Blaze/ByteString/Builder/Html/Word.hs, dist/build/Blaze/ByteString/Builder/Html/Word.o )
[ 5 of 11] Compiling Blaze.ByteString.Builder.Char8 ( Blaze/ByteString/Builder/Char8.hs, dist/build/Blaze/ByteString/Builder/Char8.o )
[ 6 of 11] Compiling Blaze.ByteString.Builder.Char.Utf8 ( Blaze/ByteString/Builder/Char/Utf8.hs, dist/build/Blaze/ByteString/Builder/Char/Utf8.o )
[ 7 of 11] Compiling Blaze.ByteString.Builder.Html.Utf8 ( Blaze/ByteString/Builder/Html/Utf8.hs, dist/build/Blaze/ByteString/Builder/Html/Utf8.o )
[ 8 of 11] Compiling Blaze.ByteString.Builder.ByteString ( Blaze/ByteString/Builder/ByteString.hs, dist/build/Blaze/ByteString/Builder/ByteString.o )
[ 9 of 11] Compiling Blaze.ByteString.Builder.HTTP ( Blaze/ByteString/Builder/HTTP.hs, dist/build/Blaze/ByteString/Builder/HTTP.o )
[10 of 11] Compiling Blaze.ByteString.Builder.Word ( Blaze/ByteString/Builder/Word.hs, dist/build/Blaze/ByteString/Builder/Word.o )
[11 of 11] Compiling Blaze.ByteString.Builder ( Blaze/ByteString/Builder.hs, dist/build/Blaze/ByteString/Builder.o )
[ 1 of 11] Compiling Blaze.ByteString.Builder.Internal.Write ( Blaze/ByteString/Builder/Internal/Write.hs, dist/build/Blaze/ByteString/Builder/Internal/Write.p_o )

In file included from /Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Rts.h:30:0: error:
    0,
                     from /var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/ghc20833_0/ghc_13.c:2:

/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Stg.h:30:3: error:
     error: #error __STDC_VERSION__ does not advertise C99 or later
     # error __STDC_VERSION__ does not advertise C99 or later
       ^
   |
30 | # error __STDC_VERSION__ does not advertise C99 or later
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20439/blaze-builder-0.4.1.0'
Failed to install colour-2.3.5
Build log ( /Users/TFM/.cabal/logs/ghc-8.2.1/colour-2.3.5-JEsnCS3sSHd7HdTjUp6M7v.log ):
cabal: Entering directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20438/colour-2.3.5'
Configuring colour-2.3.5...
Preprocessing library for colour-2.3.5..
Building library for colour-2.3.5..
[ 1 of 14] Compiling Data.Colour.CIE.Chromaticity ( Data/Colour/CIE/Chromaticity.hs, dist/build/Data/Colour/CIE/Chromaticity.o )
[ 2 of 14] Compiling Data.Colour.CIE.Illuminant ( Data/Colour/CIE/Illuminant.hs, dist/build/Data/Colour/CIE/Illuminant.o )
[ 3 of 14] Compiling Data.Colour.Chan ( Data/Colour/Chan.hs, dist/build/Data/Colour/Chan.o )
[ 4 of 14] Compiling Data.Colour.Internal ( Data/Colour/Internal.hs, dist/build/Data/Colour/Internal.o )
[ 5 of 14] Compiling Data.Colour.Matrix ( Data/Colour/Matrix.hs, dist/build/Data/Colour/Matrix.o )
[ 6 of 14] Compiling Data.Colour.RGB  ( Data/Colour/RGB.hs, dist/build/Data/Colour/RGB.o )
[ 7 of 14] Compiling Data.Colour.RGBSpace.HSL ( Data/Colour/RGBSpace/HSL.hs, dist/build/Data/Colour/RGBSpace/HSL.o )
[ 8 of 14] Compiling Data.Colour.RGBSpace.HSV ( Data/Colour/RGBSpace/HSV.hs, dist/build/Data/Colour/RGBSpace/HSV.o )
[ 9 of 14] Compiling Data.Colour.SRGB.Linear ( Data/Colour/SRGB/Linear.hs, dist/build/Data/Colour/SRGB/Linear.o )
[10 of 14] Compiling Data.Colour.RGBSpace ( Data/Colour/RGBSpace.hs, dist/build/Data/Colour/RGBSpace.o )
[11 of 14] Compiling Data.Colour.SRGB ( Data/Colour/SRGB.hs, dist/build/Data/Colour/SRGB.o )
[12 of 14] Compiling Data.Colour      ( Data/Colour.hs, dist/build/Data/Colour.o )
[13 of 14] Compiling Data.Colour.Names ( Data/Colour/Names.hs, dist/build/Data/Colour/Names.o )
[14 of 14] Compiling Data.Colour.CIE  ( Data/Colour/CIE.hs, dist/build/Data/Colour/CIE.o )
[ 1 of 14] Compiling Data.Colour.CIE.Chromaticity ( Data/Colour/CIE/Chromaticity.hs, dist/build/Data/Colour/CIE/Chromaticity.p_o )

In file included from /Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Rts.h:30:0: error:
    0,
                     from /var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/ghc20906_0/ghc_3.c:2:

/Library/Frameworks/GHC.framework/Versions/8.2.1-x86_64/usr/lib/ghc-8.2.1/include/Stg.h:30:3: error:
     error: #error __STDC_VERSION__ does not advertise C99 or later
     # error __STDC_VERSION__ does not advertise C99 or later
       ^
   |
30 | # error __STDC_VERSION__ does not advertise C99 or later
   |   ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/var/folders/zg/h28pdh5s2vldlvzbls1tjnn80000gn/T/cabal-tmp-20438/colour-2.3.5'
cabal: Error: some packages failed to install:
base-orphans-0.8.1-1ZPS5Bdn4cGAFsiFaSKBoB failed during the building phase.
The exception was:
ExitFailure 1
bifunctors-5.5.4-KMJsJzeddbh31WX1paURYg depends on bifunctors-5.5.4 which
failed to install.
blaze-builder-0.4.1.0-2BGGsmNQw0nCOX3ckEmSsq failed during the building phase.
The exception was:
ExitFailure 1
cabal-doctest-1.0.6-9O7RODlr6Em2d8dir5ofmU failed during the building phase.
The exception was:
ExitFailure 1
clock-0.7.2-9fV7rV7wNUo6v6mDurfiVg failed during the building phase. The
exception was:
ExitFailure 1
colour-2.3.5-JEsnCS3sSHd7HdTjUp6M7v failed during the building phase. The
exception was:
ExitFailure 1
comonad-5.0.5-3tf1RbA5BUO7zvPayd4NxC depends on comonad-5.0.5 which failed to
install.
distributive-0.6-Lne1Tonexu0K2w4cErv6tj depends on distributive-0.6 which
failed to install.
hosc-0.17-JBmrlDANUTMGZ9oB47DY9I depends on hosc-0.17 which failed to install.
tidal-1.0.13-8CYq8UmFXum90FTrVZ8FlS depends on tidal-1.0.13 which failed to
install.

**Comment by yaxu** [comment]
Sorry to hear about these woes.

Try installing with `stack` instead of `cabal`.

This is done with the following command in a terminal window:

```
stack install tidal
```

Once that's done, you just have to tell the atom plugin to use the tidal installed with stack. In atom, find the settings for the tidalcycles package, and set the `ghci path` setting to `stack ghci`. Then, restart atom and all should be well.

**Comment by outlowd** [comment]
Hi alex, 

thanks for your help. Really looking forward to using tidal.

I tried using $ stack install tidal 
and received the following error.
Thanks in advance!

Downloaded lts-13.21 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

**Comment by outlowd** [comment]
i just tried to run 
$ stack update
and then try to install again using
$stack install tidal 
but it gave the same error as before

Downloaded lts-13.21 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: "bytestring--lt-0_10_4""

**Comment by dktr0** [comment]
The part about lts-13.21 looks odd to me - it signals that stack is using much more recent version of many packages than is expected, and possibly too new for your ghc version. I wonder what happens if you try to build with stack but downloading the source first, something like this:
cd ~
git clone https://github.com/TidalCycles/Tidal.git
cd Tidal
stack build
stack install
[I would think you will see something about downloading lts-12.20 and probably also something about downloading ghc-8.4.4]

**Comment by outlowd** [comment]
my stack version is 1.5.1

Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1

and my ghc version is 8.2.1

The Glorious Glasgow Haskell Compilation System, version 8.2.1

should i update? do you think it'd muck up stuff if I tried building from the git clone?

**Comment by yaxu** [comment]
Hi @outlowd, sorry for being slow, I've had a busy month. Did you get anywhere with this?

**Comment by yaxu** [comment]
This seems to be the problem with stack: https://github.com/commercialhaskell/stackage/issues/2759

`curl -sSL https://get.haskellstack.org/ | sh -s - -f` should get you a working stack.

Will close for now, please reopen if you still have problems
