### ISSUE TITLE
[discussion] VCV Rack module with pattern engine

### ISSUE THREAD

**Issue by stalexxx** [tidalcycles/Tidal#522]
I'm sure everyone heard about VCV Rack. I am specifically experincing difficulties when it comes to create rythm. I thing tidal have great pattern language and it would be great to have it as a module in VCV rack. Do you thing crossing algo-music and modulars is a good idea?

**Comment by yaxu** [comment]
I don't know too much about it, and haven't used it, but looks very nice. Is all free/open source?

**Comment by stalexxx** [comment]
Both, and most "modules" a free, so, cool modular right on you laptop

**Comment by delaudio** [comment]
Hi! I usually play with tidalcycles, VCV Rack and Ableton together. 
I found a workaround to make them communicate this way:
I send midi clock from tidal to ableton and sync it with ableton's midi settings, instead regarding to VCV Rack, i send a note on midi channel 0 and use it as a clock passing through a clock module in vcv rack.
This way, all three things are clocked together, and I can use all other midi channels except for 0, to send midi data .to Ableton and VCV Rack, even using Bridge.
It would be even nicer to receive midi clock from Ableton to Tidal, but is it not possible yet right? 
About routing midi messages and audio signals, I configured (I'm on Mac) Soundflower 64 ch and IAC DRIVER.

**Comment by XiNNiW** [comment]
I've had the same thought about a dedicated VCV module (or even a dedicated hardware module) that could make cv and gates in response to tidalcycles patterns. Like an implementation of Dirt but for control voltage instead of samples.

**Comment by msp** [comment]
I have an ES8 that allows you to send voltages from your PC to your modular. Pretty sure the complimenting Silent Way software has an OSC interface so you could map Tidal patterns with a bit of work. Ableton also now has native CV Tools plugins but not sure if they speak OSC.

https://www.expert-sleepers.co.uk/es8.html

I always gig/produce with a laptop around so saving rack space by offloading LFOs and other control voltage signals to the PC makes a lot of sense.

**Comment by AndrewBelt** [comment]
Does it make sense to add Tidal as a "scripting engine" in the new VCV Prototype module?

https://twitter.com/vcvrack/status/1173131521814867968
https://twitter.com/vcvrack/status/1177568707918348289

Download: https://vcvrack.com/plugins.html#VCV%20Prototype
Source: https://github.com/VCVRack/VCV-Prototype
Adding a script engine: https://github.com/VCVRack/VCV-Prototype/blob/master/README.md#adding-a-script-engine

**Comment by bgold-cosmos** [comment]
I've only just started looking at VCV Rack, but it looks like the "scripting engine" is supposed to handle DSP/CV computation, which isn't what Tidal does.

It'd be nice if there were OSC-CV bridging, I think that'd simplify connecting Tidal to it.

**Comment by yaxu** [comment]
This would be great but closing for now unless there's a concrete issue. Otherwise vcvrack control would be a good discussion to have on https://club.tidalcycles.org/
