### ISSUE TITLE
Tidal completely crashes on euclid syntax error

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#529]
I accidentally used a tilde for a value in a Euclid pattern:

d1 $ fast 2 $ midinote "5(3,8,<~ 3>)"

This immediately resulted in the following error:

```
Warning: GHCi | ghc: Syntax error in sequence:
Warning: GHCi |   "5(3,8,<~ 3>)"
Warning: GHCi |           ^  
Warning: GHCi | unexpected "~"
Warning: GHCi | expecting white space, "-", "+", integer, "c", "d", "e", "f", "g", "a", "b", "'", "[", "{", "<", ".", "_", "," or ">"
```

Audio stopped, but, Tidal did not recover and appeared to completely crash. Had to restart the editor. 

Would be great if Tidal could more gracefully handle this scenario without crashing. These little audio-stopping errors in the Euclid parsing happen to me often and I have to restart my editor each time.

**Comment by bgold-cosmos** [comment]
Are you sure this is on the latest Tidal version?  When I try it I get a syntax error but Tidal doesn't stop and the editor is fine.

**Comment by kindohm** [comment]
Ah, probably not, I will check again.

**Comment by kindohm** [comment]
I upgraded Tidal and still continue to have these issues. It happened again yesterday during a recording sessions. In the moment, I did not take the time to copy the code here to this issue, but I think it was something like this:

`d1 $ s "bd(3,8,<6)"`

Or it may have been:

`d1 $ s "b(3,8,<6>"`

I believe the issue #539 is related.

**Comment by yaxu** [comment]
@kindohm those are both fine for me on (unreleased) master, are you on the latest release?

**Comment by yaxu** [comment]
(I've been having these issues too by the way, keen to get it solved.)

**Comment by yaxu** [comment]
@kindohm If you can confirm some code which definitely cause tidal to crash (is the original one still a problem for you?) and the ghc and tidal version you're on that'd be ace

**Comment by kindohm** [comment]
@yaxu haven't tried `master` yet. Yes, I will document any specifics here; specifics are much more useful than "it may have been...." ;)

**Comment by yaxu** [comment]
Don't worry about trying it on master - just let me know what crashes the latest release, the more crash examples the better! ta

**Comment by kindohm** [comment]
Updated to the latest `master`. Throwing everything I can think of at it now, and it isn't crashing/stopping.

**Comment by yaxu** [comment]
Great, please report if you find something!
