### ISSUE TITLE
Separate out tidal-parse (minitidal) from tidal

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#535]
To reduce dependencies for a core Tidal install, we should separate out MiniTidal (perhaps renaming to tidal-parse).

The disadvantage of doing this is that having them tested together makes it easier to keep Tidal and MiniTidal in sync. So perhaps we keep them in the same repo, with coordinated releases, and get Travis to somehow test them together?

**Comment by yaxu** [comment]
This doesn't seem to be as simple as having two .cabal files in the root folder. AFAICT, cabal will only build a local folder if it contains exactly one .cabal file.

**Comment by dktr0** [comment]
Does the cabal new-build stuff help here? I haven't grokked it closely yet myself...
http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/

**Comment by yaxu** [comment]
@dktr0 Possibly, I haven't really looked into it either though.

For now I made a tidal-parse repo, and set it to be a submodule of tidal:
  https://github.com/tidalcycles/Tidal

Apparently travis automatically checks out submodules.

Next steps
- move over tests
- try to get tidal's travis to run those tests

The function exported from `Sound.Tidal.Parse` is called `parseTidal`, OK?

I'm not sure whether to rename `Sound.Tidal.ParseBP` to `Sound.Tidal.Parse.BP`..

**Comment by yaxu** [comment]
I don't really know what I'm doing with this stuff, but.. This doesn't work:
```
alex@stanage:~/src/tidal/tidal-parse$ cabal v2-test
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```
For some reason v2-test doesn't work in a submodule. If I move the tidal-folder up a level it works. Bah!
However this works:
```
alex@stanage:~/src/tidal/tidal-parse$ cabal test
Warning: The test command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-test command
or the legacy v1-test alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Preprocessing library for tidal-parse-0.0.1..
Building library for tidal-parse-0.0.1..
Preprocessing test suite 'tests' for tidal-parse-0.0.1..
Building test suite 'tests' for tidal-parse-0.0.1..
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to: dist/test/tidal-parse-0.0.1-tests.log
1 of 1 test suites (1 of 1 test cases) passed.
```
So for now I'm trying this:
https://github.com/tidalcycles/Tidal/commit/10d4e52e9036a20414c9fe25b9c8b099e96c2ac7

v2-install is a bit of a mystery to me and I can't find any clear documentation for it.

**Comment by dktr0** [comment]
My experience has been that submodules are a huge pain - because they don't get updated automatically when people pull (you have to do git submodule update manually each time) which makes it so easy for people to not realize they have an outdated version of the submodule...

**Comment by yaxu** [comment]
Ok. Putting everything back in the same repo again could be an option. Maybe as a cabal v2 'project' with tidal and tidal-parse as 'packages'. Hopefully this would allow separate uploads to hackage / stackage

**Comment by dktr0** [comment]
I think it should allow separate uploads to hackage. Also maybe uploads to hackage (ie. at all) are not very important for tidal-parse right now. In Estuary we grab dependencies with nix and can probably work around all kinds of configurations.

**Comment by dktr0** [comment]
Are we going to put this back in the same repo? I think it would be better, especially as it becomes increasingly possible for additions/changes to the rest of Tidal to be reflected in MiniTidal right away. Having to make commits in two separate repositories sounds kind of tedious for that. Also when people are accessing these things via Nix (like we are in Estuary) they'll do so by pinning particular commits - by separating them it makes it easier to fall into the trap of pinning incompatible versions.

**Comment by yaxu** [comment]
Yes agreed, I think we should put it back and try out the separate cabal v2 packages as above.

**Comment by yaxu** [comment]
If that works, we could bring tidal-vis in here too, it's always falling behind. Maybe feedforward too.

**Comment by yaxu** [comment]
@dktr0 I've removed the tidal-parse submodule, basically copying the files over to a folder with the same name.
The only change needed to get them to build together seems to have been to add tidal-parse to the cabal.project file. I thought I'd have to move the tidal library to its own subfolder, but so far cabal seems fine with it being specified as `./`.
Then `cabal new-build all` builds both.

**Comment by yaxu** [comment]
@dktr0 How do you feel about losing the git history? We could try to get it back..

**Comment by yaxu** [comment]
Adding to travis for testing was easy too (pending tests..) https://github.com/tidalcycles/Tidal/commit/3ebc5db9bf089b562b3e9e323566332e35c71da8
I think this is done!

**Comment by dktr0** [comment]
Awesome! No big deal about the history - after all, it's not so much losing the history as putting a little distortion in it... ;)

**Comment by yaxu** [comment]
Jolly good, have deleted the tidal-parse repo
