### ISSUE TITLE
Batch evaluate/execute entire editor at once

### ISSUE THREAD

**Issue by dandrewstewart** [tidalcycles/Tidal#537]
I'd like to "batch" evaluate/execute everything in my Atom text editor. Alternatively, can we evaluate multiple synth connections simultaneously, ignoring others?  <code>stack</code > is a good solution, of course. However, are there any other ways to execute "everything" that's in one editor window?

**Comment by yaxu** [comment]
You could script something in javascript to run in atom, this would be an issue for https://github.com/tidalcycles/atom-tidalcycles/ , though

**Comment by ndr-brt** [comment]
nice idea, issue created

**Comment by ndr-brt** [comment]
Released in atom plugin v3.11.0
