### ISSUE TITLE
Control surface: code evaluation

### ISSUE THREAD

**Issue by dandrewstewart** [tidalcycles/Tidal#538]
I'd like to send an OSC message from, say, a gestural controller (or control surface) and I'd like the OSC message to evaluate all code. Could the MIDI features be extended to include "code evaluation/execution"? This issue could be related to an early github issue: Batch evaluate/execute entire editor at once #537

**Comment by yaxu** [comment]
This would require communication between your control surface and atom, Tidal wouldn't really be involved. Perhaps an issue for https://github.com/tidalcycles/atom-tidalcycles/
