### ISSUE TITLE
 pattern syntax "[cp/4 hh #gain 0.7] ~" causes irreversible silence

### ISSUE THREAD

**Issue by purelazy** [tidalcycles/Tidal#539]
Running the first code fragment starts a rhythm.
Second one causes silence.
Third one doesn't restore the original

[issue.tidal.txt](https://github.com/tidalcycles/Tidal/files/3391422/issue.tidal.txt)

SuperCollider 3.10.2
tidal-1.0.14
Haskell version 8.4.3
Windows 10 Pro

**Comment by kindohm** [comment]
I'm sensing this is related to #529. I continue to have these issues as well.

**Comment by yaxu** [comment]
Fixed in https://github.com/tidalcycles/Tidal/commit/8b0c306b034fc9628f64f280746f5e17b478d04f
