### ISSUE TITLE
delay gives up every other cycle at low cps

### ISSUE THREAD

**Issue by rseymour** [tidalcycles/Tidal#542]
**Description**
When running at certain cycles per second the delay effect seems to engage sporadically.

**To Reproduce**
1. Fire up editor and SuperDirt
2. Run
```
setcps 0.62

d1 $ "cp" # delay 0.9 # delayt 0.144
```
on my machine any cps 0.62 or lower produces `cp cpd    cp       cp cpd     cp` where cpd is the delayed cp sound. It seems to skip every other cycle. 

**Expected behavior**
 At `setcps 0.63` and above I hear `cp cpd cp cpd cp cpd` as expected

**Environment (please complete the following information):**
 - OS: Linux (UbuntuStudio 19.04) JACK2
 - Haskell version: GHCi, version 8.4.4
 - Tidal version:  1.1.0
 - SuperCollider version: SuperCollider 3.10.0 (w/ latest superdirt recompiled restarted)

**Additional context**
I've had a lot of squidgy bugs w/ delay, but this is the first reproducible one.  Then again it may just be this machine at this moment. :) Thanks as always.

**Comment by yaxu** [comment]
Confirmed under linux mint. I checked with a packet sniffer and the messages to superdirt are identical apart from the cycle count, so I think it's an issue with superdirt.

@telephon any ideas why this might happen?

**Comment by yaxu** [comment]
@rseymour I'm guessing expected behaviour of `cp cpd cp cpd cp cpd` is a copy-paste error and you're really expecting cpd cpd cpd cpd cpd cpd

**Comment by rseymour** [comment]
yeah that was me lacking a good notation for the delay... the typed in line is "cp" so under normal circumstances I'd here the cp and then the delay line cp which I wrote cpd, but yeah regardless you got the gist of it. :) I want the delay every time ;)

**Comment by telephon** [comment]
I won't have the time to dive into it, but as a first question, is your dirt using `SwitchDelay` or `CombL`? You can test this in sclang, when you type SwitchDelay and hit cmd-i so you see if there is the definition (it's in the sc3-plugins).

One reason could be that the current maximal delay time is 4 sec. Your resulting delay time is `0.62 / 0.144 = 4.3055555555556` seconds, so maybe this is it?

**Comment by rseymour** [comment]
I was doing the math differently in my head (and it sounds differently) to me: 

not working: 
( 0.144 cycles )/ 0.62 (cycles/sec) = 0.23225806451 seconds
working: 
( 0.144 cycles )/ 0.63 (cycles/sec) = 0.22857142857 seconds

with division flipped:
not working:  
0.62 / 0.144 = 4.3055555555556

working:
0.63 / 0.144 = 4.375

Doesn't answer much but by the flipped math they're both over 4 seconds. By my ear the delay is in the subsecond regime... then again my math may be completely off if for instance delay isn't measured in cycles.

**Comment by telephon** [comment]
no, your math is right, I was too quick.

**Comment by yaxu** [comment]
For me, sc3-plugins is installed and SwitchDelay is defined.

On Mon, 29 Jul 2019 at 12:25, Julian Rohrhuber <notifications@github.com> wrote:
>
> I won't have the time to dive into it, but as a first question, is your dirt using SwitchDelay or CombL? You can test this in sclang, when you type SwitchDelay and hit cmd-i so you see if there is the definition (it's in the sc3-plugins).
>
> One reason could be that the current maximal delay time is 4 sec. Your resulting delay time is 0.62 / 0.144 = 4.3055555555556 seconds, so maybe this is it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
blog: http://slab.org/

**Comment by telephon** [comment]
for a test, you could throw the `SwitchDelay` UGen out of its folder and recompile the class library, and then see if the behaviour changes.

**Comment by rseymour** [comment]
I think I found the bug (maybe?) in SuperDirt there is a statement:

https://github.com/musikinformatik/SuperDirt/blob/878c4a6a56535fc5286ca927d8a7c4d2f0bf9dcc/synths/core-synths-global.scd#L86

which looks like:

`delaytime = delaytime * if(lock, reciprocal(cps), 1);`

`lock` is set to 0

In most programming languages that would be false, but in SC it doesn't seem to auto cast it as such and something like

`z =  if(0,"truthy","falsy");` throws an error `The preceding error dump is for ERROR: Message 'if' not understood. RECEIVER: 0`

`z =  if(0==1,"truthy","falsy");` works

I *think* making the line(s) (for both delays):

`delaytime = delaytime * if(lock==1, reciprocal(cps), 1);`

would fix this.  When I have a minute I'll try it and PR it to SuperDirt if it works.

**Comment by rseymour** [comment]
woah I found the bug, or at least why I could never get delay to work properly to my ear.  cps = 1 in the function/method definition forced everything to be relative to cps = 1.  Changing that to plain `cps` works.  I also made some other changes which I need to disentangle, but finally a delayt of 0.5 actually makes a single "cp" sound like "cp cp"! 💯

**Comment by telephon** [comment]
No, this is not how it works. The message `if`, when passed to a `UGen` behaves differently:

https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Audio/UGen.sc#L431

**Comment by rseymour** [comment]
Not a problem when `# lock 1` is in effect.  I updated a couple wiki pages on delaytime to show lock.
