### ISSUE TITLE
Fixing segment, by moving analog/digital distinction from patterns to events

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#543]
The recent 'fixes' to `<*` and `*>` has broken `segment`. E.g. this no longer segments:

```
d1 $ sound "arpy*8" # speed (segment 2 $ range 1 2 saw)
```

I think the fix will involve making definitions of `<*` and `*>` for the cases where one side is analogue and the other digital.

Indeed, from the source:
```
-- If one of the patterns is digital, treat both as digital.. (TODO - needs extra thought)
(<*) pf px = Pattern Digital q
```

**Comment by yaxu** [comment]
This opens a can of worms. We probably should treat combinations of analogue and digital patterns differently (or otherwise drop the distinction again), but it's very easy to turn an analogue pattern into a digital one. E.g.: `nature $ slow 2 sine` is `Digital`, because the `2` is digital.

Perhaps we should make bare numbers like `2` a continuous signal, but that would be a big change, and we probably do want a bare number to be discrete.

For now changing this line: https://github.com/tidalcycles/Tidal/blob/master/src/Sound/Tidal/Pattern.hs#L376
... so that the whole rather than the part of the 'f' event is used to query the 'x' pattern, seems to fix things somewhat, at least `segment` starts working again. This might make things less efficient though..

**Comment by telephon** [comment]
What does the distinction help us to do?

**Comment by yaxu** [comment]
The distinction between digital and analogue? It was used as a hint when combining patterns. For example in the case where "structure comes from the left", what that means depended on whether the pattern on the left has structure (i.e. is digital) or not (i.e. is analogue).

However now I've realised that it's _not_ structure that comes from one side or the other, but _wholes_. Where two events (one from each pattern) match (intersect), you are always left with the intersection as event 'parts'.. But you're also left with a memory of what the event 'whole' was - that is what either comes from the left, right or both ('both' here meaning the intersection of the two wholes).

So it turns out the digital/analogue distinction doesn't help us do anything! The distinction is only meaningful in terms of:
a) the behaviour of the events
b) how you query the patterns

.. and isn't in the types.

This is great and is another big simplification, as you can see from all the deleted code here! https://github.com/tidalcycles/Tidal/commit/b51fdd50b033bd3e0c1925eaf54d3813fccefb8a

I really hope this means that the digital/analogue nature can be removed from the pattern type.

**Comment by yaxu** [comment]
This (hopefully) means that it now makes sense to do `stack ["1 0.5", sine]`, which in theory wasn't before..

**Comment by yaxu** [comment]
Here's a release candidate, would be great to have people testing it out.. I'm going cycling for a couple of weeks tomorrow though, so probably shouldn't release it before then.
https://hackage.haskell.org/package/tidal-1.2.0/candidate

**Comment by yaxu** [comment]
I noticed in 1.1.x, every note will be randomised in the following: `d1 $ struct "t(3,8)" $ sound "arpy" # speed rand`

in 1.0.x and 1.2.x, a new random value will only come once per cycle.

I'll play around with it a bit more but I think best to release 1.2.x now, as 1.1.x is quite broken

**Comment by yaxu** [comment]
Ok, released!

**Comment by yaxu** [comment]
I had to partly back this change out, as simple things like `d1 $ rev $ sound "sn:2"` were causing double events..
So 1.2.1 now up with a broken `segment` again :/

**Comment by kindohm** [comment]
Sounds like this fix is still in progress. Glad to help test; since you backed out the change it doesn't sound like there is anything to test right now.

**Comment by kindohm** [comment]
I'm not sure if this is related to the original issue, but in 1.2.1 I am hearing a lot of duplicated events when `degrade` or the `?` are used:

`d1 $ s "bd*8?"`

`d1 $ degrade $ s "bd*8"`

Those patterns sound as if they were `d1 $ s "bd*64?"`

**Comment by jwaldmann** [comment]
even without "*8". Try `d1 $ s "bd?"` This gives a LOT of events. How can we debug this? This looks normal:
```
tidal>  s "bd?"
(0>1)|s: "bd"
```
but it's not what I am hearing.

**Comment by yaxu** [comment]
Yes the error is only apparent at higher sample rates.
I'm away from my laptop for a while but the answer came in a dream.. Wrap
the 'whole' arc in a Maybe type and set it to nothing for continuous
events, which should then never trigger anything.

**Comment by yaxu** [comment]
Had a go at wrapping wholes in Maybe, seems to help some things:
https://github.com/tidalcycles/Tidal/commit/0368426621c887820b5f4d454a9e7acde5035c47
