### ISSUE TITLE
Variable not in scope: main from GHCi

### ISSUE THREAD

**Issue by ekg** [tidalcycles/Tidal#544]
**Describe the bug**

I have installed tidal on linux as instructed at the userbase.

I've also installed the emacs tidal plugin from melpa.

I start superdirt using sclang:

```
echo 'SuperDirt.start' >/tmp/g && sclang /tmp/g
```

I open a file x.tidal and run the command `C-c C-s` in emacs.

I then try to run:

```
d1 $ sound "bd sn"
```

But this error appears in the GHCi shell below:

```
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> Some flags have not been recognized: prompt-cont,

<interactive>:2:1: error:
    • Variable not in scope: main
    • Perhaps you meant ‘min’ (imported from Prelude)
```

I must be doing something really obvious wrong.

**Comment by yaxu** [comment]
Hm, I'm wasn't sure why it's trying to run a 'main', and looking at the tidal.el file it seems there's a function `tidal-run-region` that does this.. I think this is old stuff that should probably be removed. You want tidal-run-multiple-lines (ctrl-c ctrl-e) or tidal-run-line (ctrl-c ctrl-c)

**Comment by ekg** [comment]
Thanks @yaxu, now I seem to get further:

Running the line:

```
d1 $ sound "bd sn"
```

With `C-c C-c` or `C-c C-e` results in this:

```
<interactive>:7:1: error: Variable not in scope: d1 :: t0 -> t

<interactive>:7:6: error:
    • Variable not in scope: sound :: [Char] -> t0
    • Perhaps you meant ‘round’ (imported from Prelude)
```

I'm still doing something wrong.

**Comment by ekg** [comment]
I've resolved this by reinstalling the entire GHC system and rebuilding tidal from scratch, as per https://github.com/tidalcycles/Tidal/issues/480#issuecomment-499091751
