### ISSUE TITLE
discretise does not work for multiple-cycle "holds"

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#547]
This bug is occurring after pulling the latest from `master` after the #546 fix. 

When using `discretise` it does not seem to "hold" values if the duration is given as greater than a single cycle. 

I would expect this to "hold" a random speed value for eight cycles:

`d1 $ s "bd*16" # speed (discretise (1/8) $ range 0.5 2 $ rand)`

But instead it changes the value every cycle.

These also do not hold for 2, 4, or 16 cycles, respectively:

```
d1 $ s "bd*16" # speed (discretise (1/2) $ range 0.5 2 $ rand)
d1 $ s "bd*16" # speed (discretise (1/4) $ range 0.5 2 $ rand)
d1 $ s "bd*16" # speed (discretise (1/16) $ range 0.5 2 $ rand)
```

However, the patterns below do sound correct, holding for one half or one quarter cycles, respectively:

```
d1 $ s "bd*16" # speed (discretise 2 $ range 0.5 2 $ rand)
d1 $ s "bd*16" # speed (discretise 4 $ range 0.5 2 $ rand)
```

**Comment by yaxu** [comment]
Thanks for this, unfortunately I missed it until after release.. It seems to work with `_range` rather than `range`:
```
d1 $ s "arpy*16" # speed (segment (1/8) $ _range 0.5 2 $ rand + 1)  
```

**Comment by yaxu** [comment]
Yes the way `range` was patterning parameters was the culprit. Will need to look closely at how patterned parameters are implemented on other functions, too.
https://github.com/tidalcycles/Tidal/commit/1f3ccedacd0fbfdff2d3e2f873d39005c4737073

**Comment by kindohm** [comment]
Working great, thanks!
