### ISSUE TITLE
cutBy

### ISSUE THREAD

**Issue by axcmp** [tidalcycles/Tidal#551]
By previously suggesting an orbitBy function, I think it would be appropriate to also suggest a cutBy function, which would control the level of intensity to which cutBy would be applied. 

### cutBy prototype

cutBy _cutgroup_ _intensity_

```
d1 $ stack [
	sound "bd",
	sound "~ [~ [ho:2 hc/2]]" # cutBy "1" 0.75
	]
```

This would make for cutBy to be applied at 75%.

**Comment by bgold-cosmos** [comment]
What do you mean by level of intensity to which cut is applied?  Either a sample interrupts another one or it doesn't, I'm not sure how to partially apply `cut`.

**Comment by axcmp** [comment]
I don’t know if “intensity” is the correct term to use, but I’ve made an illustration to show you what I mean.

![cutBy](https://user-images.githubusercontent.com/39309008/64908719-3e2c5300-d6f3-11e9-81ff-3ca7ff3167f0.png)

On Fig. 1 you can see the space intercrossing the two samples, which is where cutBy would be applied. It is divided from 0. to 1. to show the range of incidence of the cutBy function.

The cut could be abrupt, meaning that there is no change in amplitude at the cut, or there could be smoothness applied to the transition, which could be defined linearly, like shown in Fig. 2.1 for a linear cutBy 0.75 example, or not, like shown on Fig 2.2 for a skewed cutBy 0.25 example.

**Comment by yaxu** [comment]
I think controlling the envelope in this way is already doable with the `fadeTime` superdirt parameter, and shaping the envelope would also be best done on the superdirt side.
