### ISSUE TITLE
Logarithmic and exponential functions

### ISSUE THREAD

**Issue by axcmp** [tidalcycles/Tidal#552]
Suggesting the implementation of logarithmic and exponential functions into Tidal.

### log function prototype

log _x_ _base_

Base could be optional, with _e_ being the default value.

Example results:

log 1000 == 6.907755278982137

log 1000 10 == 3

log 1000 2 == 9.965784284662087

etc.

```
d1 $ s “sample”
	# speed (slow 2 $ log ((run 100) + 1) 100)
```

### exp function prototype

exp _x_

Example result:

exp 2 == 7.38905609893065

```
d1 $ s “sample”
	# speed (exp (rand))
```

**Comment by bgold-cosmos** [comment]
I don't know if there's explicit documentation, but you can use `exp` and `log` on patterns as if they were numbers.  From your example:
```
d1 $ s "sample" # speed (slow 2 $ log (run 100 + 1))
```
should just work, although Haskell's `log` is base e.  You can get base b by just dividing by log b:
```
d1 $ s "sample" # speed (slow 2 $ log (run 100 + 1) / log 100)
```

**Comment by axcmp** [comment]
@bgold-cosmos Yes, this may be it.
