### ISSUE TITLE
timestretch, timestretchBy and time stretch operator

### ISSUE THREAD

**Issue by axcmp** [tidalcycles/Tidal#554]
Suggesting the implementation of time stretching, with the possibility of selectively expanding the duration of single note events inside a pattern (i.e. for use with samples). 
I think maybe this should be of a selective nature, in order not to interfere with the normal behaviour of functions such as chop, slice or striate. Not withstanding, it could also be optionally enabled to work at a connection level, like for example the degrade function which has a specialised operator (?). In this case, it could be timestretch or timestretchBy, with any other available symbol, which would serve as the timestretch operator, values of 1.0 being the regular duration, 1.5 a half more than normal and so on. Pitch shifting would be disabled of course, as the purpose would be to focus on duration explicitly.

### timestretch prototype

timestretch

```
d1 $ timestretch
	$ n “12 16”
	# s “arpanet”
```

This would connect notes events, creating a general legato effect.

### timestretchBy prototype

timestretchBy _duration_

```
d1 $ timestretchBy 1.5
	$ n “12 16”
	# s “arpanet”
```

This would expand general notes duration in half more of its current duration.

### timestretch operator prototype

In this example, I’ll be using the @ symbol as an operator simulator only, not suggesting it.

```
d1 $ n “12@2 16@0.5”
	# s “arpanet”
```

This would make the first note event “12@2” double its duration and the second note event “16@0.5” decrease its duration by half.

Sorry for not making pull requests on these, as I am still not well versed in Haskell to be able to do it.

Thank you!

**Comment by bgold-cosmos** [comment]
Sample manipulation happens in SuperDirt, so for something like this to work most of the code would have to be on that end of things.  I think in principle something like this could be implemented as a special kind of "effect", but to get it to work as described would involve a bit of custom playing around with what Tidal sends as the "delta".

**Comment by axcmp** [comment]
Thank you @bgold-cosmos , how can I learn more about this?

**Comment by bgold-cosmos** [comment]
I think the most up-to-date way is to go into the SuperDirt `library` folder and look at `default-effects-extra.scd` and `default-synths-extra.scd`.  Using stuff in there as an example would be a good start for a timestretch effect.  I think getting the "delta" automatically set up is just a matter of figuring out the right variable to pass into the SynthDef.

**Comment by yaxu** [comment]
I've opened an issue on SuperDirt, as it's really an issue for the synthesis rather than tidal side.

Just to clarify though, you do mean extend a sound without altering its pitch?

**Comment by axcmp** [comment]
Thank you for the info @bgold-cosmos !

Hi @yaxu , thank you, yes I mean extending the duration of note events, without pitch shifting.

**Comment by telephon** [comment]
Often, these methods don't sound that good. It would be good to analyse the soundfiles, and add metadata about them that can be used for this. But all this is a relatively large project.

**Comment by axcmp** [comment]
@yaxu One thing I forgot to mention, akin to the chord notation that Tidal uses, for the arp and arpg functions, having some sort of time notation would be nice, something similar would be [Max/MSP’s time value syntax](https://docs.cycling74.com/max8/vignettes/maxtime_syntax#Table_of_Ticks_and_Note_Values).

**Comment by axcmp** [comment]
@telephon You are right. When applied to samples this is not good, but is there something in place already that works like this for MIDI exclusively?
