### ISSUE TITLE
Support OSC blob type

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#558]
To support sysex, ref: https://github.com/musikinformatik/SuperDirt/issues/151

**Comment by yaxu** [comment]
@tadklimp 
Here's a draft release: https://hackage.haskell.org/package/tidal-1.4.4/candidate

You should be able to install it with 
`cabal v1-install https://hackage.haskell.org/package/tidal-1.4.4/candidate/tidal-1.4.4.tar.gz`
or
`cabal v2-install https://hackage.haskell.org/package/tidal-1.4.4/candidate/tidal-1.4.4.tar.gz`

I haven't tested it fully but you should be able to do `d1 $ array (pure [0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, 0x00, 0x00, 0x04, 0x30, 0x00, 0x00, 0x09, 0xF7])` # midicmd "sysex"`

**Comment by yaxu** [comment]
Perhaps we should call the tidal parameter `sysex` instead of `array`, and then infer the sysex miditype from that in superdirt

**Comment by tadklimp** [comment]
Success! :-D
That's fantastic @yaxu , thanks so much!

In the beginning it was not working but as soon as the `#s "midi"` command is added everything works!

With this minimal snippet on the SuperDirt side [ in the `DirtEventTypes.sc` file, inside the `midiEvent( play: {} )` block] :
```
if(~array.notNil) { midicmd = \sysex; ~array = ~array };
``` 

the Tidal command looks like this:

`d1 $ array (pure [0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, 0x00, 0x00, 0x04, 0x30, 0x00, 0x00, 0x09, 0xF7]) # s "midi" 
`

And yes, I agree, SuperDirt already takes care of the `\sysex` tag, so naming the parameter on the tidal side `sysex` is ideal, as no extra `#midicmd "sysex"` will be needed.

Should I change it and do a Pull Request on the SuperDirt repo? 
Never 've done a pr before, so i hope it will work.

Thanks again,
Tad

**Comment by tadklimp** [comment]
Hi @yaxu,

I'm experimenting a bit with this.

Will it be possible to modulate the values of the `array/sysex` message?

something like this doesn't work:
`let  cents amount p = array (pure [0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, 0x00, 0x00, 0x04, 0x30, 0x00, 0x00, amount, 0xF7]) $ p 
`

or simpler
`d1 $ array (pure [0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, 0x00, 0x00, 0x04, 0x30, 0x00, 0x00, (irand 12), 0xF7]) # s "midi"
`
thanks!

**Comment by yaxu** [comment]
Howabout this?
`let cents amount = array ((\x -> map fromIntegral [240,71,95,0,105,2,0,0,4,48,0,0,x,247]) <$> amount)`

**Comment by yaxu** [comment]
Btw you can also specify in hex
`let cents amount = array ((\x -> map fromIntegral [0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, 0x00, 0x00, 0x04, 0x30, 0x00, 0x00, x, 0xF7]) <$> amount)`
The fromIntegral is just there to convert between int and the 'word8' type that the osc library uses in blobs

**Comment by tadklimp** [comment]
Thank you, this works with most of the patterns i tried!

I'm having some issues, though i believe they have to do with my lack of Haskell knowledge:
```
-- this works
d1 $ cents "1 2 5 12" # s "midi"

-- this works too
d1 $ cents (segment 8 $ irand 8 ) # s "midi"

-- this not
d1 $ cents ( segment 8 $ range 1 15 $ sine ) # s "midi"

```
The error for the last example is `Ambiguous type variable ‘a0’ arising from a use of ‘sine’
      prevents the constraint ‘(Fractional a0)’ from being solved`

I'd also like to ask: what would be the correct syntax for having 2 arguments on the custom function you suggested?

e.g. if in the Sysex message we'd like to modulate 2 parameters, as in:
```
[0xF0, 0x47, 0x5F, 0x00, 0x69, 0x02, channel, 0x00, 0x04, 0x30, 0x00, 0x00, amount, 0xF7]
```
This has been a fantastic week!
Sysex automation opens up so many possibilities for live-coding older gear!

Thank you!

**Comment by yaxu** [comment]
Sorry missed your questions
You can fix the last one with: `d1 $ cents ( floor <$> (segment 8 $ range 1 15 $ sine)) # s "midi"`
The `floor <$>` turns a pattern of floats into a pattern of integers (you could also do `round <$>`)

Here's a way to add a parameter:
```
import Prelude hiding ((<*),(*>))

let cents channelp amountp = array ((\channel amount -> map fromIntegral [240,71,95,0,105,2,channel,0,4,48,0,0,amount,247]) <$> channelp <* amountp)
```

**Comment by tadklimp** [comment]
Thank you @yaxu, these work great!

**Comment by yaxu** [comment]
I think this is done, but still needs documenting.
