### ISSUE TITLE
reading and writing scores

### ISSUE THREAD

**Issue by mxmxyz** [tidalcycles/Tidal#559]
a function that writes osc messages (+ times when they are sent) to a text file, that can be read at a later time by using another function

Examples:

`writeScore "~/foo.osc" $ seqP [(0,8,pattern), etc]`

`d1 $ readScore "~/foo.osc"`

If reading the score is easier on ghci, computationally speaking, than making all the necessary computations in the 'traditional way' (as would be my intuition), this could be a way to make patterns that are too complicated for ghci to compute in real time -- similarly to how "freezing" usually works in DAWs. 

the pattern from the score could also be made to go through more functions, and the process could be iterated time and time again.

(perhaps `writeScore` should take a `Rational` argument specifying how many cycles should be written down?)

**Comment by yaxu** [comment]
Closing as speculative, until someone wants to work on this.
