### ISSUE TITLE
More flexible `whenmod`

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#565]
The workings of `whenmod` are a bit hard to explain, but roughly, `whenmod a b f` apples the function `f`, `(a - b)` times out of `a`. For example, `whenmod 8 7` is roughly equivalent to `every 8` (although the function is applied out of phase by one cycle). 

It's a useful function, but the `a` and `b` parameters aren't patterns. Having to use `<~` to get the phase you want is a bit fiddly, too. A more flexible version would be great

**Comment by yaxu** [comment]
It could be based on binary patterns, where the function is applied when a value is true, isn't applied when a value is false, and events are lost where a value is missing altogether. It'd look like this:
```
while :: Pattern Bool -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
```
and could be used like this:
```
d1 $ while "t f" (hurry 2) $ n "0 .. 7" # sound "numbers"
d1 $ while "<t t t f f>" (hurry 2) $ n "0 .. 7" # sound "numbers"
d1 $ while "t(3,8)" (hurry 2) $ n "0 .. 7" # sound "numbers"
d1 $ while (every 3 inv "t(3,8,<0 3>)") (hurry 2) $ n "0 .. 7" # sound "numbers"
```
I think this would be the same as `chunk 4 (hurry 2)`:
```
while (iter 4 "t f f f") (hurry 2)
```
To access functionality similar to `whenmod`, we could add another operator for constructing binary patterns.
```
d1 $ while (3 // 5) (hurry 2) $ n "0 .. 7" # sound "numbers"
```
`3 // 5` would be the same as `t t t f f`

**Comment by yaxu** [comment]
This didn't turn out to be very difficult to implement:
```
while b f pat = sew b (f pat) pat
```
Fun!
```
d1 $ while (every 3 inv "t(3,8,<0 3>)") (hurry 2) $ n "0 .. 7" # sound "drum"
```

**Comment by bgold-cosmos** [comment]
`while` here is pretty similar to `when`, I wonder if there's a way to generalize that too.

Also, your `while` has the typical issues that arise from treating patterns like lists - overlapping or empty patterns can get weird, for example

```
tidal> while ("t ~ f"::Pattern Bool) (fast 2) ("11 12 13"::Pattern Int)
(0>⅙)|11
(⅙>⅓)|12
(⅔>1)|13
tidal> while ("t ~ ~"::Pattern Bool) (fast 2) ("11 12 13"::Pattern Int)
(0>⅙)|11
(⅙>⅓)|12
tidal> while ("[t ~ f, ~ f t]"::Pattern Bool) (fast 2) ("11 12 13"::Pattern Int)(0>⅙)|11
(⅙>⅓)|12
(⅔>⅚)|12
(⅚>1)|13
(⅓>⅔)|12
(⅔>1)|13
tidal> 
```

Maybe that's OK?

**Comment by yaxu** [comment]
Yes I think that's nice behaviour, e.g. `while "[t,f]"` acts like `superimpose`.

**Comment by yaxu** [comment]
A good thought about `when`, I was wondering about renaming the existing `when` to `while`, and calling this function `when`. The names would work better that way around, I think.

**Comment by yaxu** [comment]
Well I suppose `when` and `while` are pretty much synonymous, so maybe best to leave `when` with the current definition and keep the new one as `while`.

**Comment by yaxu** [comment]
Fun using this for emphasis patterns:
`d1 $ while ("t(3,8,<0 2 3>)") (# (gain 1.4 # speed 1.2)) $ n "0*8" # sound "gretsch"`

**Comment by yaxu** [comment]
Fixed via https://github.com/tidalcycles/Tidal/commit/5c55e9268728cb8eda6e9a49fcb37632c0650253
