### ISSUE TITLE
seeing "skip" messages, Tidal stops playback

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#567]
**Describe the bug**
Sometimes Tidal produces "Skip" messages in the ghci output. Correlated: when this happens, Tidal can't really keep up and seems to have trouble correctly sequencing events until it is restarted. 

**To Reproduce**
I was doing something like this:

```
let times = "<3 5 7 10>"
let denom = ("4" * (discretise 1 $ range 0.5 1 $ rand) * (range 0.5 1 $ slow 3 sine))

d1 $ plyWith times (# gain 0.8) $ slow (times/denom) $ fast 4 $ s "bd"
```

Which produced in the output:

```
tidal> skip: 9
skip: 8
skip: 36
```
Tidal kind of "stopped" playing for a bit, then kind of caught up, but then even after modifying the pattern to be much simpler (e.g. `s "bd"`) the timing/sequencing was very erratic.

**Environment**
 - OS: MacOS
 - Tidal version: 1.4.4

**Comment by yaxu** [comment]
Strange that the timing goes permanently awry after a skip, I haven't seen that behaviour. Do you get late messages in supercollider as well, when that happens?

**Comment by kindohm** [comment]
I don't recall if I see late messages in SC or not. When I get a chance I will try to cause the issue and provide more info here.

**Comment by kindohm** [comment]
Just caused the issue now:

Tidal code:
```
  d1
    $ fast (smooth "<1 1.2 0.8 2 1.5 3>") 
    $ s "bass*16" 
    # n 1 # gain 1.2 # cut 1 # cps 1
```

GHCI output:
```
tidal> tidal> tidal> tidal> Warning: GHCi | skip: 15
Warning: GHCi | skip: 22
Warning: GHCi | skip: 88
tidal> Warning: GHCi | skip: 209
tidal> 
```

Lots of late messages in SuperDirt:

```
late 0.183419958
late 0.651652582
late 1.724338114
late 4.974297644
late 5.009923078
late 5.033939331
late 5.069567054
late 5.093585585
late 5.129235541
late 5.153226388
```

Tidal code no longer evaluates in my editor. GHCI output has stopped. Sometimes sound comes out at unpredictable times.

Rebooting SuperCollider alone does not resolve the issue. I need to restart my editor in order to resume coding.

If I restart my editor and eval the same code, I immediately get `skip` messages.

I had to slow `cps` down to `0.1` for the `skip` messages to stop appearing.

Granted, my pattern is producing a lot of events, and I would expect the `late` messages. But I'm surprised the `skip` messages happen for low values of `cps`. The fastest that that above pattern would go is `fast 3 $ s "bass*16"`, and that sounds just fine (at `cps 1`) when not interpolating `fast` with `smooth`. 

I can see how `smooth` might cause Tidal to grind hard when doing the interpolation calculation. I'm probably pushing it too hard, but this is a perfect example of seeing `skip`.

**Comment by yaxu** [comment]
Ok I can reproduce this strange behaviour. 

I run the pattern, then stop it.

Then I run `d1 $ sound "cp"`, and the claps come at uneven intervals, with ghc pegged at 100% cpu. 

I stop it and the cpu drops to normal. Very strange !

**Comment by yaxu** [comment]
This is fine:
```
d1 $ fast (slow 8 $ saw + 1) 
   $ s "bass*16"
```
This isn't:
```
d1 $ fast (slow 8 $ saw + 1) 
   $ s "bass*16"
   # cps 1
```
This is fine:
```
d1 $ fast (segment 8 $ slow 8 $ saw + 1) 
   $ s "bass*16"
   # cps 1
```
So it seems to be a weird problem around continuous changes to `fast` and the handling of `cps`

**Comment by yaxu** [comment]
These examples work fine for me now..
