### ISSUE TITLE
tidal-midi won't install on mac

### ISSUE THREAD

**Issue by amillionspiders** [tidalcycles/Tidal#57]
Fails while trying to install alsa-core-0.5.0.1, which I've read elsewhere is Linux only. Any possible workarounds?

>Resolving dependencies...
Configuring alsa-core-0.5.0.1...
Failed to install alsa-core-0.5.0.1
Last 10 lines of the build log ( /Users/athousandsharks/.cabal/logs/alsa-core-0.5.0.1.log ):
Configuring alsa-core-0.5.0.1...
setup-Cabal-1.18.1.4-x86_64-osx-ghc-7.8.3: The program pkg-config version
 >=0.9.0 is required but it could not be found.
cabal: Error: some packages failed to install:
alsa-core-0.5.0.1 failed during the configure step. The exception was:
ExitFailure 1
alsa-seq-0.6.0.5 depends on alsa-core-0.5.0.1 which failed to install.
tidal-midi-0.0.1 depends on alsa-core-0.5.0.1 which failed to install.

**Comment by yaxu** [comment]
Yes you need to use @lennart's development version for mac support and other stuff. Hopefully it'll get merged back soon.

Info here for how to install it:
  http://lurk.org/groups/tidal/messages/post/3wKQ9gaJ4QldxCoDOkSbWv

**Comment by lennart** [comment]
@yaxu it seems we should be merging my branch into master some time soon, requests for mac/windows support start to come up more often.

Are there any blockers left to fix?

**Comment by yaxu** [comment]
No blockers I do't think, just edge cases, which are better than being single platform. I'd be surprised if anyone is using the current main branch, anyway.

**Comment by yaxu** [comment]
There is my PR though https://github.com/lennart/tidal-midi/pull/4

**Comment by yaxu** [comment]
Ah you've merged it, thanks!

**Comment by yaxu** [comment]
One other thing @lennart, how about renaming 'keyproxy' to 'midiproxy'? The former is a reference to volca keys.

**Comment by lennart** [comment]
yes, I'd love to do that. I guess we should not rush it and use the time to ask on the lurk list for any suggestions for refactorings (naming things) before we merge to master and update the cabal package.

Actually one could eventually merge the documentation from tidal-midi's README into the main docs on tidal.lurk.org

I guess I'll start with renaming `keyproxy` to `midiproxy`!

**Comment by kindohm** [comment]
One thing I noticed is that the Volca Bass "cutoff" parameter conflicts
with Tidal's. I was going to change it to "kcutoff" to match the Volca
Keys. No strong feelings about it being corrected before merging to master
though.
