### ISSUE TITLE
Tidal crashes with invalid mini notation code

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#575]
I crashed Tidal with the following (invalid) pattern and had to restart my host editor:

```
ccv (slow 4 $ "<0 1 2+>")
```

Error:

```
Failed to send. Is the 'SuperDirt' target running? Syntax error in sequence:
  "<0 1 2+>"
          ^  
unexpected ">"
expecting number
```

**Comment by yaxu** [comment]
I can't reproduce this, `d1 $ sound "bd" # ccv (slow 4 $ "<0 1 2+>")` fails immediately and doesn't crash the scheduler. Which tidal version are you on?

**Comment by kindohm** [comment]
I can't seem to reproduce it any more either!
