### ISSUE TITLE
scales only support integers

### ISSUE THREAD

**Issue by quakehead** [tidalcycles/Tidal#579]
I'd like to be able to create Arabic scales ([maqams](http://maqamworld.com/en/maqam.php)) many of which use quartertone notes.

The scales here use the typeclass Num, which make it seem like I could use a fraction, but it's Haskell error.
https://github.com/tidalcycles/Tidal/blob/master/src/Sound/Tidal/Scales.hs

When I try to add
```
bayati :: Num a => [a]
bayati = [0,0.5,4,6,8,8.5,12]
```
I get this error.
```
   • Could not deduce (Fractional a) arising from the literal ‘0.5’
      from the context: Num a
        bound by the type signature for:
                   bayati :: forall a. Num a => [a]
        at :5890:1-22
      Possible fix:
        add (Fractional a) to the context of
          the type signature for:
            bayati :: forall a. Num a => [a]
    • In the expression: 0.5
      In the expression: [0, 0.5, 4, 6, ....]
      In an equation for ‘bayati’: bayati = [0, 0.5, 4, ....]
```

@yaxu mentioned on the chat that it could be a simple case of a type change. For example, this is valid Haskell:
```
bayati :: Fractional a => [a]
bayati = [0,0.5,4,6,8,8.5,12]
```

**Environment (please complete the following information):**
 - Haskell version: The Glorious Glasgow Haskell Compilation System, version 8.6.5
 - Tidal version 1.4.4

**Additional context**
 http://maqamworld.com/en/maqam/bayati.php

**Comment by quakehead** [comment]
I changed the typeclass of scales to Fractional and it compiled.

Though the frequencies that actually gets sent to SuperCollider (or SuperDirt) are off - looks like the quarternotes are rounded. I used SuperCollider IDE's Server OSC dump to see the frequencies.

I used this to play notes in a scale
`d1 $ (scale "bayati" "0..10") # s "superpiano" # sustain "1"`


Bayati [0,0.5,4,6,8,8.5,10]

261.626 0
261.626 0.5
329.628 4
369.994 6
415.305 8
261.626 8.5
466.164 10
523.251 12 Octave
523.251 12.5
659.255 16


The pattern seems ok:
```
(scale "bayati" "0..8") :: Pattern Double
t>(0>⅑)|0.0
(⅑>²₉)|0.5
(²₉>⅓)|4.0
(⅓>⁴₉)|6.0
(⁴₉>⁵₉)|8.0
(⁵₉>⅔)|8.5
(⅔>⁷₉)|10.0
(⁷₉>⁸₉)|12.0
(⁸₉>1)|12.5
```

Looks like somewhere before it gets converted to a frequency, it gets rounded

**Comment by yaxu** [comment]
@quakehead Try with a different synthesiser. I think superpiano acts like a piano in that you can't do anything between notes :)

**Comment by quakehead** [comment]
I tried superhex and supergong. same thing. I identified where it's rounding:

`(scale "bayati" "0..10") # s "supergong" # sustain "1"`

```
(0> 1/11)|n: 0, s: "supergong", sustain: 1.0f
( 1/11> 2/11)|n: 0, s: "supergong", speed: 0.5f, sustain: 1.0f
( 2/11> 3/11)|n: 4, s: "supergong", sustain: 1.0f
( 3/11> 4/11)|n: 6, s: "supergong", sustain: 1.0f
( 4/11> 5/11)|n: 8, s: "supergong", sustain: 1.0f
( 5/11> 6/11)|n: 0, s: "supergong", speed: 8.5f, sustain: 1.0f
( 6/11> 7/11)|n: 10, s: "supergong", sustain: 1.0f
( 7/11> 8/11)|n: 12, s: "supergong", sustain: 1.0f
( 8/11> 9/11)|n: 12, s: "supergong", speed: 0.5f, sustain: 1.0f
( 9/11> 10/11)|n: 16, s: "supergong", sustain: 1.0f
( 10/11>1)|n: 18, s: "supergong", sustain: 1.0f
```

**Comment by quakehead** [comment]
My bad...I found something that works!
I added `note`:

d1 $ note (scale "bayati" "0..10") # s "superpiano"

this produces all the correct frequencies

I realized this was producing an expected result. E.g.
`note "0 1 1.5 2 3" # sound "superpiano"`
```
(0>⅕)|note: 0.0f, s: "superpiano"
(⅕>⅖)|note: 1.0f, s: "superpiano"
(⅖>⅗)|note: 1.5f, s: "superpiano"
(⅗>⅘)|note: 2.0f, s: "superpiano"
(⅘>1)|note: 3.0f, s: "superpiano"
```

**Comment by yaxu** [comment]
Is this still an issue? Would be good to get these extra scales in Scales.hs

**Comment by quakehead** [comment]
Yeah, I'll make a PR with the new scales and the type change (from Num to Fractional)

I saw that supercollider also has these scales:
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Collections/Scale.sc
SuperCollider is also more general - it parametrizes the number of notes in a scale, so a scale is always entered in terms of degree and no fractions are in it.

For now it's simpler to write the scales in terms of the 12-notes, like `[0, 1.5, 3, 5, 7, 8, 10]`.
In terms of 24 notes it would be `[0, 3, 6, 10, 14, 16, 20]`

Maybe save that for another change?
