### ISSUE TITLE
Ply with parallel patterns

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#591]
From [derekxkwan in the forum](https://forum.toplap.org/t/ply-with-parallel-patterns/987):

I’m a bit perplexed with how ply works with parallel patterns (Tidal 1.4.5).

For example, `ply 2 $ s [bd, cp]` results in `bd cp bd cp`, offsetting cp 0.25 of a cycle, while something like `ply 2 $ s [bd*2, cp]` gives something like `[bd*4, cp*2]` where cp doesn’t get offset. Is this expected behavior and if so, how could I use a function to get from `[bd,cp] to [bd*2, cp*2]`? Thanks!

**Comment by gadfly16** [comment]
Hey!

I came up with the following solution:

```
let ply' :: Pattern Int -> Pattern a -> Pattern a
    ply' = tParam _ply'
    _ply' :: Int -> Pattern a -> Pattern a
    _ply' n p = stack [withResultArc (offshort n i) $ withQueryArc (offshort_inv n i) p | i <- [0..(n-1)]]
      where
        offshort n i (Arc s e) = Arc s' e'
          where
            d' = (e - s) / fromIntegral n
            s' = s + d' * fromIntegral i
            e' = s' + d'
        offshort_inv n i (Arc s e) = Arc s' e'
          where
            d' = (e - s) * fromIntegral n
            s' = s - (e - s) * fromIntegral i
            e' = s' + d'
```

It seems to work fine, but I don't know why I have to apply an invert transformation on `withQueryArc` first. Without that the output seems fine, but the new notes aren't always playing. I'm new to both Tidal and Haskell, so I would really appreciate some insight.

Thanks for this awesome musical tool, that finally gave me reason to start to learn this awesomw language!

**Comment by yaxu** [comment]
Thanks @gadfly16, and sorry for being slow.. This looks like that fixed it!

So you mean you're not sure why you can't just do this?
```
let ply' :: Pattern Int -> Pattern a -> Pattern a
    ply' = tParam _ply'
    _ply' :: Int -> Pattern a -> Pattern a
    _ply' n p = stack [withResultArc (offshort n i) $ p | i <- [0..(n-1)]]
      where
        offshort n i (Arc s e) = Arc s' e'
          where
            d' = (e - s) / fromIntegral n
            s' = s + d' * fromIntegral i
            e' = s' + d'
```
I'm not sure either. Can you share an example of something that fails without the use of `offshort_inv`?

**Comment by gadfly16** [comment]
Hey @yaxu ! No worries, as you can see I'm even slower.

That's exactly what I mean. That was my first version letter by letter, and what happens if I use this version is the following:

`ply' 2 $ s "bd ~ sd ~"` gives the expected result:

```
(0>⅛)|s: "bd"
(⅛>¼)|s: "bd"
(½>⅝)|s: "sd"
(⅝>¾)|s: "sd"
```

But when I **play** it like `d1 $ ply' 2 $ s "bd ~ sd ~"` some 'plyed' notes are not played (or aren't audible at least) in a seemingly random manner. I got the idea of the 'invert transform-transform' trick from the source, as can be seen in `zoomArc` for example.

I hope this helps!

PS.: My instinct says that it might be related to how Tidal handles operation between patterns with different length, but maybe that's just stupid.

**Comment by yaxu** [comment]
Ok I had a closer look. It's to do with how tidal works. You query a pattern with a timespan (aka arc), and it returns the events taking place during that timespan. If you then just manipulate the time of the events you get back, you might end up with events outside the timespan that was queried. More noticeably, you will miss events that aren't in the timespan you queried, but should cause one to be in the timespan you queried.

So my version misses events, but unfortunately yours isn't right either - you can hear it's doubling events up. Expanding the query doesn't really make sense, so you end up with duplicated events.

I had a go at working out the logic for this and it was getting really tricky. You have to deal with fragments of events (e.g. if you get an event that is only partly in the timespan you ask for), so you have to work out what fragments of the ply'd events you end up with..

In the end I gave up and tried a more declarative approach:
```
ply :: Pattern Time -> Pattern a -> Pattern a
ply = tParam _ply
 where _ply n pat = squeezeJoin $ (_fast n . pure) <$> pat
```
This takes each value in a pattern, turns of those values into a pattern with one event per cycle, and speeds it up by the ply'd factor, so you end up with a pattern of patterns. You join them back into a 'flat' pattern with squeezeJoin, which takes a cycle of the inner pattern to fit the timespan of the original outer event... and it seems to work!
