### ISSUE TITLE
Repeating a sequence

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#597]
`"[a b]!3 d"` is the same as `"[a b] [a b] [a b] d"`.

`"a b a b a b d"` is harder to express. `"[a b]*3@3 d"` will do it but is a bit fiddly.

What would be a better way of doing a such a 'top level' repeat?

**Comment by yaxu** [comment]
`"(a b)!3 d"` - could be ok, but overloads use of parens in euclidean syntax.. so woudl be confusing.

**Comment by bgold-cosmos** [comment]
Maybe just a different symbol?  Something related like `!!` or maybe to indicate "top level" `^!`  (ease of typing is an issue...)

**Comment by ndr-brt** [comment]
if I evaluate `"[a b]*3@3 d"` I get
```
(0>⅛)|s: "a"
(¼>⅜)|s: "a"
(½>⅝)|s: "a"
(⅛>¼)|s: "b"
(⅜>½)|s: "b"
(⅝>¾)|s: "b"
(¾>1)|s: "d"
```
not `"a b a b a b d"`

btw, I like the `!!` idea.

**Comment by yaxu** [comment]
@ndr-brt if you look at the event times, that is right, they're just not printed in the right order.

I like the !! idea too but I think that currently means the same as !2, which is also nice..

**Comment by telephon** [comment]
is there a way to embed arbitrary haskell/tidal function names into the pattern language? Then maybe something like `"a b (roll 3) d"`  would be a way to write it clearly without adding more load to the pattern language?

**Comment by yaxu** [comment]
@telephon not currently..

These days you can specify half-steps to solve this problem.
```
"[a b]!3 d@0.5"
```
I think that's a simpler solution, rather than adding new syntax, so will close this for now.
