### ISSUE TITLE
resetCycles will glitch the sound if EspGrid is being used

### ISSUE THREAD

**Issue by gilfuser** [tidalcycles/Tidal#603]
Using EspGrid and evaluating `resetCycles` is causing a long glitch in the sound. Similar to the one that happens if one is already playing a pattern and starts espgrid `espgrid tidal`

**To Reproduce**

0. You need to have [Esp](https://dktr0.github.io/EspGrid/) installed.

1. Start EspGrid in the terminal: `espgridd` 

2. Go to SuperCollider and start EspClock:

```supercollider
    Esp.person = Esp.person ? "skmecs";
	1.wait;
	TempoClock.default = EspClock.new;
    0.2.wait;
	t = TempoClock.default;
    0.2.wait;
	t.start;
	t.tempo = 110/60/4;
    q.tempo =  q.tempo ?? Bus.control(s, 1).set(t.tempo);
	Esp.clockAdjust = -0.1; // slide synced tempo/metre backward/forward in time
```

2. Start SuperDirt as you normally do.

3. start Tidal in your favorite IDE and evaluate this, one line at a time:

```haskell
espgrid tidal

cpsEsp (110/60/4)

p 1 $ " bd"

resetCycles

```
4. You will listen the glitch. I suspect that the longer you ran tidal, the longer the glitch.
SzperCollider will post lots of "late" messages with pretty big numbers. Here goes a sample of it:

```
...
late 359.197901554
late 357.016082628
late 354.834267584
late 352.652451039
late 350.470634062
late 348.288822104
late 346.106997303
late 343.925183611
late 341.743362373
late 339.561544945
late 337.379723501
late 335.197901902
late 333.016083372
late 330.834266380
late 328.652449839
late 326.470631856
late 324.288811268
late 322.106992417
...
```

ghc-pkg list tidal
**Expected behavior**
Resetting cycles and using Esp Grid without glitching the sound

**Environment (please complete the following information):**
 - OS: linux ubuntu
 - Haskell version would that be the ghc version? If so: 8.6.5
 - Tidal version 1.4.4 (that's weird. I thought I was using 1.4.7. I checked it with `ghc-pkg list tidal`)
 - SuperCollider version: 3.10.3

**Additional context**
I'm not sure if I should have reported this issue in the Esp side of it. Bus as the bug was manifested in Tidal I decided to start by the synthom.

**Greetings**

Thank you.

best regards,
Gil

**Comment by dktr0** [comment]
EspGrid has a model of tempo that only goes forward (as, basically, does SuperCollider's tempo classes), so although I haven't looked at resetCycles closely, I suspect it contradicts that model (and SuperCollider's).

**Comment by gilfuser** [comment]
Hi @dktr0, thank you for your answer.

I see. So there's no way around it.
I will try to find in the forum an alternative to achieve what I wanted with `resetCycles` (start a seqPLoop from the beginning).
