### ISSUE TITLE
incorrect major 13 chord

### ISSUE THREAD

**Issue by ovitus** [tidalcycles/Tidal#605]
I found a chord that is incorrect:

thirteen :: Num a => [a]
thirteen = [0,4,7,10,14,17,21]

going by the "3 + 4 semitone" rule of thumb, I think this should be:

thirteen :: Num a => [a]
thirteen = [0,4,7,11,14,17,21]

**Comment by bgold-cosmos** [comment]
I don't really understand everything there, but https://en.wikipedia.org/wiki/Thirteenth seems to indicate that the seventh is most often flattened:

> In modern pop/jazz harmony, after the dominant thirteenth, a thirteenth chord (usually notated
> as X13, e.g. C13) contains an implied flatted seventh interval. Thus, a C13 consists of C, E, G,
>B♭, and A.

**Comment by ovitus** [comment]
ah ok, I'm learning. thanks
