### ISSUE TITLE
textual output of patterns: don't print source loc, sort by time

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#608]
For understanding semantics of operations on patterns, I like to view their events in ghci, as in
```
stack exec --resolver=lts  -- ghci -isrc Sound.Tidal.Context
...
*Sound.Tidal.Context> :set -XOverloadedStrings 
*Sound.Tidal.Context> "[0 <1 2>]*2" :: Pattern Int
[((2,1),(4,1)),((11,1),(12,1))](0>¼)|0
[((2,1),(4,1)),((11,1),(12,1))](½>¾)|0
[((5,1),(7,1)),((11,1),(12,1))](¼>½)|1
```
What is the best way to get this output
* sorted (by start time) (in the above, 1/4 comes after 1/2)
* shortened (omit source spans)?
I am not asking for the Show instance to be changed - just whether there's some other function that does it.

When I want to look at a longer interval, I am doing
```
*Sound.Tidal.Context> mapM_ print $ queryArc ("[0 <1 2>]*2" :: Pattern Int) (Arc 0 2)
[((2,1),(4,1)),((11,1),(12,1))](0>¼)|0
[((2,1),(4,1)),((11,1),(12,1))](½>¾)|0
...
```
again, this could be shorter. 

If there's no such function, I can hack it like
```
import Data.List (sortOn)
newtype S a = S (Pattern a)
instance Show a => Show (S a) where 
  show (S p) = unlines $ map (\e -> show(part e, value e)) $ sortOn part $ queryArc p (Arc 0 1)

:set -XTypeApplications 

S @Int "[0 <1 2>]*2"  

(0>¼,0)
(¼>½,1)
(½>¾,0)
(¾>1,2)
```

**Comment by yaxu** [comment]
There is currently only `show` for this, apart from `deconstruct` for which 'visualises' a pattern of strings  by sampling it at a fixed rate.

This all looks sensible. I'm in two minds about changing the current `show` to omit information, but I think sorting would be helpful for that, too.
