### ISSUE TITLE
Sync with Jack Transport

### ISSUE THREAD

**Issue by muziker** [tidalcycles/Tidal#609]
**Is your feature request related to a problem? Please describe.**
In one of my workflows, tidalcycles is used to generate drum patterns. Right now, tidalcycles is the main orchestrator as an interface to synths, etc, through midi. 

**Describe the function/feature you'd like**
If i can let a DAW be the main center to control all other instruments, it would be easier to generate music. So tidalcycles needs to understand Jack transport, or midi clock input. Also a standardised way to select d1-d12/mutes using midi would really help as well.

**Comment by yaxu** [comment]
This would be good. I don't see Haskell bindings for jack transport though, it doesn't seem to be part of this package http://hackage.haskell.org/package/jack

**Comment by yaxu** [comment]
With the native link support in tidal 1.9.x, this should now be possible via jack_link https://github.com/rncbc/jack_link
