### ISSUE TITLE
xfade jumps to 1 before fading

### ISSUE THREAD

**Issue by Djoust** [tidalcycles/Tidal#61]
there is an other little problem with xfade.
if you xfade between the old and the new pattern all the gains of the old will
jump to 1 and than fade to 0.

so if you have something like this

d1 $ stack [
sound "bd*4",
sound "{~ ho}*4" |+| gain "0.8"
]

and than

t1 xfade $ stack [
sound "bd*4",
sound "{~ ho*2}*4" |+| gain "0.8"
]

the gain of the old ho pattern jump to 1 and the gains of new ho pattern fade
and at 1.

is it possible to multiply the current gain by the env from xfade, so that the
old goes from 0.8 to 0 and the new goes from 0 to 0.8?

i'm talking about this xfade:
https://github.com/tidalcycles/Tidal/blob/master/Sound/Tidal/Dirt.hs#L191

and this env:
https://github.com/tidalcycles/Tidal/blob/master/Sound/Tidal/Pattern.hs#L369

**Comment by yaxu** [comment]
I think this is now solved in 0.6-dev branch:
  https://github.com/tidalcycles/Tidal/tree/0.6-dev/

**Comment by Djoust** [comment]
Nice, did you test it? other wise i will give it a go this weekend
