### ISSUE TITLE
Be more clever when parsing ratios / note names / exponential numbers

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#610]
E.g. for mini-notation of patterns of doubles the parser could guess:
* `e` - note e in the middle octave
* `e3` - note e in the third octave
* `1e` - one eighth
* `3e` - three eighths
* `3e3` - 3000

**Comment by khoparzi** [comment]
Currently errors out with 
`rotL "3e" $ s "bd"`

**Comment by fdragovic** [comment]
just thinking isn't it a bit more consistent for 3e3 to be 3 eights middle
e?

**Comment by ndr-brt** [comment]
as implemented in #702 `e` for doubles is always 1/8, and for "notes" is "4", so the only case not yes understood by the parser is the last `3e3`
