### ISSUE TITLE
tidal.el on Linux expects Tidal to be installed through Cabal

### ISSUE THREAD

**Issue by pashultz** [tidalcycles/Tidal#615]
Arch Linux has [a package for TidalCycles](https://www.archlinux.org/packages/community/x86_64/tidalcycles/), which installs BootTidal.hs under /usr/share/x86_64-linux-ghc-8.8.3/tidal-1.4.8/ (version numbers and architectures may change, of course). Unfortunately the code in tidal.el has a path hardcoded under ~/.cabal/store/, as of 
https://github.com/xmacex/Tidal/commit/59fe608d77cfe9ea33504e8f6a0c9b35706c63e6 (Note that the message on that commit anticipates this problem: "what if libraries are not under user's home directory?") This means tidal.el can't find Tidal when it's installed systemwide.

**To Reproduce**
Steps to reproduce the behavior are mostly the same as in https://github.com/tidalcycles/Tidal/issues/583:
1. Install `emacs` and `tidalcycles` through the Arch Linux package system, along with SuperDirt and any other requirements.
2. Open a .tidal file (C-x C-f my-humps.tidal), and verify that tidal-mode is active.
3. Run the `tidal-start-haskell` command with C-c C-s

**Expected behavior**
There should be a `tidal>` prompt in the Comint buffer, but it fails with "file not found" messages. 

Here's the offending passage:
```
'(("path" . "ghc-pkg field -f ~/.cabal/store/ghc-$(ghc --numeric-version)/package.db tidal data-dir")
             ("separator" . "/")
```
If I delete the hardcoded path (removing the -f option), it loads just fine:
```
'(("path" . "ghc-pkg field tidal data-dir")
             ("separator" . "/")
```
I assume the -f option was added because ghc-pkg [doesn't otherwise know](https://gitlab.haskell.org/ghc/ghc/issues/17341) about the user's .cabal. Is there a fallback mechanism that would let it check .cabal first, then fall back to the systemwide database if that fails?

**Environment:**
 - OS: Arch Linux, x86_64
 - Haskell version: 8.8.3
 - Tidal version: 1.4.8-13 (as packaged [here](https://www.archlinux.org/packages/community/x86_64/tidalcycles/))
 - SuperCollider version: 3.11.0-beta1

Thanks in advance for your help!

**Comment by pashultz** [comment]
Oh, actually instead of (or in addition to) a list of fallback locations, what about just defining the variable with [defcustom](https://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html)? Note the :type and :group options at the end; [others](https://www.gnu.org/software/emacs/manual/html_node/elisp/Customization.html#Customization) may be useful too.

```
(defcustom tidal-boot-script-path
  (let ((filepath
         (cond
          ((string-equal system-type "windows-nt")
           '(("path" . "echo off && for /f %a in ('ghc-pkg latest tidal') do (for /f \"tokens=2\" %i in ('ghc-pkg describe %a ^| findstr data-dir') do (echo %i))")
             ("separator" . "\\")
             ))
          ((or (string-equal system-type "darwin") (string-equal system-type "gnu/linux"))
           '(("path" . "ghc-pkg field tidal data-dir")
             ("separator" . "/")
             ))
          )
         ))
    (concat
     (string-trim (cadr (split-string
                         (shell-command-to-string (cdr (assoc "path" filepath))) ":")))
     (cdr (assoc "separator" filepath))
     "BootTidal.hs")
    )
  "*Full path to BootTidal.hs (inferred by introspecting ghc-pkg package db)."
  :type 'file
  :group 'tidal
  )
```
Thanks to @yaxu for the suggestion in https://github.com/tidalcycles/Tidal/issues/583#issuecomment-562895862 I'm also new to Elisp (and Tidal and Haskell for that matter), so I hope this isn't counterproductive.

**Comment by vrx** [comment]
thanks, i was struggling with the same problem and i can confirm

("path" . "ghc-pkg field tidal data-dir")

works well and simple

as with ghc8.0.2 and cabal-install 1.24.2,  tidal is installed in : 
~/.cabal/share/x86_64-linux-ghc-8.0.2/tidal-1.4.8/

**Comment by yaxu** [comment]
I know very little about elisp, but happy to take PRs!

**Comment by jamagin** [comment]
I ran into this with a cabal-installed Tidal on Ubuntu 18.04 as well.  The suggested change worked for me, so here's a PR. :)

**Comment by yaxu** [comment]
Thanks @jamagin

**Comment by jwaldmann** [comment]
This strongly depends on the version of ghc/cabal being used, and the way that tidal was installed. For me,
```
$ cabal install tidal --lib
...
$ ghc-pkg field tidal data-dir
ghc-pkg: cannot find package tidal
$ ghc-pkg field -f ~/.cabal/store/ghc-$(ghc --numeric-version)/package.db tidal data-dir
data-dir: /home/waldmann/.cabal/store/ghc-8.8.3/tidal-1.5.1-456e3b8c22d3eb6a78e3b75594b6a10a00be137a20147c6a2073aa00bd801dcf/share

$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
```
As ghc-8.0.2 was mentioned - this is from 3 years ago.
