### ISSUE TITLE
audio input #in glitch at every cycle

### ISSUE THREAD

**Issue by b1tfl0w** [tidalcycles/Tidal#618]
**Describe the bug**
I'm not sure if this is a tidalcycles or superdirt issue, but when I use audio input #in I can hear a short audio clip at every cycle, something like a buffer drop, which coincides with tempo if I change cps.

**To Reproduce**
I connect my guitar to my audio card, then evaluate
d1 $ s "in"

**Expected behavior**
A clean sound without clips.

**Environment:**
 - OS: Linux Ubuntu 18.04
 - GHCi, version 8.6.4
 - tidal-1.4.8
 - SuperCollider 3.10.2

**Additional context**
I'm using Supercollider via ALSA direct portaudio becouse jack server is too glitchy, so apart from this issue the sound is clean at low latency when playing synths and samples, also I've no issues using audio input in other softwares like for example pure data.

**Comment by telephon** [comment]
Yes, that is quite possible, because the fade time in standard synths is very short (to keep the general feel crispy). You could try to write `# legato 1.1` - is that better?

**Comment by b1tfl0w** [comment]
Nope, I tried 1.1, 1.01, 1.001 and other values. Maybe the only solution could be to elaborate an algorithm which makes the audio buffer continuous..becouse something is restarting when a cycle ends and the next starts...that gap should be filled, or maybe a fade effect that smooths the end with the start..

**Comment by telephon** [comment]
Could you try `# fadeTime 0.2` ?

**Comment by b1tfl0w** [comment]
I did: 
`d1 $ s "in" # fadeTime 0.2`

I got:
```
tidal> d1 $ s "in" # fadeTime 0.2 

<interactive>:19:15: error:
    Variable not in scope: fadeTime :: Double -> Pattern ControlMap
```
Also I can't find `fadeTime` keyword in the documentation..

**Comment by telephon** [comment]
Ah sorry, I didn't know it wasn't added to the tidal side (I can't try right now). If I remember correctly, it was in tidal:
```haskell
let fadeTime = pF "fadeTime"
```
@yaxu shouldn't we add that?

you could try this.
Otherwise, in supercollider:

```supercollider
~dirt.orbits[0].set(\fadeTime, 0.1)
```

But then this is global, and all the sounds will be "softened".

**Comment by b1tfl0w** [comment]
Ok I made some test using the first option by putting `let fadeTime = pF "fadeTime"` in my Tidal.ghci in vim plugin, now it works..but it is like a fade out and still gives "digital kisses"..I did try negative values also. Better without it.

**Comment by telephon** [comment]
Ah now I understand why this is. Other synths have their own envelope for the attack section, but the input synths don't have this.

Forget about the fadeIn, just run this in sclang:

```supercollider
(
SynthDef(\in, { |out, sustain = 1, pan|
	var env, sound;
	env = Env.asr(0.002, sustain).kr; // fade out is done by external envelope
	sound = SoundIn.ar([0, 1]); // stereo in
	sound = sound * env;
	OffsetOut.ar(out,
		DirtPan.ar(sound, ~dirt.numChannels, pan)
	)
}).add
);
```

I'll correct the source as well. You can adjust the crossfade as you like in the code (now it is `0.002`).

**Comment by telephon** [comment]
Ah now I understand why this is. Other synths have their own envelope for the attack section, but the input synths don't have this.

Forget about the fadeIn, just run this in sclang:

```supercollider
// live audio input
(
SynthDef(\in, { |out, sustain = 1, pan, inputFadeTime = 0.03|
	var env, sound;
	env = Env.linen(inputFadeTime, sustain - (2 * inputFadeTime), inputFadeTime).kr;
	sound = SoundIn.ar([0, 1]); // stereo in
	sound = sound * env;
	OffsetOut.ar(out,
		DirtPan.ar(sound, ~dirt.numChannels, pan)
	)
}).add
);
```

I'll correct the source as well. You can adjust the crossfade, if you add to tidal:
`let inputFadeTime = pF "inputFadeTime"`, and then `# inputFadeTime 0.02` or so...

**Comment by yaxu** [comment]
I made an issue on the tidal repo for the missing parameter
