### ISSUE TITLE
Adding sample folders issue

### ISSUE THREAD

**Issue by chanof** [tidalcycles/Tidal#619]
Hi there by using the code belove, i get into tidal my sample instead the common tidal samples, im unable to get both: my custom samples and the original library, how con i do thanks!
Currently i  got or the original one or my folders.

```
(
s.waitForBoot {
	~dirt = SuperDirt(2, s); // two output channels
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/s1"); // specify sample folder to load
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/s2");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/s5");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/s6");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/s7");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/kit1");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/kit2");
	~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/kit4");
	
							//~dirt.loadSoundFiles("/Users/gianmaria/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples/");
	s.sync; // wait for supercollider to finish booting up
	~dirt.start(57120, [0, 0]); // start superdirt, listening on port 57120, create two orbits each sending audio to channel 0
};
)
```

i  also tried to insert the path of the original sample library but it seems to be unable to works with sub directories.. do you know what is going on?

Thanks a lot!

**Comment by yaxu** [comment]
Try without argument, `~dirt.loadSoundFiles;`

**Comment by chanof** [comment]
Hi! i just tried, but im a bit confused, do i need to includes the extra folders to get my samples working? but if i do it i loose the originals one

**Comment by telephon** [comment]
for loading all folders in a path, try this 

```supercollider
~dirt.loadSoundFiles("/Users/gianmaria/Documents/samples/*")
```

**Comment by chanof** [comment]
ok, sorry, i understand about the * to includes folders
