### ISSUE TITLE
Patterning the number of steps in an arpeggio

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/Tidal#620]
The current iteration of `arp` functionality within function `note` allows you to specify the number of arpeggiated steps in a given chord; e.g. `note (arp "updown" "c5'maj'**8**")`.

I would like to propose modifying the `arp` functionality to include a way to pattern the steps using mini notation; e.g. `( . . . "c5'maj'**<4 5 6>**")` or `(. . . "c5'maj'**[4|8|16]**")`.

Perhaps another way to approach this would be to add a third argument to `arp`; i.e. `note (arp "updown" **"<4 5 6>**" "c5'maj")`.

Thank you for considering this feature!

**Comment by Git-Christopher** [comment]
would love for this to still become a feature!

**Comment by yaxu** [comment]
With recent improvements to chord parsing, this seems to work now
