### ISSUE TITLE
Modulate "key signature"

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/Tidal#621]
an interesting feature that i think might benefit some composers would be the ability to "modulate" keys. `modulate` would be a global control function passed to all active patterns using `note` and would allow you to raise or lower your key on the fly by adding a single (integer) argument.

`d1 $ stack [
  note "<c5'maj f3'maj d5'min c5'maj>" # s "supersaw" # gain 0.7
, note "0 4 5 7" # s "superchip"
]`

the above bit of code is playing a simple melody over a simple chord progression in the key of c major. if were to introduce a new sample into my stack exactly one semitone above my code, i'd need to add 1 to all of my `note` patterns to match the key of the sample (especially if i did not want to alter the playback speed of the sample).

`d1 $ stack [
  s "my sample in the key of c # maj"
, note ("<c5'maj f3'maj d5'min c5'maj>" + 1) # s "supersaw" # gain 0.7
, note ("0 4 5 7" + 1) # s "superchip"
]`

however, if i could apply `modulate 1` to my entire stack, i could add 1 to all patterns passing values to `note` simultaneously.

`d1 $ modulate 1 $ stack [
  s "my sample in the key of c # maj"
, note "<c5'maj f3'maj d5'min c5'maj>" # s "supersaw" # gain 0.7
, note "0 4 5 7" # s "superchip"
]`

i believe this function would add a lot of flexibility to improvisation and reduce tedium when matching existing note patterns to samples or when alternating between two code blocks that were not composed in the same key.

**Comment by yaxu** [comment]
You can do this with `|+ note 1`. Closing for now
