### ISSUE TITLE
Click glitch from audio input

### ISSUE THREAD

**Issue by chanof** [tidalcycles/Tidal#622]
Hi there, may I ask help to fix an audio glitch that happen when I try to get audio back to tidal,
In my setup, I sent midi messages to hw synths and I wish get the audio of the synths back to tidal to process it with the on boards effects.
To be able to get more synths back to tidal I customize this:

```
// live audio input
(
SynthDef(\in, { |out, sustain = 1, speed = 1, begin = 0, end = 1, pan, accelerate, offset|
	var env, sound, rate, phase;
	//phase = Line.ar(begin, end, sustain);
	//rate = (begin + 1) * (speed + Sweep.kr(1, accelerate));
	sound = SoundIn.ar([begin, begin+1]); // stereo in
	OffsetOut.ar(out,
		DirtPan.ar(sound, ~dirt.numChannels, pan)
	)
}).add
);
```

"begin" variable used to selects the audio inputs.

MY ISSUE:
I can hear a glitch click with a regular frequencies, like every four beats, on all my synths,
The results should be very nice, but this glitch really hurt me, I need  to understand what is going on, can you help me about?

Thanks a lot!

Gian

**Comment by telephon** [comment]
This has been fixed in the meantime, just try and update your SuperDirt (use developer branch for now, because it hasn't been merged back into master).

**Comment by yaxu** [comment]
Please re-open if this is still an issue.
