### ISSUE TITLE
SuperDirt MIDI Tutorial not working

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/Tidal#624]
**Describe the bug**
When running:
>d1 $ n "0 2 4 7" # s "midi"

SuperCollider errors:
>no synth or sample named 'midi' could be found

**To Reproduce**
In SC:

```
MIDIClient.init;
~midiOut = MIDIOut.newByName("IAC Driver", "IAC Bus 1");
~dirt.soundLibrary.addMIDI(\midi, ~midiOut);

```
In Atom:
>d1 $ n "0 2 4 7" # s "midi"

**Expected behavior**
Hear sounds

**Environment (please complete the following information):**
 - OS: Mac 10.15.4
 - Haskell version The Glorious Glasgow Haskell Compilation System, version 8.4.2
 - Tidal version  0.9.9
 - SuperCollider-ht  0.3
 - SuperCollider version supercollider-midi 0.2.1

**Comment by kindohm** [comment]
@songproducer when you run each SC line one by one:

```
MIDIClient.init;
~midiOut = MIDIOut.newByName("IAC Driver", "IAC Bus 1");
~dirt.soundLibrary.addMIDI(\midi, ~midiOut);
```

What is the output in the SC post window?

**Comment by songproducer** [comment]
-> MIDIClient
-> a MIDIOut
-> a DirtSoundLibrary

**Comment by yaxu** [comment]
I can't reproduce this, I'm afraid.

**Comment by songproducer** [comment]
No worries I think I was trying to make it work with the iac bus but I got it working today with a hardware synth so happy to close this
