### ISSUE TITLE
someCyclesBy doesn't support patterns as first argument

### ISSUE THREAD

**Issue by PLNech** [tidalcycles/Tidal#625]
**Describe the bug**
One can use `sometimesBy` with a pattern: 
```
d1 $ sometimesBy "0.5 1" (fast 2) $ s "dr*8"
```
However, `someCyclesBy` only accepts a `Double` as first argument:
```
d1 $ sometimesBy "0.5 1" (fast 2) $ s "dr*8"
-> • No instance for (Data.String.IsString Double)
->     arising from the literal ‘"0.5 1"’
-> • In the first argument of ‘someCyclesBy’, namely ‘"0.5 1"’
```

I feel this is a mistake in the implementation of the last function, as the two base functions have the same signature (see in *Expected Behavior*).

**To Reproduce**
1. In a `.tidal` file, write `d1 $ sometimesBy "0.5 1" (fast 2) $ s "dr*8"`
2. Execute the code
3. See error

**Expected behavior**
As `sometimes` and `someCycles` share the same signature:
```
t> sometimes :: (Pattern a -> Pattern a) -> Pattern a -> Pattern a
t> someCycles :: (Pattern a -> Pattern a) -> Pattern a -> Pattern a
```

I would expect the `By` variants to also have the same one:
```
t> sometimesBy
  :: Pattern Double
     -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
 
-- CURRENT signature:
t> someCyclesBy
  :: Double -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a

-- Desired signature:
t> someCyclesBy
  :: Pattern Double
	  -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
```

**Comment by bgold-cosmos** [comment]
It's possible (I've submitted a PR), but be warned that stuff like
```
d1 $ someCyclesBy "[1 0]" (fast 2) $ s "bd sn"
```
doesn't do the "same" thing all cycle like you might expect.  In this case, it sounds like "[[bd sn] sn]"

**Comment by yaxu** [comment]
Thanks @bgold-cosmos !
