### ISSUE TITLE
someCyclesBy causes "slow" function to be ignored

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#632]
The following code results in the `cp` being played every cycle, when it should only be played every 8 cycles:

```
d1 
  $ someCyclesBy 0 id
  $ stack [  
    slow 8 $ s "cp"
  , s "bd"
  ] 
```

It sounds correct once `someCyclesBy` is removed. 

Maybe this is due to the recent changes made to `someCyclesBy`. 

Tidal version: 1.4.9

**Comment by bgold-cosmos** [comment]
Yes, it's due to patternizing that first argument - it's taking the structure from the `someCyclesBy` argument instead of the other pattern.

**Comment by bgold-cosmos** [comment]
OK, I think #644 solves this, if it works we can close.

**Comment by yaxu** [comment]
Thanks!
