### ISSUE TITLE
Recording & Routing Multichannel Audio in Windows

### ISSUE THREAD

**Issue by tugrulsalci** [tidalcycles/Tidal#634]
I couldn't make it to route audio to Ableton in Windows, so I decided to record as separate audio channels in Supercollider. I’ve changed Superdirt startup file for 6 stereo channel output, 12 in total; but when I play in tidalcycles after first three channels (after d3 or orbit 2), I am not getting any sound. Is there anyone who also facing this issue?

**Comment by telephon** [comment]
could you please post your startup, then we can see if it is a simple configuration problem?

**Comment by tugrulsalci** [comment]
Actually I figured it out with _s.meter_ that Supercollider gets the multichannel audio as it is defined. But the most channel **default audio device** gives to Supercollider is 6 channels (so 3 stereo). I've changed the audio device the most I could have was 8 channels. I think Windows has some kind of limitations...

**Comment by telephon** [comment]
hm, ok. Maybe you could ask on the sc-users mailing list if there are similar experiences, I'm sure there is some solution.
