### ISSUE TITLE
Understanding nix

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#637]
I'm getting increasingly frustrated with helping people around cabal, and wondering if nix could help with a more accessible way to install Tidal.. But I'm finding it a bit hard to understand. Following the documentation, it seems that this should find tidal:
```
nix-env -qa tidal
```
It doesn't, but this works nonetheless:
```
nix-env -iA nixpkgs.haskellPackages.tidal_1_4_9
```
That has also installed ghc. I can't directly use `ghci` until I run this command
```
nix-env -i ghc
```
But perhaps that was a bad idea? I think I could have instead done
```
nix-shell --packages ghc --run ghci
```
However, tidal isn't available in there. Furthermore, this doesn't work: 
```
nix-shell --packages ghc nixpkgs.haskellPackages.tidal_1_4_9 --run ghci
```
This runs:
```
nix-shell --packages ghc haskellPackages.tidal_1_4_9 --run ghci
```
... but the library still isn't available in that ghci. So far my searching around isn't turning up a solution to this problem that works..

**Comment by yaxu** [comment]
Aha, this is working:
```
nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.tidal])" --run ghci
```

**Comment by yaxu** [comment]
So how does this help us?
* It seems that it is reliable (and unlike cabal, it's UI isn't in a state of flux).
* Supercollider, atom, vscode, emacs, vim etc is also available
* We could make packages for superdirt and the various tidal editor plugins, and maybe something like a "tidal-system" package that depends on those and has an easy way of starting everything up

nix isn't available for windows (yet) but this could make things a lot easier for linux and mac

**Comment by juniorctl** [comment]
Nix is currently having issues on the latest version of MacOS. Might want to wait and see how https://github.com/NixOS/nix/issues/2925 is resolved.

**Comment by yaxu** [comment]
Thanks. I've found that the nix atom and supercollider versions don't really work on Linux mint. So maybe this isn't the way forward for now

**Comment by jcguu95** [comment]
I'm another failed case of using `cabal` with `tidal`. Sad.

**Comment by jwaldmann** [comment]
@jcguu95  if you provide some detail, I (or others) can try to help. I am running a cabal-installed tidal on fedora-gnu-linux (32) on x86_64.
