### ISSUE TITLE
Separate OSC shape from connection

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/Tidal#638]
Building off #557:

```
cx <- connectTarget superdirtTarget defaultConfig

streamReplace cx superdirtShape "gabbazero" $ s "gabba(3,8)" # crush 3
-- or in practice:
p = streamReplace cx superdirtShape 
d1 = p 1
d1 $ s "gabba(3,8)" # crush 3
```

**Comment by yaxu** [comment]
Motivations from #557
* OSCTarget can only use one message spec (oPath, oShape, etc), but most OSC speaking systems have a range of message specs
* This currently means multiple OSCTargets have to be created to have a complete protocol, which in turn means multiple streams are created (along with their schedulers and network connections)

**Comment by jarmitage** [comment]
You can see how I'm trying to work around these current limitations in practise here:

https://github.com/jarmitage/jarmlib/blob/master/hs/targets/Bitwig/BitwigAPI.hs

Note that I don't even try to set up transitions for each individual target:
- Having one `xfade` per target would be too much to remember
- Can't `xfade` across targets

**Comment by yaxu** [comment]
Here's the types so far
```haskell
data Stream = Stream {sConfig :: Config,
                      sInput :: MVar StateMap,
                      sOutput :: MVar ControlPattern,
                      sListenTid :: Maybe ThreadId,
                      sPMapMV :: MVar PlayMap,
                      sTempoMV :: MVar T.Tempo,
                      sGlobalFMV :: MVar (ControlPattern -> ControlPattern),
                      sCxs :: [Cx]
                     }

type PatId = String

data Cx = Cx {cxTarget :: OSCTarget,
              cxUDP :: O.UDP
             }

data OSCTarget = OSCTarget {oName :: String,
                            oAddress :: String,
                            oPort :: Int,
                            oLatency :: Double,
                            oWindow :: Maybe Arc
                           }
                 deriving Show

data OSCShape = OSCShape {oPath :: String,
                          oParams :: Maybe [(String, Maybe Value)],
                          oTimestamp :: TimeStamp,
                          oPreamble :: [O.Datum]
                         }

superdirtTarget :: OSCTarget
superdirtTarget = OSCTarget {oName = "SuperDirt",
                             oAddress = "127.0.0.1",
                             oPort = 57120,
                             oLatency = 0.02,
                             oWindow = Nothing
                            }

superdirtShape :: OSCShape
superdirtShape = OSCShape {oPath = "/play2",
                           oParams = Nothing,
                           oTimestamp = BundleStamp,
                           oPreamble = []
                          }
```
Then:
```
superdirt <- startTidal superDirtTarget defaultConfig
p = streamReplace superdirt superdirtShape 
```
It'd be great if streamReplace could turn a pattern of controls into a pattern of OSC messages, ready to be schedule. It can almost do that at the moment with the shape that's passed to it. The problem is where the timestamp goes - sometimes in the message, sometimes on the bundle.. and only the scheduler can calculate the timestamp, based on the mapping from cycle time to clock time.

So maybe streamReplace will instead make use of a function that looks something makes a pattern of functions that take a logical to physical timeline mapping, and returns the message for that  `controlToMessage :: Pattern Control -> Pattern ((Time -> Double) -> Message)` .. Then the scheduler code should end up a bit simpler.

**Comment by jarmitage** [comment]
Ok. This all looks good in terms of addressing the title of this issue now.

Could you clarify how this impacts the original goals in #557 of using a wider range of OSC paths in a single stream?

I was assuming that would still require modifying OSCShape itself further to make it more flexible. 

I can see how having it decoupled from OSCTarget is heading towards making that easier. But perhaps it’s worth thinking the UI through a bit too.

**Comment by yaxu** [comment]
The shape is then just the spec for the osc message.. If you want to just e.g. change the path you could
```
streamReplace cx (myShape {oPath = "/different/path"})
```

**Comment by yaxu** [comment]
Ah you want to pattern the path? like
```
d1 $ value "bing(3,8)" # thing "<thing1 thing2>" # _path "/my/path/{thing}/1"
```

**Comment by yaxu** [comment]
Could you share some tricky real world osc paths you want to send and manipulate?

**Comment by yaxu** [comment]
Better names:
* Shape -> OSCSpec
* startTidal -> startTarget

**Comment by jarmitage** [comment]
> The shape is then just the spec for the osc message.. If you want to just e.g. change the path you could

```haskell
streamReplace cx (myShape {oPath = "/different/path"})
```

This wouldn't improve things from a UI standpoint.

> Ah you want to pattern the path?

Yes. I already have been patterning the path (see below), but not with the level of flexibility you just suggested.

> Could you share some tricky real world OSC paths you want to send and manipulate?

I am encountering problems with simple, normal OSC paths, not tricky ones. For example there's nothing complex or unusual about this [Bitwig OSC Protocol](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Generic-Tools-Protocols/Open-Sound-Control-(OSC).md).

Yet this is my current Tidal implementation: [`BitwigAPI.hs`](https://github.com/jarmitage/jarmlib/blob/master/hs/targets/Bitwig/BitwigAPI.hs)

`oPaths` in `BitwigAPI.hs`:

```haskell
"/tempo/raw"
"/scene/{scene}/launch"
"/track/{track}/{action}"
"/track/{track}/clip/{clip}/{action}"
"/master/{action}/{value}"
"/vkb_midi/{channel}/{action}/{value}"
"/vkb_midi/{channel}/{action}/{channel}/{value}"
"/user/{channel}/value"
```

`oShapes`  in `BitwigAPI.hs`:

```haskell
Just [("raw", Just $ VF 0)],
Just [],
Just [("volume", Just $ VF 0), ("pan", Just $ VF 0)],
Just [],
Just [("volume", Just $ VF 0), ("pan", Just $ VF 0)],
Just [("value", Just $ VI 0)],
Just [("value", Just $ VI 0)],
Just [("value", Just $ VF 0)],
```

Tidal examples:

```haskell
bwT 1
  $ volume "0 100 1000 5000 10000"
  # track "1" # action "volume"

bwT 1
  $ volume "1000 5000"
  # track "1" # action "pan"

bwC 1
  $ fast "0.25 2 1 3"
  $ track (fast "<1.75 1>" $ "1 8 5 3 6 1 2")
  + clip  (fast "<0.88 1 1.2>" "2 3 1 5 4 7 8 6")
  # action "launch"

bwV 1
  $ vi "20"
  # channel "1"
  # action "note"
```

So to recap, there's two problems:

1. Currently these Shapes and Paths are all split into separate `OSCTargets`, duplicating connections & schedulers, clogging UI namespace, and preventing use of transitions.
2. Even with this workaround, the path patterning so far is still not flexible enough to cover the range of paths in the [Bitwig Virtual Keyboard](https://github.com/git-moss/DrivenByMoss-Documentation/blob/master/Generic-Tools-Protocols/Open-Sound-Control-(OSC).md#receive---play).

---

What you are suggesting with streams seems to address problem 1.

Regarding problem 2, if I understand correctly I *think* this:

```haskell
d1 $ value "bing(3,8)" # thing "<thing1 thing2>" # _path "</my/path/{thing}/1 /my/other/path/{thing}/2>"
```

Would cover what I (and I think a lot of people using OSC) am trying to do.

I was assuming you would want to add sophistication to `oPath` to achieve this. But now it seems then that (optionally) moving the path into the pattern is perhaps the simplest way to achieve this. What do you think?

**Comment by jarmitage** [comment]
One potential issue...

Each unique `_path` might require unique `oParams` (formerly `oShape`).

For example `/vkb_midi/{Channel:1-16}/note/{Note:0-127} {Velocity:0-127}` would have a different `oParams` to `/vkb_midi/{Channel:1-16}/note/+`.

**Comment by yaxu** [comment]
It'd be simplest if each pattern only addressed one osc path. Is that too much of limitation for you?

**Comment by jarmitage** [comment]
Actually maybe it would only require adding a type parameter adding to your example:

```haskell
d1 $ value "bing(3,8)" 
  # thing "<thing1 thing2>" 
  # _path "</my/path/{thing}/1 /my/other/path/{thing}/2>"
  # _type "s f" -- if it was String, Float
```

---

To answer your question:

It's much too limited for me personally, but I think it's a notable limitation of Tidal overall as a generic pattern language and explains why the majority of users do not explore it outside of SuperDirt.

Tidal is in the minority as it "uses OSC" but in practise only supports sending on one path, whereas the majority of systems that speak OSC do so using a variety of paths.

Tidal seems like it *should* control any OSC endpoint out of the box, but it doesn't. Instead you have to write custom parser middleware for every single use case, and there's no canonical examples of how to do this. Even if there was, this kind of development is out of the reach of most people who just want to send OSC messages.

If Tidal *could* address any OSC endpoint on the other hand, it would have a huge diversifying impact on who would use Tidal and what they would be used for. There's 1000s of systems out there that Tidal would instantly be able to pattern in its unique way.

**Comment by jarmitage** [comment]
I still feel like this is two separate issues `Separate OSC shape from connection` and `Pattern control of OSC paths`, so maybe we should reopen #557.

**Comment by yaxu** [comment]
I've reopened #557 but lets continue discussion here as it seems a bit interrelated.

I agree Tidal's OSC should be flexible, it's a difficult many-to-many problem though, which you don't have to deal with if you're just e.g. mapping a button or slider to a message.

That people put data in the path as well as the parameters makes it worse. 

If we don't put the path and types in the pattern, that means each pattern addresses a single path + types, and things get simple again.

If we do, then we have that many-to-many problem, and hit problems like:

```
d1 $ path "[/compression, /resonance]" # value "[50, 30]"
```
That would trigger four messages, both paths getting both values. You could do this:
```
d1 $ stack [path "/compression" # value 50, path "/resonance" # value 40]
```
But that's fiddly and you may as well put them in different patterns.

With the mapping to MIDI, it looks for the presence of data and *then* decides what MIDI to send. E.g. if there's a cc name and value, it sends a cc message. That could work here too.

```
compressionshape = OSCShape {oPath = "/compression/{instrument}",
                           oParams = Just [("compress", Nothing), ("instrument", Just $ VI 0)],
                           oTimestamp = BundleStamp,
                           oPreamble = []
                          }
resonanceshape = OSCShape {oPath = "/resonance/{instrument}",
                           oParams = Just [("resonance", Nothing), ("instrument", Just $ VI 0)],
                           oTimestamp = BundleStamp,
                           oPreamble = []
                          }
streamReplace [compressionshape,resonanceshape] "bing" $ compress 40 --  instrument defaults to 0
streamReplace [compressionshape,resonanceshape] "bing" $ compress 40 # instrument 5 -- resonance doesn't get sent if its required parameters aren't set
streamReplace [compressionshape,resonanceshape] "bing" $ compress 40 # instrument 5 # resonance 6 -- can send both in one pattern. 
```
Probably the timestamp and preamble can be moved to the target. Maybe preamble isn't really needed.

**Comment by jarmitage** [comment]
The idea of learning from how MIDI works is appealing, since that was well thought out over quite a long time period. The example you've given looks pretty good to me.

Probably not as good as what you've proposed, but these don't look too bad to me:

```
d1 $ osc "/compression" 50
```
```
d1 $ osc "/compression:50"
```
```
d1 $ osc ["/compression", "/resonance"] ["50 100 5", "30 20 40"]
```

Definitely agree re moving `timestamp` and `preamble` to `OSCTarget`. The leaner `OSCSpec` / `OSCShape` is the better.

**Comment by yaxu** [comment]
I think I will move `preamble` and `timestamp` to OSCTarget. There's no reason to remove preamble, I can see it being useful sometimes.

The current implementation already works this way - if you don't supply a required parameter, then no OSC message will be sent. All that is needed is supporting multiple shapes, and then probably just mapping over those somewhere.. Hopefully a quick job.

You'd have to supply both the path and it's parameters, so
```
streamReplace 1 [Shape "/compression" [("compression", Nothing)], Shape "/resonance" [("resonance", Nothing)]] $ compression "0.4" # resonance 0.5
```
So the next problem is how to make that more usable.

**Comment by jarmitage** [comment]
What about

```haskell
let shapes = [
  ("/compression", [("compression", Nothing)]), 
  ("/resonance",   [("resonance", Nothing)])
]

streamReplace 1 (shapesHelper shapes) $ compression "0.4" # resonance 0.5
```

Where `shapesHelper` is some sort of lookup?

**Comment by yaxu** [comment]
I like the idea of being able to mix different targets in the same pattern.. Then the tidal dispatcher would just need a list of targets with the accepted shapes
```
oscmap = [(superdirt, [play2]),
          (processing, [play2,circle])
         ]
```
in full:
```
superdirt <- connect (Target {hostname = "127.0.0.1",
                              port = 57120,
                              schedule = Pre BundleStamp,
                              latency = 0.2,
                              window = Nothing
                             }
                     )

processing <- connect (Target {hostname = "127.0.0.1",
                               port = 57120,
                               schedule = Live,
                               latency = 0.2,
                               window = Nothing
                              }
                      )

play2 = OSC {path = "/play2,
             args = Named {required = ["sound"]}
            }

circle = OSC {path = "/shape/circle,
              args = Args [S "colour" (Default "red"),
                           I "brightness" (Default 3),
                           F "size" Required
                          ]
             }

-- list of targets, with the osc formats accepted by that target 
oscmap = [(superdirt, [play2]),
          (processing, [play2,circle])
         ]

sched <- startScheduler oscmap

d1 = set sched 1

d1 $ sound "bd(3,8)"
  # size 3.5
  # colour "blue green"
```

**Comment by jarmitage** [comment]
That looks brilliant to me!

**Comment by yaxu** [comment]
Not actually tested it yet!

**Comment by yaxu** [comment]
Currently It looks a bit like this, def not fully working though

```
p5Target = Target {oName = "p5",
                   oAddress = "127.0.0.1",
                   oPort = 5712,
                   oLatency = 0.2,
                   oWindow = Nothing,
                   oSchedule = Pre BundleStamp
                  }

play2 = OSC {path = "/play2",
             args = Named {required = ["sound"]}
            }

circle = OSC {path = "/shape/circle",
              args = ArgList [("colour", Just $ VS "red"),
                              ("brightness", Just $ VI 3),
                              ("size", Nothing)
                             ]
             }

-- list of targets, with the osc formats accepted by that target 
oscmap = [(superdirtTarget, [play2]),
          (p5Target, [play2,circle])
         ]

sched <- startStream defaultConfig oscmap
```

**Comment by jarmitage** [comment]
Cool, I just tried this with the following added that I assume you meant but missed

```haskell
superdirtTarget = Target {oName = "sd",
                          oAddress = "127.0.0.1",
                          oPort = 57120,
                          oLatency = 0.2,
                          oWindow = Nothing,
                          oSchedule = Pre BundleStamp
                         }
```

The code runs without error but I don't see any OSC messages on either port so far

**Comment by yaxu** [comment]
Ok does seem to be working after all.. Just pushed a minor change to the superdirtShape to make 's' required (and not 'sound').  Note that a 'size' param is required for a 'cicle' osc message to be sent, and 's' for a dirt or superdirt one to be sent

`superdirtShape` and `superdirtTarget` are defined in Sound.Tidal.Stream

I think the only bug is that if it fails to send a message to the first target, then it'll give up without trying the second one.
```
p5Target = Target {oName = "p5",
                   oAddress = "127.0.0.1",
                   oPort = 57120,
                   oLatency = 0.2,
                   oWindow = Nothing,
                   oSchedule = Pre BundleStamp
                  }

circle = OSC {path = "/shape/circle",
              args = ArgList [("colour", Just $ VS "red"),
                              ("brightness", Just $ VI 3),
                              ("size", Nothing)
                             ]
             }

-- list of targets, with the osc formats accepted by that target 
oscmap = [(superdirtTarget, [superdirtShape]),
          (p5Target, [dirtShape,circle])
         ]

stream <- startStream defaultConfig oscmap

streamReplace stream 1 $ size 2 # s  "clap"
```

**Comment by jarmitage** [comment]
Ok can confirm it works for me!

> I think the only bug is that if it fails to send a message to the first target, then it'll give up without trying the second one.

I haven't been able to reproduce this. Will do some more rigorous tests soon..

Out of curiosity is there any reason why you included `dirtShape` inside `oscmap` in the example above?

**Comment by yaxu** [comment]
Great! 

I included `dirtShape` to test sending multiple shapes to one target

**Comment by jarmitage** [comment]
I ported my Bitwig example:

https://gist.github.com/jarmitage/0e98e1be3d647fd43d9012d778410e61

So far I've realised that every OSC path param needs a unique name to prevent clashes, so the above would actually need to be more organised but in a good way.

Currently every OSC message gets sent regardless of whether that param is used in the pattern, so for example using the above this pattern:

```
b 1
  $ s "bd"
  # tempo 120
  # track 1 # clip 1 # action "launch"
```

Will send the following to `bwTarget` resulting in some broken messages (e.g. `vkb_miidi//launch/`):

<img width="299" alt="Screenshot 2020-05-14 at 21 53 22" src="https://user-images.githubusercontent.com/2885827/81984878-5f03ca00-962d-11ea-9d2f-127e834612fd.png">

Is it possible to only send OSC messages when their params are present in the pattern?

**Comment by yaxu** [comment]
I see, I've pushed a change that stops messages with incomplete paths being sent.

You can now put default values in paths e.g.: 
```
bwScene  = OSC "/scene/{scene=5}/launch"    $ ArgList []
```
(The above would always be sent again)

**Comment by yaxu** [comment]
If bitwig isn't honouring bundle timestamps you'll want
oSchedule = Live

**Comment by jarmitage** [comment]
Ok this is looking good. 

There's still a bit of an edge case going on:

```haskell
bwTempo  = OSC "/tempo/raw" $ ArgList [("raw", Just $ VF 0)]
...
tempo = pF "raw"
```

This will still always send as it's always a complete message, even if the `tempo` param is not in the pattern, and if it's not then it will send `0.0f` to `bwTempo`.

**Comment by yaxu** [comment]
The `Just $ VF 0` bit is the default value. If you don't want it to be optional, then set it to `Nothing` instead:
```
bwTempo  = OSC "/tempo/raw" $ ArgList [("raw", Nothing)]
```
`Just` and `Nothing` are standard haskell constructors for optional 'Maybe' values. I was thinking about making aliases i.e. `required = Nothing` and `default = Just`, so this example would then be
```
bwTempo  = OSC "/tempo/raw" $ ArgList [("raw", required)]
```

**Comment by jarmitage** [comment]
Great, I thought it would be something like this!

Re `required` and `default`, I would support those aliases.

**Comment by yaxu** [comment]
`setcps` seems broken by my refactoring..

**Comment by yaxu** [comment]
Unfortunately 'default' is a reserved word in Haskell

**Comment by jarmitage** [comment]
Think I might have found an edge case, does this send any OSC for you? For me it doesn't

```haskell
target = Target {oName = "target",
                   oAddress = "127.0.0.1",
                   oPort = 8000,
                   oLatency = 0.2,
                   oWindow = Nothing,
                   oSchedule = Pre BundleStamp
                  }

track = OSC "/track/{trackstate}/{trackstateprop}" $ ArgList [("trackstatepropval", Nothing)]

oscmap = [(superdirtTarget, [superdirtShape]), (target, track)] 

stream <- startStream defaultConfig oscmap

let trackstate = pI "trackstate" -- {1-8}
  trackstateprop = pS "trackstatepop"  -- mute, solo, recarm
  trackstatepropval = pS "trackstatepropval"   -- {1,0,-}

streamReplace stream 1 $ trackstate 0 # trackstateprop "mute" # trackstatepropval 0
```

**Comment by jarmitage** [comment]
I'm not sure that `BundleStamp` is working, or maybe I don't understand it

**Comment by jarmitage** [comment]
Re `oSchedule = Live`, `Live` is not found

**Comment by yaxu** [comment]
@jarmitage superdirt uses `BundleStamp`, so it should be working.

`Live` is found for me, once I `import Sound.Tidal.Context`. Do you have the latest version installed?

**Comment by jarmitage** [comment]
So if I understand correctly anything using `oSchedule = Pre BundleStamp` should result in `delta` `cycle` and `cps` being sent with the pattern? If that's the case I can't get that to work, and it seems it's maybe coupled to `superdirtTarget`? 

Ok `Live` does work not sure what happened there

**Comment by yaxu** [comment]
Yes those should still be added.

**Comment by jarmitage** [comment]
Ok yeah, those are not being added

**Comment by yaxu** [comment]
Ah that'll be it, they're added automatically to 'Named' style parameters, but if there's an arglist you'll have to add them to that.

**Comment by yaxu** [comment]
Here's a spec for ASCII-Simple-Video-Synth ..

```
let target = Target {oName = "ascii",
                     oAddress = "127.0.0.1",
                     oPort = 5050,
                     oLatency = 0.2,
                     oWindow = Nothing,
                     oSchedule = Live
                    }
    formats = [OSC "/{asccolour}/speed"  $ ArgList [("ascspeed", Nothing)],
               OSC "/{asccolour}/mode"   $ ArgList [("ascmode", Nothing)],
               OSC "/{asccolour}/offset" $ ArgList [("ascoffset", Nothing)],
               OSC "/{asccolour}/scale"  $ ArgList [("ascscale", Nothing)],
               OSC "/shape/sides" $ ArgList [("ascsides", Nothing)],
               OSC "/shape/size"  $ ArgList [("ascsize", Nothing)],
               OSC "/shape/xinc"  $ ArgList [("ascxinc", Nothing)],
               OSC "/shape/yinc"  $ ArgList [("ascyinc", Nothing)]
              ]
    ascSpeed  = pI "ascspeed"
    ascMode   = pI "ascMode"
    ascOffset = pI "ascOffset"
    ascScale  = pI "ascScale"
    ascSides  = pI "ascSides"
    ascSize   = pI "ascSize"
    ascXinc   = pI "ascXinc"
    ascYinc   = pI "ascYinc"
    ascColour = pS "ascColour"
    oscmap = [(target, formats)]
```

**Comment by jarmitage** [comment]
Ahhhhhhh ok got it, now it's sending those. One for the docs #650

**Comment by jarmitage** [comment]
Maybe we need a public repo of Tidal OSC specs

**Comment by yaxu** [comment]
Maybe best to put it in a folder in the main Tidal repo?
