### ISSUE TITLE
Syntax error in mini-notation with ! and ?

### ISSUE THREAD

**Issue by tedthetrumpet** [tidalcycles/Tidal#646]
**Describe the bug**
`d1 $ s "bd!8?"` produces:
```
Error in pattern: Syntax error in sequence:
  "bd!8?"
       ^  
unexpected '?'
expecting charnum, rest, "[", "{", "<", "." or end of input
```
Would probably have expected it to behave like this, which works:

`d1 $ s "[bd!8]?"`

**Comment by yaxu** [comment]
Yes, `"bd*8?"` works, so why not `"bd!8?"`
