### ISSUE TITLE
Document new OSC scheme

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#650]
ref #638

**Comment by jarmitage** [comment]
I'm writing a rather large scheme now so can help with this...

**Comment by jarmitage** [comment]
Here's my first go at a more complex OSC scheme:

https://github.com/jarmitage/jarmlib/tree/tidal-osc-refactor/tidal/streams/Bitwig

**Comment by yaxu** [comment]
Here's a go at documenting, please edit!
https://tidalcycles.org/index.php/Custom_OSC

**Comment by jarmitage** [comment]
Documenting here for later a couple of improvements that could be made (too tired to edit right now):
- Explain the `BundleStamp` parameters and that you need to manually put them in the `Target` for it to work, 
- Likewise adding manually the `sec` + `usec` params for `MessageStamp`

**Comment by jarmitage** [comment]
Doc updated
