### ISSUE TITLE
repair instance NFData (Pattern a)

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#662]
I doubt that the behaviour of
```
instance NFData a =>  NFData (Pattern a) where 
    rnf (Pattern q) = rnf $ \s -> q s
```
was intended. It should be ` .. = rnf q`? Then it could be derived generically (see #661 )

See discussion at https://github.com/tidalcycles/Tidal/issues/606#issuecomment-638400358

**Comment by dktr0** [comment]
Makes sense to me!

**Comment by yaxu** [comment]
That looks good to me too.

The NFData instance was originally added for the purposes of benchmarking by @nini-faroux.
