### ISSUE TITLE
preferred workflow for creating/handling a branch that fixes an issue?

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#663]
If I want to suggest code changes (for others to review), I need a fresh branch (in my fork) from official master. How do I best create and manage this? I find it involves a lot of busywork, with a lot of chances to mess up. (Starting with picking the proper name and  branching at the right point.)

From a local gitlab installation I am used to this very useful feature: when viewing an issue in the tracker, I can click a button to create a branch (starting at master) for this issue It is reasonably named, and merging the branch to master will close the issue. Incredibly, github has nothing of this sort (https://github.com/isaacs/github/issues/1125)

So, how do you do this?

**Comment by bgold-cosmos** [comment]
I do a lot of syncing up from the command line, it is a bit of busywork.  The Desktop app can also do a lot of it, but in the past I've had some issues with more complex things so I had to learn command line (mostly my fault, and the app's gotten better).  A lot of these things can also be done from inside Atom, but I'm still learning some of that.

Before I do anything, I make sure my local files are up to date

```
git checkout master
git fetch upstream
git pull upstream master
git push
```
Then if I want to work on something
```
git checkout -b fix-some-issue
```
edit files, test, etc.
```
git commit -a
git push --set-upstream origin fix-some-issue
```

At that point if I go my fork on the github web site, it shows up highlighted as a "recently pushed branch" with a nice green "compare & pull request" button.

**Comment by jwaldmann** [comment]
Thanks. Keep this issue open, or move contents to a better place, as developer documentation?

**Comment by yaxu** [comment]
Hi @jwaldmann, you could add it here: https://github.com/tidalcycles/Tidal/blob/master/CONTRIBUTING.md

**Comment by jwaldmann** [comment]
yes I'm on it.

**Comment by yaxu** [comment]
Thanks by the way @bgold-cosmos, with this new git knowledge I'll try to make changes via my own fork more often..
