### ISSUE TITLE
Stream.doTick: handle tempo' safely

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#669]
Function `Stream.doTick` does 
```
takeMVar (sTempoMV stream)
...
let (tes, tempo') = ...
...
putMVar (sTempoMV stream) tempo'
```
This is risky: if an uncaught exception happens, this MVar remains empty. I think this is the reason for tidal going silent, and needing a restart, in #606. (Re-setting the history of patterns does not help, it just kills the stream of error messages.)

The standard recommendation is to wrap take/put in `modifyMVar_`, cf. https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Concurrent-MVar.html#v:modifyMVar_
(it will put back the original value in case of an exception -  is this a reasonable fallback? Meaning "no tempo change"?)

But - if the computation of `tempo'` gives `undefined`, and we are unlucky, then we'll see the exception very late only, and this method may not help. So, `tempo'` needs to be forced somehow.

Note: `modifyMVar_` restores the value but re-raises the exception (I think), so we need to catch it on the outside.

**Comment by jwaldmann** [comment]
Yes indeed this works:
```
doTick fake stream st =
  E.handle (\ (e :: E.SomeException) ->
              putStrLn $ "Stream.doTick: caught " ++ show e ) $
  modifyMVar_ (sTempoMV stream) $ \ tempo ->
  do ...
    
     tempo' `seq` return tempo'
```

**Comment by yaxu** [comment]
Looks good, thanks @jwaldmann
