### ISSUE TITLE
how to use current hosc?

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#671]
`hosc` has added strictness to constructors ( #667  https://github.com/rd--/hosc/commit/f8716423013c5a333d036daefc3c0265d8a05d3e) and we want to use that. 

Locally, I have this in `stack.yaml`
```
extra-deps:
  - git: https://github.com/rd--/hosc
    commit: f8716423013c5a333d036daefc3c0265d8a05d3e
```
but this doesn't help for building with cabal, and  it also requires
```
allow-newer: true
```
in `$HOME/.stack/config.yaml`. 

So, currently, travis builds using cabal will miss it completely, and using stack, will fail.

**Comment by yaxu** [comment]
So we want the hosc maintainer Rohan to release a new version?

**Comment by yaxu** [comment]
I think this is solved, please reopen if not.
