### ISSUE TITLE
travis CI does not run tests in cabal (but it does in stack)

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#676]
Travis CI config has both a `cabal` and a `stack` way of building things. Tests are only being run in the `stack` way, cf. https://travis-ci.org/github/tidalcycles/Tidal/builds/695657396.

Is this intended?

(this is already happening before my #675)

**Comment by yaxu** [comment]
I occasionally wonder about the amount of electricity used by travis, but I think this was probably not intended.
