### ISSUE TITLE
Tidal sync not working?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#681]
Running two streams, and they don't synchronise..

```
import Sound.Tidal.Tempo
import Control.Concurrent.MVar
import qualified Sound.OSC.FD as O

nowCps str = do tempo <- readMVar $ sTempoMV str
                return $ Sound.Tidal.Tempo.cps tempo 
  
nowCps tidal
setcps 0.8
nowCps tidal

atomStream <- startStream (defaultConfig {cCtrlListen = False})
  [(Target {oName = "atom",
            oAddress = "127.0.0.1",
            oPort = 20202,
            oLatency = 0,
            oWindow = Nothing,
            oSchedule = Live,
            oBusPort = Nothing,
            oHandshake = False
           },
     [OSC {path = "/cps",
           args = ArgList [("cps", Nothing),
                           ("cycle", Nothing)
                          ]
          }
     ]
   )
  ]

nowCps atomStream
setcps 0.6
nowCps tidal
nowCps atomStream

```

**Comment by yaxu** [comment]
It seems past improvements to fine-grained cps changes have broken network sync. `doCps` isn't called at all in Stream.hs.

The cps can change from one event to the next. To calculate this accurately, the tempo is manipulated from one event to the next, during a frame.

Previously, the cps was changed via a shared clock server over OSC. This server still runs but no cps is shared. 

Probably some changes need to made to the old clock server code, to cope well with these cps changes which can be very frequent. Or longer term we could switch to use superdirt as a clock server, for easy integration with link etc..

**Comment by yaxu** [comment]
@ndr-brt noticed that two processes are perfectly in sync if the cps has never been changed, up until it is next changed

**Comment by yaxu** [comment]
It could be nice to move the clock server to superdirt, and then benefit from the new link support in supercollider. That would mean superdirt would need to keep a list of current tidal clients and update them when the cps changes though.

For now tidal could send out a cps update to the existing clock server once per frame, if it's changed that frame.

**Comment by yaxu** [comment]
This works:
```
import Sound.Tidal.Tempo

setcps = setCps (sTempoMV tidal)

setcps 2
```

**Comment by ndr-brt** [comment]
@yaxu it works also without the `setcps` redefinition, just
```
setcps 2
```
