### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#683]
We should rename the 'master' branch to 'main'. Trying this now, opening this in case of unintended issues..

**Comment by jwaldmann** [comment]
What's the goal here? Do you want to use "master" for something else?

**Comment by kindohm** [comment]
it's a metaphor that we should not use any more: https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1

**Comment by yaxu** [comment]
Yes github are switching to 'main' as default branch name but I guess won't do this change to older projects.

I removed master/slave metaphors from the source in tidal-1.0

**Comment by yaxu** [comment]
@brandondyer64 why the downvote, is this causing you problems?

**Comment by BrandonDyer64** [comment]
I believe that changing it makes things inconsistent.

I also believe that the terminology draft is referring to master-slave (as stated in the title of the section)

"master" in git does not mean master of slaves, but rather original copy.

I also don't think it should be changed until GitHub have actually made their change.

I'm not here to tell you how to run your repository. The -1 was just to show my disagreement with the change. I'm not going to complain if you do.

**Comment by yaxu** [comment]
@BrandonDyer64 Do you actually use Tidal or are you just a random passing white man with an opinion?

**Comment by froozeapp** [comment]
There's also no "slave" in git what makes this even funnier. Also, should we ban the entire BDSM community if the terminology is so bad? Kind of off-topic, I know

**Comment by yaxu** [comment]
Dear trolls, if you're spending extended amounts of time scanning github issues, in order to tell people not to waste time on a minute change, then maybe you should reconsider your priorities.

**Comment by bgold-cosmos** [comment]
Alex, thanks for taking the time to deal with this.  IIRC, before git were SVN/CVS where it was called "trunk" anyway.  I don't understand why some people get so worked up when _other_ people change a name in their own code.

**Comment by dktr0** [comment]
Yes, thanks Alex. Going to make similar changes in a bunch of my repositories now too.

**Comment by froozeapp** [comment]
@yaxu the problem isn't that it's easy, the problem is that people are going to see everything as a problem when there really isn't one. It's about control. The terms Master and Slave do describe functionality in electronic devices. And if anyone is voicing that they do not like the term being used by Github, then they should voice their opinion and not someone who is white. Also, Git doesn't even have something like a "slave", so what's wrong with just master. If it is that wrong we should change a lot of things: Masters Degree, BDSM etc..., while it may just be a simple name change, there are automation that could cause issues depending on how GitHub if/will implement this.

**Comment by yaxu** [comment]
@bgold-cosmos hm, I do like 'trunk' a lot better than 'main' actually, I'd be tempted to rename again, if it doesn't cause people problems..

**Comment by yaxu** [comment]
These interlopers made me a little curious, so I spent five minutes looking into the etymology of master, and it's all about masters of slaves and men in positions of power. I've no idea how fragile people must be to feel threatened by people not wanting to use this metaphor in daily life. As Lakoff and Johnson point out, a "dead metaphor" is just one that's so old that it structures subconscious thought without us even being aware of it.

**Comment by thilojaeggi** [comment]
There's nothing called slaves in git though?

**Comment by yaxu** [comment]
Well as 'main' is probably becoming the default, which @dktr0 is using as well, may as well stick with convention.

There is of course not a big deal, and really not worth random trolls not involved in Tidal dropping by to signal outrage. There are much better ways to work against systemic racism, but this is a very easy change.

**Comment by dktr0** [comment]
I went with 'main' on simple repositories that basically only have work on one 'main' branch. For Estuary, I went with 'dev' and 'stable' instead, since dev is really the main branch and 'stable' is just updated now and then with stuff from dev.

**Comment by yaxu** [comment]
yes superdirt has 'develop' as the default branch, hmm
