### ISSUE TITLE
hosc 0.18 fails on new install

### ISSUE THREAD

**Issue by mashaal** [tidalcycles/Tidal#684]
This seems to break most linux distros (elementary, mint, ubuntu). As hosc 0.18 does not install.

```
cabal: Error: some packages failed to install:
hosc-0.18 failed during the building phase. The exception was:
ExitFailure 1
tidal-1.6.0 depends on hosc-0.18 which failed to install.
```

I believe this needs to be reverted? https://github.com/tidalcycles/Tidal/commit/d6bdf993254847dca150b12c7d09b777c63e4d0a

**Comment by ndr-brt** [comment]
No errors for me on ubuntu 20.04.

**Comment by yaxu** [comment]
This is a problem with distros having older versions of ghc.

I'm not keen on reverting, as not supporting the latest package causes problems for stackage.

I have a pull request on hosc here which should hopefully fix things: https://github.com/rd--/hosc/pull/3

For now a workaround is installing `hosc-0.17` before installing `tidal-1.6.0`

**Comment by yaxu** [comment]
hosc 0.18.1 now released (thanks @rd-- !) - could you check if it installs on your system please @mashaal

**Comment by mashaal** [comment]
@yaxu yes, 0.18.1 installs fine
