### ISSUE TITLE
unwrap incorrectly modifies rhythm when pattern includes "@"

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#693]
I am trying to map a pattern of 0's, 1's, and 2's to a `speed` pattern, where 0 maps to a speed of 1, 1 maps to a speed of 2, and 2 maps to a rest "~":

```haskell
let pat = "{0@2 0@3 1@2 1@3 2@2 2@2}%16"

d1 $ speed (unwrap $ fmap (["1", "2", "~"]!!) $ pat) # s "bd"
```

In this case, `unwrap` must be used with `fmap` because I am including the "~". The problem is that `unwrap` changes the rhythmic structure. If you eval and listen to the pattern above, you should hear some incorrectly doubled notes.

The pattern sounds correct when `unwrap` is not used, but then I must only map to numbers (I have to remove the "~"):

```haskell
let pat = "{0@2 0@3 1@2 1@3 2@2 2@2}%16"

d1 $ speed (fmap (["1", "2", "3"]!!) $ pat) # s "bd"
```

And `unwrap` sounds correct when I do not include the "@" in the pattern:

```haskell
let pat = "{0 0 1 0 1 2 2}%16"

d1 $ speed (unwrap $ fmap (["1", "2", "~"]!!) $ pat) # s "bd"
```

**Comment by yaxu** [comment]
I think that's by design. Just as `|+|` combines structure from both sides, `unwrap` will combine structure from both the inner patterns (the `"1"`,`"2"`, `"3"` and `"~"`) and the outer (`pat`) pattern. Try with `outerJoin` instead of `unwrap`.

**Comment by bgold-cosmos** [comment]
I'm not sure what's going on with `unwrap` here, but if you're not really trying to mess with patterns of patterns, you could try using bare Int values with a dummy value for rests which can then be filtered out:

```
d1 $ (speed $ filterValues (/=0) $ fmap ([1,2,0]!!) pat) # s "bd"
```

**Comment by kindohm** [comment]
Ah, got it, thank you @yaxu and @bgold-cosmos! Both solutions work fine for me.
