### ISSUE TITLE
Ratio alias "e" evaluated not correctly on delay

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#702]
I noticed this strange behaviour with ratio aliases and delay.

This pattern:
```haskell
d1 $ s "bd" $ delay "h"
```
works correctly, as in the osc message the parameter ```delay``` is 0.5
but, using `e`:
```haskell
d1 $ s "bd" $ delay "e"
```
in the osc message the parameter ```delay``` is 4

probably it's interpreted as the note `e` (the fifth semitone, so, number 4)

**Comment by ndr-brt** [comment]
I noticed this problem also with all the other parameters

**Comment by ndr-brt** [comment]
It works correctly used for temporal alias like:
```
d1 $ off "e" (|* speed 2) $ s "bd"
```

**Comment by yaxu** [comment]
Yes it works for temporal and other rational numbers. For floating point numbers, musical notes do indeed get in the way. 

One way around this could be to make `n` and `note` a different type, so that they are parsed in a different way. This would likely cause complications, though.

**Comment by ndr-brt** [comment]
And what about defining those parameters (at least those that do not concern notes) as rational parameters?
I tried with a unit test, defining a rational parameter:
```haskell
pR :: String -> Pattern Rational -> ControlPattern
pR name = fmap (Map.singleton name . VR)
```
then setting the parameters as `pR` instead of `pF`, it works correctly.
For a parameter like "delay" but also... "gain" or any other parameter "0 to 1" I think it works better.
Do you see any possible issue with that?

**Comment by yaxu** [comment]
The only problem is efficiency - as far as I know, floats are much more efficient than rationals.. and ultimately it'll be a float in the resulting OSC message. I think it's better to create different 'flavours' of float values.. So as well as VF float values we could have VN for notes, the only difference being in how the parsing is handled.

**Comment by ndr-brt** [comment]
Ok, I writed a pair of unit test and played a little, but I eventually need some help...
I introduced a
```haskell
newtype Note = Note Double
```
and duplicate some code to make it work associated at the value `VN`
I have some problems implementing a `pDouble` that works with `Note`.

Any suggestion?

**Comment by jwaldmann** [comment]
+1  I can look into the newtype stuff if you share your code (and highlight the problem)

**Comment by ndr-brt** [comment]
created PR #708 , when you can take a look :)
thanks for the help
@jwaldmann @yaxu

**Comment by jwaldmann** [comment]
OK I am looking at it now. 

The type error goes away after
`pNote = wrapPos $ fmap (fmap Note) $ do ...`
and `data TPat a ... deriving (.., Functor)`

but then
```
Sound.Tidal.Params
  VN params
    should parse note value - *** Failed! Falsified (after 1 test): | [[](0>1)|note: 0.125f, s: "bd"] /= [[](0>1)|note: 4.0f, s: "bd"] | 
```

When should the new parser be called? I thought, for any string argument for the `note` function. Then do we need the following?
```
note :: Pattern Note -> ControlPattern
note = pN "note"
```
But this makes your test case `sound "bd" # note (1/2)` fail. (I think it should indeed fail.)

Well I can comment it out, then I get
```
Sound.Tidal.Params
  VN params
    should parse note value - *** Failed! Falsified (after 1 test): | [[](0>1)|note: Note 4.0n, s: "bd"] /= [[](0>1)|note: Note 4.0n, s: "bd"] | 
```
which I don't understand - these events look the same

(my code here: https://github.com/jwaldmann/Tidal/tree/introduce-vn-value)


NB: It's very good that you included tests, as it allows to discuss intent, independent from  implementation.

**Comment by ndr-brt** [comment]
ok, @jwaldmann, I applied your suggestion, thank you!
Now it compiles (yeeee!), the test was broken because I missed the `Fractional` extension on Note, now both the tests are broken:
```
 should parse note value - *** Failed! Falsifiable (after 1 test): | [[](0>1)|note: Note 4.0n, s: "bd"] /= [[](0>1)|note: Note 4.0n, s: "bd"] | 
 should parse correctly floating point number - *** Failed! Falsifiable (after 1 test): | [[](0>1)|note: Note 0.5n, s: "bd"] /= [[](0>1)|note: Note 0.5n, s: "bd"] | 
```

Seem the same event, but the assertion fails...

PS: yes, I'm a test-addicted, since I discovered Test Driven Development technique, I try to avoid to write production code without a test that shows the intents, it helps a lot

**Comment by ndr-brt** [comment]
@jwaldmann ok, now all tests pass!
I missed the `Eq` implementation for `VN`.
Don't know if also VN vs VR/VI/VR are needed.

@yaxu what do you think about this implementation?
