### ISSUE TITLE
Feature suggestion: Absolute version of `legato`

### ISSUE THREAD

**Issue by OscarSouth** [tidalcycles/Tidal#711]
It would be useful to have an 'absolute' version of the relative (to pattern length) `legato` control function, which could take its length pattern as an absolute    (or proof a second)

A useful functionality example over an entire piece would be for staccato effects where dependance on pattern lenth is undesirable, for example a partial application such as as `staccato = legato' 0.25` would give a really easy /literate shortcut, where `legato` itself runs into all sorts of problems with this when patterns get extended or compressed/sped up or slowed down.

Let me know if this already exists and I haven't noticed it yet -- has happened before!

**Comment by bgold-cosmos** [comment]
I think `sustain` works like this, though it's possible there's a difference in behavior between synths and samples.

**Comment by telephon** [comment]
Yes, `sustain` is intended to work exactly like this.

**Comment by OscarSouth** [comment]
Thanks for the info! Didn't think to use this for MIDI (musically I'd associate sustain more with resonance, but thinking about it it's perfectly logical). I've not tested yet but given insight shared I'm sure that this can be safely closed.
