### ISSUE TITLE
Timing issues with "ur" function

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/Tidal#713]
when moving an independent piece of code to an `ur` block, i am finding there's a distinct change in the timing, a kind of lagging and then a snapping back -- durations are not holding, patterns are not firing, and there's just a general out-of-sync-ness to it. it's subtle but i am keeping patterns/subdivisions pretty straightforward -- no odd meters or polyrhythm -- otherwise it might be hard to spot.

**Comment by yaxu** [comment]
Hi, that's strange.. Do you have a minimal example?

**Comment by jwaldmann** [comment]
Are longer patterns involved? The docs don't really say what's supposed to happen. E.g.,
```
let disp p = map (\e -> (part e, value e)) $ flip queryArc (Arc 0 9) p -- for convenience

disp ("<<0 1> <2 3 4 5> <0 1>>" :: Pattern Int)
[(0>1,0),(1>2,2),(2>3,0),(3>4,1),(4>5,3),(5>6,1),(6>7,0),(7>8,4),(8>9,0)]

isp ( ur 3 "a b a" [("a", "<0 1>"),("b", "<2 3 4 5>")] []  :: Pattern Int )
[(0>1,0),(3>4,1),(6>7,0),(1>2,3),(4>5,2),(7>8,5),(2>3,0),(5>6,1),(8>9,0)]
```
Note the differences at `(1>2), (4>5), (7>8)`, containing values from `b`.

Also, the order of events is different (output of `ur` is not monotic by time). Should not matter, but perhaps it does, if the pattern uses global effects, and there are simultaneous events that fight to set parameters.

**Comment by yaxu** [comment]
Closing as unreplicable - please reopen if you have an example.
