### ISSUE TITLE
network problem with Custom OSC

### ISSUE THREAD

**Issue by tgirod** [tidalcycles/Tidal#715]
Following the [Custom OSC tutorial](https://tidalcycles.org/index.php/Custom_OSC), I'm having a network error. Here is my code:

```
let renoise = Target {
    oName = "renoise",
    oAddress = "localhost",
    oPort = 8000,
    oLatency = 0.2,
    oSchedule = Live,
    oWindow = Nothing}

-- /renoise/trigger/note_on(inst, track, note, velocity)

let noteOn = OSC "/renoise/trigger/note_on" $ ArgList [("inst", Just $ VI (-1)),
                                                       ("track", Just $ VI (-1)),
                                                       ("note", Just $ VI 48),
                                                       ("velocity", Just $ VI 127)]

let oscmap = [(renoise, [noteOn])]

stream <- startStream defaultConfig oscmap
```

Exception: Network.Socket.connect: <socket: 12>: unsupported operation (Address family not supported by protocol)

Could it be related to this? https://stackoverflow.com/a/26589257

**Comment by yaxu** [comment]
Yes, it seems tidal isn't able to send to ipv6 addresses yet. A workaround
for now would be to change `"localhost"` to `"127.0.0.1"`

**Comment by tgirod** [comment]
OK, it works, but leads to another problem:

```
tidal> stream <- startStream defaultConfig oscmap
Listening for controls on 127.0.0.1:6010
Control listen failed. Perhaps there's already another tidal instance listening on that port?
```

I guess the line `tidal <- startTidal (superdirtTarget {oLatency = 0.1, oAddress = "127.0.0.1", oPort = 57120}) (defaultConfig {cFrameTimespan = 1/20})` from `BootTidal.hs` is launching a tidal instance, and I should close it before I can run my instance, but how do I do that ?

**Comment by yaxu** [comment]
`startStream` is the new `startTidal`. So you could delete the `startTidal` line and change the startStream line to `tidal <- startStream defaultConfig oscmap`, and all the other definitions/aliases in the BootTidal that make use of `tidal` would work with your new oscmap

**Comment by tgirod** [comment]
Oh ok so the idea is to customize `BootTidal.hs` - I thought this was more of a global config file, but it is more of a per project config. Thanks a lot for the answers!
