### ISSUE TITLE
New release of tidal (1.6.2/1.7)

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#735]
We're a bit overdue for a new tidal release, it'd be good to get that done by the end of 2020.

I made a project here:
  https://github.com/tidalcycles/Tidal/projects/4

Feel free to add issues to the project.

We could do an incremental release as-is but maybe nice to take the opportunity to go through all the pull requests and issues and do something substantial.

One big unresolved feature is to support parameter busses via `dial`. https://github.com/musikinformatik/SuperDirt/issues/190

**Comment by ndr-brt** [comment]
I removed PR #729 because it's already linked by it's issue #723 .
Added issue #702
