### ISSUE TITLE
tidal-see-output called by tidal-start-haskell displays duplicate buffer

### ISSUE THREAD

**Issue by marcora** [tidalcycles/Tidal#748]
tidal_version is 1.6.1

If I type C-c C-s (bound to tidal-start-haskell) starting from a single buffer displaying a Tidal file (first screenshot) I end up with three buffers (two duplicates of the original buffer plus the Tidal interpreter buffer (second screenshot)). I believe the desired outcome would be to have only one Tidal file buffer alongside the Tidal interpreter buffer (third screenshot).

I am on MacOS Big Sur 11.1  and Emacs 27.1.

![Screen Shot 2021-01-03 at 14 17 07](https://user-images.githubusercontent.com/6343/103486956-96e39b80-4dcf-11eb-84ac-5b59789ec5af.png)

![Screen Shot 2021-01-03 at 14 17 24](https://user-images.githubusercontent.com/6343/103486961-9e0aa980-4dcf-11eb-9e8a-388644260cc8.png)

![Screen Shot 2021-01-03 at 14 17 35](https://user-images.githubusercontent.com/6343/103486965-a2cf5d80-4dcf-11eb-9bc9-09ea2ceb8762.png)

**Comment by yaxu** [comment]
Yes I've seen the same thing under linux. If you start with a narrower window, does it still happen?

**Comment by marcora** [comment]
If I make the window very narrow, then it puts the Tidal interpreter at the
bottom and doesn't duplicate the Tidal file buffer. I believe this is the
intended behavior then (rather than side by side). It would be great if it
could be consistent across any size of the window.

Best wishes

**Comment by yaxu** [comment]
Yes I make the window narrow, start tidal then adjust to the size I want. It would be good to fix this bug but my elisp skills are weak

**Comment by marcora** [comment]
Thanks for your reply! I may take a look at a possible solution and issue a
pull request in case I get somewhere. Time and Elisp knowledge are
limiting factors! :)

**Comment by yaxu** [comment]
A PR would be very welcome!

**Comment by jwaldmann** [comment]
I have the same issue. I am trying to debug:

* `emacs check.tidal`, opens one frame containing one window showing one buffer in Tidal mode, set breakpoint and start debugging, see below
* after a few steps, `split-window-vertically` is executed, now two windows in one frame, both showing `check.tidal`
* after a few more steps, `display-buffer (current-buffer)` is executed, this splits the upper window horizontally, left part shows `ghci` process (we now have three windows)

method: M-x debug-on-entry tidal-see-function, C-s, then step with d/c,  see https://www.gnu.org/software/emacs/manual/html_node/elisp/Debugger-Commands.html#Debugger-Commands

**Comment by jwaldmann** [comment]
Aha! Then we just don't `split-window-vertically`?

```
$ diff .emacs.d/lisp/tidal.el~ .emacs.d/lisp/tidal.el
121c121
<     (split-window-vertically)
---
>     ;; (split-window-vertically)
```

**Comment by marcora** [comment]
I can confirm that commenting out that line makes it work perfectly!!!

**Comment by yaxu** [comment]
Aha thanks @jwaldmann, this problem has been plaguing me for years!

**Comment by jwaldmann** [comment]
@yaxu Do you want a PR for this?

I still wonder why that command was there in the first place. "git blame" shows that this line is from 8 years ago. Perhaps it worked at the time, and some elisp library meanwhile changed semantics. I guess it's too hard to find out now.

**Comment by yaxu** [comment]
@jwaldmann Yes please!

I adapted this from Rohan Drape's 'hsc' (haskell supercollider) library many years ago, without really understanding it, so yes I fear the cause is lost to the mists of time.
