### ISSUE TITLE
Tidal can't count

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#750]
**Describe the function/feature you'd like**
What if we had a feature where the events in a cycle could be reset back to the beginning of the cycle after a certain number of events had fired?

```
d1 $ resetCounter 6 $ n "0 1 2 3 4 5 6 7" # s "feel"
```

Would sound the same as:

```
d1 $ n "0 1 2 3 4 6 0 1" # s "feel"
```

... at least for the first cycle. I imagine that the counter would continue incrementing and resetting in subsequent cycles:

`[0 1 2 3 4 5 6 0 1] [2 3 4 5 6 0 1 2] [3 4 5 6 0 1 2 3]`

The rhythmic structure of the original pattern would remain unchanged. 

Other examples:

```
d1 $ resetCounter 3 $ n "0 1 2 3 4 5 6 7" # s "feel"
-- for the first cycle:
d1 $ n "0 1 2 0 1 2 0 1" # s "feel"
```

```
d1 $ resetCounter 11 $ n "0 1 2 3 4 5 6 7" # s "feel"

-- for first two cycles:
d1 $ cat [ n "0 1 2 3 4 5 6 7", n "0 1 2 0 1 2 3 4" ] # s "feel"
```

```
d1 $ resetCounter 1 $ n "0 1 2 3 4 5 6 7" # s "feel"
d1 $ n "0 0 0 0 0 0 0 0" # s "feel"
```

As the counter value gets larger, and as the pattern it is affecting gets more complex, I don't know what the outcomes would be. Sounds fun?   

Of course, would be great to patternize the counter:

```
d1 $ resetCounter "<11 17 3>" $ n "0 .. 7" # s "feel"
```

**Comment by kindohm** [comment]
In a way, this kind of feels like a weird variation on `iter`.

**Comment by jwaldmann** [comment]
is this, or could this be, an instance of https://club.tidalcycles.org/t/accumulation-over-patterns-why-we-cannot-have-it/2706 ? which we can't have? ...

**Comment by yaxu** [comment]
Yes it's a problem around state. We might be able to solve this sort of thing by holding state outside a pattern. For example have a circular list, whenever a value is taken, it gets cycled:
```
setRingF "melody" [0,1,2,3,4,5]
d1 $ n "^melody*4" # s "piano"
```
We would just need to make sure that the events get calculated in the right order. That would solve the 'counter' part. Manipulating that counter with patterns could also be possible.

**Comment by jwaldmann** [comment]
I'd much prefer to handle this in Haskell - not with extra string-names (because these don't have scopes and types). But that's the old problem that we cannot refer to Haskell names from inside the mini notation. Is it possible to separate these issues?
* how to handle state (semantically, and in the Haskell API)
* how to express this in mini notation

**Comment by yaxu** [comment]
The above builds on what we already have for handling state.  e.g. this would work to name a pattern:
```
setF "melody" "<0 1 2 3 4 5>"
d1 $ n "^melody*4" # s "piano"
setF "melody" "5(3,8)" -- state change
```
So we already have a way to handle state, and access that within mini-notation. So the proposal is to 
* handle state that behaves in more stateful ways
* make sure that these values are calculated in the the right order

Refactoring what we already have working might then be the separate issue.

**Comment by jwaldmann** [comment]
I see. Sorry, I was not aware of "^" - it's not in https://tidalcycles.org/Mini_notation_syntax. I do see it in the source now (ParseBP.pVar).

**Comment by yaxu** [comment]
Currently tidal handles state like this:
```
data State = State {arc :: Arc,
                    controls :: StateMap
                   }
type Query a = (State -> [Event a])
```
A first attempt would be:
```
type Query a = (State -> (State, [Event a]))
```
I don't think this is enough though. Each event needs to be able to change state independently. 

So maybe it would be more like:
```
data State = State {controls :: StateMap}
type Query a = (Arc -> [Event (State -> (State, a)]))
```
Where the time Arc is taken out of the state, which is then just a dictionary which each event modifies.

**Comment by yaxu** [comment]
Thinking about this a bit more, I guess this is what I meant:
```
type Query a = (Arc -> [State -> (State, Event a)])
```
This would allow the events to change their value according to the state, but I think the structure of the couldn't really be changed. By the time the state gets passed, you already have to commit to a certain number of events within the arc.

An alternative would be:
```
type Query a = (Arc -> State -> (State, [(Event a)]))
```
But that would get really messy. The state needs to be updated by individual events. Hmm..

**Comment by yaxu** [comment]
I guess it's not a problem that patterns can't change their structure according to state. We just need them to be able to count. Once that's solved, structural changes can hang off that.

**Comment by yaxu** [comment]
I'm also looking at putting this within the event, i.e. 
```
data Event a = Event
  { whole :: Maybe Arc
  , part :: Arc
  , value :: State -> (State, a)
  }
```
However the problem is you can't do anything like filter by that `a` value until the state is known. For example this function can't be written:
```
-- | Remove events from patterns that do not meet the given test
filterValues :: (a -> Bool) -> Pattern a -> Pattern a
```

**Comment by yaxu** [comment]
I think the answer is a new value constructor `VState`..
```
data Value = VS { svalue :: String   }
           | VF { fvalue :: Double   }
           | VN { nvalue :: Note     }
           | VR { rvalue :: Rational }
           | VI { ivalue :: Int      }
           | VB { bvalue :: Bool     }
           | VX { xvalue :: [Word8]  } -- Used for OSC 'blobs'
           | VState {statevalue :: StateMap -> (StateMap, Value)}
           deriving (Typeable, Generic)
```
This seems to work fine.. Can probably still do arithmetic through higher order magic.. and the Show instance can work on empty state. One problem though is that `StateMap` currently doesn't contain values but patterns of values..

**Comment by yaxu** [comment]
I've never been so excited watching a computer count to 3:
```
> putStrLn $ showStateful $ struct "t(3,8)" $ pStateF "note" "hello" (maybe 0 (+ 1))
(0>⅛)|note: 0.0f
(⅜>½)|note: 1.0f
(¾>⅞)|note: 2.0f
```
