### ISSUE TITLE
Travis builds failing for stack 

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#765]
Not sure what's going on here, e.g. .. 

https://travis-ci.org/github/tidalcycles/Tidal/builds/755827401

**Comment by yaxu** [comment]
@tonyday567 suggested this just needed a retry, but now tidal 1.7 failed to build on stackage: https://github.com/commercialhaskell/stackage/issues/5848

@jwaldmann Could it be that the the `Paths_tidal` thingie in tidal.cabal is breaking haddock?

**Comment by tonyday567** [comment]
Sorry, my bad, forgot to check haddocks.

lts-12.26 is a long time ago?

Are you going to migrate over to travis.com?

**Comment by jwaldmann** [comment]
Huh? My guess is that
```
Running Haddock on library for tidal-1.7..

src/Sound/Tidal/Params.hs:25:1: error:
    parse error on input ‘import’
   |
25 | import qualified Data.Map.Strict as Map
   | ^^^^^^
```
means that haddock could not parse the source text of this module, up to line 25. The start of the file looks suspicious:
```
module Sound.Tidal.Params where

-- **Please note**, ...
```
could be that haddock is interpreting `-- *` as a command (and failing)

**Comment by tonyday567** [comment]
That would be interpreted as a main header in haddock passing, and then the trailing ** messes with its mind.

I'm remove the stars.

**Comment by yaxu** [comment]
Oh so it's my fault, thanks! I can fix this later.

I haven't looked into the switch to travis.com. @ndr-brt suggests github actions: https://github.com/tidalcycles/Tidal/issues/768

I think lts-12.26 / 8.4.4 was there to test for the ghc shipped with debian. Perhaps debian stable has moved on since, I'll check on that later too.

**Comment by yaxu** [comment]
Yes removing the stars seems to have done the trick.
