### ISSUE TITLE
"Listening for controls on" message on stderr

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#770]
After upgrade to tidal 1.7 on startup, the `Listening to controls on` message appears on stderr.
Not a big issue, but on atom plugin is printed as an error and it can be confusing.
https://github.com/tidalcycles/Tidal/blob/d82f68638a622a6707b06fc45d03fa3b8fae0b64/src/Sound/Tidal/Stream.hs#L598

**Comment by yaxu** [comment]
I think it might be best to just remove this message as it generally only confuses people. We could add a 'status' command at some point to get this sort of info.

**Comment by yaxu** [comment]
Actually I think I'll add a 'verbose' config setting

**Comment by yaxu** [comment]
I think this is done now
