### ISSUE TITLE
Mini-notation spaces less forgiving

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#772]
A couple of user reports:

This used to work (spaces around the `%`):
```
"{a b c} % 4" :: Pattern String
```
As did this:
```
" bd" :: Pattern String
```
I think these are probably regressions, following from here:
https://github.com/tidalcycles/Tidal/commit/170221292819e4157e9ac46334c17a4df1e52bc4

I remember some discussion with @ndr-brt and @jwaldmann about this but can't find it at the moment..

**Comment by ndr-brt** [comment]
Yep, it was my fault, we discussed that here: https://github.com/tidalcycles/Tidal/pull/738
I think it's time to define a test case describing this behaviour :)

**Comment by yaxu** [comment]
I see, so reading this we should look at how to fix the lexer in general (or use it better) rather than add all the `spaces` back?

**Comment by ndr-brt** [comment]
It seems that was just a `spaces` missing
