### ISSUE TITLE
dontcrash tests are hanging

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#790]
Some recent change has caused the dontcrash tests to hang
```
$ cabal v1-test dontcrash
alex@olga:~/src/tidal$ cabal v1-test dontcrash
Preprocessing library for tidal-1.7.2..
Building library for tidal-1.7.2..
Preprocessing test suite 'dontcrash' for tidal-1.7.2..
Building test suite 'dontcrash' for tidal-1.7.2..
Running 1 test suites...
Test suite dontcrash: RUNNING...
```

**Comment by yaxu** [comment]
This seems to be the culprit:
```
d1 $ gain (unwrap $ fmap (["1", "0."]!!) $ "{0 0@7 0 1@7}%16") # s "harmor" # midichan 11
```
The error gets caught, but then following patterns hang.

I think the new `takeMVar` in the scheduler is to blame. https://github.com/tidalcycles/Tidal/commit/e0ba79e9b523d0ecffb13a30e144d2347f479972

Thanks for contributing the tests, @jwaldmann !

**Comment by jwaldmann** [comment]
Hi. I'm a bit out of the loop here (because very busy at work). Any action required from me?

**Comment by yaxu** [comment]
No all is good @jwaldmann, just thanking you because one of your tests caught a crash bug before release
