### ISSUE TITLE
mute/unmute/unmuteall with midi

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#797]
Would be nice to have the mute/unmute/unmuteAll functions controllable by midi (through osc)
As proposed in https://club.tidalcycles.org/t/the-atom-plugin-thread/2244/57

**Comment by yaxu** [comment]
Ref #682

**Comment by mindofmatthew** [comment]
I've added a PR that would add this functionality via `/mute`, `/unmute`, `/muteAll`, and `/unmuteAll` messages sent to a stream's control port, mirroring the relevant functions.

I'm not particularly wedded to those command paths—not sure if there's a current place for OSC api discussion, but thought I'd go ahead and implement some functionality as a starting point.

**Comment by yaxu** [comment]
I think these osc paths are fine good. I think we just need the sc example expanding to include this now
