### ISSUE TITLE
Using a consistent tag format

### ISSUE THREAD

**Issue by dvzrv** [tidalcycles/Tidal#808]
**Describe the bug**
Hi! I package tidal for Arch Linux.
With version 1.7.2 the tag format of this repository has changed from `<major>.<minor>.<patch>` to `v<major>.<minor>.<patch>`.

It may not look like much, but from a downstream's perspective consistency in tagging format is important to be able to track the latest version of an upstream and be able to download the latest version of a software (the source tarball) in a more or less standardized manner.

Will the tags always be prefixed with a `v` from now on?

**Comment by yaxu** [comment]
Hi @dvzrv, apologies for the slow reply, I missed this somehow. The 'v' was a mistake.

**Comment by dvzrv** [comment]
No problem. Thanks for getting back on this! :)

**Comment by yaxu** [comment]
I wonder @dvzrv if it would be better if we did standardise on the `v` prefix. Github recommends it, and we have it there for superdirt releases.
