### ISSUE TITLE
gain no longer affects MIDI velocity

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#810]
`gain` patterns no longer seem to affect MIDI velocity in Tidal 1.7:

```
d1 $ gain "1 0.5 0.75" # s "midi" # note "c5
```

The above pattern results in all notes having the same velocity.

**Comment by telephon** [comment]
yes, it was introduced as we moved the gain calculation away from `DirtEvent` into the Synth. We need to add it again to `DirtEventTypes`.

https://github.com/musikinformatik/SuperDirt/pull/236

**Comment by yaxu** [comment]
Thanks @telephon, @kindohm are you able to try this out

**Comment by kindohm** [comment]
Thank you @telephon! @yaxu yes I will give this a try later today.

**Comment by kindohm** [comment]
@telephon @yaxu seems to be working now, thank you!
