### ISSUE TITLE
Consolidate OSC messages in bundles when possible

### ISSUE THREAD

**Issue by mindofmatthew** [tidalcycles/Tidal#812]
**Describe the function/feature you'd like**
Tidal supports the ability to send timestamped messages as OSC bundles. It should also take advantage of the other feature of bundles: grouping messages into a single UDP datagram, so that all messages arrive together and are executed in a defined order. Two different situations to cover:

- Cases where there are stacked events at the same time (such as chords)
- Cases where a given target has multiple OSC shapes that apply to the same (or stacked) events

(Of course, messages should still be sent separately to targets where `oSchedule` is either `Live` or `Pre MessageStamp`)

**Comment by yaxu** [comment]
I _think_ the order of notes in a chord shouldn't generally matter, I think superdirt should execute them at the same time, accurate within the samplerate. One exception is where global effects and other monophonic events are changed - the last one to arrive will 'win'.

Other advantage is that it might be slightly more efficient to send bundles with multiple messages, or even bundles of bundles. It's possible that it's less efficient to do that though.

**Comment by mindofmatthew** [comment]
Yes, that's my understanding of how chords would work as well—I just mentioned it an easy test case. The actual use-case I've got in mind is sending multiple MIDI CC messages to SuperDirt, where order sometimes can matter (e.g. synths that expect a high-resolution value to be transmitted over two consecutive CC messages).

My assumption is that there's a _slight_ efficiency boost, but am curious to see if that can be demonstrated experimentally. Also, to be clear, this is less a feature request than a description of a PR that I'm going to try and put together.
