### ISSUE TITLE
Invalid Argument on controlling remote superdirt

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#825]
Situation:
```
Tidal version: 1.7.4
Ghc version: 8.10.4
```
I have one laptop running superdirt listening to remote connections:
```
~dirt.start(57120, 0!10, NetAddr("0.0.0.0"));
```

From another laptop on the same network I'm trying to send events to that superdirt.
Configured osc target:
```
superdirtTarget { oLatency = 0.20, oPort = 57120, oAddress  = "192.168.1.61" }
```

On tidal startup on the second laptop I receive this error:
```
*** Exception: Network.Socket.sendBufTo: invalid argument (Invalid Argument)
```

It's strange because if I send an osc message through the command line tool `sendosc` the message is correctly handled by superdirt.
The only detail that differs from the two laptops is that the "remote one" has a 32bit CPU

**Comment by ndr-brt** [comment]
From the remote laptop I executed this program from ghci and it worked:
```
import qualified Sound.OSC.FD as O

main = do
  u <- O.openUDP "192.168.1.61" 57120`
  O.sendMessage u (O.Message "/play2" [O.string "s", O.string "bd"])
  return ()
``

and it's working.

**Comment by yaxu** [comment]
I think this is probably because tidal opens a socket on 127.0.0.1 which it uses to both listen for controls and send messages to supercollider. This is configured as `cCtrlAddr`, so if you set that to the local address of the laptop running tidal, it should work. I'd be interested to know if it also works if you set it to 0.0.0.0 .

**Comment by ndr-brt** [comment]
setting `cCtrlAddr` = "0.0.0.0"` it works. 
Interesting behaviour, shouldn't that sockets be separated?

**Comment by yaxu** [comment]
Ah interesting.. Maybe that should be the default. I'd be a bit worried about this being different on other o/s's though. 

The same socket is used to make things much simpler with communicating with supercollider, it can send replies to the same socket that sent a message. This is how supercollider normally works between sclang + scsynth.

**Comment by ndr-brt** [comment]
ok, that makes sense. In the meantime I close this issue. Thanks
