### ISSUE TITLE
Integrate tidal-listener

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#841]
As discussed on tidal club (https://club.tidalcycles.org/t/tidal-listener-for-windows/3531/2?u=ndr_brt), would be great to integrate all the tidal-listener codebase into this one.

**Comment by yaxu** [comment]
Just merged a couple of PRs, I'll try copying it in now..

**Comment by yaxu** [comment]
Ok done. I'm not what to do about the outstanding issues. Maybe duplicate them here?

https://github.com/tidalcycles/tidal-listener/issues/

**Comment by yaxu** [comment]
I just tried merging tidal-listener again properly so that the commit history would be maintained, based on this gist: https://gist.github.com/trongthanh/2779392
It hasn't worked..

**Comment by yaxu** [comment]
Ah, it did work, but before the merge I had to `git mv` everything in the subfolder, and it turns out that `git mv` loses the git history.. Bah

**Comment by yaxu** [comment]
Nice one
