### ISSUE TITLE
Modulo operator doesn't work on ValueMaps 

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#859]
As mentioned on https://club.tidalcycles.org/, operators of type `|%`, `|%|`, `%|` are defined but only work in cases like
```
n $ run 8 |% "2 3.5"
```
but do not work when used like
```
(n $ run 8) |% (n "2 3.5")
```
as (unlike most similar operators) this gives an error
```
    • No instance for (Real ValueMap) arising from a use of ‘|%’
```

AFAICT the issue ultimately arises because `|%|` uses `Data.Fixed.mod'` which operates on type `Real`, but `ValueMap` only has instances for `Num`, `Fractional`, and `Floating`.   I don't think it should be too tricky to add a Real instance for ValueMap except that Reals must also be Ord, and I'm not quite sure how `<=` should be implemented for a ValueMap.

**Comment by yaxu** [comment]
Sounds good. A lot of functions aren't implementable in many of the instance declarations in Pattern.hs, so it's not a huge deal to not implement `<=`, just putting a `noOv` call there like the others. It's a bit of a mess but it's probably worth it.

**Comment by bgold-cosmos** [comment]
The way Haskell implements `Real` is a little weird, and we really only want it for the modulus operator, so I wound up using a different workaround.
