### ISSUE TITLE
Url at finish of tc installer not found

### ISSUE THREAD

**Issue by falanges** [tidalcycles/Tidal#872]
Hi, there are a dead link. When you finish the install via ```curl https://raw.githubusercontent.com/tidalcycles/tidal-bootstrap/master/tidal-bootstrap.command -sSf | sh```, the script gives us the following link: <https://tidalcycles.org/index.php/Start_tidalcycles_and_superdirt_for_the_first_time> , i guess you have to modify some proxy_pass on nginx or the http server that are used for. Cheers, i will be happy to contribute with you guys

**Comment by mindofmatthew** [comment]
This has been fixed with a [recent PR](https://github.com/tidalcycles/tidal-bootstrap/pull/23) and should be resolved now
