### ISSUE TITLE
Wrong tidal-listener?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#884]
I'm confused.. Tidal listener here isn't using `unsafeRunInterpreterWithArgsLibdir` so I guess isn't using the relocatable set of libraries under haskell-libs: https://github.com/tidalcycles/Tidal/blob/main/tidal-listener/src/Sound/Tidal/Hint.hs

It looks very different from @polymorphicengine 's version: https://github.com/polymorphicengine/tidal-gui/blob/main/src/Hint.hs

What's going on? Did I copy in the wrong branch or something?

**Comment by polymorphicengine** [comment]
I guess you meant to link to this:
https://github.com/polymorphicengine/tidal-listener/blob/master/src/Sound/Tidal/Hint.hs

it seems that I've never made a PR to commit my changes, can't remember the reason, but I possibly just forgot.

Now it seems I'm behind 5 commits, I'll have to look into what the changes were there

**Comment by yaxu** [comment]
Ok thanks @polymorphicengine !

**Comment by polymorphicengine** [comment]
It's able to merge now, the repo is archived though

**Comment by yaxu** [comment]
@polymorphicengine yes the codebase has moved here https://github.com/tidalcycles/Tidal/tree/main/tidal-listener

So I guess you need to clone the tidal repo if you don't have it already, and manually copy the files there

@sorki Do you also have some changes to contribute to tidal-listener?

**Comment by polymorphicengine** [comment]
Ok, just opened a pull request

**Comment by yaxu** [comment]
Thanks
