### ISSUE TITLE
remove -1 default parameters

### ISSUE THREAD

**Issue by telephon** [tidalcycles/Tidal#89]
Currently, we have this:

```
delayfeedback :: Pattern Double -> ParamPattern
delayfeedback = make' VF delayfeedback_p
delayfeedback_p = F "delayfeedback" (Just (-1))
```

Which will send `-1` instead of nothing. Assuming that `delay` is the "keyword" that will say that you want to actually use the delay, there seems to be no reason why we shouldn't just send `nil` (aka `Nothing`) instead. 

The current behaviour requires special treatment of the `delaytime` and `delayfeedback` parameters.

**Comment by lennart** [comment]
see #152 for reasons why we keep these defaults.
