### ISSUE TITLE
https://tidalcycles.org/index.php/Start_tidalcycles_and_superdirt_for_the_first_time not found

### ISSUE THREAD

**Issue by bwagner** [tidalcycles/Tidal#892]
**Describe the bug**
Installed tidalcycles running Automatic Installation Script on a MacBook Pro (15-inch, 2016), macOS Big Sur 11.6. At the end of the installation there's a hint to go visit:
https://tidalcycles.org/index.php/Start_tidalcycles_and_superdirt_for_the_first_time
which is a "Page Not Found".

**Comment by mindofmatthew** [comment]
There's an [open pull request](https://github.com/tidalcycles/tidal-bootstrap/pull/23) that would resolve this over on the `tidal-bootstrap` repo.

**Comment by ndr-brt** [comment]
Merged :+1:
