### ISSUE TITLE
cut group disappears when panic is used

### ISSUE THREAD

**Issue by muziker** [tidalcycles/Tidal#893]
For 1.7.10, the cut group disappears from the server once <panic> is used. A stream of failure in server messages appear in super collider. A new cutgroup must be assigned for cut to work again.

**Comment by telephon** [comment]
You mean `superpanic`? as defined in 
superdirt:
```supercollider
~dirt.soundLibrary.addSynth(\superpanic, (play: { ~dirt.orbits.do(_.freeSynths) }))
```
