### ISSUE TITLE
parsing boolean patterns with consecutive *

### ISSUE THREAD

**Issue by polymorphicengine** [tidalcycles/Tidal#897]
https://club.tidalcycles.org/t/struct-behavior-in-mininotation/3886/2
It seems there is a bug in parsing boolean patterns that have a consecutive application of the `*` mini-syntax operator.

Examples:

`struct "t*1 t*1" $ s "bd"`
`while "t*1 t*1" rev $ s "bd"`

throw the following error:

```
Syntax error in sequence:
  "t*1 t*1"
        ^  
unexpected '*'
expecting rest, "[", "{", "<", "^", ".", "?" or end of input
```
just one application, or alternating applications work: `"t*1"`, `"t*1 t t*2"`.

if we replace the `t` by `1` it also works.

**Comment by polymorphicengine** [comment]
After some more tests I also observed the following:

```
*Sound.Tidal.Bjorklund Sound.Tidal.ParseBP Text.Parsec.Error> parseTPat "t*1 t" :: Either ParseError (TPat Bool)
Right (TPat_Seq [TPat_Fast (TPat_Atom (Just ((3,1),(6,1))) (1 % 3)) (TPat_Atom (Just ((1,1),(2,1))) True)])
```

which should result in

`Right (TPat_Seq [TPat_Fast (TPat_Atom (Just ((3,1),(5,1))) (1 % 1)) (TPat_Atom (Just ((1,1),(2,1))) True),TPat_Atom (Just ((5,1),(6,1))) True])`

unfortunately I'm not very familiar with the mini syntax parser (and I'm always getting confused when I try to look into it) but it seems something is wrong with the `pMult` parser in combination with `t`?

**Comment by polymorphicengine** [comment]
Ok, I found the problem. It is trying to parse the `t` or `f` as a rational with the function `pRatioChar` that parses `t` as `1/3`.

Easiest fix would be to remove that from there (is actually anybody using that shorthand for triplets?). So the function would read like this:

```
pRatioChar :: Fractional a => MyParser a
pRatioChar = pRatioSingleChar 'w' 1
             <|> pRatioSingleChar 'h' 0.5
             <|> pRatioSingleChar 'q' 0.25
             <|> pRatioSingleChar 'e' 0.125
             <|> pRatioSingleChar 's' 0.0625
             <|> pRatioSingleChar 'x' (1/6)
```

Probably there is another fix, by putting a `try` in the right place. Can't really figure out where at the moment.

Does anybody have any thoughts on this?

**Comment by ndr-brt** [comment]
Please don't do that! I use them A LOT.
The right way would be to differentiate the parsing of a `Pattern Boolean` from the `Pattern Double`

**Comment by yaxu** [comment]
@bgold-cosmos This might be a good reason for moving to megaparsec: https://markkarpov.com/tutorial/megaparsec.html#debugging-parsers
It doesn't look difficult, and would likely come with other benefits, like better error messages: https://github.com/mrkkrp/megaparsec-site/blob/master/tutorials/switch-from-parsec-to-megaparsec.md

**Comment by polymorphicengine** [comment]
Ok I think I found the mistake: in `pRatio` there seems to be a weird application of `pRatioChar`. The corrected version reads like this:

```
pRatio :: MyParser Rational
pRatio = do
  s <- sign
  r <- do n <- try intOrFloat
          v <- pFraction n <|> return (toRational n)
          --r <- pRatioChar <|> return 1
          return v
       <|>
       pRatioChar
  return $ applySign s r
```

I'm pretty sure the current implementation was a mistake since it would allow to write mini syntax like `"bd*1%3 t"` to get a total multiplication of `1/9`, that seems really counterintuitive, right?

I agree that it would be nice to switch to a parser that is easier to debug, I might look into doing that

**Comment by yaxu** [comment]
Yep @polymorphicengine, I think this is a parser bug rather than an issue with types @ndr-brt. Hmm, `"t*1" :: Pattern Bool` works fine. `"t*t" :: Pattern Bool` reads a bit funny but does work - it's equivalent of `"t/3"`.

**Comment by polymorphicengine** [comment]
Oh on the other hand, people might actually use it like this `"bd*2t"` @ndr-brt ?

So the way to do it would be to check that there is no space after the parsed float/integer/rational. I'll look into that tomorrow

**Comment by ndr-brt** [comment]
@polymorphicengine that function parses a generic ratio number, maybe `1%3t` doesn't make a lot of sense, but `2t` does (two thirds), and commenting that line would break this case too. The real problem is that the whitespace is not seen as separator and so the second `t` is considered part of the same expression. 
I can't see why.

**Comment by ndr-brt** [comment]
The ratio numbers are not only parsed after `*`, so if you do, e.g. `off "3q" id` it works and it's pretty handy

**Comment by polymorphicengine** [comment]
> The real problem is that the whitespace is not seen as separator and so the second `t` is considered part of the same expression.

Exactly, the integer/float parsers eat the trailing whitespace, which sometimes might be a good thing, but here it's definitely not a good thing..

there might be other places where we should be stricter about whitespace, maybe this is an issue all of it's own.

But for now we can just introduce a new parser similar to `intOrFloat` that doesn't consume whitespace
