### ISSUE TITLE
`arp` step patterns not working

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/Tidal#901]
`n (arp "up" "c'maj7'8")` works but `n (arp "up" "c'maj7'[8]")` does not -- when the step argument is placed within square brackets for patterning, it does not produce eight steps and the notes produced do not relate to the chord that is defined.

**Comment by polymorphicengine** [comment]
just saw this, this is fixed in 1.9.x, since chords are patternable now.

this issue can be closed
