### ISSUE TITLE
stut/stutWith inconsistency

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/Tidal#902]
As notified by some people (like @cleary and @felixroos), there's an inconsistency between `stut` and `stutWith`, as:

> stut is (times, feedback, time)
> stutWith is (times, time, func) 
> probably stut (times, time, feedback) would be more logical

I also point out that `stut` can be considered an ableist term (as it was done on supercollider, and deprecated: https://github.com/supercollider/supercollider/issues/5383)

So one option could be to deprecate `stut` and `stutWith` and define a new pair of functions with the right definition, the other would be to fix the inconsistency of `stut` and release a major version (probably including other breaking changes as well).

I would prefer to define a new pair of function and leave `stut`/`stutWith` there, mark them as deprecated and remove them in the next major release.
Some terms proposed for this rename are:
- `echo` (already used)
- `dup` (as done in supercollider)
- `comb`
- `ditto`
- `retrig`
- `rep`

**Comment by mxmxyz** [comment]
I would prefer to keep `stut` and `stutWith` as aliases for backwards compatibility (at least the second one, since there would be no functional changes).

I agree that it's better to have a different 'main' name to use in documentation and the like.

**Comment by yaxu** [comment]
Just to add that `echo` is already used, but not for anything very useful. I think `echo` `echoWith` would be best. I'm not familiar with supercollider's `dup`, but probably it does something a bit different to our `stut`, so we don't need to follow their name change necessarily.

**Comment by mxmxyz** [comment]
personally I kinda dislike `echo` because it makes the function look like an audio effect, and it kinda behaves like it, but it's not

i'd rather have something more neutral, like `cloneWith`

**Comment by telephon** [comment]
in supercollider we changed it to `dup` and `dupEach` (from duplicate)

**Comment by ndr-brt** [comment]
At the end I think I enjoy `dup` as shorthand for `duplicate`, I agree that `echo` can be confused with an effect.

**Comment by yaxu** [comment]
I prefer `echo`. `dup` feels a bit cold in referring to a copying process rather than an echo sensation. I also don't think it is contradictory to work with it as an audio effect, as that is how it behaves.

I haven't looked closely so and not sure, but I think the supercollider `stutter` is a bit different from the tidal `stut`, in which case there is no need to follow a naming convention between them.

**Comment by ndr-brt** [comment]
what could be the "action plan" in the case we would choose `echo`? Change it and release a tidal 2.0?

**Comment by yaxu** [comment]
I think as with supercollider, support both and focus on changing the documentation.

**Comment by ndr-brt** [comment]
I was referring to the fact that `echo` is an already used function, as you said, probably not a lot because it's not that used

**Comment by yaxu** [comment]
Ah yes I see what you mean. We could release it as 1.8, as second level number change is enough to indicate an API change.

**Comment by ndr-brt** [comment]
Was putting some ideas in this, and while I was adding tests for `echo` I discovered something that looks like a bug to me but I'm not sure...

a test like this:
```haskell
it "stut" $ do
  compareP (Arc 0 1)
    (stut 4 0.5 0.25 $ sound "bd" # gain 1)
    (sound "bd*4" # gain "1 0.5 0.25 0.125")
```
has a correct assertion right? because `stut` should echo the event by the steptime and multiplying gain by the `feedback` parameter.

But test fails:
```
[-1¼-(0>¼)|gain: 0.875f, s: "bd",-1½-(0>½)|gain: 0.75f, s: "bd",-1¾-(0>¾)|gain: 0.625f, s: "bd",(0>1)|gain: 1.0f, s: "bd",(¼>1)-1¼|gain: 0.875f, s: "bd",(½>1)-1½|gain: 0.75f, s: "bd",(¾>1)-1¾|gain: 0.625f, s: "bd"] 
/= 
[(0>¼)|gain: 1.0f, s: "bd",(¼>½)|gain: 0.5f, s: "bd",(½>¾)|gain: 0.25f, s: "bd",(¾>1)|gain: 0.125f, s: "bd"] |
```
Why are there 7 events, 3 of which are in the past?

**Comment by ndr-brt** [comment]
> @ndr-brt I have not checked the numbers, but I'm pretty sure your assertion is wrong: As I understood it, `stut n d g` will essentially copy the event `n` times, and delay it by `i*d` where i is the index of the copy, multiplying gain by `g` each time.
> 
> So the 7 events should be 1 - 4: 4 onsets, 3 of which are delayed 5 - 7: the tails of the 3 delayed copies (leaping over to next cycle)
> 
> This is also what an acoustical echo would do, which is why I think the name is quite fitting.

I don't get the tails... why they are produced? 
If I specify a value of 4 I expect 4 events, 7 seems like a weird number... why 7 and not 10 for example? why they should leap only to the next cycle and not to the one after?

Personally I would stick with the definition that's reported in the `stut` function comments:
```
{- | Stut applies a type of delay to a pattern. It has three parameters,
which could be called depth, feedback and time. Depth is an integer
and the others floating point. This adds a bit of echo:

@
d1 $ stut 4 0.5 0.2 $ sound "bd sn"
@

The above results in 4 echos, each one 50% quieter than the last,
with 1/5th of a cycle between them. It is possible to reverse the echo:

@
d1 $ stut 4 0.5 (-0.2) $ sound "bd sn"
@
-}
```

**Comment by ndr-brt** [comment]
ok, makes sense. So how could be a test written? Is there another way to represent the `stut` behavior without using `stut`?

**Comment by felixroos** [comment]
something like that?

```hs
d1 $ stack [
  rotR 0 "bd" # gain 1,
  rotR 0.25 "bd" # gain 0.9, 
  rotR 0.5 "bd" # gain 0.8, 
  rotR 0.75 "bd"  # gain 0.7
]
```

not sure how the calculation of the gain works though..

**Comment by ndr-brt** [comment]
Yeah, that did the job, the gain calculation seems like it's not a simple multiplication, so I think the documentation it's not correct.
@yaxu do you remember why the `scalegain` was implemented this way?
I always thought that `stut 2 0.5 0.2` would produce a repetition with a gain scaled by the 50%, so `0.5`, but it's `0.875`
