### ISSUE TITLE
cabal install tidal fails on Windows 10

### ISSUE THREAD

**Issue by fdch** [tidalcycles/Tidal#906]
Hi there. Apologies for the bummer issue ;) Tidal newebie here. 

I've managed to get a clean install on macos but I can't get it working on Windows 10. While, Haskell and SC3+SuperDirt are working fine, the problem is I can't get tidal to install.

I can do further tinkering but would not know where to start. So, **any pointers will be much appreciated.**

Here's the Atom console error:
```
t> 
: error:
    Could not find module `Sound.Tidal.Context'
    It is not a module in the current program, or in any known package.
```

Here's the log with `cabal install tidal -v --lib` [log.txt](https://github.com/tidalcycles/Tidal/files/8492047/log.txt). It ends like: this
```
cabal-3.6.2.0.exe: Failed to build
clock-0.8.3-c818fff5b75d906f803595f11a547dfea67f0eb8.
Failed to build hosc-0.19.1 because it depends on hosc-0.19.1 which itself
failed to build.
Failed to build hsc2hs-0.68.8-60959addfd1aa8190def15ae9b06433cded65805.
Failed to build network-3.1.2.7 because it depends on network-3.1.2.7 which
itself failed to build.
Failed to build tidal-1.7.10 because it depends on tidal-1.7.10 which itself
failed to build.
Failed to build tidal-1.7.10 because it depends on tidal-1.7.10 which itself
failed to build.
```

**Comment by albreche** [comment]
Hi there, i've ran into a similar issuee yesteraday. Could you check the output of `ghc-pkg list` ? 
For some reasons, cabal may install tidal properly in the user package db ,  but ghci does not know that db .

**Comment by cdorsman** [comment]
@albreche  That's correct. I don't see any Tidal in the list. How to fix this?

**Comment by yaxu** [comment]
Please take install issues to the https://club.tidalcycles.org/ forum or discord.
