### ISSUE TITLE
"@" operator not working in tidal 1.7.10

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/Tidal#907]
in tidal 1.7.10, the expression `n "fs@0.75 f@0.25" # s "superchip"` does not elongate the first note and shorten the second note as one would expect. the same expression works fine in version 1.7.8

**Comment by polymorphicengine** [comment]
this is already fixed by #900, so it will work in the next release. It might be good to add this example to the testsuite aswell, could you do that @Git-Christopher ?
