### ISSUE TITLE
[Feature Request - DSP] - Reverse Engineering (ASM), DSP in order to include it in tidal

### ISSUE THREAD

**Issue by ahtoaXoov7D** [tidalcycles/Tidal#908]
**_[Feature Request - DSP] - Reverse Engineering (ASM), DSP in order to include it in tidal_**

### **Greetings**

**it would be nice if we could:**
_- reverse engineering (using ASM, C++, Faust and CUDA):_
  _- parts of opensource freeware plugins to implement them in tidal_
  _- parts of inexpensive commercial hardware dsp to implement in tidal_

**Looking Forward**
_Kind Regards_
_**\T.**_

**Comment by yaxu** [comment]
Sounds good but will close as the request is very broad and tidal doesn't make sound itself.
