### ISSUE TITLE
Mini-notation for euclidInv

### ISSUE THREAD

**Issue by ritchse** [tidalcycles/Tidal#915]
What if inserting negative values into the first argument of euclid mininotation resulted in the inverted version of that euclidian rhythm. So that, for example:
```
"bd(-3,8)"
```
was the same as
```
euclidInv 3 8 $ s "bd"
```

**Comment by ndr-brt** [comment]
Why don't have this implemented directly in the `euclid` function?
e.g.
```haskell
euclid (-3) 8
```
would be the same as 
```haskell
euclidInv 3 8
```

**Comment by ritchse** [comment]
i didn't even think about it,,, makes more sense tbh
