### ISSUE TITLE
Cabal install tidal fails because of typo

### ISSUE THREAD

**Issue by cdorsman** [tidalcycles/Tidal#921]
**Describe the bug**
Please describe the bug, along with the code example, and any errors you get. Please also give the version of tidal you're using, which you can get by running `tidal_version` in a tidal session.

I did the following steps on Windows 10:
PS C:\Windows\system32> cabal v1-update
cabal.exe: unrecognised command: v1-update (try --help)
Maybe you meant `v2-update`?
PS C:\Windows\system32> cabal v2-update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-06-17T12:06:41Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2022-06-17T11:30:41Z'
PS C:\Windows\system32> cabal v2-install tidal
Resolving dependencies...
Build profile: -w ghc-9.2.3 -O1
In order, the following will be built (use -v for more details):
 - async-2.2.4 (lib) (requires build)
 - clock-0.8.3 (lib) (requires build)
 - hsc2hs-0.68.8 (exe:hsc2hs) (requires build)
 - primitive-0.7.4.0 (lib) (requires build)
 - splitmix-0.1.0.4 (lib) (requires build)
 - tagged-0.8.6.1 (lib) (requires build)
 - th-abstraction-0.4.3.0 (lib) (requires build)
 - transformers-compat-0.7.1 (lib) (requires build)
 - network-3.1.2.7 (lib:network) (requires build)
 - random-1.2.1.1 (lib) (requires build)
 - distributive-0.6.2.1 (lib) (requires build)
 - hosc-0.19.1 (lib) (requires build)
 - temporary-1.3 (lib) (requires build)
 - comonad-5.0.8 (lib) (requires build)
 - hint-0.9.0.6 (lib) (requires build)
 - bifunctors-5.5.12 (lib) (requires build)
 - tidal-1.8.0 (lib) (requires build)
 - tidal-1.8.0 (exe:tidal) (requires build)
Starting     primitive-0.7.4.0 (lib)
Starting     hsc2hs-0.68.8 (exe:hsc2hs)
Starting     th-abstraction-0.4.3.0 (lib)
Starting     clock-0.8.3 (lib)
Starting     async-2.2.4 (lib)
Starting     tagged-0.8.6.1 (lib)
Starting     transformers-compat-0.7.1 (lib)
Starting     splitmix-0.1.0.4 (lib)
Building     hsc2hs-0.68.8 (exe:hsc2hs)
Building     th-abstraction-0.4.3.0 (lib)
Building     clock-0.8.3 (lib)
Building     tagged-0.8.6.1 (lib)
Building     splitmix-0.1.0.4 (lib)
Building     async-2.2.4 (lib)
Building     primitive-0.7.4.0 (lib)
Building     transformers-compat-0.7.1 (lib)
Installing   async-2.2.4 (lib)
Installing   tagged-0.8.6.1 (lib)
Completed    async-2.2.4 (lib)
Completed    tagged-0.8.6.1 (lib)
Installing   transformers-compat-0.7.1 (lib)
Completed    transformers-compat-0.7.1 (lib)
Installing   splitmix-0.1.0.4 (lib)
Completed    splitmix-0.1.0.4 (lib)
Installing   th-abstraction-0.4.3.0 (lib)
Completed    th-abstraction-0.4.3.0 (lib)
Installing   primitive-0.7.4.0 (lib)
Completed    primitive-0.7.4.0 (lib)

Failed to build clock-0.8.3.
Build log (
C:\Users\Chris\AppData\Roaming\cabal\logs\ghc-9.2.3\clock-0.8.3-195f019c953f195e25409c7337685c7a547b0e9d.log
):
Preprocessing library for clock-0.8.3..
linking dist\build\System\Clock_hsc_make.o failed (exit code 1)
rsp file was: "dist\\build\\System\\hsc2641.rsp"
command was: C:\tools\ghc-9.2.3\lib\../mingw/bin\gcc.exe dist\build\System\Clock_hsc_make.o dist\build\System\Clock_hsc_utils.o -o dist\build\System\Clock_hsc_make.exe -LC:\msys64\mingw64\lib -LC:\tools\ghc-9.2.3\lib\x86_64-windows-ghc-9.2.3\base-4.16.2.0 -lwsock32 -luser32 -lshell32 -lmsvcrt -lmingw32 -lmingwex -lws2_32 -lshlwapi -lole32 -lrpcrt4 -lntdll -LC:\tools\ghc-9.2.3\lib\x86_64-windows-ghc-9.2.3\ghc-bignum-1.2 -LC:\tools\ghc-9.2.3\lib\x86_64-windows-ghc-9.2.3\ghc-prim-0.8.0 -luser32 -lmingw32 -lmingwex -LC:\tools\ghc-9.2.3\lib\x86_64-windows-ghc-9.2.3\rts-1.0.2 -lm -lwsock32 -lgdi32 -lwinmm -ldbghelp -lpsapi -lmingwex
error: C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_app_type[.refptr.mingw_app_type]+0x0): undefined reference to `mingw_app_type'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initcharmax[.refptr.mingw_initcharmax]+0x0): undefined reference to `mingw_initcharmax'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltssuo_force[.refptr.mingw_initltssuo_force]+0x0): undefined reference to `mingw_initltssuo_force'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdyn_force[.refptr.mingw_initltsdyn_force]+0x0): undefined reference to `mingw_initltsdyn_force'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdrot_force[.refptr.mingw_initltsdrot_force]+0x0): undefined reference to `mingw_initltsdrot_force'
collect2.exe: error: ld returned 1 exit status

Failed to build exe:hsc2hs from hsc2hs-0.68.8.
Build log (
C:\Users\Chris\AppData\Roaming\cabal\logs\ghc-9.2.3\hsc2hs-0.68.8-d6f10045b2b41e70d4c7cd54d70066a1eeed9b3d.log
):
Preprocessing executable 'hsc2hs' for hsc2hs-0.68.8..
Building executable 'hsc2hs' for hsc2hs-0.68.8..
[ 1 of 12] Compiling ATTParser        ( src\ATTParser.hs, dist\build\hsc2hs\hsc2hs-tmp\ATTParser.o )
[ 2 of 12] Compiling Compat.ResponseFile ( src\Compat\ResponseFile.hs, dist\build\hsc2hs\hsc2hs-tmp\Compat\ResponseFile.o )
[ 3 of 12] Compiling Compat.TempFile  ( src\Compat\TempFile.hs, dist\build\hsc2hs\hsc2hs-tmp\Compat\TempFile.o )
[ 4 of 12] Compiling Common           ( src\Common.hs, dist\build\hsc2hs\hsc2hs-tmp\Common.o )
[ 5 of 12] Compiling Flags            ( src\Flags.hs, dist\build\hsc2hs\hsc2hs-tmp\Flags.o )
[ 6 of 12] Compiling HSCParser        ( src\HSCParser.hs, dist\build\hsc2hs\hsc2hs-tmp\HSCParser.o )
[ 7 of 12] Compiling C                ( src\C.hs, dist\build\hsc2hs\hsc2hs-tmp\C.o )
[ 8 of 12] Compiling CrossCodegen     ( src\CrossCodegen.hs, dist\build\hsc2hs\hsc2hs-tmp\CrossCodegen.o )
[ 9 of 12] Compiling Paths_hsc2hs     ( dist\build\hsc2hs\autogen\Paths_hsc2hs.hs, dist\build\hsc2hs\hsc2hs-tmp\Paths_hsc2hs.o )
[10 of 12] Compiling UtilsCodegen     ( src\UtilsCodegen.hs, dist\build\hsc2hs\hsc2hs-tmp\UtilsCodegen.o )
[11 of 12] Compiling DirectCodegen    ( src\DirectCodegen.hs, dist\build\hsc2hs\hsc2hs-tmp\DirectCodegen.o )
[12 of 12] Compiling Main             ( src\Main.hs, dist\build\hsc2hs\hsc2hs-tmp\Main.o )
In file included from C:\tools\ghc-9.2.3\lib\x86_64-windows-ghc-9.2.3\base-4.16.2.0\include/HsBase.h:147,

                 from cbits\utils.c:9:0: error:

C:\msys64\mingw64\include\shlobj.h:611:3: error:
     warning: useless storage class specifier in empty declaration
      611 |   };
          |   ^
    |
611 |   };
    |   ^
Linking dist\\build\\hsc2hs\\hsc2hs.exe ...
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_app_type[.refptr.mingw_app_type]+0x0): undefined reference to `mingw_app_type'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initcharmax[.refptr.mingw_initcharmax]+0x0): undefined reference to `mingw_initcharmax'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltssuo_force[.refptr.mingw_initltssuo_force]+0x0): undefined reference to `mingw_initltssuo_force'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdyn_force[.refptr.mingw_initltsdyn_force]+0x0): undefined reference to `mingw_initltsdyn_force'
C://tools//ghc-9.2.3//mingw//bin/ld.exe: C://tools//ghc-9.2.3//mingw//bin/../x86_64-w64-mingw32/lib/crt2.o:crtexe.c:(.rdata$.refptr.mingw_initltsdrot_force[.refptr.mingw_initltsdrot_force]+0x0): undefined reference to `mingw_initltsdrot_force'
collect2.exe: error: ld returned 1 exit status
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
cabal.exe: Failed to build clock-0.8.3 (which is required by exe:tidal from
tidal-1.8.0). See the build log above for details.
Failed to build exe:hsc2hs from hsc2hs-0.68.8 (which is required by exe:tidal
from tidal-1.8.0). See the build log above for details.

Can someone take a look at this?

**Comment by yaxu** [comment]
Hi, what's the typo you're referring to?

**Comment by cdorsman** [comment]
As I already given in my start post: 

error:
warning: useless storage class specifier in empty declaration
611 | };
| ^
|
611 | };
| ^

**Comment by yaxu** [comment]
@cdorsman I'm not sure what that is, but it doesn't seem to be a typo, and is a warning rather than an error.
The error you're having seems to be with your ghc/haskell installation being unable to compile things. How did you install ghc?
