### ISSUE TITLE
latest release 1.8.0 missing on `CHANGELOG.md` file

### ISSUE THREAD

**Issue by joenio** [tidalcycles/Tidal#943]
The latest version listed on `CHANGELOG.md` file is tidal 1.7.10 and AFAIK the latest release is 1.8.0, on Github release version 1.8.0 we have the [What's Changed](https://github.com/tidalcycles/Tidal/releases/tag/v1.8.0) section and I guess the content there could be added to `CHANGELOG.md` file.

I noted it when I was searching tidal on hackage:
- https://hackage.haskell.org/package/tidal-1.8.0/changelog

Suggestion:

- Add a step on section **A process for making a release** in the file `CONTRIBUTING.md`

**Comment by yaxu** [comment]
Hopefully fixed in the latest release
