### ISSUE TITLE
tidal 1.8.1 on hackage doesn't have an executable

### ISSUE THREAD

**Issue by felixonmars** [tidalcycles/Tidal#945]
The whole `executable tidal` section is missing from [tidal-1.8.1 on hackage](https://hackage.haskell.org/package/tidal-1.8.1/), and this change doesn't seem to be in this repository.

**Comment by dvzrv** [comment]
For context: We are packaging this project for Arch Linux and the hackage release being broken means that tidal on Arch Linux is broken currently.

**Comment by dvzrv** [comment]
Also, 1.8.1 is not reflected as a tag/release in this repository. Please add it and create a new release that has the executable

**Comment by yaxu** [comment]
Hi, this stems from the latest ghc release not yet supporting hint, and therefore the executable not building on that platform, which was breaking the windows choco install. As the executable is currently a pretty useless work-in-progress, and I was on holiday I made a quick fix of an interim hackage release without that executable. 

I've just got back home, so can look into this properly now.. Is there a particular reason why the executable required under arch?

**Comment by yaxu** [comment]
I'm going to do a release or two this week and will tidy this stuff up, but could you please clarify if/why you need an executable in the cabal file? @dvzrv

**Comment by dvzrv** [comment]
> I'm going to do a release or two this week and will tidy this stuff up, but could you please clarify if/why you need an executable in the cabal file? @dvzrv

Sorry, forgot about this ticket!

Hm, not sure if we really need the executable. I was under the impression, that it is a new default thing that you are offering cross-platform to start tidal. If that is not the case, I don't mind if it is not there of course!

**Comment by yaxu** [comment]
Great, thanks for clarifying that!

**Comment by yaxu** [comment]
@dvzrv v1.9.0 is up now, please lmk if you spot issues with it

**Comment by yaxu** [comment]
@felixonmars @dvzrv please note that tidal know requires g++ to build, due to the ableton link library being a c++ thing

**Comment by felixonmars** [comment]
Thanks. We have added `tidal-link` as a separate package and it depends on gcc-libs on runtime. Everything looks good so far.

**Comment by felixonmars** [comment]
Actually `pacman`, the default system package manager, should work directly. But since the linked blog uses `yay`, keeping it should not be a big issue either.

**Comment by dvzrv** [comment]
That being said: `yay` is unsupported and should not be encouraged, as it implies people will have to deal with the AUR (which contains user-provided build scripts, but no prebuilt packages).

Using

```
pacman -S haskell-tidal
```

should do mostly what people want. If users also want the sc3-plugins they can use

```
pacman -S sc3-plugins
```

The package is also listed as an optional dependency of haskell-tidal though.
