### ISSUE TITLE
up not working correctly

### ISSUE THREAD

**Issue by Xpktro** [tidalcycles/Tidal#95]
I found that:

`d1 $ stack [sound "trump*3" |+| up "0 3 5"]`

Might be the same as:

`d1 $ stack [sound "trump*3" |+| up "0 3 5"] |+| up "0"`

Since the additional `up "0"` shouldn't alter the pitch at all. However, the latter sounds an octave up than the former.

I tried to _normalize_ the pitch using a negative amoung for the second `up`, but it didn't seem to shift an exact octave when passed -12, lower values didn't scaled linearly as well.

**Comment by bgold-cosmos** [comment]
This is correct behavior, unfortunately for a confusing reason.  `up` is actually a shortcut for modifying the pitch using the `speed` parameter.  So `up "0"` is translated to `speed "1"`, and `up "12"` to `speed "2"`.  But you don't *add* speeds for different pitches, you *multiply* them.  So to get the behavior you want, you'd use
```
d1 $ stack [sound "trump*3" |*| up "0 3 5" |*| up "0"
```
It looks a bit weird, but it works.

**Comment by Xpktro** [comment]
@lennart commented about this:

> `up` uses `speed` internally. it takes your input and calculates `1.059466^yourinput` if this is `0` then it results in `1`.
> so `up "0"` is the same as `speed "1"`
> if you are calculating the output speed from your examples, then you are actually increasing speed by `1` on each part of your inner up pattern `up "0 3 5"` (which results in `speed "1.0 1.1892168994438068 1.33485815865987312"`) eventually producing roughly `speed "2 2.1 2.3"`.

Thus, `up "0" |+| up "0"` is equivalent to `speed "2"` and so to `1.05...^2`. Then this explain those strange effects. Hope you guys fix it soon (I'm too newb in haskell/tidal-dev to contribute at this point :( ).

**Comment by yaxu** [comment]
To get the right behaviour you just switch `|+|` to `|*|`. We could make `|+|` work though by doing this calculation in the innards of tidal rather than in the parameter. Is this worthwhile?

**Comment by yaxu** [comment]
`up` is being deprecated in favour of `note`, which will be calculated in superdirt and work as expected.
