### ISSUE TITLE
tidal.el | `C-v C-1` command and `tidal-stop-d1` don`t work anymore

### ISSUE THREAD

**Issue by harte-echtzeit** [tidalcycles/Tidal#953]
Hey.
It seems that since v1.9 (not exactly sure, but about since this time) emacs does not recognize the shortcut C-v C-1 (or equivalent for other channels) anymore. The error message of the haskell interpreter shows
` <interactive>:48:21: error: parse error on input ‘,' `
. I have tested to run the corresponding command as in tidal.el -> `M-x tidal-stop-d1` but that shows the same error. The corresponding command `C-c C-1` to execute d1 works still without trouble.
If someone gives me a hint where to search, I will do some investigation myself. Any hints are welcome.
(I have tested it on two different machines already, both running Arch linux)

**Comment by Zalastax** [comment]
Looking at the implementation, it does look like a strange placement of `,` to me https://github.com/tidalcycles/Tidal/blob/c135f6339a5b60cf649e816e5b4c30d89ab8b08a/tidal.el#L231

**Comment by yaxu** [comment]
Yes it looks like a regression from @zzkt 's recent improvements. That `name` should be the lisp variable that's coming in to the function, and the comma is indeed spurious I think.

I'm not a lisp person, but I wonder if this works: `(tidal-send-string (concat " mapM_ ($ silence) [" name "]"))`

**Comment by zzkt** [comment]
the syntax looks ok, the comma should be part of the backquoted macro template (details at [backquote](https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html)) so there's probably something else going wrong...

i haven't tested it, but if the string `:{  mapM_ ($ silence) [ d1 ] :}` is valid, then the changes below might work (otherwise some linebreaks)

```emacs-lisp
(defmacro tidal-create-runner-stop (name)
  "Macro to generate `d1' style pattern runners with NAME."
  (let ((stop-fname (intern (concat "tidal-stop-"  name))))
    `(defun ,stop-fname ()
       ,(format "Send %s $ silence as a single line." name)
       (interactive)
       (tidal-send-string
        (concat ":{ mapM_ ($ silence) [" ,name "] :}")))))
```
then a macroexpansion should correctly substitute `"d1"` where `,name` appears above

```
(format "%S" (macroexpand '(tidal-create-runner-stop "d1")))
```

specifically...

```
(tidal-send-string (concat ":{" " mapM_ ($ silence) [" "d1" "]" ":}"))))
```

**Comment by zzkt** [comment]
which reminds me there are some updates to the emacs section of the docs I should probably cleanup & merge...
