### ISSUE TITLE
add `rolled'` and `rolledBy'` variants (reverse roll direction)

### ISSUE THREAD

**Issue by cleary** [tidalcycles/Tidal#983]
This is one for @thgrund mostly I think - I'm loving the inclusion of the `rolled` functions, I'm hoping you would be interested in adding the reverse roll variants as well (ie chord tones played from high to low, opposite to rolled currently)?

In great hope of a New Year miracle, 
Bernie :D

PS I tried to take a look today, but I couldn't get a dev environment running. The scraps of info around aren't working and I don't know what the errors mean ... I hope it's a trivial change, I have similar working examples [here](https://github.com/cleary/livecode/blob/main/global/function_helpers.hs)

**Comment by thgrund** [comment]
Hey cleary! Because this is still open (and quite new): you can use the reverse direction easily by using negative values. So I already intended to do this :-)

**Comment by cleary** [comment]
Awesome! thankyou - you thought of everything ;)
