### ISSUE TITLE
Could not find module ‘Sound.Osc.Fd’ - in CI job "stack resolver" only

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#988]
(duplicate of #981 ?)

I was building a harmless doc patch, and got this error

```
tidal              > /home/runner/work/Tidal/Tidal/src/Sound/Tidal/Tempo.hs:9:1: error:
tidal              >     Could not find module ‘Sound.Osc.Fd’
tidal              >     Perhaps you meant Sound.OSC.FD (from hosc-0.18.1)
```

https://github.com/tidalcycles/Tidal/actions/runs/3817947807/jobs/6494527178#step:6:1006

only for the "stack resolver" job. the other jobs (cabal-* ghc-*) look fine.

indeed I can reproduce this locally, and the WARNING looks suspicious. I don't know that I enable allow-newer (which means -older in this case)
```
stack test --resolver=lts-20.5

WARNING: Ignoring tidal's bounds on hosc (>=0.20 && <0.21); using hosc-0.18.1.
Reason: allow-newer enabled.
```
Oh - stack.yaml pins the old hosc  version. Do we want that?

**Comment by yaxu** [comment]
Hopefully the nix build is just lagging a bit with the hosc package and it'll all come out in the wash.
